### ISSUE TITLE
关于 ctex 2.x 对 luatexja 的使用方式

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#147]
Original [issue 148](https://code.google.com/p/ctex-kit/issues/detail?id=148) created by sobenlee on 2014-04-15T12:12:04.000Z:

目前是基本上禁用了 luatexja 在 LaTeX 下的设置（ltj-latex）。主要原因是 ltj-latex 扩展了 NFSS（\DeclareYokoKanjiEncoding 等），现在看来意义并不大，特别是在用 fontspec 选择字体和目前还不支持直排的情况下。其中一些必要的设置已经被我移植到 ctex-engine-luatex.def 中。

由于我并不掌握 luatexja 的整个运作机制，可能有些疏漏。同时严重依赖它的内部函数，随着 luatexja 的更新，很容易出问题。

**Comment by leo-liu** [comment]
`luatexja` 刚刚发布了带竖排支持的版本，不知道有没有问题。

**Comment by qinglee** [comment]
咱们也要跟着做竖排支持么？

不知道难度怎么样，我这周末集中点时间看一下吧。

**Comment by leo-liu** [comment]
我觉得竖排先不用吧，毕竟不光是 luatexja。
如果真要做先独立开个包可能会好些。
我主要是担心 `luatexja` 更新后会有兼容性问题。

**Comment by qinglee** [comment]
https://github.com/CTeX-org/ctex-kit/commit/3d246c020f21ad0871d3ffb1252d34da6baf47a8 兼容 LuaTeX-ja 20150420，主要是两点修改：

* https://github.com/CTeX-org/ctex-kit/commit/3d246c020f21ad0871d3ffb1252d34da6baf47a8#diff-16e85c653b0c2cd97fbaab4ccd881096R4256
* https://github.com/CTeX-org/ctex-kit/commit/3d246c020f21ad0871d3ffb1252d34da6baf47a8#diff-16e85c653b0c2cd97fbaab4ccd881096R4270

暂不支持竖排。
