### ISSUE TITLE
ctex 2.0 包的 fntef 接口已与 xeCJKfntef 脱节

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#168]
Original [issue 169](https://code.google.com/p/ctex-kit/issues/detail?id=169) created by LeoLiu.PKU on 2015-03-07T12:01:39.000Z:

除了命令名还保留原来的 \CJKunderline 等命令一样，xeCJKfntef 已经有了基于 key-value 语法的格式设置方式，功能也增加不少，已经与原来不同了。

例如，\CJKunderdotbasesep、\CJKunderdotcolor 这些宏已经不复存在。宏名替换没有意义。

旧的 ctex 宏包中，fntef 选项主要用于同时兼容 CCTfntef 和 CJKfntef。这二者只有宏名的 CJK 和 CCT 不同，其他语法用法都完全相同。
现在 2.0 版中，fntef 选项被用于兼容 CJKfntef 和 xeCJKfntef。但是，这二者的基本命令是完全相同的，没有必要特别做兼容；高级的设置则在语法上完全不同，没有办法用现在的方式简单做宏名替换达到兼容了。

由于 luatexja 和以后的 ptex-ng 等引擎也不支持 CJKfntef 这套东西，也由于 CJKfntef 与 xeCJKfntef 的现状，fntef 选项已经失去原来的重要性。

我整理文档看到这一部分，感觉这部分代码的意义已经比较小。
我现在的倾向是：
1、删除 fntef 选项及 \CTEXunderline 等命令的定义与文档。
2、对 fntef 选项，在调用时给出 deprecated 的警告。
即处理方式与 captiondelimiter 选项相同。

大家看怎么样？

**Comment by leo-liu** [comment]
由于 `CJKfntef` 的修改和更新需要等 Werner Lemberg，而他那边又实在很慢（我 2014 年 6 月给 `CJKutf8` 打的补丁很早就被接受进入 `CJK` 的版本库了，至今未更新），看起来保留 `fntef` 选项并做适当的调整是更灵活的做法。

`CJKfntef` 的问题在于：
* 没有向 `ulem` 包传递 `normalem` 选项，影响正常的 `\emph` 语义。
* 彩色设置是通过检测 `\color` 命令的有无决定的，只要前面引用了常见的绘图包就一定带颜色，华而不实。禁用此功能却很麻烦。

`xeCJKfntef` 已经传递了 `normalem` 选项，但也保留了默认的彩色设置。

彩色设置对于使用 `ctexart` 等文档类的情况其实问题不大，因为 `ctex` 内部没有引用 `color` 包；但对于在其他文档类中使用 `ctex.sty` 时，如在 beamer 中，则可能产生出人意料的后果。

现拟在 `fntef` 选项后直接关闭 `CJKfntef` 的彩色设置。同时关闭 `xeCJKfntef` 中的默认颜色设置。

**Comment by leo-liu** [comment]
按 #187 的做法，可以使用 `\ctex_at_end_package:nn` 的方式处理 `CJKfntef` 或 `xeCJKfntef` 宏包，从而删掉 `fntef` 选项。

另一方面，因为 `fntef` 这个功能算是比较基本的中文支持，感觉直接加入 `ctex` 包而去掉这个选项也是可以的。

@qinglee @LiamHuang0205 觉得怎样？

**Comment by qinglee** [comment]
`fntef` 确实意义不大，当年也是为 `CJKfntef` 和 `CCTfntef` 提供统一接口。

我看现在默认加入 `CJKfntef` 或 `xeCJKfntef` 宏包就行。

**Comment by LiamHuang0205** [comment]
汗，我没开邮箱 App，没看到这个 Issue。还到 commit 下画蛇添足说了一句，囧死了。


—
