### ISSUE TITLE
给 zhnumber 增加干支计数

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#169]
Original [issue 170](https://code.google.com/p/ctex-kit/issues/detail?id=170) created by LeoLiu.PKU on 2015-03-11T02:58:53.000Z:

天干（甲乙丙丁等）在条目计数时使用很多。

地支（子丑寅卯等）与干支（甲子、乙丑等）则多用于纪年等日期。

增加一组命令：
```TeX
\zhtiangan{<数字>}
\zhdizhi{<数字>}
\zhganzhi{<数字>}
```
分别将数字转换为天干、地支、干支的文字。

增加一个选项：
```TeX
ganzhi-cyclic = true|false
```
决定是否对超出范围的数字取模。

注：

1. 不建议用英文命令名。
2. 干支不涉及简化字。

**Comment by qinglee** [comment]
目前，关于 `0` 的转换结果都是空值。

超过范围的正整数直接取摸就可以，负整数目前的实现是采用倒数的方式，例如，`\zhtiangan{-1}` 是 `\zhtiangan{10}`，`\zhtiangan{-10}` 是 `\zhtiangan{1}` 等。

类似于纪年的方式吧，我不确定采用这种方法是否妥当。

**Comment by leo-liu** [comment]
不考虑负数好像也没什么关系，先这样吧。
