### ISSUE TITLE
ctex: 增加 ctex/punct 选项

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#172]
在 ctex 2.0 版中增加 `ctex/punct` 选项，使得可以使用 `\ctexset` 来设置标点格式。

**Comment by qinglee** [comment]
ed0a28f 补充了 luatexja 的情况。此时 punct 设置的是字体默认的 JFM，应该在 fontset 选项之前使用。例如

    \documentclass[fontset=none]{ctexart}

    \ctexset{punct=kaiming, fontset=adobe}

    \begin{document}

    你好，世界！

    \end{document}

没有 CJKpunct 和 xeCJK 灵活。
