### ISSUE TITLE
向 CTAN 提交一个新版本的 CJKpunct

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#173]
目前版本库里面的 CJKpunct 比 CTAN 上的新，修正了一些错误。需要向 CTAN 提交一个新版本。

可能需要整理代码。
可能需要与 CTAN 维护者、孙文昌老师做邮件确认。

**Comment by qinglee** [comment]
https://github.com/CTeX-org/ctex-kit/commit/b057b50d0fea7b43c3482bfda0cf901588675ac9 修正了一个由宏名写错造成的无效循环。

**Comment by Liam0205** [comment]
这件事情有提上议程吗？

BTW，@Harry-Chen 发现，四年前 CTeX 套装里的 `CJKpunct` 版本号都比 CTAN 中的高。

**Comment by Harry-Chen** [comment]
目前 CTAN 中的`CJKpunct`版本号是 4.8.1-2
最后一个 CTeX 稳定版中的是 4.8.2-2
由于没有独立的版本号机制，也没有Git SHA-1来对比，我不知道是来源于哪一个commit后，但是可以肯定版本比 CTAN 的要新。

**Comment by leo-liu** [comment]
主要因为是和 `CJK` 一起发布的。大约要联系 Werner？

**Comment by qinglee** [comment]
不用吧，虽然 `CJKpunct` 的版本号看起来是跟着 `CJK` 的，但在 CTAN 上市独立的包，我们自己发应该问题不大。

**Comment by leo-liu** [comment]
是我记错了，`CJKfntef` 才是和 CJK 一起发布的。

**Comment by qinglee** [comment]
已经发邮件和孙老师确认了。我想在今天晚上或者明天，把 `README` 都换成 `Markdown` 格式的，然后把 `xeCJK` 等其他几个包的文档类换成 `ctxdoc.cls`，就统一提交到 CTAN 上吧，应该赶得上 TL 2016 冻结。
