### ISSUE TITLE
ctex: 提供手工选择 Windows XP 前字体与 Vista 后字体的选项

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#175]
问题来源见 http://bbs.ctex.org/forum.php?mod=redirect&goto=findpost&ptid=79955&pid=466028&fromuid=102734

有 Windows XP 用户报告其字体名是 `KaiTi` 和 `Fangsong`，没有 GB2312 字样。可能是后来使用的其他软件安装了新字体导致。

`ctex` 利用系统文件判断操作系统并设置字体，也不无误判或用户字体被更换的可能。现计划增加字体集 `windowsold` 与 `windowsnew`，分别对应 XP 以前的字体（GB2312、无雅黑）与 Vista 之后的字体设置（GB18030、有雅黑）。

此时这类用户可以通过设置 `ctexopts.cfg` 来处理此问题。

@qinglee

**Comment by qinglee** [comment]
嗯，提供手动选择的机会也好。实现的话增加个 bool 变量来切换就可以。

**Comment by leo-liu** [comment]
我觉得可以直接增加两个新的 `fontset`，然后让 `ctex-fontset-windows.def` 按情况调用 `ctex-fontset-windowsnew.def` 或者 `ctex-fontset-windowsold.def`。

这样生成的文件虽然多了两个，但可以直接利用原来的 `fontset` 选项，不需要增加新的选项。

**Comment by qinglee** [comment]
行，现在不同版本的 windows 字体放一个文件里，其实比较难看。
