### ISSUE TITLE
xeCJK: LoadFandol 选项中定义字体建议修改

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#176]
OS X 里，XeLaTeX 不使用 fontconfig 库来搜索字体，因此随 MacTeX 发行的字体必须使用字体名来指定。

当前 xeCJK 里，LoadFandol 选项定义的时候，使用的是字体 PostScript 名。如果安装 MacTeX 但为对字体做软链接，则下列代码会提示 Fandol 字体找不到的错误。

    \documentclass{article}
    \usepackage{xeCJK}
    \begin{document}
    Fandol 字体找不到。
    \end{document}

建议修改成带 .otf 后缀的字体名字。

@qinglee @leo-liu

**Comment by LiamHuang0205** [comment]
ctex 的 fontset = fandol 选项也有类似问题，在使用 xeCJK 的时候同样建议修改成带 .otf 后缀的字体名字。

**Comment by qinglee** [comment]
行。

把字体装在 OS X 里，通过 PostScript 名也找不到么？

**Comment by LiamHuang0205** [comment]
@qinglee 如果不做软连接，通过 PostScript 名字是找不到的。
必须做软连接，让 FontBook 管理字体，才能用 PostScript 名来调用字体。
在此之前，只能用字体文件名。

现在 Fandol 字体至少有三个版本。一是 CTAN 上的版本，这个版本最旧。再就是版本库里的版本，这个版本稍微新一点。马起园自己使用的版本，相对版本库里的版本要新的多——字体更全，也做了更多的字体特性。
我去催催他。

**Comment by LiamHuang0205** [comment]
xeCJK 设置这个 fallback 就是为了在用户没配置字体的情况下，载入一个可用的字体。现在在 OS X 上，这个效果实际上是失效的。
ctex 的话目的是为了简化配置。如果在 OS X 上使用 fontset = fandol 还要让用户自己做软连接，就有点违背初衷了。

所以我觉着，直接改成字体名字比较好。

另外啊，ctex 的 make.bat，我还得写一个 shell 版本……不懂它啊，愁死了……

**Comment by qinglee** [comment]
make.bat 这个其实不用改成 shell 脚本，要跨平台的话，用 l3build 就可以，只是我懒得弄了。

**Comment by LiamHuang0205** [comment]
我先手工编译吧，弄完了再搞搞 l3build 看。

**Comment by leo-liu** [comment]
我试了一下 l3build，大致能用是没问题的。
不过这货可扩展性太差，很多命令都是写死在脚本里面的，目前看唯一可加钩子的地方是自定义 main 函数。我先试试吧。
