### ISSUE TITLE
ctex: 在导言区使用 \ctexset{ fontset = adobe } 等报错

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#178]
2.0 版本的 ctex 宏包会自动检测操作系统，然后加载对应的字体设置。这个工作在用户使用 \ctexset 之前就已经完成。因此下列代码会报错：

    %!TEX program = xelatex
    \documentclass{ctexart}
    \ctexset{ fontset = adobe }
    \begin{document}
    测试
    \end{document}

实际使用的时候，必须写成类似下面的代码才能奏效：

    %!TEX program = xelatex
    \documentclass[ fontset = none ]{ctexart}
    \ctexset{ fontset = adobe }
    \begin{document}
    测试
    \end{document}

这就有些繁琐了。

看了一下代码：

                \str_if_eq:onTF { \g_@@_fontset_tl } { none }
                  {
                    \tl_gset:Nx \g_@@_fontset_tl {#1}
                    \ctex_load_fontset:
                  }
                  {
                    \msg_error:nnxx { ctex } { fontset-loaded }
                      { \g_@@_fontset_tl } {#1}
                  }

在 \ctexset{ fontset = } 的时候，会检查是 \g_ctex_fontset_tl} 为 none。是则加载字体，否则报错。

实际使用的过程中，用户可能会使用 \ctexset 直接选择字体，而不会在宏包选项里直接修改。所以这可能是个 bug。检测操作系统并设置字体应该放在导言区的末尾进行，起到和 xeCJK 宏包的 LoadFandol 一样的效果：如果用户不设置，那就检测系统并设置；如果用户设置了，以用户设置为准。不知道 @qinglee 当初这么设计是出于什么考虑，我感觉多次设置字体以最后设置的生效比较符合习惯。

**Comment by qinglee** [comment]
用户没有指定字体集时，在导言区的末尾，才检测操作系统并设置字体应该问题不大。这样用 `\ctexset` 设置字体就不需要像目前一样先设置宏包选项 `fontset=none`。

不允许重复设置字体，是因为字体集并不是完全的的覆盖关系。比如，先后设置 `windows` 和 `mac` 字体集，`mac` 不能完全覆盖掉 `windows` 的设置。

**Comment by LiamHuang0205** [comment]
原来是出于这样的考虑。


那就把检测操作系统和设置缺省字体的工作放在导言区末尾吧，这样保留现在不允许重复设定字体的策略也就没问题了。


—

**Comment by qinglee** [comment]
现在的 `fontset` 选项是在设置时就马上载入字体集的，所以不方便重复设置字体。可以修改成，`fontset` 只设置变量 `\g_@@_fontset_tl`，然后在导言区末尾，根据 `\g_@@_fontset_tl` 载入相应的字体集。

这样可以保证只会载入一个字体集，并且可以保留多次设置但只以最后的设置为准的习惯。

这样做，主要的问题是：

* 与旧版本不兼容，旧版本在宏包内部就载入字体。
* 导言区没有中文字体可用，`\songti` 等没有定义。这在某些特殊情况下会出问题，比如在导言区把汉字保存在盒子里。

给 `\ctexset` 提供 `fontset` 选项的初衷是，给用户提供一个延迟字体载入的机会。这可能在某些情况下有用，比如 #172。并不推荐一般用户使用吧。高级用户都是怎么复杂怎么来，繁琐一点，我想也就更无所谓了。:)

**Comment by LiamHuang0205** [comment]
感觉兼容性这种东西尽力了就好，问题倒是不大。

比较担心的是后面的「导言区没有可用的中文字体」这个问题。感觉这个碰到 bug 的几率要大得多……




我想了想，在 \ctexset 里设置字体其实并不那么自然。

老版本的 \CTEXsetup 是设置章节标题用的，\CTEXoptions 是设置汉化名字用的。这些功能都是局部版式上的东西，和「字体设置」这种东西还是有点区别。所以老版本过来的用户，可能也不会有用 \ctexset 设置字体的习惯。

另一方面，对宏包和模板作者来说，需要延后设置字体，只需要在代码里直接用 xeCJK 的接口去设置就好了，也用不上 \ctexset 去设置整套的字体。




现在保留 \ctexset 的话，要么可能会遇到导言区无法使用中文的尴尬情况，要么会遇到这个 Issue 提到的问题。有种两边不讨好的感觉。要不然就干脆不允许在 \ctexset 里设置字体算了？


—

**Comment by leo-liu** [comment]
删掉这个功能就没必要了。不如保留这个功能。
重复载入字体就算造成覆盖问题，其实问题也不太大，把那个 error message 改成 warning，用户自己了解风险也是一个折中的办法。

**Comment by SherryDong** [comment]
Hello all,
从 CTEX 论坛跟到这里留言了。

我目前在写一个论文模板，就打算基于 ctex2.0了，也遇到了同样的问题。不过后来想了下，即便是在 ctex1.0 下，也是需要设置 `nofonts` 选项后才能设置其它字体，所以觉得加 `fontset = none` 选项也不算问题。

延迟载入字体还是需要的，此时用 `\ctexset{fontset=xxx}` 就很方便，否则还得自己判断引擎和系统。这个功能还是必要的。

best
northwater

**Comment by LiamHuang0205** [comment]
ctex 1.x 的时候，不需要 nofonts 就可以修改字体。参考：





    \documentclass{ctexart}

    \setCJKmainfont{STSong}

    \begin{document}

    中文

    \end{document}







—

**Comment by LiamHuang0205** [comment]
@qinglee 
这个问题现在预计会怎么解决？文档推进到这里了。

**Comment by qinglee** [comment]
基本上就是维持现状，不想动了。

可以在 `ctex/fontset` 的选项说明里提醒用户，使用这个选项要先设置宏包选项 `fontset=none`。

**Comment by LiamHuang0205** [comment]
好，那就这么干。


—
