### ISSUE TITLE
ctex: 使用 l3build 来生成系统无关的编译脚本

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#179]
基本的很好做，就是需要加一些 hooks 来处理诸如 checksum 修正、编码转换、中文索引的问题。

原来的 Windows 脚本用着也挺好，这个不着急。

**Comment by leo-liu** [comment]
以下仅在 Windows 测试：
* 已实现编码转换、中文索引、Git 版本更新。
* 未实现 checksum 修正。
* 此外打包似乎还有点问题。

`makeindex` 是内部函数，不方便单独修改，太坑爹。l3build 的通用性还是不够好。

**Comment by LiamHuang0205** [comment]
`texlua build.lua ctan` 报错。

    This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    LaTeX2e <2014/05/01>
    Babel <3.9l> and hyphenation patterns for 79 languages loaded.
    (./build/doc/ctex.dtx
    (/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/expl3.sty
    (/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/expl3-code.tex
    (/usr/local/texlive/2014/texmf-dist/tex/latex/etex-pkg/etex.sty))
    (/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/l3unicode-data.def)
    (/usr/local/texlive/2014/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
    (./ctex.ver)
    ! Use of \GetIdInfoAuxI doesn't match its definition.
    \ctexGetVersionInfo ->\GetIdInfo :
                                       ctex.dtx 043225c 2015-04-10 03:40:17 +080...
    l.349 \ctexGetVersionInfo
                             

    ! LaTeX Error: Missing \begin{document}.

之后 ltx3 的语法都没有被正确处理，全都是报错（@符号，下划线）。

**Comment by leo-liu** [comment]
像是你 LaTeX3 的版本比较低造成的。升级一下吧。

**Comment by LiamHuang0205** [comment]
咦？我昨天刚更新的……



—

**Comment by leo-liu** [comment]
那不应该啊，都是一样的东西。其实就是要求 `git -log` 输出的信息符合 `\GetIdInfo` 的格式。比如目前的版本就是
```
$Id: ctex.dtx 043225c 2015-04-10 03:40:17 +0800 Liu Haiyang <leoliu.pku@gmail.com> $
```
其中 `\GetIdInfo` 只从前向后读取文件名、版本号、日期，所以后面我就没有再仔细处理了。

**Comment by leo-liu** [comment]
哦好像是因为 *NIX 下面命令的差异，你的 `ctex.ver` 不是这种格式的，是 `$Id` 被当成环境变量展开就没了吧？
这个要改一下 `git` 的命令参数。

**Comment by LiamHuang0205** [comment]
应该是了。




我得改成





git log -1 --pretty=format:"\def\ctexPutVersion{\string\GetIdInfo\$Id: ctex.dtx %h %ai %an <%ae> $}" ctex.dtx > ctex.ver

git log -1 --pretty=format:"\def\ctexGetVersionInfo{\GetIdInfo\$Id: ctex.dtx %h %ai %an <%ae> $}" ctex.dtx >> ctex.ver





这样才行……




—

**Comment by LiamHuang0205** [comment]
b6c2584 在我这里已经可以正常工作了。

> MacTeX 2014，OS X 10.9.5。

**Comment by leo-liu** [comment]
不用把 `\` 改成 `\\` 么？应该还是不对吧？

**Comment by LiamHuang0205** [comment]
不用吧？

    os_dollar = "\\$"

首先在 lua 里转义，实际上是 \$。然后在 *nix 里转义，变成 $。这就是我们要的呀。

**Comment by leo-liu** [comment]
不是这个，是 `git` 命令里面的 `\def\ctexGetVersionInfo` 之类的。

**Comment by LiamHuang0205** [comment]
按道理应该要改的，但是这里不改也无所谓。不过还是改了吧，严谨一点总是好的？

\d \c 之类的在这里没有什么含义，于是照原样输出了。

**Comment by LiamHuang0205** [comment]
0150a16 在 Mac 里测试通过了。

**Comment by leo-liu** [comment]
除了 `makeindex` 的命令行改起来比较麻烦之外（[l3build](https://github.com/latex3/svn-mirror/issues/210)），还有一个问题就是 `l3build` 不能自由定制文件在 TDS 里面的布局位置。

按 Windows 的批处理脚本，`ctex` 包中的 `.tex` 文件需要放在 `tex/generic/ctex/` 下，而在 `tex/latex/ctex/` 目录下面也还分有 `config/`、`fd/`、`engine/`、`fontset/` 几个子目录。看起来还要重写 `copytds()` 函数。

感觉 `l3build` 处理复杂一些的包还是功能不足啊。

**Comment by qinglee** [comment]
`l3build` 的目录定制方面不如 `ctanify` 灵活。

还发现一个问题是，我们的 `README.txt` 是由 `dtx` 解包得来的，`l3build` 不能加到压缩包里。

**Comment by leo-liu** [comment]
log 忘记了，手动引用一下：
* 1e102d0eb278fd2f123e6a1dfb0b0b328a4cdccf 清理 `ctex.ver`
* 4ce5bc9b7de02e3a5e02056588088419002dbdfe 处理 `generic` 目录
* a62a4bd7e52d55bd25fff88c0fc89141bcee32cb 复制 `README`

**Comment by leo-liu** [comment]
功能差不多齐了。

@LiamHuang0205 你试试 Mac OS X 下的兼容性

**Comment by LiamHuang0205** [comment]
去 CTeX 论坛找到了 darwin_x64 的 zhmakeindex，然后 `texlua build.lua ctan` 通过了。

现在的问题是，在目录里会多出 NUL 这个文件。这是什么情况？

**Comment by leo-liu** [comment]
zhmakeindex 在 CTAN 就能下载啊。
`NUL` 应该是误植了，Windows 用的，相当于 `/dev/null`

**Comment by LiamHuang0205** [comment]
啊，想起来在 CTeX 上看到过帖子，就没去 CTAN。

不过 CTAN 的地址还是指向 googlecode，改改？

**Comment by LiamHuang0205** [comment]
还有，`build/local/yes` 这个文件似乎也是多余的？

**Comment by leo-liu** [comment]
CTAN 等更新新版本的时候再改，迁移到 GitHub 以来也没有任何重要的更新，没关系。

`build/local/yes` 是由 `l3build` 生成的临时文件，不影响。`local` 本来也只是临时目录。
最终发布的是打包的 `ctex.zip` 和里面的 `ctex.tds.zip`。

**Comment by LiamHuang0205** [comment]
感觉 l3build 没有一个本地 unpack 很不方便。虽然在 build 目录里有一个 unpack 子目录，但是每次都要手工复制还是蛮麻烦的。

加一个 unpack 参数，或者在 ctan 编译之后，自动把 unpack 里的内容复制到当前目录？不过这样就需要加一个清理工作了。


—

**Comment by leo-liu** [comment]
你要做临时小测试的话直接在 `build/unpacked` 目录写你的测试文件就行。

**Comment by LiamHuang0205** [comment]
不，我是要在主目录 `xelatex ctex.dtx` 生成 `ctex.pdf`。没有这些文件的话，没法生成……


—

**Comment by leo-liu** [comment]
啊那只好自己 `xetex xeCJK.dtx` 了。

**Comment by LiamHuang0205** [comment]
看上去还是写个 bash 脚本或者弄过 makefile 比较好……

╮(╯▽╰)╭


—

**Comment by leo-liu** [comment]
`xetex ctex.dtx` 就是 unpack。
`xelatex ctex.dtx` 才是排版。

**Comment by LiamHuang0205** [comment]
我知道……我的意思是，l3build 有这么多不尽如人意的地方，还不如写个 bash 脚本或者 makefile。


—

**Comment by leo-liu** [comment]
写 Makefile 也很麻烦，跨平台更难。bash/batch 脚本要做到同样功能也比写 l3build 要长，你看现在 `make.bat` 就比 `build.lua` 要长。
其实无所谓，也就我们三个人。

**Comment by LiamHuang0205** [comment]
算了我还是自己手工编译好了……

—

**Comment by leo-liu** [comment]
今天发现 `dtxchecksum.lua` 的调用早于 `unpack` 操作，也不会调用已解包的文件，编译的时候会有问题：如果没有在 `ctex` 当前目录解包过，计算 checksum 的时候仍然用的是旧版本的 `ctex` 包，会出编译错误而失败。

**Comment by qinglee** [comment]
嗯，将 `l3build` 的 `localdir` 加入 `TEXINPUTS` 路径就可以。

**Comment by LiamHuang0205** [comment]
`texlua build.lua ctan` 我这里又过不去了……

    *******************
    * Checksum passed *
    *******************
    ) [111]
    No file ctex.gls.
    No file ctex.ind.
    (./build/doc/ctex.aux)

    LaTeX Font Warning: Some font shapes were not available, defaults substituted.


    LaTeX Warning: There were undefined references.


    LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

     )
    (see the transcript file for additional information)
    Output written on ./build/doc/ctex.pdf (111 pages).
    Transcript written on ./build/doc/ctex.log.
     ! Compilation failed

    ====================
    Typesetting failed, zip stage skipped!
    ====================

**Comment by leo-liu** [comment]
如果是 TeX Live 2015，你可能需要使用最新的 xeCJK。

**Comment by LiamHuang0205** [comment]
xeCJK 我这边是最新版，而且也没去参加 pretest 来着……
一周前还好用，昨天试试就不行了。

**Comment by qinglee** [comment]
你确定你使用的是最新的版本么？

我们开始往 `doc()` 里加入 `checksum()`，忘了返回值，那时 ctan 功能会失效，就会出现上面的提示。后来的 https://github.com/CTeX-org/ctex-kit/commit/c3f290ec433bb6453ce9a17f1f5622c024452780 修正了。

**Comment by leo-liu** [comment]
`hologo` 的问题，在页眉里面成大写了。我觉得这是 `hologo` 的致命缺陷，所以我不爱用它。

**Comment by LiamHuang0205** [comment]
@qinglee 
版本库里的呀，肯定是最新版的嘛……

@leo-liu 
`hologo` 这个问题我前年好像就给 Oberdiek 提过，不过他说暂时没时间管，就一直拖到现在。

**Comment by LiamHuang0205** [comment]
3cb10c2 之后可以了。

**Comment by leo-liu** [comment]
https://github.com/latex3/svn-mirror/commit/49a78dc7f9250e56848563300daea3be04da5198 给脚本增加了 `makeindexexe` 变量。`l3build` 更新后应该可以简化 `build.lua` 的写法。

**Comment by leo-liu** [comment]
eef555eeff5b434b19056b8a363e78829c04d483 固定了一个 `l3build.lua` 脚本。

在 `xeCJK`、`xpinyin` 都试了一下。用起来感觉就是，`l3build` 要完善还有很长的路要走。

**Comment by zohooo** [comment]
似乎没法在 miktex 中使用：
````
../tool/dtxchecksum.lua:151: attempt to concatenate local 'kpse_texinputs' (a nil value)
````

**Comment by LiamHuang0205** [comment]
于是又不行了……

    $ texlua build.lua ctan
    ../tool/zhconv.lua:173: table index is nil

**Comment by qinglee** [comment]
我这边 Windows 没有报错呀。第 173 是
```lua
gb18030_ranges[prev_pointer] = { prev_code_point, 0x110000 }
```
没看出会有什么问题。

**Comment by LiamHuang0205** [comment]
这我就更不知道了，完全不懂 Lua。出了问题连怎么测试都不知道……

还能有什么测试嘛？试着提供更多信息？

**Comment by qinglee** [comment]
原因应该是 `index-gb18030-ranges.txt` 没有被下载下来，是个空文件，然后那个循环没有效果，`prev_pointer` 等就没有被赋值。

**Comment by LiamHuang0205** [comment]
62d8d315 的改进在我这里效果不彰啊，还是老样子。

尽管加入了异常处理，但是还是以前那样的报错提示。除了行号从 173 变成了 176。

**Comment by qinglee** [comment]
呃，你先看一下本地的文件 `index-gb18030-ranges.txt` 正常么，不会是空文件吧。

如果还报错的话，我就不清楚了。

**Comment by LiamHuang0205** [comment]
`index-gb18030-ranges.txt` 是这样的：
    <HTML>
    	<HEAD>
    		<TITLE>Service Unavailable - Fail to connect</TITLE>
    		<META http-equiv=Content-Type content="text-html; charset=UTF-8">
    	</HEAD>
    	<BODY>
    		<H1>Service Unavailable</H1>
    		The server is temporarily unable to service your request. Please try again later.
    		<P>Reference #60.27b2dc9d.801e3464.1431261504</P>
    	</BODY>
    </HTML>

看上去就不太正常对吧……

**Comment by leo-liu** [comment]
网络下载临时出错，这个问题你自己掌握就好，不用问了吧……

**Comment by LiamHuang0205** [comment]
嗯。
看上去 build 的时候还得翻墙……

**Comment by zohooo** [comment]
3216ced 在最新的 miktex 下还是无法编译成功：
````
! LaTeX Error: Unknown option `punct=kaiming' for package `ctex'.
! LaTeX Error: Unknown option `heading' for package `ctex'.
````

**Comment by LiamHuang0205** [comment]
这个是编译的时候使用了老版本的 CTeX 导致的吧…

发自我的 iPhone

**Comment by qinglee** [comment]
看样子是 `TEXINPUTS` 的设置没起作用，等我装一个 MiKTeX 再看看吧。

**Comment by qinglee** [comment]
@zohooo 貌似在 MiKTeX 里，环境变量 `TEXINPUTS` 优先级低于系统路径。所以会优先使用系统里的旧版本 `ctex.sty`，而不是解包出来的新文件。已经通过设置编译选项 `-include-directory` 来解决。

但我在最新的 MiKTeX 里，用脚本编译 `ctex.dtx` 时，最后会出现奇怪错误：

```
** WARNING ** Obsolete four arguments of "endchar" will be used for Type 1 "seac" operator.
** ERROR ** This font using the "seac" command for accented characters...

Output file removed.

Error 1 (driver return code) generating output;
```

**Comment by zohooo** [comment]
我用的是 miktex portable，现在可以正常编译，没有遇到这个问题。

**Comment by zohooo** [comment]
@qinglee  从 ffd6ea3 开始 miktex 又无法编译了，还是上面所述的路径问题导致的错误。

**Comment by qinglee** [comment]
@zohooo 新版 `l3build.lua` 更新造成的，我当时没有注意看，现在应该好了。
