### ISSUE TITLE
G-Code: 我发现转移过来的时候还是出问题了……

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#180]
contributors 里面写的是 Liam0205，但是我这边 GitHub 账号是 LiamHuang0205。那个不是我……

**Comment by leo-liu** [comment]
这个似乎要一开始转过来的时候换，否则现在改不了了。修改这个的页面在：
https://import.github.com/CTeX-org/ctex-kit/import

你现在的 commit 里面也没有自己的用户名链接啊。你自己去点那个问号设置一下自己帐号和邮箱的关联。
![1](https://cloud.githubusercontent.com/assets/570611/7089636/eaa53f0e-dfcf-11e4-8ec4-f201ddb796b7.png)

**Comment by LiamHuang0205** [comment]
这个是因为我本地 git 配置的邮箱没有在 GitHub 登记吧？


我去关联一下。


—

**Comment by LiamHuang0205** [comment]
关联的问题解决了，不过 ID 错误的问题我还是不知道怎么搞。




import 页面里，貌似也没有出现 Liam0205@GitHub 这个 ID。不知道 GitHub 是怎么关联过去的。


—

**Comment by leo-liu** [comment]
可能是我开始的时候搞错了，后面再修改就关联不上了。github 这个流程不好。其实你看其他几个人的 id 也关联不上。

**Comment by LiamHuang0205** [comment]
嘛，那就这样吧……
