### ISSUE TITLE
ctex: 关于 cap 选项的改进

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#181]
cap 这个选项，含义和实际效果有一定的差距，和 heading 选项也有点说不清的关系。

@leo-liu 之前提到，改成 scheme 可能会比较好。我也觉得这样会更好。

将 cap 改成 scheme，然后用 cap 和 nocap 做一个对旧版本的兼容可能是个不错的方案。

@qinglee 怎么看？

**Comment by qinglee** [comment]
我看行，就交给你吧。

**Comment by LiamHuang0205** [comment]
好。


—

**Comment by leo-liu** [comment]
这事情我想过，当时觉得有些难度，就没弄。

* `cap`, `nocap` 是二元的，如果改成 `scheme=<xxx>` 就是多元的了，语法不一样。预定义的 theme 应该至少有两个，一个是默认的中文格式，一个是默认的原英文文档格式。原英文文档格式甚至可以做得和没有用 `ctex` 包一样，只提供中文文字输出支持。

* 目前关于 `\l__ctex_caption_bool` 这个条件的代码散落于多处，表示不同的意义：

  1. 日期 `\today` 的格式；
  2. 调整 `varioref` 包对引用的格式；
  3. 有关章节标题的格式（即 `ctex/part` 到 `ctex/paragraph` 的设置）；
  4. 在 `ctexcap-gbk.cfg` 或 `ctexcap-utf8.cfg` 中定义的翻译内容。

  上面这几条，以标题格式和翻译为主体。如果是做 `scheme` 选项的话，那么就有一些其他格式是应该考虑加进去的，如行距、page style、标点格式以及现有的各种能用宏包选项或 `\ctexset` 操作的东西。

  此外上面几条中，关于 `varioref` 的条目还是错误的，应该使用 `heading` 选项来判断（即条件变量 `\l__ctex_heading_bool`）。

* 可能需要集中有关 `scheme` 的代码到单独的文件，这样就和 `fontset` 一样方便扩展了。

接口怎么设计，先讨论一下看看。实现上可能也会有一些困难。不过还是优先把接口设计好，实现到后面重构都可以。

**Comment by qinglee** [comment]
嗯，要不咱们先这样吧，用 `ctex` 的工具模拟一个标准文档类的效果，提取到单独文件中，作为一个 `scheme`。目前的汉化效果也提取到单独文件，作为另外一个 `scheme`。

`scheme` 的内容除了目前 `cap` 选项控制的内容外，再加上我们对标准文档类的改动就可以，例如上面提到的行距、page style 和段首缩进。我看只包括这些就差不多了。

**Comment by LiamHuang0205** [comment]
感觉工作量突然就变大了的说。

我本来的意思就是将现在的 cap 换个名字，同样作为 bool 形式的选项。然后定义 cap 和 nocap 两个选项，cap 选项设置 scheme = true，nocap 选项设置 scheme = false。这两个选项作为兼容选项。

提取到单独文件似乎是问题不大就是了，不过似乎没有太大意义？短期内，我们应该不会添加第三个 scheme；可预见的时间内，应该也不会有使用 ctex 的开发者，自定义自己的 scheme。所以实际上是把原来的功能分散到文件中去了。除了宏包本身变得更清晰一点，将繁琐的定义分开，并没有别的好处？

**Comment by leo-liu** [comment]
确实短期内不大会添加新的 theme，但用 `scheme = true` 就不大通顺了，肯定是 `scheme=plain` 这种才通顺。前期为了省事把用户界面定义得比较难看，后期改起来就不好办了。毕竟升大版本号打破兼容性的机会更少。

实现怎么搞都无所谓，现在哪怕还用一个 bool 变量实现两个 theme 呢，但给用户呈现的时候不能写 `theme=true` 或 `false`。

**Comment by LiamHuang0205** [comment]
嗯，确实是这样，有道理。


那就先实现成 sheme = plain | chinese 好了。然后 cap 意味着 scheme = chinese，nocap 意味着 scheme = plain。


—

**Comment by leo-liu** [comment]
`scheme` 选项名起什么好？
短一点可以 `zh`, `en`，默认 `zh`。
长一点可以 `chinese`, `english` 或 `plain`，默认 `chinese`。
按目前的代码风格似乎是倾向用长的？

**Comment by LiamHuang0205** [comment]
我决定用 chinese, english, zh, en 这些其实不大好，这其实不是语言选项，而是风格选项。


plain 和 traditional 可能是个候选项？




—

**Comment by qinglee** [comment]
取长一点的名字吧，默认中文叫 `chinese`，英文叫 `english`、`plain` 或者 `standard` 都可以。

**Comment by LiamHuang0205** [comment]
那就 `chinese` 和 `plain` 吧，默认为 `chinese`。先这么写着了。

**Comment by LiamHuang0205** [comment]
暂时是这么改了，简单测试了一下，效果和之前保持了一致。

用 `\str_if_eq_x:nnT { \l_@@_scheme_tl } { chinese }` 代替原来的 `\bool_if:NT \l_@@_caption_bool` 来做判断。
