### ISSUE TITLE
ctex: 文档索引中 \| 的索引会出问题

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#182]
可能是 `l3doc` 的 Bug。

目前的 `ctex.dtx` 会生成这样一行 `.ind` 索引：
```
\indexentry{!|={\verbatim@font \verb!*&!\!!|&}|hdclindex{1783}{}}{1187}
```
其中 `\verb!*&!\!!|&` 是由 `__codedoc_special_index_set:Nn` 对 `\|` 处理生成的。但应该生成的是
```
\verb!*&!\!|&
```
多了一个 `!`。（注 `!` 是 `gind.ist` 中设定的 quote char）

makeindex 会拒绝这一行错误的索引，而 zhmakeindex 会生成错误的结果。
小问题吧，不过文档编译会出错。

**Comment by qinglee** [comment]
`|` 是 `\encapchar`，`\__codedoc_special_index_set:Nn` 会给 `\actualchar`、`\encapchar` 和 `\levelchar` 加上 `\quotechar`：

```TeX
        \tl_map_inline:nn { \actualchar \encapchar \levelchar }
          {
            \tl_replace_all:Nxn #1
              { \tl_to_str:N ##1 } { \quotechar \tl_to_str:N ##1 }
          }
```

但是源代码中出现的 `\|`，名字是单字符 `|`，按照 `doc` 宏包的处理，在送给 `\__codedoc_special_index_set:Nn` 处理之前，它已经被 `\it@is@a` 给加上过 `\quotechar` 了：

```TeX
\cs_gset_protected:Npn \it@is@a #1
  {
    \use:x
      {
        \__codedoc_special_index_module:nnnn
          { \quotechar #1 }
          { \quotechar \bslash \quotechar #1 }
          { }
          { }
      }
  }
```
上述的参数 `#1` 是 `\string |`。

不好处理，但是可以祭出 `\DoNotIndex` 回避掉：

```TeX
\begingroup
  \edef\x{\noexpand\DoNotIndex{\string\|}}
\expandafter\endgroup\x
```
写这么乱，是因为 `|` 可能被 `\MakeShortVerb` 掉了，而 `\` 要被 `\DoNotIndex` 转成 `12` 类。

另外，我看了一下，CTAN 上最新版的 zhmakeindex 生成错误结果，但是旧版本能警告说语法错误并拒绝掉。

**Comment by leo-liu** [comment]
zhmakeindex 新版是有意做的容错机制。在把什么当成错误什么允许输入这方面，一直和 makeindex 的行为略有点差异，不过现在的版本问题应该不大。
