### ISSUE TITLE
ctex: 链接到 zhmCJK.lua 但以 CTeXFonts.lua 显示

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#183]
参照 a5892cd。

    % 注意：使用 (pdf)\LaTeX{} 编译的时候，若设置 \opt{zhmap = false}（比如需要
    % 使用 \LaTeX{} + DVIPS 编译），则需要按照传统方式^^A
    % \footnote{可以使用 \pkg{zhmetrics} 宏包提供的脚本
    % \href{https://github.com/CTeX-org/ctex-kit/blob/master/zhmetrics/zhmCJK.lua}
    % {\file{CTeXFonts.lua}}。}^^A
    % 在本地安装好 CJK 字体。

**Comment by leo-liu** [comment]
这种笔误你看到直接改了就好了……
是 `CTeXFonts.lua`

**Comment by LiamHuang0205** [comment]
因为我不确定要指向那个 lua……
没用过这个……

那我去改了。
