### ISSUE TITLE
将 ctex 的 scheme 提取到单独的文件中

### ISSUE THREAD

**Issue by qinglee** [CTeX-org/ctex-kit#184]
#181 将原来的 `cap` 选项改为 `scheme`，并提供了 `chinese` 和 `plain` 两个 `scheme`。

为了方便扩展，可以将这两个 `scheme` 的代码提取到单独文件中，与 `fontset` 的处理类似。

**Comment by LiamHuang0205** [comment]
我昨天想了想，`plain` 这个东西怎么写。结果发现好像什么都不要写就可以了。

莫不是想用 `\ctexset` 照着标准文档类的格式写一遍？

**Comment by leo-liu** [comment]
`plain` 的内容主要散在 `ctex-book.def` 等几个文件中。
@LiamHuang0205 对这块代码可能不熟，就不用管了。

**Comment by leo-liu** [comment]
不过确实可以让 `plain` 什么都没有，原来的代码仍放在 `ctex-book.def` 等几个文件里。

**Comment by LiamHuang0205** [comment]
比起这个，吐槽了很久的 `\section` 默认居中，是不是改改？


—

**Comment by leo-liu** [comment]
之前主要是为兼容性考虑。
既然把 `cap` 选项设置为过时的了，其实可以让 `cap` 选项和 `scheme=chinese` 区分开。这样需要兼容的可以手工用 `cap` 选项？

**Comment by LiamHuang0205** [comment]
新建一个 `scheme=chineseold` 做兼容用 = =?


—

**Comment by qinglee** [comment]
https://github.com/CTeX-org/ctex-kit/commit/ed88b8e44cd8ad263dc0e740b859ba2cebfab6e8 初步完成了。

* `plain` 是标准文档类的设置，与原 `nocap` 的区别是不调整行距和禁用 `autoindent`。
* `chinese` 我们的汉化设置，与原 `cap` 的功能一致。

**Comment by LiamHuang0205** [comment]
这样 `plain` 的效果就相当于只做了中文支持，而不调整版式。
