### ISSUE TITLE
ctex: 文档对于 space 选项的描述问题

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#185]
现在文档里写着，`space` 选项的默认值是 `auto`。但是代码里实际默认值是 `true`；在 `ctex` 里给了个初始值是 `auto`，`ctex / option` 里则没有给初始值。

`ctex / option` 里不给初始值似乎没什么问题，反正最终都会交给 `ctex` 里的 `space` 来处理。不过加上可能更好？
另外，这里代码和宏包文档不一致。

老版宏包里只有 `space` 和 `nospace`，对应新版的 `true` 和 `false`。所以我想，应该在代码里把默认值改为 `auto`，初始值改为 `true` 比较好。

-----

还有的问题，`space` 选项在 pdfTeX、XeTeX、LuaTeX 三个引擎下的行为都不一致。

* LuaTeX 下该选项无效，不必说
* XeTeX 下该选项实际会将空格处理交给 `xeCJK` 处理，而此时 `auto` 和 `false` 的效果一致
* pdfTeX 下，`true` 相当于 `CJK` 环境，`false` 相当于 `CJK*` 环境，而 `auto` 相当于使用 `CJKspace` 宏包

在 XeTeX 下，该选项不会影响 CJK 字符和西文字符之间的空格；而在 pdfTeX 下该选项会影响上述类型的空格。

当前版本的文档，我第一反应就是「那么这个选项对 CJK 字符和西文字符之间的空格怎么处理的呢？」。我以为是我的习惯问题，于是又给一个对中文处理比较熟悉的朋友看了，他也提出了这个问题。
所以看起来，这还是一个需要在文档里讲清楚的事情。

这里怎么说比较好？一方面我不太熟悉 `CJK` 对空格的处理，另一方面文档的描述取决于代码。所以 @qinglee 和 @leo-liu 你们再商量一下？

**Comment by qinglee** [comment]
按照一般 `bool` 键的习惯，`space` 选项的默认值是 `true`，即 `\ctexset { space }` 等价于 `\ctexset { space = true }`。

文档里黑体表示选项的初始设置。2.0 版初始设置 `auto` 是为了强制使用 `CJKspace` 宏包的功能，这是与旧版不一致的地方。但我认为这是一个好的改动。

`ctex / option` 没有初始值是实现上的考虑，不用重复执行一次设置代码。

**Comment by qinglee** [comment]
我觉得目前文档对 `space` 这个选项的说明还是清楚的。

* `true` 总是保留汉字后面的空格。
* `false` 总是忽略掉汉字后面的空格，而不管这个空格后面是什么。
* `auto` 视空格后的情况决定是否保留：如果空格后面是汉字，则忽略该空格；其他情况（比如西文）都保留。

这是 pdfTeX 下的效果。pdfTeX 区分 `false` 和 `auto` 只是为了兼容旧版本。

**Comment by leo-liu** [comment]
@LiamHuang0205 区分一下 `.initial` 和 `.default` 是不同的。这里的代码设置没错。
```
    space .default:n = { true } ,
    space .initial:n = { auto }
```

**Comment by LiamHuang0205** [comment]
我知道 default 和 initial 是不一样的，之前有区分过，但是不大确定。我的理解是：* 如果用户没有配置 space 选项，那么 space 选项启用 default 值

* 如果用户配置了 space 选项，但是没有给出等号后面的值，也就是写作 space =，那么 space 选项启用 initial 值。。

是这个理解吗？


—

**Comment by LiamHuang0205** [comment]
@qinglee 我理解了，我想想怎么叙述，再到群里问问是否表述清楚了。

—

**Comment by qinglee** [comment]
@LiamHuang0205 你对 `default` 和 `initial` 的理解刚好反了。

* 如果用户没有显式设置 `space`，生效的是 `initial` 初始设置，即 `auto`。
* 如果用户设置 `space`，但是没有等号，生效的是 `default`，即 `true`。
* `space` 等号后面的值只能是 `true`、`false` 和 `auto` 之一，等号后面的其他值（包括留空 `space=`）都是非法的。`.default:n` 说的是 `space` 没有等号的情况。注意，没有等号和等号给留空值是两种不同的情况。

**Comment by LiamHuang0205** [comment]
原来我理解反了。这样就没问题了。

—
