### ISSUE TITLE
ctex: 兼容选项 hyperref 造成与 cleveref 宏包不兼容

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#186]
示例代码：

    \documentclass[hyperref]{ctexbook}
    \usepackage{cleveref}
    \crefformat{chapter}{#2第#1章#3}
    \renewcommand{\thechapter}{\chinese{chapter}}
    \begin{document}
    \chapter{测试章节}
    \label{cha:test}
    参见\cref{cha:test}。
    \end{document}

编译之后提示 label undefined，但是 aux 文件里是有相关 label 标记的。直接调用 `hyperref` 宏包则无问题。

该问题在 2.0 版本中依旧存在。

参看：
http://bbs.ctex.org/forum.php?mod=viewthread&tid=80028&extra=page%3D1

**Comment by qinglee** [comment]
这其实与我们无关。

`cleveref` 宏包要求它尽可能晚的被载入。如果 `hyperref` 宏包先于 `cleveref` 被载入，就会出问题：

```TeX
\documentclass{book}

\usepackage{cleveref}
\usepackage{hyperref}

\begin{document}

\chapter{test}
\label{cha:test}

see \cref{cha:test}。

\end{document} 
```

我们的 `hyperref` 选项的目的是替用户传递合适的选项给 `hyperref`。如果用户没有手动载入 `hyperref`，我们就在导言区末尾自动载入。这在大多数情况下没什么问题，但是就没法兼顾到这里的特殊情况。用户需要根据实际情况在合适位置载入 `hyperref` 宏包。

**Comment by LiamHuang0205** [comment]
那我在文档里说一下，然后把这个 Issue 关掉吧。



—
