### ISSUE TITLE
ctex: 在导言区使用 \ctexset{ fontset = adobe } 等造成无法分段的问题

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#189]
代码：

    \documentclass[fontset = none]{ctexart}
    \ctexset{fontset = adobe}
    \begin{document}
    你好

    你好
    \end{document}

**Comment by leo-liu** [comment]
应该是导入文件时 catcode 问题

**Comment by qinglee** [comment]
呃，是我大意了，还是我来吧。
