### ISSUE TITLE
ctex: 新版套件的文档全局字号机制屏蔽非标准文档类的字号选项

### ISSUE THREAD

**Issue by zohooo** [CTeX-org/ctex-kit#190]
新版本字体比旧版本的小，在 beamer 文档全屏显示时差别尤其明显：
````tex
\documentclass[14pt]{beamer}
\usepackage{ctex}
\setCJKmainfont{SimSun}
\setCJKsansfont{SimHei}
\begin{document}
\title{测试测试}
\begin{frame}
\titlepage
\end{frame}
\end{document}
````

**Comment by LiamHuang0205** [comment]
这里传给 `beamer` 的 `14pt` 选项在加载新版宏包的情况下没有起作用，而在老板宏包里会起作用。因此看起来字体比原来小了很多。

这应该是个小瑕疵：`ctex` 宏包在处理传给非标准文档类的字号选项的时候，应该检测这个数值，然后在内部做相应的调整。

不过新版宏包和旧版宏包本身在字号设定上也有些许差别。不过一般人应该很难注意到这样的差别。（文档里有写）

**Comment by zohooo** [comment]
个人认为 `ctexart.cls` 等专门的中文文档类默认改为 `c5size` 是合适的。但 `ctex.sty` 默认情形还是不修改 `article`、`beamer` 等其它文档类的字号更合适，要修改应该通过选项明确指定。

现在这样，`\documentclass{article}\usepackage{ctex}` 在新旧版本中的排版结果是稍有不同的。虽说大版本号升级可以不兼容，但在不造成太大困难的前提下，让排版结果保持不变会减少普通用户的困惑。

**Comment by qinglee** [comment]
我看还应该把 `cs4size` 和 `c5size` 的功能加入到 `chinese` 这个 `scheme` 当中。

拟增加一个字号选项 `csize`：

csize = <5|-4|false>

分别用于调整 `\normaisize` 调整为五号、小四号和关闭默认字号调整。这名字我觉得不好取，请大家给出意见。

**Comment by leo-liu** [comment]
叫 `csize` 还不如 `size` 呢，其实应该是 `fontsize`，或者 `zihao`。我也拿不准。
默认关掉也未尝不可就是了。

**Comment by LiamHuang0205** [comment]
直接调用 ctex 的时候，默认关掉字号处理吧。
一方面省事，另一方面和旧版本保持一致。

**Comment by LiamHuang0205** [comment]
明天就 7 号了，就要冻结了的说，这个最后咋搞啊？
要不然我先给做个简单的处理？

**Comment by leo-liu** [comment]
前一阵有个 deadline，没顾上这个。
看了一下 `beamer` 的代码，根本没有相关代码嘛，明明是 extsizes 宏包自身的功能，只是写在 beamer 手册里面了而已。仅此而已。

先简单处理一下吧，似乎不会有大的问题。接口不去动它了，回头遇到问题再说，不遇到问题就不管了。

其实提交的主要问题是：`zhwinfonts.tex` 与 `zhmetrics` 包中的同名文件重复了！

**Comment by qinglee** [comment]
那咱们是重新上传一个 `zhmetrics`，把其中的 `zhwinfonts.tex` 删掉，还是将 ctex 包中的 `zhwinfonts.tex` 改个名字？我倾向于改名。

我现在也是够呛，`luatexja` 都一直都没来得及看。看了一下，8 号是代码截止日期，CTAN 包更新会持续到 15 号，应该还来得及。

**Comment by LiamHuang0205** [comment]
都改成 ctex-zhwinfonts.tex 之类的名字吧，带个前缀？

—

**Comment by leo-liu** [comment]
嗯改名比较容易处理。
你可以先提交一个 xeCJK。

在 2015年5月6日 下午10:41，Qing Lee <notifications@github.com>写道：

**Comment by qinglee** [comment]
XeTeX 修复了 `\string` 等对非 BMP 字符结果不正确的 bug，等他们发布了，xeCJK 的代码要做点调整。我想到时再一块提交吧。

http://tug.org/pipermail/xetex/2015-May/025941.html

**Comment by leo-liu** [comment]
目前的版本问题又出现了。

**Comment by leo-liu** [comment]
退回到旧版本问题依然存在，看来不是 `ctex` 代码造成的问题，猜测可能是 LaTeX3 参数传递机制变化造成的。因为测试表明，全局选项不再传递给使用 LaTeX3 的 `ctex` 宏包，如：
```latex
\documentclass[zihao=false]{article}
\usepackage{ctex}
\begin{document}
\makeatletter\f@size
\end{document}
```
在目前更新过的 TeX Live 2015 下会显示五号字大小，而非 10pt。

**Comment by qinglee** [comment]
这个问题是 `l3keys` 的改动造成的：https://github.com/latex3/svn-mirror/commit/48cd07c82c4a7a14d67e5ce4e2bec4bfa9118bbc

已经在开发版本中修复了：https://github.com/latex3/svn-mirror/commit/a619a73516ffb81f5cfaf6718d8fefc10669ac0e

所以咱们等 LaTeX3 的下一轮 CTAN snapshot 吧。

**Comment by leo-liu** [comment]
已经正常了。
