### ISSUE TITLE
ctex: 华文字库为啥不能支持 LaTeX - DVIPDFMx 方式？

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#191]
喵，如题……

**Comment by leo-liu** [comment]
你自己在 mac 上试试，如果行就加上。

**Comment by LiamHuang0205** [comment]
= =……
好……

**Comment by qinglee** [comment]
我以前在 OS X Mavericks 下试验的结果是，华文宋体和华文楷体可以用，其他的字体不行。这个在源代码 mac 字体集那里有记录。

不知道现在 Yosemite 的字体怎么样了，我估计依旧不行。

**Comment by LiamHuang0205** [comment]
Okay，我试试看。

**Comment by LiamHuang0205** [comment]
试了一下，确实不行，所以这个 Issue 可以关闭了。
