### ISSUE TITLE
googlecode 维基文档迁移？

### ISSUE THREAD

**Issue by alick** [CTeX-org/ctex-kit#192]
项目在 googlecode 上时，有一些维基文档，例如 https://code.google.com/p/ctex-kit/wiki/SimpleChineseTemplates 等。这些现在访问不了了，会直接定向到 github，而 github 没有这些维基。可否将它们迁移过来？

**Comment by leo-liu** [comment]
当时我看了一下，没有特别值得迁移的文档。
相对有用的是关于 ctex  宏包 1.x 版本在不同操作系统平台下的中文支持问题，这个在即将发布 2.0 中也没有必要存在了。
你举的那个，在当时也是没用的一页。

**Comment by leo-liu** [comment]
旧的 wiki 内容目前还可以从 https://ctex-kit.googlecode.com/svn/wiki/ 访问到。
我又看了一遍：
* CTeXPackage 意义不大，不如直接看手册。
* OurPackageAtCTAN 内容有用，需要更新，但应直接写入 README 中。
* SimpleChineseTemplates 目前没有用，如果需要写些什么应该放在对应目录的 README 中。
* SourceCodeGuideline 过时。目前就我们三个人，意义不大。
* SupportedSystemsInCTeXPackage 过时，不如直接看手册。
* UnixFonts 过时，已失去意义。
* XeTeXinputencoding 可能有点用。

**Comment by alick** [comment]
最初是想查一下各种编译方式输出PDF可复制可搜索的情况。确认一下，现在ctex支持的编译方式出来的PDF中文复制搜索都正常，对吧？

在 2015年5月12日 下午7:34，Liu Haiyang <notifications@github.com>写道：

**Comment by LiamHuang0205** [comment]
新版套件：

XeLaTeX 和 LuaLaTeX 的话，肯定是没问题的。

pdfLaTeX 的话，在 UTF-8 模式下工作没问题，在 GBK 模式下，需要 `ccmap.sty` 处理一下。

LaTeX - DVIPDFMx，在 UTF-8 模式下工作没问题，在 GBK 模式下，也没问题。

**Comment by LiamHuang0205** [comment]
OurPackageAtCTAN 部分加入 Repo 的 Readme 了，doc 部分等 @zohooo 加入 ctex-doc 的 Readme 吧。

**Comment by leo-liu** [comment]
不用 `ccmap`，用 `xcjk2uni`。你看 ctex 2.0 代码。

**Comment by LiamHuang0205** [comment]
哦对，是不用的。我前几天还看过，这就忘记了。

**Comment by zohooo** [comment]
无力爬墙看不到 google code，不过我记得没啥可以加入 ctex-doc 的。
