### ISSUE TITLE
ctex: scheme = chinese 的时候，应该默认载入 indentfirst 宏包

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#194]
嗯，现在的代码只有在显式声明 `indent` 选项的时候才会载入 `indentfirst` 宏包，而 `indent` 是个过时选项。

**Comment by leo-liu** [comment]
我们总不载入 `indentfirst` 宏包。标题后首段是否有首行缩进，是由 `beforeskip` 的正负号决定的。

**Comment by LiamHuang0205** [comment]
所以下面代码不缩进，这样真的好吗？



\documentclass{article}

\usepackage{ctex}

\begin{document}

\section{你好}

缩进吗？\\

不缩进？

\end{document}




—

**Comment by leo-liu** [comment]
与 \documentclass{ctexart} 的等价用法是
```latex
\usepackage[heading]{ctex}
```
目前不加 `heading` 选项就是不做相关版式修改。

**Comment by LiamHuang0205** [comment]
不对吧？heading 选项是是否打开原来 \CTEXsetup 那一套接口。不做相关版式修改应该是


\usepackage[heading = false, scheme = plain]{ctex}




当 scheme = chinese 的时候使用中文方案，我觉得还是应该有 indent first 的效果。


—

**Comment by leo-liu** [comment]
标题后是否首行缩进，这个东西就是属于标题格式的一部分，这个设置是在 `chinese` 这个 scheme 里面定义的，但这个设置是否有效则是`heading` 由选项控制开关的。参考 source2e 的 59.2 Sectioning 一节。

如果觉得 `chinese` 这个 scheme 应该有相关的功能，那也应该让这个 scheme 的代码检测到标准文档类时自动打开 `heading` 选项。

**Comment by LiamHuang0205** [comment]
这个的话，我还是认为，scheme = chinese 应该无条件加上 indent first 的效果。因为按照中文习惯，确实应该缩进。

另一方面，检查标准文档类意义不大。一方面我们不推荐这么用；二一个就算不是和标准文档类联用，和 ltxdoc 之类的文档类联用同样会有 indentfirst 的需求。

再者就是兼容性了。旧版默认开启 indent 选项，所以会有差异……


—

**Comment by leo-liu** [comment]
`ltxdoc` 也是能检测到 `article` 文档类的，因为里面有
```latex
\LoadClass{article}
```
而 `beamer` 就检测不到。

**Comment by LiamHuang0205** [comment]
改代码的时候，想了想不对啊……

`heading` 选项只能在 `ctex` 宏包与标准文档类（及其衍生物）联用的时候启用，如果为了 `scheme = chinese` 的时候 heading 之后的段落有段首缩进就自动检测标准文档类然后设置 `\l_@@_heading_bool` 为 `true` 的话，那么 `heading` 选项就没意义了嘛。

所以 2994585e3 的做法是在 `scheme = chinese` 的时候检测到标准文档类，如果检测成功，则载入 `indentfirst` 宏包。

这样一来，通过 `beforeskip` 的正负号设置 heading 后的段首缩进在使用 `ctex` 宏包且 `scheme = chinese, heading = true` 的时候依然有效。这正是期待的效果。
