### ISSUE TITLE
能否给一个ins文件，或者告诉我们如何提取sty文件和cls文件?

### ISSUE THREAD

**Issue by yangdaweihit** [CTeX-org/ctex-kit#196]
对docstrip不了解，想使用ctex2.0，能帮给点提示？

**Comment by leo-liu** [comment]
首选：
MiKTeX 运行 Update 在线更新宏包；TeX Live 安装 2015 版，用 tlgmr 更新。

次选：
去 CTAN 下载打包的版本 http://mirrors.ctan.org/install/language/chinese/ctex.tds.zip

如果你要协助开发，可以使用 `texlua build.lua ctan` 来生成。但对普通用户来说不推荐，也没有必要。

**Comment by yangdaweihit** [comment]
我的环境是Ubuntu+Texlive，看来只能用您说的次选方案。对此我还没有尝试过，不过我的理解是：将各文件夹和文件置于TDS之中，置换掉原来的ctex文件。是这样吗？如果是这样，那就可以写一个脚本，用程序实现ctex的安装。

**Comment by leo-liu** [comment]
用 Ubuntu 有什么妨碍你用第一种方案的？

还是去 http://ftp.cstug.cz/pub/tex/local/tlpretest/ 下载 install-tl 包，解压运行 install-tl，把官方版本的 TeX Live 2015 安装到你的 `$HOME` 目录就行了，或者 `sudo` 安装到 `/usr/local/`。

因为 2.0 版的 ctex 与 1.x 版本文件有差异，并不建议你直接置换（鉴于你并不懂 TDS 包）。即使手工安装也是安装到本地目录的，而不是覆盖。

**Comment by yangdaweihit** [comment]
感谢帮助。不过安装遇到问题如下。
sudo ./install-tl --gui

=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2015
 repository: 2014
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via http://tug.org/texlive/doc.)
=============================================================================

**Comment by leo-liu** [comment]
安装 pretest 要指定 repository。
用 
```
sudo ./install-tl gui -repository http://ftp.cstug.cz/pub/tex/local/tlpretest/
```
就可以了。其中 `http://ftp.cstug.cz/pub/tex/local/tlpretest/` 是捷克的镜象，支持 IPv6，我在用的是这个。
其他镜象可以见 http://tug.org/texlive/mirmon/
但不要先中国的 CTeX 镜象，吴凌云明确说了中科院那边的网管对 CTeX 网站现在有限制，下载会断掉。

**Comment by yangdaweihit** [comment]
谢谢指导。试了一下，果然可以安装。不过安装之前有个疑问，是否需要删除TeX Live2014？

**Comment by leo-liu** [comment]
可以不用删。哪个在 PATH 变量的前面就会用哪个。
如果选了在 /usr/local/bin 下面建立符号链接的话，则是看链接指向哪个用哪个。

当然了，如果 2015 用得还可以，旧的就可以卸载了（运行 2014 的 `tlmgr uninstall`）。

**Comment by yangdaweihit** [comment]
好，那我试试了。
