### ISSUE TITLE
sectsty宏包冲突

### ISSUE THREAD

**Issue by yangdaweihit** [CTeX-org/ctex-kit#197]
当使用sectsty宏包时，ctex的中文标题格式失效。

      \documentclass[UTF8]{ctexrep}
      \usepackage{sectsty}

      \begin{document}
          \chapter{前言}
      \end{document}

**Comment by leo-liu** [comment]
有 `\ctexset` 的功能，似乎没有兼容 `sectsty` 的必要。

**Comment by yangdaweihit** [comment]
是的，最好在文档中说明冲突的宏包。
