### ISSUE TITLE
microtype宏包使用expansion选项时报编译错误

### ISSUE THREAD

**Issue by yangdaweihit** [CTeX-org/ctex-kit#198]
\documentclass[UTF8]{ctexrep}
    \usepackage[expansion=true]{microtype} 
       \begin{document}
    \chapter{前言}
    \end{document}

**Comment by leo-liu** [comment]
如果你用的是 XeLaTeX 编译，烦请仔细看编译信息
```
! Package microtype Error: Font expansion does not work with xetex.
```
若有疑问，请咨询身边英文好的人。

**Comment by yangdaweihit** [comment]
没看仔细，谢谢！
