### ISSUE TITLE
在默认scheme=chinese时定制 chapter/format时编译出错

### ISSUE THREAD

**Issue by yangdaweihit** [CTeX-org/ctex-kit#199]
\documentclass[UTF8,scheme=chinese]{ctexrep}

    \begin{document}

    \ctexset{
       chapter/name = {第,回},
       contentsname = {目录},
       chapter/format += \raggedright
    }
    \tableofcontents
    \chapter{前言}
    \end{document}

**Comment by leo-liu** [comment]
那个 key 叫 `format+`，并没有一种 `+=`。所以你把空格要去掉。

**Comment by yangdaweihit** [comment]
谢谢回复，学习了。
