### ISSUE TITLE
ctex: 关于名字

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#200]
唔。

原来叫「ctex 宏包」，容易和 ctex.sty 混淆。后来 2.0 改成「CTeX 宏包」，出于同样的原因，我改成了「CTeX 套件」。但是这样又容易和「CTeX 套装」混淆。

所以趁着发布不久，还能纠正，要不然就再改一次名字好了。

现在有两个名字备选

* 宏集
* 宏包集合

两个名字都体现「宏」的概念，名称上不至于和 CTeX 套装混淆。个人倾向于「宏集」，因为简练。但是旧版 lshort-cn 的翻译里，把 format 的概念翻译成了宏集，也可能存在混淆。
不过 lshort-cn 现在看的人不多，我们也都管 format 叫格式，所以会这样混淆的人应该不多。另一方面，lshort-cn 现在也在 ctex-doc 里面，去修复一下这个问题也行。

所以我现在倾向于改称宏集。如果不妥，就改称宏包集合。
@leo-liu @qinglee 以为如何？

**Comment by zohooo** [comment]
我也觉得称为宏集更好，更简洁些。lshort-cn 的翻译就该改过来。

**Comment by LiamHuang0205** [comment]
cd6f812 改成了「宏集」。
