### ISSUE TITLE
part无法显示编号

### ISSUE THREAD

**Issue by seisman** [CTeX-org/ctex-kit#201]
TeXLive 2015 + xeLaTeX + ctex v2.0.2 + UTF8

测试代码：
~~~~~~
\documentclass{ctexbook}
\begin{document}
\part{测试}
\chapter{测试1}
\chapter{测试2}
\chapter{测试3}
\part{测试}
\chapter{测试1}
\chapter{测试2}
\chapter{测试3}
\end{document}
~~~~~~~~~~

效果图：

![screen](https://cloud.githubusercontent.com/assets/3974108/8142894/d3041c74-11c2-11e5-854c-e26b75fb8061.png)

**Comment by leo-liu** [comment]
呃，真是严重的 Bug。
大约之前测试只在 `ctexart` 上做，`ctexrep` 和 `ctexbook` 都不对。

**Comment by leo-liu** [comment]
这是已知的问题。在 5375f6c4fe2848b8bec26fccc8094c8bc1224d14 已经修复过了。请等待新版本发布。
