### ISSUE TITLE
fontset=ubuntu 时不同引擎下字体配置不太一致

### ISSUE THREAD

**Issue by alick** [CTeX-org/ctex-kit#203]
ctex/ctex.dtx:L8318-8352 

pdftex 时指定了黑体替换字体：

        \setCJKmainfont
          [ BoldFont = wqy-zenhei.ttc , ItalicFont = ukai.ttc ] { uming.ttc }

非 pdtex 下似乎忘了指定：

    \setCJKmainfont [ ItalicFont = AR~PL~UKai~CN ] { AR~PL~UMing~CN }

**Comment by leo-liu** [comment]
这个倒没什么，好改。不过 15.04 已经不预装文泉驿了，默认用 Droid Sans Fallback。
话说还真有人用这个选项啊，比 `Fandol` 差远了。

**Comment by alick** [comment]
我只是测试。不过既然提供了选项，难免有人想用啊。

Google Noto Sans CJK 即 Adobe 思源黑体替代文泉驿正黑如何？

不预装不是大问题，有需求的用户可以很容易地从软件仓库安装。

**Comment by leo-liu** [comment]
没必要。黑体质量问题不大，主要是文鼎的宋体不行。

**Comment by fyears** [comment]
（挖坟挖到这里，想了想，似乎不用开新 issue？）

>黑体质量问题不大，主要是文鼎的宋体不行。

最近思源宋体发布了，而且 Ubuntu 16.04 预装的成了思源黑体（Noto Sans CJK）。看来 Ubuntu 的设置能够改进了？

**Comment by leo-liu** [comment]
改用思源宋体当然是可以的，肯定比文鼎的报宋强，当然比 Ubuntu 根据文鼎魔改出来的 uming 更不知强到哪里去了。

但这个问题的关键是 Linux 发行版，不是 ctex 包。Linux 发行版要及时更新，预装思源宋体（当然，更可能是 Nono Serif CJK），并且把它作为中文默认字体，把 uming、ukai 赶走才行。

**Comment by leo-liu** [comment]
就简中打印来看，Fandol 还是比 uming/ukai 实用，WPS 的方正字体更实用多了。
我个人倾向于不加这种 fontset 了。Linux 发行版的中文预装字体太支离破碎了，还不如让用户自己设置。
