### ISSUE TITLE
ctex: 新版宏集关于 OS X 系统检测失效的问题

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#205]
#103 里我们用 `/mach_kernel` 的存在性检测 OS X 系统，当时的理由是：

> 该文件是 Darwin 系统的微内核，必然存在。

在 10.9.x 及之前的系统版本中，这样判定是没有问题的。不过在 10.10 之后，Apple 把它从目录根移到了别的位置。

现在考虑直接判断 `/Library/Fonts/Songti.ttc` 字体文件的存在性。理由：

1. 除了 OS X，不会有人故意往这目录里放字体，如果放了也是不值得我们处理的用户行为，所以如果该字体文件存在，那么可以认为是 OS X 系统。
2. 如果是 OS X，那么我们会调用 `Songti.ttc` 这个文件，因此检测其他文件，不如就检测它本身。

虽然有点耍赖的嫌疑，但是在搞清楚 Kernel 的情况之前，就先这么干吧？

**Comment by leo-liu** [comment]
这样挺好。

**Comment by zepinglee** [comment]
貌似改在/System/Library/Kernels/kernel了
