### ISSUE TITLE
ctex: 手册调整安装部分的说明，面向普通用户

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#206]
今天有用户发邮件问我，`ctex` 宏包怎么安装。他下载了宏包的源代码，仔细读了第 3 节“依赖与安装”，然后很自然，就彻底迷失了。

于是我意识到，这部分文档写得还是有点难。因为大部分用户是直接使用 MiKTeX、TeX Live 这样的发行版的，几乎没有用户需要自己手工安装宏包。而在手册非常靠前的第三节内容讲依赖的宏包、`zhmCJK` 什么的，其实很容易把人弄晕。

现在看是不是能把这部分东西放在手册的最后，前面把包管理器和更新什么的更详细讲一下？

**Comment by LiamHuang0205** [comment]
好。


我在赶 due，明天白天来改吧。




tlmgr 和 mpm 的话怎么写比较好？step-by-step 图文讲解似乎太繁琐了？


—

**Comment by leo-liu** [comment]
完全不急。
只是个想法。我也觉得未必要一步一步图文讲解，只要不引起歧义误解就好。我先写个知乎专栏文。
