### ISSUE TITLE
ctex: chapter/beforeskip 的值不准

### ISSUE THREAD

**Issue by qinglee** [CTeX-org/ctex-kit#207]
下面的例子显示，章标题顶部与页面顶部有一定距离，不是 `0pt`。`chapter/beforeskip` 并不是章标题顶部到页面顶部的准确距离。

```TeX
\documentclass{ctexbook}

\usepackage[showframe]{geometry}

\ctexset{chapter/beforeskip=0pt}

\begin{document}

\chapter{章标题}

\end{document}
```
LaTeX 会换新页输出章标题，因而章标题前的垂直间距是用 `\vspace*` 加上的，额外的空白间距是 `\topskip` 加上行间胶。

将 `chapter/beforeskip` 设置为负值也没有效果，因为在 `ctex` 2.0 中，`chapter/beforeskip` 的符号也被用于判断章标题后首段是否有段首缩进。

**Comment by qinglee** [comment]
修复的办法也很简单：

```diff
diff --git a/ctex/ctex.dtx b/ctex/ctex.dtx
index 22e0434..24402f6 100644
--- a/ctex/ctex.dtx
+++ b/ctex/ctex.dtx
@@ -6688,6 +6688,11 @@ This package consists of the file ctex.dtx, and the derived files
   \else
     \@afterindenttrue
   \fi
+  \par
+  \ifdim \pagetotal = \z@
+    \advance \@tempskipa -\topskip
+    \nointerlineskip
+  \fi
   \vspace*{\@tempskipa}%
 % {\normalfont \parindent \z@ \raggedright
   {\normalfont \parindent \CTEX@chapter@indent \relax \CTEX@chapter@format
@@ -6721,6 +6726,11 @@ This package consists of the file ctex.dtx, and the derived files
   \else
     \@afterindenttrue
   \fi
+  \par
+  \ifdim \pagetotal = \z@
+    \advance \@tempskipa -\topskip
+    \nointerlineskip
+  \fi
   \vspace*{\@tempskipa}%
 % {\normalfont \parindent \z@ \raggedright
   {\normalfont \parindent \CTEX@chapter@indent \relax \CTEX@chapter@format
```
但如此一来，与旧版本 `ctex` 不兼容，对旧文档的版式影响是比较大的。

**Comment by leo-liu** [comment]
诶，我上午的回复呢？

之前回复了 `titlesec` 也有这个问题。

**Comment by qinglee** [comment]
book 和 report 类的 `part/beforeskip` 也存在同样问题。而其他各级标题的 `beforeskip` 都会在标题换页时丢失，没有效果。

**Comment by shifujun** [comment]
我就是为了修复这个问题才改的内部命令\@makechapterhead。才导致现在v2.3中aftername失效的。。。

**Comment by Liam0205** [comment]
那么你当时应该做的是过来提 Issue，而不是修改内部代码。
内部代码是不保证兼容性的。

在 2016年3月6日 下午1:23，shifujun <notifications@github.com>写道：

**Comment by leo-liu** [comment]
关于这个问题，是不是可以加上个类似 `fix-beforeskip` 之类的选项，默认关闭？
或者默认打开似乎也不是不可以，既然不准，2.x 以后应该没有人依赖这个准确值。1.x 不用考虑兼容性。

**Comment by qinglee** [comment]
嗯。就需要考虑 `chapter` 的情况就可以了，`section` 类的 `beforeskip` 在换页时自动丢失看起来还是一个好的性质就不想去处理了。

那就默认打开，一通模板作者可能又来抱怨了……

**Comment by FurongPeng** [comment]
问题解决了吗？

**Comment by jiaopjie** [comment]
最近使用 `ctex` 注意到这个问题. 不知道这个是否作了修改. 不过似乎新版本里这个值还不是准确的. 二楼 qinglee 的解决办法我当然看不懂.

似乎 `\vspace*{0pt}` 也总是执行分段. 所以像顶楼说的, 这个距离是第一行基线到文档顶端的距离加上一个行间距.

我觉得, 但如果章总是分页的话, 不需要考虑章标题的开始是不是一个新段落. 所以, 可不可以使用一个 `0pt` 宽的 `\rule` 顶起这个距离. 似乎这个距离总是正确的.

把 `\vspace*{\beforeskip}` 换成 `\rule{0pt}{\beforeskip}\\` 是不是个可行的方法. 当然章标题这一行并不是一个段落的第一行了. 但章标题不需要缩进, 我觉得似乎是没有问题的.

还是希望能解决这个问题. 我们用户用起来也顺手.

**Comment by qinglee** [comment]
新的选项 `part/fixbeforeskip` 和 `chapter/fixbeforeskip` 用于解决这个问题，出于兼容性考虑，默认还是关闭的。

**Comment by jiaopjie** [comment]
我是外行了, 说的可能很外行. 这里说的 "段前xxcm" 指的是

(1) 把文档页心顶端线当做上一行的基线, 在这个行距的基础上增加 xxcm

还是

(2) 当前行的顶端到页心顶端线的距离加上 xxcm

呢? 似乎这里是按 (1) 处理的吧? 我承认一直我都以为新页面的情况下是按 (2) 来理解的......

**Comment by qinglee** [comment]
我们在代码实现中使用了 `\nointerlineskip`，就是为了实现你说的 (2)，否则就会退化为 (1)。

**Comment by qinglee** [comment]
这里还应该再减去 `\parskip`。因为用了 `\vspace*` 后，页面上已有内容，章标题会进入水平模式开始新段，就会加上 `\parskip`。

**Comment by jiaopjie** [comment]
以前不知道 `\nointerlineskip` 这个命令. 试了一下, 的确看到了效果. 这个参数 `fixbeforeskip` 的作用层次是怎样的呢. 是在略底层的 `ctexpatch, ctexheading` 这类的包里面就有了这个参数, 还是在略底层的包里直接把 `\topskip` 和 `\parskip` 减去, 底层包里不要这个参数, 然后在 `ctex` 上层包里按 `fixbeforeskip` 的设置再加上修正值呢.

**Comment by qinglee** [comment]
@jiaopjie  我其实不明白你的意思。我们重定义了标准文档类的几乎所有与章节标题有关的命令，要修改自然是在这个层面修改。`fixbeforeskip` 的就是在 `beforeskip` 的基础上减去 `\topskip` 和 `\parskip`，然后应用 `\nointerlineskip` 抑制行间胶。这是一个用户选项，设置方式没什么特别的：
```TeX
\ctexset { chapter/fixbeforeskip = true }
```

**Comment by jiaopjie** [comment]
嗯，我就是用户水平。我是想说是否 `fixbeforeskip` 选项的作用范围只限制在 `tex` 上层包，直接使用 `ctexheading` 时直接就是修正后的值，`fixbeforeskip` 对 `ctexheading` 来说是未定义的选项？

**Comment by qinglee** [comment]
不是，`fixbeforeskip` 和 `beforeskip` 一样，都是需要通过 `\ctexset` 来设置，默认值是 `false`，需要自行设置为 `true` 才是修正后的结果。

**Comment by jiaopjie** [comment]
关于兼容性，我原本觉得 “在 `ctexheading` 层面直接把多余的空白减掉，不考虑兼容性，在 `ctex` 层面设置个 `fixbeforeskip` 参数，如果值是 `false` 的话，再把减掉的空白加回去“ 会比较好。我这么觉得可能是因为我没有从代码层看起。

但在现在的解决办法的基础上，是不是也可以考虑 “在 `scheme = chinese` 的情况下把 `fixbeforeskip` 默认值设为 `false`，而在 `scheme = plain` 情况下设为 `true`” 呢？这对兼容性影响应该不大吧？
