### ISSUE TITLE
ctex: 不使用 beforeskip 和 afterskip 选项的符号作为标志

### ISSUE THREAD

**Issue by qinglee** [CTeX-org/ctex-kit#208]
目前，`ctex` 遵循 LaTeX 的标题参数意义，`beforeskip` 的符号用于确定标题后首段是否缩进，`afterskip` 的符号用于确定 section 类标题与后面正文是否排在同一段。

现在来看，最好还是用独立的选项来完成这两个功能。拟引入相应的 `bool` 选项 `afterindent` 和 `runin`。

**Comment by leo-liu** [comment]
问题是又会造成不兼容吧

**Comment by qinglee** [comment]
我想这个兼容性好解决，改个符号就行，不像 #207 要改具体的数值。

**Comment by leo-liu** [comment]
问题在于可能会影响少量用户代码。不过估计现在还不多。

**Comment by qinglee** [comment]
嗯，我们得在新手册中加以说明，引导用户改符号。
