### ISSUE TITLE
ctex: 宏集提供的 \chinese 命令与 enumitem 宏包联合使用时失效

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#209]
MWE:

    \documentclass[UTF8]{ctexart}
    \usepackage{enumitem}
    \begin{document}
    \begin{enumerate}[label = \chinese*、]
      \item 编号
      \item 项目
      \item 使用
      \item 中文
    \end{enumerate}
    \end{document}

报错：

    ! Undefined control sequence.
    <argument> \LaTeX3 error: 
                               `*' is not a LaTeX counter.
    l.5 \begin{enumerate}[label = \chinese*、]
                                               
    ?

**Comment by leo-liu** [comment]
```
\AddEnumerateCounter{\chinese}{\chinese}{}
```

**Comment by qinglee** [comment]
要给 `enumerate` 注册 `\chinese`:

```TeX
\AddEnumerateCounter*{\chinese}{\zhnumber}{1}
```

**Comment by leo-liu** [comment]
我其实不大明白 `enumitem` 中 `\AddEnumerateCounter` 第二个参数的意义何在。大约是对带星的格式，第二个参数与第三个参数一直做宽度计算；对不带星的格式，第三个参数直接得到宽度就好了，第二个参数没看出什么意义啊。

主要也是不想细看那个源代码。

**Comment by LiamHuang0205** [comment]
喵？
原来似乎不需要这么做？

**Comment by qinglee** [comment]
第一个参数（`#1`）接受 LaTeX 计数器名字，第二个参数（`#2`）的命令要在第一个参数的实现中使用到才有意义，接受实际整数。

`enumitem` 有时候（比如设置 `leftmargin=*`）需要量取标签的最大宽度，大约是这么来做的：

* 如果在列表选项中设置 `widest`，则重定义 `#2` 为选项 `widest` 的值来量取宽度。
* 如果没有设置 `widest` 选项，
  * 带星号的 `\AddEnumerateCounter` 将 `#2` 作用到 `#3` 上，再将它们重定义为 `#2` 来量取宽度。
  * 不带星号的 `\AddEnumerateCounter` 就是直接将 `#2` 重定义为 `#3` 来量取宽度。

所以我们上面的两种设置方法都欠妥当，应该是

```TeX
\AddEnumerateCounter{\chinese}{\chinese}{\quad}
```

或者

```TeX
\ExplSyntaxOn
\AddEnumerateCounter*{\chinese}{\zhnum_int:n}{1}
\ExplSyntaxOff
```
