### ISSUE TITLE
无法修改chapter标题字号

### ISSUE THREAD

**Issue by seisman** [CTeX-org/ctex-kit#210]
TeXLive 2015 + ctex 2.1

测试代码：
~~~~
\documentclass[zihao=-4]{ctexbook}
\ctexset{
    chapter/format = \zihao{4},
    section/format = \zihao{4},
}
\begin{document}
\chapter{章标题}
\section{节标题}
\zihao{4}四号
\end{document}
~~~~

效果：

![screenshot](https://cloud.githubusercontent.com/assets/3974108/8430394/7dd0b9d4-1f63-11e5-8e88-37a94237c29e.png)

section的字号可以修改，测试了一下让chapter左对齐也可以，好像只有chapter的字号不能修改。

**Comment by qinglee** [comment]
对标题格式的控制，除了 `format` 选项之外，还有 `nameformat`、`numberformat` 和 `titleformat`。这三个选项都在 `format` 之后起作用。

这里改字号对 chapter 标题无效，是因为它的 `nameformat` 和 `titleformat` 默认值都是 `\huge\bfseries`，里面的 `\huge` 会覆盖你设置的 `\zihao{4}`。需要先清空 `nameformat` 和 `titleformat` 的设置：

```TeX
\documentclass[zihao=-4]{ctexbook}
\ctexset{
    chapter/format      = \zihao{4}\bfseries,
    chapter/nameformat  = {},
    chapter/titleformat = {},
    section/format      = \zihao{4},
}
\begin{document}
\chapter{章标题}
\section{节标题}
\zihao{4}四号
\end{document}
```

**Comment by qinglee** [comment]
@leo-liu 在中文版式中，`part` 和 `chapter` 标题的 `nameformat` 和 `titleformat` 的初值是一样的，我觉得将它们都置为空值，原初值统一放在 `format` 选项的初值中比较合适。

**Comment by seisman** [comment]
明白了，多谢您的回复。

**Comment by seisman** [comment]
ctex的文档中第14页中有一个typo，`subsubsection`敲成了`subsubsecton`。

![screenshot from 2015-06-30 21 02 17](https://cloud.githubusercontent.com/assets/3974108/8431338/53e10f04-1f6b-11e5-8b46-9c8d44384462.png)

因为没找到文档的源码在哪里，所以就顺便在这里提一下这个Issue。

**Comment by leo-liu** [comment]
嗯，如果都一样就不用分成两个 format 设置了。英文有差别，中文合并也好。
