### ISSUE TITLE
无法修改单个标题的对齐方式

### ISSUE THREAD

**Issue by seisman** [CTeX-org/ctex-kit#213]
ctex默认设置section的标题的对齐方式为`\centering`。

下面的代码中想要把带星号的section标题设置为左对齐，但是却没有效果：
~~~~tex
\documentclass[UTF8]{ctexart}
\begin{document}

\section*{\raggedright 带星号的标题}
正文

\section{标题测试}
正文
\end{document}
~~~~

之前的ctex2.1是正常的，更新到ctex2.2之后代码就不能把标题左对齐了。

**Comment by leo-liu** [comment]
你这用法本来也不对啊。2.2 版 `titleformat` 选项加了花括号可以把标题当参数来用，于是在 `titleformat` 为空时就多出一个分组，所以你这种错误代码就不再能用了。

你可以考虑直接用 `\ctexset` 重设格式。

**Comment by seisman** [comment]
`\ctexset`设置的是section标题的全局格式。

我希望实现的效果是，大多数section的标题都居中，个别section的标题左对齐。所以可以用
~~~tex
\ctexset{
    section/format += \centering,
}
~~~
来设置全局section标题的居中（默认的对齐方式也是这个）。但是如何修改个别section标题的对齐方式呢？我试了一下，在不使用ctex的英文文档中，是可以用这种方式修改个别标题的对齐方式的。

**Comment by leo-liu** [comment]
`\ctexset` 可以在正文中使用。你可以在需要的 `\section` 命令前面设置 `\ctexset`，把它们放在一个分组里面就行。或者用完了恢复。

不过按你现在的需要，最好的办法是新定义一个与 \section 无关的命令。

**Comment by seisman** [comment]
了解了，多谢～
