### ISSUE TITLE
xeCJK: PunctStyle = quanjiao 时，中文弯角引号宽度不足一个汉字宽度

### ISSUE THREAD

**Issue by LiamHuang0205** [CTeX-org/ctex-kit#214]
文档：

> quanjiao 全角式:所有标点占一个汉字宽度,相邻两个标点占 1.5 汉字宽度;

但实际上设置 `PunctStyle = quanjiao` 并没有起作用。

```TeX
%!TEX program = xelatex
\documentclass{article}
\usepackage{xeCJK}
\xeCJKsetup{PunctStyle = quanjiao}
\begin{document}
汉字“U”汉字
\end{document}
```

似乎是文档与实现不一致的问题。

反馈来自马起园的 ApTeX QQ 群。

**Comment by qinglee** [comment]
这是 Fandol 字体的锅。

Fandol 字体的西文部分是 cm-unicode，但 CTAN 上发布的 1.200 版没有对一些中西文共用的标点符号调整为中文宽度。这里的引号就是这种情况。1.300 改进了。所以你们赶紧提交新版本。

-----

xeCJK 默认取的是原标点宽度的比例（`fixed-punct-ratio`），全角就是 `1`。改成宽度也可以规避这个问题，即

```TeX
\xeCJKEditPunctStyle{quanjiao}{fixed-punct-width=1em}
```

但这个作为默认设置的话，不适用于“方正兰亭长”这种汉字宽度不等于字体 `1em` 的字体。

**Comment by LiamHuang0205** [comment]
我看了下，华文宋也是这么个样子，方正书宋倒是没问题。

我去吼马起园……
