### ISSUE TITLE
ctex: 无权访问 boot.ini

### ISSUE THREAD

**Issue by ghost** [CTeX-org/ctex-kit#215]
QQ 群（31752345）反馈：

Win7, CTeX 2.0.2

```TeX
\documentclass{ctexart}
\begin{document}
测试
\end{document}
```

log:

```Text
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "article.tex"
Startup Folder: C:\Users\lenovo\Desktop\作业

This is XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./article.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(d:/texlive/2015/texmf-dist/tex/latex/ctex/ctexart.cls
(d:/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3.sty
(d:/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(d:/texlive/2015/texmf-dist/tex/latex/l3kernel/l3unicode-data.def)
(d:/texlive/2015/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
Document Class: ctexart 2015/05/16 v2.0.2 Chinese adapter for class article (CT
EX)
(d:/texlive/2015/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(d:/texlive/2015/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(d:/texlive/2015/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(d:/texlive/2015/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(d:/texlive/2015/texmf-dist/tex/latex/base/fix-cm.sty
(d:/texlive/2015/texmf-dist/tex/latex/base/ts1enc.def))
(d:/texlive/2015/texmf-dist/tex/latex/ms/everysel.sty)
(d:/texlive/2015/texmf-dist/tex/latex/ctex/config/ctexopts.cfg)
(d:/texlive/2015/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(d:/texlive/2015/texmf-dist/tex/latex/base/size10.clo))
(d:/texlive/2015/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def
(d:/texlive/2015/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(d:/texlive/2015/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
(d:/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec.sty
(d:/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec-patches.sty)
(d:/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(d:/texlive/2015/texmf-dist/tex/latex/base/fontenc.sty
(d:/texlive/2015/texmf-dist/tex/latex/euenc/eu1enc.def)
(d:/texlive/2015/texmf-dist/tex/latex/euenc/eu1lmr.fd))
(d:/texlive/2015/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(d:/texlive/2015/texmf-dist/tex/latex/tipa/t3enc.def
(d:/texlive/2015/texmf-dist/tex/latex/euenc/eu1lmss.fd))
(d:/texlive/2015/texmf-dist/tex/latex/graphics/graphicx.sty
(d:/texlive/2015/texmf-dist/tex/latex/graphics/keyval.sty)
(d:/texlive/2015/texmf-dist/tex/latex/graphics/graphics.sty
(d:/texlive/2015/texmf-dist/tex/latex/graphics/trig.sty)
(d:/texlive/2015/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(d:/texlive/2015/texmf-dist/tex/xelatex/xetex-def/xetex.def))))
(d:/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(d:/texlive/2015/texmf-dist/tex/xelatex/xecjk/xunicode-addon.sty)
(d:/texlive/2015/texmf-dist/tex/xelatex/xunicode/xunicode.sty
*** Reloading Xunicode for encoding 'EU1' ***
) (d:/texlive/2015/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def)
(d:/texlive/2015/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
(d:/texlive/2015/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty
(d:/texlive/2015/texmf-dist/tex/generic/ulem/ulem.sty)
(d:/texlive/2015/texmf-dist/tex/latex/environ/environ.sty
(d:/texlive/2015/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(d:/texlive/2015/texmf-dist/tex/latex/cjk/texinput/CJKfntef.sty)))
(d:/texlive/2015/texmf-dist/tex/latex/zhnumber/zhnumber.sty
(d:/texlive/2015/texmf-dist/tex/latex/zhnumber/config/zhnumber-utf8.cfg))
(d:/texlive/2015/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-chinese-article.d
ef (d:/texlive/2015/texmf-dist/tex/latex/ctex/config/ctex-name-utf8.cfg))
(d:/texlive/2015/texmf-dist/tex/latex/ctex/ctex-c5size.clo)
(d:/texlive/2015/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windows.defc:/boot.ini: Permission denied
xelatex.exe: 
```

似乎是因为 Win 7 的 Users 用户组在 C 盘根目录没有相应权限。
这样一来，#103 里用 `C:/boot.ini` 检测 Vista 之前的 Windows 的方案还需要修改。

**Comment by leo-liu** [comment]
怎么读权限都没有……
能不能还是直接检测字体文件？XP Sp3 是不是已经有微软雅黑但仍然用的是 GB2312 的仿宋、楷体啊？

我的 XP 虚拟机都删了好久了。

**Comment by LiamHuang0205** [comment]
这个权限问题我不是太清楚。

群里有人解释：

Win7 的 Users 用户组有在 C 盘根目录创建子目录的权限，但是没有创建文件的权限。因为 `boot.ini` 本身不存在，所以不仅涉及到读权限，还涉及到创建文件的权限。

不知道是否靠谱。

--------

我觉得检测 Windows 版本的新旧意义不大吧，我们关心的还是怎么配置字库就好了？

1. 判断是否存在雅黑
  1. 若存在，则 `\setCJKsansfont` 设置为雅黑，同时加一下 zhyahei 这个 CJKfamily
  2. 若不存在，则设置为中易黑体
2. 涉及到楷书和仿宋的设置一律用字体文件名

似乎这样就好了？

**Comment by leo-liu** [comment]
NTFS 权限我清楚，我不清楚的只是 XP 下普通 User 用户在根目录下具体有哪几个权限而已。
问题的关键不是雅黑，是仿宋和楷体。当然还可以回到旧版本的方案用字体文件名处理。

**Comment by LiamHuang0205** [comment]
现在想想还是用什么就检测什么，这样的方式比较靠谱。

比如 Mac 检测用 `STSong.ttc`，大小写检测用当前文件名。检测到了立马就能用，不能用的也不可能检测到。

**Comment by leo-liu** [comment]
我意思是说靠字体文件名检测解决不了 `KaiTi_GB2312` 与 `KaiTi` 的问题。

**Comment by LiamHuang0205** [comment]
我知道呀……所以我刚才就是说，楷书和仿宋用文件名去调用。

**Comment by leo-liu** [comment]
文件名调用的缺点是，非 Windows 系统非常难用：
1. 字体需要放在指定的地方（如 `texmf-local` 或 `~/.texlive2015` 下的对应目录，或者设置了 `OSFONTDIR` 的目录）。要知道 `kpathsea` 库默认是不会搜索诸如 `~/.fonts/` 这样的目录的。
2. 区分大小写。

这些缺点正是当时改用字体名而不是文件名的动机。

**Comment by LiamHuang0205** [comment]
额……

那时候 CTeX 宏集没有检测操作系统的能力，而现在有了。于是问题可以绕过了呀。

我们先检测操作系统，确定了 Mac、Windows 和 Others。
`boot.ini` 的权限问题是在检测 `windowsnew` 和 `windowsold` 的时候发生的——也就是说，此时已经确定是 Windows 了。因此这时候用字体文件名（是在 Windows 系统里，）就没有问题了。
至于 Mac 和 Others，当然是保持现状了。

**Comment by leo-liu** [comment]
那 `windowsnew` 和 `windowsold` 各自都要分用字体名和字体文件名两种设置方式了。也未尝不可。

**Comment by leo-liu** [comment]
由于中文不设置粗斜体，在正文中遇到需要使用粗斜体的地方，fontspec 使用字体文件名会丢失 NFSS 警告，而使用字体族名则能正确警告。
见 https://bdwm.net/bbs/t.php?MathTools/M.1461417900.A/4212/0/0

从这点来看，fontspec 避免使用字体文件名比较好。

**Comment by qinglee** [comment]
fontspec 自动设置字形是通过给字体名称加 `/B`、`/I` 等选项，然后比较得到的 `\fontname`，如果 `\fontname` 相同，就不设置字形。但是 XeTeX 的这种特性应该是只对字体内部名称有效，对文件名无效。所以使用文件名时，得到的 `\fontname` 总是不同的：
```TeX
\font\1="[cmunrm.otf]" at 10pt
\font\2="[cmunrm.otf]/B" at 10pt
\message{<\fontname\1|\fontname\2>}
\bye
```
事实上，fontspec 也不支持方括号使用字体文件名的底层语法。待设置的字形，要么全部都是字体内部名称，要么全是带 .ttf 等后缀或者指定 Extension 选项的文件名。不能诸如 SimSun 和 [simkai.ttf] 形式的混用，会造成误导。

**Comment by leo-liu** [comment]
不知道还有没有这个问题，似乎可以改用从 Vista 开始引入的字体文件 `segoeui.ttf` 判断。

**Comment by qinglee** [comment]
嗯，不能排除某些用户在 XP 上自己装 `segoeui.ttf`。我觉得这种概率比动系统文件 `boot.ini` 要大得多。

这里的问题是他有 `C:/boot.ini` 这个文件，但是权限给弄乱了，连普通读取的权限都没有。这种特殊情况，我都不想去处理了。或者我们换个文件，换成 `bootmgr` 或者 XP 的 `NTLDR`。

**Comment by leo-liu** [comment]
开了个全新的中文 XP SP3 虚拟机试了一下，Guest 帐户下，`C:\boot.ini` 确实不能访问，`ntldr` 也不行。这个不是权限弄乱了，本来低权限用户的设置如此。因此还是需要处理的。

根目录下，可以由 Guest 访问的只有开机启动菜单用的中文字体 `bootfont.bin` 文件。虽然可以被删除，但正常不会。这个文件可以作为备选。

其他目录应该能可以找到更多被 Guest 访问的特征文件，不过 `bootfont.bin` 在 C 盘根目录的好处是，个别人会把系统安装目录由默认的 `WINDOWS` 改成别的（如 `WINNT`，来自 NT4 的命名）。而根目录文件不受影响。
但缺点也很明显，只有中文操作系统会有这个文件，英文系统即使加了语言包也没这个文件。

用文件名判断系统版本，误判当然是不可避免的，不过随着 XP 用户不断减少，我们希望尽量减小对新系统用户的误判。即可以允许把一些 XP 旧系统误当成新系统，而不希望把 Vista 以后的新系统误判为旧系统。因此，选择 XP 下的特征文件比选择 `C:\Users\desktop.ini` 这种新系统下的特征要好些。

暂时忽略英文版 XP 用户，用 `C:\bootfont.bin` 吧。
