### ISSUE TITLE
Mac下的默认的\setCJKsansfont为什么是STXihei

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#216]
我用 \sffamily 调用黑体时，看来看去总觉得太细。
我想STXihei毕竟设计时就被定义粗度为light，\setCJKsansfont调用的应该是regular粗度吧。
还有Mac下\heiti命令实际用的是STHeiti，跟CJKsansfont不一样，这看起来有些矛盾。

**Comment by LiamHuang0205** [comment]
STXihei 的比划粗细和 STSong 的笔画粗细差不多，作为 `rmfamily` 和 `sffamily` 的默认字体恰恰好。

至于 `\heiti` 和 `\sffamily`，本来他俩就没有必然的关系。
