### ISSUE TITLE
\CTEXthechapter 在 \appendix 之前的bug

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#217]
这是我的代码：
```
\documentclass[UTF8]{ctexbook}
\usepackage{titleps}
\newpagestyle{main}{\sethead{}{\CTEXthechapter\quad\chaptertitle}{}}
\pagestyle{main}
\ctexset{chapter/pagestyle = main}

\begin{document}
\mainmatter
\chapter{First}
\chapter{\bibname}
\appendix
\chapter{blee blee blee}
\end{document}
```
参考文献那一章的页眉显示“附录 参考文献”，这不对啊；
如果把 `\CTEXthechapter` 换成 `\thechapter`，页眉会显示“2 参考文献”，这才是正确的计数
另外 `\CTEXthechapter` 是在哪里定义的？

**Comment by leo-liu** [comment]
应该是 `\CTEXthechapter` 展开较晚造成的问题。它会展开为 `\CTEX@prechapter \CTEX@thechapter \CTEX@postchapter`，定义时机不大对造成的。因为 `\appendix` 中会修改这几个宏，而页眉的排版会晚于 `\appendix` 命令，造成问题。

作为临时的解决方案，在 `\appendix` 之前加上 `\cleardoublepage` 就好了。或者你给 `\appendix` 命令的后面加上 `\cleardoublepage`。

在 `ctex` 中我暂时没想到好的办法处理各种可能的情况。理论上来说附录应该属于 `\backmatter`，而在 `\backmatter` 里面确实也有 `\clearpage` 或 `\cleardoublepage` 避免此类问题的存在。不过 `\backmatter` 会默认禁用编号，所以自己重定义一下 `\backmatter` 或许是语义上比较好的做法。

**Comment by zepinglee** [comment]
谢谢！
我现在的解决方案就是用的\cleardoublepage
