### ISSUE TITLE
xeCJK在fontspec v2.4e下无法运行

### ISSUE THREAD

**Issue by xieyh11** [CTeX-org/ctex-kit#221]
```tex
\documentclass[a4paper]{article}

\usepackage{xeCJK}
\usepackage{amsmath}

\setmainfont{times}[Extension=.ttf,BoldFont=*bd,ItalicFont=*i,BoldItalicFont=*bi]
\setCJKmainfont[AutoFakeBold=true,AutoFakeSlant=true]{simsun.ttc}

\title{各系列ISO/DIN纸张的格式\\（以毫米及英寸显示）}
\author{维基}
\date{}

\begin{document}
\maketitle
\end{document}
```
上面的tex文件在fontspec 2.4e后就无法编译通过了

**Comment by LiamHuang0205** [comment]
`\xetex_suppressfontnotfounderror:D` 取消了定义导致了这个问题，大概得等 `fontspec` 去修复了。

**Comment by LiamHuang0205** [comment]
看了一下，似乎是 `fontspec` 的作者 release 发早了。

`\xetex_suppressfontnotfounderror:D` 在 expl3 里还是个开发版本的命令，但是 `fontspec` 已经在 CTAN release 里用上了，于是就未定义了。

Quick fix:

```tex
%!TeX program  = xelatex
\documentclass{minimal}
\expandafter\let\csname xetex_suppressfontnotfounderror:D\endcsname
  \suppressfontnotfounderror
\usepackage{fontspec}
\setmainfont{Times New Roman}
\begin{document}
hello world!
\end{document}
```

**Comment by LiamHuang0205** [comment]
See wspr/fontspec#215.

**Comment by vvilp** [comment]
ctex 也无法使用了！！！请务必尽快修复

\usepackage[UTF8, heading = false, scheme = plain]{ctex}

latexmk -pdf  -xelatex -output-directory=./build -shell-escape report.tex

**Comment by LiamHuang0205** [comment]
@vvilp 已经标注了 wontfix，这不是我们的问题，不由我们来修复。

急用的话，上面我也给了 quick fix，自己用就好了。急什么…

**Comment by LiamHuang0205** [comment]
已经标了 wontfix，不是我们的问题，我们也没法修复。

之前已经给了 quick fix。急用的话，简单打个补丁就好了。约瑟夫已经推送了更新，最慢两天后再更新 tlmgr 就可以了。

不要急。

发自我的 iPhone
