### ISSUE TITLE
在您网站共享的中科院学位论文宏包出现了兼容性问题。

### ISSUE THREAD

**Issue by BlueBirdHouse** [CTeX-org/ctex-kit#223]
您在网站http://www.ctex.org/PackageCASthesis共享的学位论文宏包功能完善，
是我开始学习Latex最重要的教材之一。
      我一直利用MikTex自带的升级程序，保持各种宏包的最新版本。
      但是随着升级，最近您的学位论文宏包出现了兼容性故障，我学习浅薄，没有能力修复。
      向您提出如下问题：
      1. 常见的指令在编译时出现了未定义错误，比如
      Undefined control sequence. \begin{abstract}
      同时出现的还有
      Undefined control sequence. \begin{resume}
      Undefined control sequence. \begin{thanks}
      
      2.部分宏包提示使用了过时的命令
      ctex warning: "deprecated-option" Option `cs4size' is deprecated. Option `zihao=-4' is set.
      ctex warning: "deprecated-option" Option `fancyhdr' is deprecated. `fancyhdr' package is loaded.
      ctex warning: "deprecated-option" Option `fntef' is deprecated. `(xe)CJKfntef' package is always loaded.
 
      向您请教您如何修正这些错误。
      祝：万事如意
      BlueBird

**Comment by leo-liu** [comment]
CASthesis 不是集体开发的，而是 @wulingyun  研究员个人开发，代码也不在 github 上托管。
提示的警告至少在目前为止不会影响效果。错误不太清楚。

**Comment by mirguest** [comment]
您好!

这个问题似乎和 http://bbs.ctex.org/forum.php?mod=viewthread&tid=78610 中的相似.

**Comment by leo-liu** [comment]
@mirguest 今天的 `ctex` 包已经更新很多次了，论坛帖子里面还是 1.02c 版本，而现在是**不保证与旧版本兼容**的 2.2 版本。

`ctex` 包更新时已尽力保证文档中公开的命令（不带 `@` 的命令）在新版本中仍能使用且功能相同。但这里的错误多半来自于旧模板使用了旧版本 `ctex` 包中的内部命令。当然现在也没必要弄清楚。

由于 `ctex` 包是上游包，所以只能是由科学院的用户来修改更新 `CASthesis` 以满足新版本的要求。

**Comment by mirguest** [comment]
@leo-liu 好的，谢谢！
