### ISSUE TITLE
xeCJKcaption命令没了之后怎么包含cpx文件

### ISSUE THREAD

**Issue by zhuzhongshu** [CTeX-org/ctex-kit#224]
我们学校毕业论文的模板里面有一个cpx文件，使用CJKcaption或xeCJKcaption命令包含进来的，但是新版的xeCJK没有这个命令了，那么cpx文件该怎么处理呢？

**Comment by LiamHuang0205** [comment]
#141 里取消了 `\xeCJKcaption`。

这种从 `CJK` 继承过来的老式方案，一则不属于 `xeCJK` 应当处理的问题，二则现有的方案已能涵盖过去 `cpx` 文件处理的问题而且处理得更好。

所以，没办法，或者也不需要办法。
