### ISSUE TITLE
xeCJK: 将 U+2013 (en-dash) 加入中文标点

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#225]
目前 U+2014 (em dash)，即破折号是中文的 FullRight 类，这个正常。
U+2015 (horizontal bar) 也是 FullRight 类，这个不知道在哪里会用到？

而 U+2013 (en dash) 与破折号似乎可以一并处理以示一致。

据 GT/T 15834-2011《标点符号用法》4.13 节，新加了“连接号”，有短横线（应该是英文 hyphen）、一字线（em dash）、浪线（全角～）三种。
http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf

但按《夹用英文的中文文本的标点符号用法（草案）》5.13 节，则又提到有半字线连接号形式（en dash），并与一字节（em dash）和英文连字符（-）各不相同。
http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113092346124.pdf

因此，把 U+2013 (en dash) 作为中文标点的连接号来使用也是有道理的，使用起来表示复合名词如“吐鲁番–哈密盆地”也比使用英文连字符效果好些。

在字体方面，常用的 Windows 宋体、仿宋、黑体、楷体都把该字符设置为固定全角宽度，而较新的雅黑、等线（Office 2016 默认）则把 en dash 设置为全角宽度。

为了能在各种字体下正常使用中文连接号，目前的 xeCJK 需要按如下方式设置：
```latex
% U+2013 en dash
\xeCJKDeclareCharClass{FullRight}{`–}
\xeCJKsetup{MiddlePunct+={–}}
\xeCJKsetwidth{–}{0.5em}
```
感觉 xeCJK 也可以按此方式修改默认设置。

兼容性方面，如果英文的 en dash 用两个 `-` 即 `--` 输入，就不受影响。这与中文破折号的情形类似。

**Comment by qinglee** [comment]
嗯，挺合理的。

U+2015（包括 U+2500 (box drawings light horizontal)）作为中文标点确实不合适，现在应该删去。
