### ISSUE TITLE
ctex: 考虑提供 beamer 部分翻译，加强 beamer 支持

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#226]
目前 `beamer` 在配合使用 `ctex` 包时，有如下文字没有翻译，且普通用户较难自己翻译的：

* 定理类环境，如 `theorem` 环境生成的 `Theorem`
* 可断页的帧在续页标题中产生的 `cont.`
* 节名 `\sectionname` 和 `\subsectionname`
* 证明的 `\proofname`

其中定理类环境使用较多，影响比较广。`\proofname` 来自于 `amsthm` 包，在其他地方也会使用。

`beamer` 有自己的翻译机制 `translator.sty`，用法类似于 C 的 `gettext` 库。在有 `babel` 包时，会调用对应语言的翻译。在 `beamer` 源代码中搜索 `\translate` 命令的使用，可以查到其中用涉及到的各处翻译。除了上面提到的，还有就是 `\contentsname` 等已经在 `ctex` 中翻译的词。

`ctex` 支持中文不涉及 `babel` 的语言选择，通常中文幻灯片也不需要多语言支持，因此没有必要支持 `translator` 包的语言管理机制。可以直接重定义一些翻译，如原来 `beamerbaseframesize.sty` 中的
```latex
\newcommand\insertcontinuationtext{(\translate{cont}.)}
```
可以直接像 `\contentsname` 一样重定义。

另一方面，定理类环境也可以使用 `translator` 包的 `\deftranslation` 或 `\newtranslation` 命令对定理类环境重定义。

最后，`\sectionname` 等宏被用于 `\sectionpage`、`\subsectionpage`、`\partpage`。可能需要修改对应的 template，比较麻烦。

相比 `beamer` 为 12 种语言定义的翻译字典，实际用在 `beamer` 项目中的多语串不多，工作量不大。

需要考虑的实现问题：

1. UTF-8、GBK 双编码。
2. 是否要定义新的 ctex/key？倾向于不定义。
3. 受 `scheme=chinese` 选项控制。

目前对于普通用户的处理办法（未考虑 `\sectionpage` 等翻译）：
```latex
\newtranslation{Example}{例}
\newtranslation{Examples}{例}
\newtranslation{Theorem}{定理}
\newtranslation{Corollary}{推论}
\newtranslation{Fact}{事实}
\newtranslation{Lemma}{引理}
\newtranslation{Problem}{问题}
\newtranslation{Solution}{解}
\newtranslation{Definition}{定义}
\newtranslation{Definitions}{定义}
\renewcommand\proofname{证明}
\renewcommand\insertcontinuationtext{(续)}
```

**Comment by qinglee** [comment]
按现在的实现，`\partpage` 等模板也可以通过 `\ctexset` 来设置部分内部格式，可能不怎么实用，但聊胜于无吧。另外还提供了 `translator` 包的完整定理名称翻译，其中 `Comment` 和 `Remark` 的翻译我拿不太准。

**Comment by leo-liu** [comment]
给 \partpage 这几个模板确实几乎没见过有人用的。
translator 那套用在中文上很怪。

——我觉得没必要加一个 ctexbeam.cls 吧，直接 \usepackage{ctex} 就可以了。至少没必要遵循 8.3 命名了。

**Comment by qinglee** [comment]
对那三个标题页模板的修改，最主要的目的是把其中的 `\partname`、`\sectionname` 和 `\subsectionname` 改成可以通过 `part/name` 等相应选项来设置，比较符合中文习惯。我是想着既然都改了，就把其他的选项也应用上吧。

虽然我们只用到 `translator` 里的部分定理名称，但我觉得还是提供一个完整的文件比较好，所以就把 `translator` 那套给用上了。

`ctexbeam` 这个名字是想跟 `ctexart` 保持队形，现在想想看确实没必要再用这种缩写名字。同 `ctexart` 等一样，`ctexbeam` 是开启了 `heading` 的 `ctex`，就是要修改默认标题模板。还有一种做法是，遵循 `beamer` 的机制，把对标题页模板的修改放在 `beamerinnerthemectex.sty` 里，然后告诉用户用 `\useinnertheme{ctex}` 来引入。但我觉得这稍微有点繁琐。

**Comment by leo-liu** [comment]
还是别 inner theme 了，就 `ctex` 和 `ctexbeamer` 蛮可以了。
