### ISSUE TITLE
\__ctex_save_font_size： Undefined control sequence

### ISSUE THREAD

**Issue by ptbsare** [CTeX-org/ctex-kit#227]
MAC下使用Texlive2014发行版，刚刚从34313(1.02d)升级到37720(2.2)发现编译时出现以下错误，不知如何修复：
```
/usr/local/texlive/2014/texmf-dist/tex/latex/ctex/ctex.sty:671: Undefined control sequence. [  { \__ctex_save_font_size:nn #1 }]

Warnings:

/usr/local/texlive/2014/texmf-dist/tex/latex/fontspec/fontspec.sty: LaTeX Warning: You have requested, on input line 20, version               `2015/06/26' of package expl3,               but only version               `2014/05/20 v4814 L3 programming layer (loader) '               is available.
```
更新所使用的命令是：
```bash
sudo tlmgr update ctex
```
操作系统版本Mac OS X 10.9

**Comment by leo-liu** [comment]
TL 现在的版本是 2015，TeX Live 2014 你是怎么用 tlmgr 升级的？应该出错啊。
你这个出错信息来看，升级也不对。

卸载后安装 MacTeX 2015 再原地更新吧。

**Comment by ptbsare** [comment]
我再来贴个临时的解决方法吧，希望能帮到遇到同样问题的人。
手边只有一直在使用的Texlive2014，但是需要用到最新版的ctex所具有的scheme=plain接口特性。
由于有任务，暂时没那么多时间再彻底重新安装一个发行版Texlive2015。
在Texlive2014上能用上最新版的ctex的方法（有风险，时间充裕还是建议全新安装MacTeX 2015）：
```bash
sudo tlmgr update --self
```
看了ctex的文档，发现其有好几个依赖，如果是用xelatex编译的话，升级ctex包的同时也要升级它附带的几个依赖，即执行：
```bash
sudo tlmgr update ctex fontspec l3kernel l3packages zhnumber xecjk 
```
即可。
如果搞砸了也没关系，执行：
```bash
sudo tlmgr restore 包名
```
查看备份的版本号。
再执行：
```bash
sudo tlmgr restore 包名 版本号
```
还原即可。

**Comment by leo-liu** [comment]
另外应该 `update --all`，因为 `ctex` 有很多依赖项的，而 `tlmgr` 并不会自动更新依赖项。

**Comment by ptbsare** [comment]
谢谢，回复得很及时。一下子`update --all`怕挂。
经过一个个试验，发现只用升级上述几个包即可。

**Comment by Liam0205** [comment]
搞砸了直接 `tlmgr update --self --all --reinstall-forcibly-removed` 就好。
