### ISSUE TITLE
kit-release: 请找一个能直链的地方 host，例如 GitHub Releases

### ISSUE THREAD

**Issue by Arthur2e5** [CTeX-org/ctex-kit#229]

**Comment by leo-liu** [comment]
你要说什么？

**Comment by Arthur2e5** [comment]
标题说了啦。
只是觉得有个可以提供直链的地方对于 mirror 有好处罢了。

**Comment by leo-liu** [comment]
TeX 包正经发布地方是 CTAN，几个重要的包在 github release 也有。你还要放哪儿？

**Comment by Arthur2e5** [comment]
我说的 kit-release 是指安装器啊，这玩意我目前只看到百度盘。

**Comment by leo-liu** [comment]
不知所云啊，什么叫 kit-release？
我猜猜，你是不是指以 MiKTeX 为基础的 CTeX 套装？那个是由吴凌云个人维护的，发布在 http://www.ctex.org/CTeX

CTeX 套装和这里只是名称上的相近，并不是一个项目（当然有点渊源）。

**Comment by Arthur2e5** [comment]
啊……的确又和社群和社群的 Kit 搞混了。
