### ISSUE TITLE
tool: 心情再不好也请稍微 quote 一下命令里的文件名

### ISSUE THREAD

**Issue by Arthur2e5** [CTeX-org/ctex-kit#230]
Windows 可以用双引号无脑上，Linux 可以用 `"'" .. filename:gsub("'", "'\\''") .. "'"` 来处理。

**Comment by Arthur2e5** [comment]
啊还有，cp rm 这种东西请一律在参数结束之后用 `--` 要求终止参数寻找。

**Comment by Arthur2e5** [comment]
还有，cp 没有 `-a` 可能不是好事。

**Comment by leo-liu** [comment]
自用脚本，不发布，能工作就够了。

**Comment by Arthur2e5** [comment]
顺手干净一点有好处的啦，遇到可自定义的东西找个加空格的目录这种事情又不少……

**Comment by Arthur2e5** [comment]
顺手干净一点有好处的啦，遇到可自定义的东西找个加空格的目录这种事情又不少……
