### ISSUE TITLE
标点符号后紧接着的第一个中文字都没有显示出来

### ISSUE THREAD

**Issue by qiqi789** [CTeX-org/ctex-kit#232]
我使用ctex里的ctexart类，在win10系统里输出的PDF文档里每个标点符号后紧接着的第一个中文字符都没有显示出来。如果在标点后加一个空格，则后面的中文字符就能显示出来。请问这是怎么回事？难道需要在每个标点符号后面都要多敲一个空格吗？

**Comment by leo-liu** [comment]
发 issue 还是要给出代码、详细的 log、编译环境等足以重现问题的信息，否则这样无法确认你的问题。
如果是使用上的问题，最好在论坛、社区、邮件列表之类的地方讨论。

**Comment by Liam0205** [comment]
论坛里有讨论了，已经解决了的。过几天更新宏包就好了。
关了吧。

发自我的 iPhone
