### ISSUE TITLE
xeCJK: 标点处理异常

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#233]
<http://bbs.ctex.org/forum.php?mod=redirect&goto=findpost&ptid=152301&pid=541550&fromuid=178857> 时发现的。

MWE:
```tex
\documentclass{article}
% \usepackage{fontspec}
\usepackage{xeCJK}
\begin{document}
\section{foo}
bar\cite{Joshi2011Maximum}
\begin{thebibliography}{1}
\bibitem{Joshi2011Maximum}
Anagha Joshi and Berthold G\"{o}ttgens.
\newblock Maximum parsimony analysis of gene expression profiles permits the
  reconstruction of developmental cell lineage trees.
\newblock {\em Developmental Biology}, 353(2):440--447, 2011.
\end{thebibliography}
\end{document}
```

效果：
![qq 20160225132359](https://cloud.githubusercontent.com/assets/3348485/13310671/0ec8288e-dbc3-11e5-94ec-4e3643f6bfc0.png)

去掉 `xeCJK` 或改换 `fontspec`后，问题消失。

**Comment by Liam0205** [comment]
咦，所有宏包更新到最新后，问题消失。

**Comment by qinglee** [comment]
与 #232 的原因相同，都是 LaTeX 2016/02/01 取消了对 CJK 字符类的设置，造成了分配混乱。
