### ISSUE TITLE
ctex v2.3 \CTEXsetup的aftername参数失效！

### ISSUE THREAD

**Issue by shifujun** [CTeX-org/ctex-kit#234]
在通过MikTex将ctex升级到2.3之后，通过\CTEXsetup的aftername定义的\enspace消失了。

我的模板范例遇到了这个问题：
https://github.com/shifujun/UESTCthesis/tree/master/2013%E5%B9%B47%E6%9C%88%E4%BF%AE%E8%AE%A2%E7%9A%84%E7%A0%94%E7%A9%B6%E7%94%9F%E9%99%A2%E8%A7%84%E8%8C%83%E6%92%B0%E5%86%99%E8%8C%83%E4%BE%8B

**Comment by shifujun** [comment]
补充：只有chapter的aftername失效了。

**Comment by qinglee** [comment]
https://github.com/shifujun/UESTCthesis/blob/master/2013%E5%B9%B47%E6%9C%88%E4%BF%AE%E8%AE%A2%E7%9A%84%E7%A0%94%E7%A9%B6%E7%94%9F%E9%99%A2%E8%A7%84%E8%8C%83%E6%92%B0%E5%86%99%E8%8C%83%E4%BE%8B/uestcthesis.cls#L581

从 https://github.com/CTeX-org/ctex-kit/commit/7966b3de2a61c30eedb6f434b4370b7ae048510d 开始，`\CTEX@chapter@aftername` 不再包含在 `\CTEX@chaptername` 中，你自己修改了不少内部命令，使得 `aftername` 选项无效。
