### ISSUE TITLE
没有装expl3但是出现ctex error: "l3-too-old"

### ISSUE THREAD

**Issue by 605527108** [CTeX-org/ctex-kit#235]
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./readme.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 21 languages loaded.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/ctex/ctexart.cls
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/l3kernel/l3unicode-data.def)
 (/usr/local/texlive/2015basic/texmf-dist/tex/latex/l3kernel/l3pdfmode.def))
Document Class: ctexart 2016/02/02 v2.3 Chinese adapter for class article (CTEX
)

(/usr/local/texlive/2015basic/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
)
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e
.sty)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! ctex error: "l3-too-old"
! 
! Support package `expl3' too old.
! 
! See the ctex documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.50 ...or:nnn { ctex } { l3-too-old } { expl3 } }
                                                  
? H
|'''''''''''''''''''''''''''''''''''''''''''''''
| Please update an up to date version of the bundles
| 
| `l3kernel' and `l3packages'
| 
| using your TeX package manager or from CTAN.
|...............................................
? 
然后我就去删除expl3
sudo tlmgr remove expl3
Password:
expl3: package not present, cannot remove
tlmgr: no packages removed.
tlmgr: action remove returned a warning.
然后我又安装了`l3kernel' and `l3packages'
结果还是编译不了，问题同上

**Comment by Liam0205** [comment]
try:
```bash
sudo tlmgr update --self --all --reinstall-forcibly-removed
```

**Comment by leo-liu** [comment]
错误信息很清楚了，在线更新即可。
