### ISSUE TITLE
xeCJK: 改进 CJKmath 的实现

### ISSUE THREAD

**Issue by qinglee** [CTeX-org/ctex-kit#237]
目前，xeCJK 的 `CJKmath` 功能存在以下两个问题。

* `CJKmath` 设置的字符固定为 Unicode 中的 CJK 字符和一些额外设置的中文标点符号（`\c_@@_CJK_chars_clist`、`\c_@@_FullLeft_chars_clist` 和 `\c_@@_FullRight_chars_clist`）。如果用户使用 `\xeCJKDeclareCharClass` 设置了其他字符为 CJK 类，xeCJK 并不能设置这些字符的 `\mathcode`（见 [CTeX 论坛上的帖子](http://bbs.ctex.org/forum.php?mod=viewthread&tid=152517)）。这是当初实现时考虑不周，将 `\c_@@_CJK_chars_clist` 等变量换成对应的 `\g_@@_CJK_range_clist` 应该就可以。
* `CJKmath` 的字体并不遵从分区字体的设置，只能使用单一字体。这在当初实现时有过考虑，但那时 LaTeX2e 内核还只能定义 16 个数学字体，资源很有限，就没有做。现在，LaTeX2e 也已经可以定义 256 个字体，可以来做这件事。

**Comment by leo-liu** [comment]
我记得 16 个数学字体的限制是 TeX 给出的吧，然后 eTeX 没有扩充。不过 XeTeX 是扩充了的。

**Comment by qinglee** [comment]
是的，我的意思是 LaTeX 的分配器 `\newfam` 和 `\DeclareSymbolFont` 这些还是只能接受 16 个字体，没有做扩展。

**Comment by qinglee** [comment]
呃，我看了一下代码，发现 LaTeX 的扩展还不完整。他们只扩展了 `\newfam` (`\new@mathgroup`)  和 `\select@group`，但是没扩展 `\DeclareSymbolFont`，他还是被限制了只能用来不超过 16 个字体。

**Comment by leo-liu** [comment]
呃，这个可以给 LaTeX3 那边发信吧。

**Comment by qinglee** [comment]
查了一下，`\DeclareSymbolFont` 没有被扩展是有意为之：https://github.com/phst/lualatex-math/issues/7

`\select@group` 是被用于由 `\DeclareMathAlphabet` 定义的 `\mathbf` 等命令中，这些命令只是在分组内切换 `\fam`，不会涉及到 `\mathchardef` 等定义，所以可以很容易扩展。而 `\DeclareSymbolFont` 就不同，他所定义的数学字体要被用于 `\DeclareMathSymbol` 等，如果超过 16 个，需要把 `\mathchardef` 换成 `\Umathchardef`，但 LaTeX3 小组可能觉得对内核改动太大，就没有做。

**Comment by qinglee** [comment]
最新的提交定义了分配器 `\xeCJK_new_fam:N` 来分配我们的数学字体，是从 255 往下分配，应该不会占用目前 LaTeX2e 的有限资源。
