### ISSUE TITLE
是否值得突出 CTeX 宏包的章节标题格式控制功能

### ISSUE THREAD

**Issue by jiaopjie** [CTeX-org/ctex-kit#240]
我的意思是, 即使不考虑对中文格式的调整, CTeX 对英文状态下章节标题格式的控制能力也是很强的.

使用过 titlesec 之类的宏包, 跟 CTeX 比起来,首先它的设置语法不好用. 功能似乎也要差些. 比如, 想把附录在目录中的前缀设为 "附录", 同时保持前面的章的前缀不变. 西文世界讨论这个问题似乎也没什么好的方法. 但用 CTeX 就很简单.

所以我觉得, 是不是把这部分格式控制的功能拿出来单独做一个包, 淡化中文处理能力, 成为一个中西文使用者都喜欢用的包是不是更好.  这个包做的跟 xeCJK 平级, 供 CTeX 调用, 然后汉化的默认控制还是可以放在 CTeX 包.

另外, 我觉得把中文默认行距设为 1.3 倍似乎不太好. 默认设置还是原始一点比较好吧? 并且单倍行距也算很常用的吧?

**Comment by leo-liu** [comment]
关于章节标题设置，你要的单独包叫 `ctexheading`。文档里面有讲，你没有仔细看。

**Comment by leo-liu** [comment]
1.3 倍行距的问题，主要是兼容原因，需要尽量保持旧文档的一致性。
你自己用 `linespread` 可以设置为别的值。

linespread 为 1.3 这个数值是相对正常的值，比 TeX 默认的 1 要常用得多。ctex 包中 linespread 设置为 1.3 这个值继承自 CCT，而 CCT 中取这个值是 1990 年代初由科学院与传统排版人员商量出来的实用数值。

详细来说，一般字体的设置，原始行距（指相临基线间距）是字号的 1.2 倍，因此 linespread=1.3 相当于行距是字号大小的 1.2 * 1.3 = 1.56 倍。

中文出版物，大部分行距都是 1.5 倍字号左右，只有较早一些追求省纸的小说才会用 1.25 倍字号行距。这种设置惯例在很多中文排版教材上都能看到，在方正系统一般叫 1/2 行距和 1/4 行距。

事实上，有兴趣你可以自己用尺子量一下。就像出版社的朋友告诉我的，现代印中文书最为常见的字号和行距是 10 点字，1/2 行距。而不是五号字（10.5 点），1/4 行距。

因此，即使不考虑兼容性，我们也最多会调整为 linespread=1.25 左右，而不会设置 linespread=1 为默认值。

**Comment by leo-liu** [comment]
事实上，相对不符合我个人喜好的默认值是 `\section` 被居中，而下面的 `\subsection` 等级别左对齐。`ctex` 的设置对齐方式不同，但编号上又没有像 `IEEEtran` 一样用不同格式的数字分开。这样在排版上感觉就不是很一致。

如果不是兼容性问题，在 2.0 的时候我会把它改成 `\section` 左对齐。

**Comment by jiaopjie** [comment]
是的, 的确看的不仔细.

但好像 ctexheading 没有单独的说明文档. 我的感觉是, 一般不是写中文的东西的时候, 不会想到用 ctex, 所以会使人想不到用 ctexheading.

或许可以把第七章翻译成英文, 单独列一个说明文档. 另外, 看了前面有关修改章节标题字体的讨论. 似乎应该把 nameformat, numberformat 和 titleformat 这三个选项在 format 之后起作用这件事列在说明文档里. 当然, 最新的 ctex 已经对此作了修改.

**Comment by Liam0205** [comment]
宏集还有 `ctexpatch` 宏包。

没必要为这些，单独开一个文档。

**Comment by jiaopjie** [comment]
我只是觉得 ctexheading 的功能做的挺好的, 似乎不应该局限在中文社区.
