### ISSUE TITLE
xeCJK 在改变字体形状时不能正确识别中文之间的空格

### ISSUE THREAD

**Issue by jiaopjie** [CTeX-org/ctex-kit#241]
如果改变中文段落中的几个字的形状, 比如说加粗, 此时如果命令前有空格的话, 虽然这个空格也是中文之间的, 也不能正确识别.

```
\documentclass{article}
\usepackage{xeCJK}
\setCJKmainfont{FandolSong}
\begin{document}
\noindent
测试 \textbf{加粗}空格。\\
测试\textbf{加粗}空格。
\end{document}
```

**Comment by Liam0205** [comment]
已知问题，技术上无法解决。

**Comment by leo-liu** [comment]
这个我倾向于没什么好办法。用一些黑客技术可能能跳过一些场景，不过做不全。

**Comment by qinglee** [comment]
xeCJK 有个 `xCJKecglue` 选项希望解决这个问题：

```TeX
\documentclass{article}
\usepackage{xeCJK}
\setCJKmainfont{FandolSong}
\begin{document}

\noindent
测试 \textbf{加粗}空格。\\
测试 \textrm{正常}空格。

\bigskip

\xeCJKsetup{xCJKecglue}
\noindent
测试 \textrm{正常}空格。\\
测试 \textbf{加粗}空格。

\end{document}
```
可以看到，`\textrm` 之前的空格被去掉了，但对 `\textbf` 也无效。这个问题的主要困难在于怎么判断一个 glue 是由空格产生的。不同于 LuaTeX，XeTeX 并没有 subtype 来仔细区分 glue 的类别。我们的办法是计算空格的长度（`\c_xeCJK_space_skip_tl`），然后将他与 `\lastskip` 比较，如果相同，就认为之前是一个空格，可以将他去掉。注意这个计算依赖于字体，所以当字体改变时，判断可能不准。这里的情况就是 `\textbf` 改变了字体。

仔细想了一下，我们可以将 glue 都 \unskip 掉，然后判断之前的节点是不是 CJK-space 或者 default-space。如果不是，再与空格长度作比较，将 glue 还回去。

**Comment by jiaopjie** [comment]
这似乎是 latex 本身的原因, 英文状态下改变字体也不会吃掉多余的空格. 似乎各种编译方式, pdflatex, xelatex, lualatex 都不会吃掉多余的空格.

\documentclass{article}
\begin{document}

\setlength{\parindent}{0em}

Test \textbf{bold} space\\
Test \textbf{ bold} space\textbar\\
Test \textbf{bold } space\textbar\\
Test \textbf{bold} space\\

Test { \normalfont normal} space\\
Test {\normalfont normal} space\\
Test {\normalfont normal } space\\

Test\textbf{ bold\textbar} space\\
Test \textbf{bold\textbar} space\\

Test \textbf{bold} space\textbar\\
Test \textbf{bold }space\textbar\\

\end{document}

**Comment by leo-liu** [comment]
当然，`\textbf` 参数开头的空格基本上总是保留的，甚至有时作者会有意利用这种机制。
只是中文问题不大一样。因为汉字不使用空格。

我个人觉得这种句子中间多出来的空格没必要由宏来处理，主要问题是在行末由换行符产生的空格。即这种：
```latex
一行文字
\textit{下一行}
```
`xeCJK` 目前处理不了这种情形。但 `upTeX` 和 `luatexja` 则处理无误（当然方式更底层）。

单单这个是不是相对更处理处理一些？

**Comment by leo-liu** [comment]
呃好像还是不好办，后面命令里是英文的情况没有 hook 可以用了。

**Comment by leo-liu** [comment]
一个思路：
CJK->Boundary: 判断后面是否为换行符（或空格），若为真置变量 flag=true
Boundary->CJK: 判断 flag 是否为 true，若为真用 `\unskip` 去掉这个空格
其他转移情况：置变量 flag=false。

不知道可行不？
感觉又会拖慢不少编译。

**Comment by qinglee** [comment]
upTeX 和 luatexja 都没有处理句子中间的汉字之间的空格，这是因为他们有机制可以处理由换行产生的空格：upTeX 是利用 `\kcatcode`，luatexja 则是在 ` process_input_buffer` 这个 callback 中处理。而对于 xeCJK，在不改变 `\endlinechar` 的情况下，我们基本上没有办法判断出后面是否是换行符。所以利用了通常情况下换行会产生一个空格来处理。xeCJK 处理句子中间的汉字间空格，只是这种处理办法的副产品。

@leo-liu 后面提到的思路，实际上 xeCJK 目前就这么做了。这个 flag 叫 `\xeCJK_make_node:n { CJK-space }`，是两个长度互相抵消的 `\kern`，不用宏作为 flag，是因为宏可能不能反应真实的情况。然后 Boundary->CJK 时，目前是判断 lastnodetype 是否是 glue，如果是，再将 \lastskip 与 `\c_xeCJK_space_skip_tl` 作比较，如果相同，就 \unskip 掉，再判断之前是不是 CJK-space。现在看来，可以把 glue 先 \unskip 掉，再判断之前是否是 CJK-space，如果不是再与空格作比较，把 glue 还回去。

关于性能方面，我大概测试了一下，随着 LuaTeX 和 luaotfload 的改进，现在 luatexja 的速度已经不必 xeCJK 慢多少了，用 luajitlatex 编译的话，甚至还要快一些。

**Comment by qinglee** [comment]
我们最新的提交已经能处理顶楼的情况，需要开启 `xCJKecglue` 选项才有效。

**Comment by leo-liu** [comment]
话说允许修改 `\endlinechar` 是不是可行。这个值在 LaTeX 除了偶尔设置为 -1 以外，似乎也很少变化。

**Comment by qinglee** [comment]
我觉得会比较危险。例如正文中出现宏定义的话，就会遇到各种麻烦。

**Comment by leo-liu** [comment]
这个倒是……
`\futurelet` 拿不到单个字符啊，这里底层添个 `\futureletchar` 之类的东西就能判断了。
