### ISSUE TITLE
ctex: 应用 ApTeX 的 \ngostype 来判断操作系统

### ISSUE THREAD

**Issue by qinglee** [CTeX-org/ctex-kit#242]
目前 ApTeX 和 upTeX 共用一个引擎文件，对操作系统的判断还是通过找文件的方式。ApTeX 有 `\ngostype`，可以利用他。

有鉴于此，我觉得可以把他们都独立出来，就不在一个文件里加分支判断了。

**Comment by leo-liu** [comment]
ApTeX 没向 CTAN 之类渠道正式发布，很多地方都不稳，我估计还没多少人会拿 ApTeX 的非商业支持版用在正式环境中。
所以目前 upTeX 支持真心也就是 upTeX 支持，在 ApTeX 中能用只是附带效果。

clerkma 前一阵跟我说今年要加 OpenType 字体支持（可能比 XeTeX 再朴素点），这样的话整个引擎的支持代码就要和 upTeX 分离，我觉得到时候再大改也不迟。

**Comment by qinglee** [comment]
嘛，我还是先独立出来吧 XD

**Comment by mtf-tpxs** [comment]
前边提到：「我估计还没多少人会拿 ApTeX 的非商业支持版用在正式环境中。」

那么，ApTeX 的商业支持版是什么？是这篇文章提到的吗：
https://zhuanlan.zhihu.com/p/19832049
还是另有其他？谢谢！
