### ISSUE TITLE
ctex: beamer 默认字号、行距无须修改

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#243]
对幻灯片没有必要设置默认参数 `zihao=5` 与 `linespread=1.3`。与原有模板相比，这会造成风格的不统一，也影响单页文字数量。

另外，用户反映大行距影响多行公式美观。

**Comment by leo-liu** [comment]
现在行距对 `beamer` 做了例外处理。

另一种可能是只对标准文档类 `article`, `report`, `book` 设置行距，而不设置其他文档类。即在 `ctex-scheme-chinese.def` 中也不设置 `linespread` 默认值。

两种方式都不存在兼容性问题。考虑到印刷目的中扩大行距比较多，采用目前的改法。

**Comment by leo-liu** [comment]
`beamer` 不是印刷，字号恢复 11pt 没有疑义，技术上需要保证在 `beamer` 中使用 `\usepackage{ctex}` 与使用 `ctexbeamer` 效果一致，代码改起来不是很直接。

关于字号，我多说两句。

从今天的排版实践来看，越来越少的书刊使用 10.5 磅的五号字印刷，更多采用 10 磅字。不仅仅是科技类图书，手头人民文学出版社的小说、北京出版社的散文集子也开始改用 10 磅左右较小的字号（但字距可能会松一些）。感觉这个与现在出版业使用的软件更新不无关系。

因此未来如果还要打破兼容性，可以对印刷目的的文档类全部采用 10pt 默认字号，并将 `linespread` 稍减至 1.25。

当然这里的版本还是不考虑这些。

**Comment by qinglee** [comment]
目前这部分代码在 dtx 中有重复的地方。本来用 DocStrip 可以避免这种重复，也方便维护。但是我觉得解包出来的文件，缩进会不好看，会是下面这样子：
```TeX
\tl_set:Nn \l__ctex_tmp_tl { beamer }
\tl_if_eq:NNTF \c__ctex_std_class_tl \l__ctex_tmp_tl
  {
\str_if_eq:onTF { \l__ctex_encoding_tl } { GBK }
  {
    \uselanguage { ChineseGBK }
    \languagealias { chinese } { ChineseGBK }
    \ctex_file_input:n { ctex-name-gbk.cfg }
  }
  {
    \uselanguage { ChineseUTF8 }
    \languagealias { chinese } { ChineseUTF8 }
    \ctex_file_input:n { ctex-name-utf8.cfg }
  }
\clist_put_left:Nn \trans@languagepath { chinese }
  }
  {
\str_if_eq:onTF { \l__ctex_encoding_tl } { GBK }
  { \ctex_file_input:n { ctex-name-gbk.cfg } }
  { \ctex_file_input:n { ctex-name-utf8.cfg } }
\int_compare:nNnF \g__ctex_font_size_flag > \c_minus_one
  { \cs_gset_eq:NN \g__ctex_font_size_flag \c_zero }
\fp_compare:nNnT { \l__ctex_line_spread_fp } ? { \c_zero_fp }
  { \keys_set:nn { ctex / option } { linespread = 1.3 } }
\tl_if_exist:NT \c__ctex_std_class_tl
  { \RequirePackage { indentfirst } }
  }
```
所以就采用了现在的处理方式。还一种处理就是把 `ctex-scheme-chinese.def` 也按分支分出几个文件，但这样的话文件又多了些，名字也会长很多，大概得叫 `ctex-scheme-chinese-beamer-generic.def`

**Comment by leo-liu** [comment]
我下午弄别的没仔细考虑这一块，代码改了一点就放下了。我开始的代码思路是设置
```latex
zihao .value_required:n = true ,
zihao .initial:n = { false } ,
```
（原来设置 `zihao .default:n = { 5 }` 感觉是误植）
然后在标准文档类的 scheme-chinese 中额外设置 `zihao=5`，在 beamer 的 scheme-chinese 中不设置。这里需要处理一个默认设置与手工设置的逻辑。而两个 `.clo` 文件很晚才载入，不影响。

你改的代码我再看看。

**Comment by qinglee** [comment]
`zihao` 选项设置的是 `\g_@@_font_size_flag`，他的初始值是 `-1`，表示 `zihao` 没有被设置过。我们在 scheme 文件中检查他的值，如果他还保持 `-1`，说明 `zihao` 没有被用户设置，我们就修改默认字号为五号字。现在的 beamer 就不再执行这一过程。

设置 `zihao .default:n = { 5 }` 的目的是，让选项 `zihao` 和 `zihao=5` 的意义相同。

**Comment by leo-liu** [comment]
我觉得让 `zihao` 等同于 `zihao=5` 不大合理

**Comment by qinglee** [comment]
我的想法是，用户使用 `zihao` 就是想改默认字号，给一个默认行为也未尝不可，虽然我们现在只有 `-4` 和 `5` 两个有效值。

**Comment by leo-liu** [comment]
还是禁用了 `zihao` 的无参形式。这个以前在文档中没有说明，也不直观，还是算了。
倒是以后可以考虑加 `zihao=10pt` 之类的等价形式。

**Comment by zohooo** [comment]
从兼容 1.0 版本的角度来看，Beamer 中字号不修改是合适的；但取消了对 linespread 的设定，导致旧文档全部都变样了，编译效果差别较大。虽说可以每个旧文档都改回来，但个人认为 ctex 中设定  linespread 确实是应该的。

默认为 linespread=1 的中文文档各行挤成一团，根本就没法看，幻灯片也同样。一个中文文档，合适的行距是最基本的要求了。不大清楚模板风格不统一是具体是什么情况，英文模板拿来用于中文幻灯片需要稍作定制是自然的。对于幻灯片来说，单页文字数量实际是越少越好，只要能说明要点。而多行公式的行距问题，这对于其他文档类也是一样的，在其他文档类中用户怎么处理，在 Beamer 中自然也就可以同样处理。
