### ISSUE TITLE
ctex: 关于章节标题的 beforeskip 和 afterskip

### ISSUE THREAD

**Issue by qinglee** [CTeX-org/ctex-kit#248]
目前，标题前后的空白距离除了 `beforeskip` 和 `afterskip` 以外，还包括了 TeX 为保持 `\baselineskip` 而加入的行间 glue。这个额外距离可以由用户在`format` 和 `aftertitle` 中设置 `\nointerlineskip` 加以抑制 [*]。

我们已经在 #207 中引入 `fixbeforeskip` 特别处理了 `\part` 和 `\chapter` 标题之前的距离。是不是也可以在各级标题中引入 `fixskip` 统一解决这个问题？

[*]: https://www.zhihu.com/question/46618031

**Comment by leo-liu** [comment]
可以。
