### ISSUE TITLE
xeCJKfntef 的彩色又出问题了

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#249]
```latex
\documentclass{article}

\usepackage{xeCJK}[2016/05/14 3.4.0]
\usepackage{xeCJKfntef}[2016/05/14 3.4.0]

\usepackage{xcolor}

\setCJKmainfont{SimSun}

\begin{document}

前前前前\CJKunderline{\color{red}汉字汉字}后后后后

\xeCJKsetup{underline/format=\color{red}}
前前前前\CJKunderline{汉字汉字}后后后后

\end{document}
```

![1](https://cloud.githubusercontent.com/assets/570611/15561631/5621a616-232a-11e6-9141-5992342d4d82.png)

前一个问题是 `CJKfntef` 也有的。
后一个问题似乎是新的。

感觉类似的问题出过好多次。

**Comment by qinglee** [comment]
呃，这其实是 `l3drivers` 的锅，在 latex3/latex3#302 已经修正了。这个版本是在 TeX Live 冻结前提交上去的，现在应该还能更新到。

**Comment by leo-liu** [comment]
好吧，更新后第二个正常了。
前一个问题一直在……还是算了吧。

**Comment by qinglee** [comment]
前一个问题是一直都存在的，这个没什么好的解决办法。

我想加入新选项 `underline/textformat`，单独设置正文的颜色和字体等。

**Comment by leo-liu** [comment]
利用啥实现？`\CJKsymbol` 还是放进状态转移表里？

**Comment by qinglee** [comment]
不会这么复杂，在 `\ULon` 之前设置格式就好，实际相当于

```TeX
{\color{red}\CJKunderline{汉字汉字}}
```
这种实现不能解决 `\color` 放在文字中间的情况：
```TeX
\CJKunderline{一二\color{red}三四}
```
上面的例子，还是只有 `\color` 后面三会变成红色。要解决这个问题，我们可以在 `\XeTeXinterchartoks` 跟踪 `\current@color` 的变化；或者重定义 `\special`，让他断开下划线，到外部来设置。但我不想去这么处理了，就只简单地提供 `textformat` 选项，把对文字的格式放到外部来。

**Comment by qinglee** [comment]
话说回来，对于下划线，我们实际上也可以不依赖 ulem 包，完全通过 `\XeTeXinterchartoks` 处理，也有望完全解决这里的问题，但是这个工作量就比较大了。

**Comment by leo-liu** [comment]
嗯，不用太复杂了。这种下划线的东西也不多。
