### ISSUE TITLE
ctex-name-utf8.cfg 等的内容可以放进 \AtBeginDocument 钩子里么？

### ISSUE THREAD

**Issue by louisstuart96** [CTeX-org/ctex-kit#251]
遇到一个中文与俄文的混排问题，如果用到 babel 的话，由于 babel 里对相关标题的改动是放在这个钩子里的，即使在 babel 之后使用 ctex，也无法自动改中文标题，解决的办法可能只有自己手动往钩子里加代码。

**Comment by leo-liu** [comment]
确实可以把 `.cfg` 文件与  `\ctexset` 的设置移到钩子里面。但这可能会影响用户手动修改一些值的做法，造成不兼容。
此时用户写 `\renewcommand\proofname{证}` 都可能失效。

`ctex` 毕竟是为中文文档设计的，目前完全没有考虑与 `babel`、`polyglossia` 的兼容。

如果全文俄文，部分汉字支持，直接用 `xeCJK` 之类可能更好。反之，如果全文中文，不需要各方面的俄文翻译，那也没有必要用 `babel`/`polyglossia`，只是输入少量成段的西里尔文还是容易的。

全文在双语间来回切换的版式，感觉似乎太小众，暂时还是手工定义吧。或者我对需求理解有问题？

未来如果真要做 `babel`、`polyglossia` 的兼容，恐怕也要在 `babel`/`polyglossia` 框架里面使用 `\selecelanguage` 等机制。

**Comment by louisstuart96** [comment]
这是我之前帮人调试模板的时候遇到的问题，用户对双语文档的排版多数只用到 hyphenation pattern 就够了，这个直接上 babel 可能都画蛇添足了。
