### ISSUE TITLE
tool: zhconv 下载编码转换表会出错

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#258]
目前 `zhconv.lua` 用的是 http://www.w3.org/TR/encoding/indexes/index-big5.txt 等几个文件地址。
不过遗憾的是，这几个地址已经 404 了。由于 W3C 的 Encoding 这部分是在 WHATWG 的一个历史版本，原文件可以在 WHATWG 上找到。即
https://encoding.spec.whatwg.org/index-big5.txt
等几个文件地址。

但是，杯具的是，whatwg.org 是限定 HTTPS 的，而我们的 LuaTeX 并没有把 HTTPS 支持内置。

所以只能用回 wget 了。

@qinglee

**Comment by leo-liu** [comment]
以及就我本人来说我还是更愿意依赖 iconv。

**Comment by qinglee** [comment]
呃，本来是想减少依赖，现在没有 HTTPS 内置支持的话，就用回 iconv 好了。
