### ISSUE TITLE
xeCJK 破折号的压缩过挤

### ISSUE THREAD

**Issue by zeetex** [CTeX-org/ctex-kit#259]
代码是
```TeX
\documentclass{article}

\usepackage{xeCJK}

\setCJKmainfont{FZSSK.TTF}

\begin{document}

《大学》——《中庸》——《论语》——《孟子》。——四书

\end{document}
```
结果是
![pzh](https://cloud.githubusercontent.com/assets/7959602/20639263/77976712-b3f9-11e6-9cc9-dbecc6005e4c.PNG)
书名号、句号与破折号之间的间距过小。

尽管可以用 `\xeCJKsetkern` 自行调整，但是我觉得应该不用压缩破折号与其它标点的间距。

**Comment by qinglee** [comment]
确实是，当初我注意到过这个问题，后来给疏忽了。

**Comment by qinglee** [comment]
https://github.com/CTeX-org/ctex-kit/commit/b4055399c9b8c73b1a7d1e9cc20b7b8671f6545e 已实现。

**Comment by nanmu42** [comment]
辛苦了。
