### ISSUE TITLE
upLaTeX 使用报错

### ISSUE THREAD

**Issue by zeetex** [CTeX-org/ctex-kit#262]
简单试了一下 ctex 宏集在 upLaTeX 下的情况，发现下面的简单例子居然会出现编译错误

```TeX
% !TeX program = uplatex
% !TeX encoding = UTF-8

\documentclass{ctexart}

\begin{document}

\section{汉字}

\end{document}
```
编译错误是
```
Runaway argument?
{豎牙Φʑ\par \end {document} 
! File ended while scanning use of \@xdblarg.
<inserted text> 
                \par 
```
我的系统是 TeX Live 2016，宏包都是刚更新过的。

**Comment by leo-liu** [comment]
像是 uptex 更新后出的问题。我看看先

**Comment by qinglee** [comment]
这个问题其实与 ctex 没有关系，把文档类换成 `article` 或者 `ujarticle` 都可以重现。

我们注意到编译时的终端的以下输出：
```
(./utbug.tex(guessed encoding: Shift_JIS = sjis)
```
看起来是 uptex 将编码猜成了 Shift-JIS，引发了错误转换。

从 TeX Live 2016 开始，Windows 版本的 (u)ptex 具有自动猜测文件编码的功能，可以猜测到 EUC-JP、JIS、Shift-JIS 等几个常用日文编码。可能是“汉”这个字在日文编码中没有，导致猜测错误。

可以在每个文件的开头设置
```TeX
\epTeXinputencoding UTF-8
```
指定编码，或者编译时加选项 `-no-guess-input-enc`。但是作为中文用户，我们完全可以禁用猜测功能。这个功能受环境变量 `guess_input_kanji_encoding` 的控制，TeX Live 在 `texmf.cnf` 中默认设置为 `1`：
```
% Guess input encoding (SJIS vs. Unicode, etc.) in pTeX and friends?
% Default is 0, to not guess.
guess_input_kanji_encoding = 1
```
因此在本地的 `texmf-local\web2c\texmf.cnf` 中设置 `guess_input_kanji_encoding=0` 就可以禁掉。

**Comment by leo-liu** [comment]
嗯，我刚在 Linux x64 下一切正确。
切回 windows 试了一下，简单的解决方式就是加 `-no-guess-input-enc` 选项就好。一般是直接在编辑器按钮的命令设置里面加选项。

其实字稍微多点也就没事了，这里是字太少使 uptex 识别编码出错。
——当然，正文字多了，.aux 文件字少的话还是有可能自动猜错。

**Comment by leo-liu** [comment]
UTF-8 编码特征那么明显，作为现代编译引擎，upTeX 正常做法明明是应该在歧义时优先选 UTF-8 的。这里 upTeX 的编码识别策略就不大对头。

**Comment by qinglee** [comment]
嗯，换成繁体的“漢”就没问题，不知道 `ptexenc` 库是什么思路。w32tex 的 banner 也是一样的，
```
This is upTeX, Version 3.14159265-p3.7-u1.21 (utf8.uptex) (TeX Live 2016/W32TeX)
```
自动识别编码时，这里显示的 `utf8.uptex` 容易让人混淆。

**Comment by leo-liu** [comment]
好在正经文档字都比较多，即使是 `.aux` 文件，多几个 `\section` 应该也没事了。

**Comment by zeetex** [comment]
谢谢开发者详细的解释！

**Comment by louisstuart96** [comment]
应该是这里的 utf8.uptex 前者是文本编码，后者是 TeX 用的内码，uptex 多半是 UTF-16 了。如果一样的话（像 Windows 的 pTeX 都是 sjis）就只显示一个，如果用 ptex -kanji=utf8 的话 banner 变成 utf8.sjis。

然而 texmf.cnf 的注释是这么写的：
% Guess input encoding (SJIS vs. Unicode, etc.) in pTeX and friends?
% Default is 0, **to not guess**.
然后设成 1？坑爹嘛这是……

**Comment by qinglee** [comment]
最开始确实是 `0`，[后来](https://tug.org/svn/texlive?view=revision&revision=33620)才被改成`1`，但是注释没改。
