### ISSUE TITLE
ctex 用 lualatex 编译, \verb 的一个字体错误

### ISSUE THREAD

**Issue by jiaopjie** [CTeX-org/ctex-kit#264]
最近试了一下 `LuaLaTeX` 编译中文. 正文中有 `\verb` 命令的时候碰到了一个字体的错误. 在生成的 pdf 中插入了两个命令.
```
\FontspecSetCheckBoolFalse\FontspecSetCheckBoolFalse
```
系统是 TeXLive 2016, 前几天刚刚把安装的宏包都升级了一下. 代码如下.
```
\documentclass{article}
\usepackage{ctex}
%\usepackage{luatexja-fontspec}
%\setmainjfont{SimSun}
\begin{document}
1. 用 \verb|LuaLaTeX| 编译.\par
2. 用 \texttt{LuaLaTeX} 编译.\par
3. Compile with \verb|LuaLaTeX|.\par
4. Compile with \texttt{LuaLaTeX}.\par
\end{document}
```
网上搜了一下这个错误, 有人在 `fontspec` 下面提了类似的问题. 因此特地试了一下 `luatexja-fontspec` 方式, 发现在这种情况下没问题. 所以这里可能不是 `fontspec` 的问题 (或者是设置的问题?).

这里有几点疑问.
1. 额外插入的这两个命令只在第一个 `\verb` 命令处插入.
2. 如果把代码中的 `2` 移到 `1` 之前, 则全程都没问题了.
3. 当然如果把 `1` 和 `2` 都移除, 不用 `ctex` 宏包, 也没问题.
4. 另外有一个 `luatexja` 的问题. 当不使用 `ctex` 直接使用 `\usepackage{luatexja, fontspec} \setmainfont{SimSun}` 时, 两行中文的 `编译` 二字都不能显示出来, 但是 `用` 字却能显示. 甚至写为 `\usepackage{luatexja-fontspec} \setmainfont{SimSun}` 也是一样. 感觉有点奇怪.

**Comment by qinglee** [comment]
这是 fontspec 包的问题：见 https://github.com/wspr/fontspec/issues/230 ，已经修复了，等着近期的更新吧。

至于后面的疑问 4，那是因为不进行字体设置时，luatexja 默认对汉字使用的字体是 `IPAExMincho`，这是日文字体，缺`编译`这两个汉字，设置 `\setmainfont{SimSun}` 仅对西文字符生效。

**Comment by jiaopjie** [comment]
但是还有一个疑问, 使用 `\usepackage{luatexja-fontspec}` 时不也是调用了 `fontspec` 宏包吗? 然后设置中文字体 `\setmainjfont{SimSun}` 这种情况下编译没问题啊.

**Comment by qinglee** [comment]
这是因为，ctex 包对新字体定义的时间有些不一样，这也是你的疑问 2 出现的原因。

**Comment by jiaopjie** [comment]
这个对字体调用之类的细节不懂. 总之谢谢你的回复. 等 `fontspec` 宏包更新出来再试试.
