### ISSUE TITLE
xeCJK: \setCJKsansfont, \setCJKmonofont 在 fontspec 2.5d 下无效

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#268]
刚刚把 `fontspec` 宏包从 v2.5a 更新到 v2.5d，就出现了这样的问题。似乎是 `\setsansfont` 和 `\setsansfont` 把 `\setCJKsansfont` 和 `\setCJKmonofont` 覆盖掉了。代码如下：

```
\documentclass{article}
\usepackage{xeCJK}

\setmainfont{TeX Gyre Termes}
\setsansfont{TeX Gyre Heros}
\setmonofont{TeX Gyre Cursor}

\setCJKmainfont{楷体}
\setCJKsansfont{黑体}
\setCJKmonofont{仿宋}

\begin{document}
你好 world

\textsf{你好 world}

\texttt{你好 world}
\end{document}
```

![1](https://cloud.githubusercontent.com/assets/18233088/22834019/d243d138-efee-11e6-9c67-27715a5db672.PNG)

作为对照，把设置英文字体的三行注释掉后，结果是这样的：

![2](https://cloud.githubusercontent.com/assets/18233088/22834113/0eac6c16-efef-11e6-8da9-4037b0653909.PNG)

希望能给出一个解决方案，谢谢！

**Comment by qinglee** [comment]
新版本的 `fontspec` 包会在`\setmainfont`等命令中重新定义`\rmfamily`等命令，确保字体编码并展开族名，导致 `xeCJK` 不能匹配。
