### ISSUE TITLE
ctex 文档类下的 \defaultCJKfontfeatures

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#270]
ctex 文档类不设置 `fontset` 的时候，导言区使用 `\defaultCJKfontfeatures` 似乎没有用诶。文档类选项里面设成 `fontset = none` 再在后面重新用 `\ctexset` 定义 `fontset` 倒是可以，但是 `\defaultCJKfontfeatures` 好像必须在 `\ctexset` 之前设置才有用。请问是我用法不对还是宏包的问题呢？

**Comment by Liam0205** [comment]
`\defaultCJKfontfeatures` 对其后的字体设置起作用。
