### ISSUE TITLE
关于 ctexset 设置

### ISSUE THREAD

**Issue by thucoldwind** [CTeX-org/ctex-kit#273]
问题描述：使用`\ctexset{autoindent=4em}`设置缩进，但段缩进保持不变。使用`\setlength{\parindent}{4em}` 也无法设置缩进。
另外，在加入下述代码后，会出编译错误：
```
\ctexset {
  part/pagestyle = empty,
  chapter = {
    format = \raggedright,
    pagestyle = empty,
  },
  section = {
    name = {第,节},
    number = \chinese{section},
  }
}
```
错误如下：
Errors:
C:\Tools\work\CTeX\MiKTeX\tex\latex\ctex\ctex.sty:28: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [}]
C:\Tools\work\CTeX\MiKTeX\tex\latex\ctex\ctex.sty:28: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [}]
C:\Tools\work\CTeX\MiKTeX\tex\latex\ctex\ctex.sty:28: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [}]

刚接触CTex，有人知道这个是哪里的问题吗？谢谢大家！

**Comment by Liam0205** [comment]
1. CTeX 套装里的 ctex 宏包不支持这个用法，除非你主动更新了宏包。
2. 请给出完整可复现问题的代码。
3. 请给出完整的报错，而不是一堆无用的信息。
