### ISSUE TITLE
希望可以为 ctxdoc 提供文档

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#276]
各位前辈，可以提供 ctxdoc 的文档吗？ `ctxdoc.sty` 和 `ctxdocstrip.tex` 都没有几行注释，本人水平有限，看懂有点难度啊。

**Comment by Liam0205** [comment]
这两个都是所谓「文学编程」用的工具，应该是改自标准的 `doc.sty` 和 `l3docstrip.tex`。看他们的文档就好了。

**Comment by Stone-Zeng** [comment]
其实我主要关注的是 `ctxdoc` 对 `l3doc` 的各种 patch 和重定义。`l3doc` 感觉问题蛮多的，好多东西都是写死在里面的，很不好弄，所以才想借鉴 `ctxdoc`。
说起来写 LaTeX3 风格的宏包文档的话你们有些什么建议吗？

**Comment by qinglee** [comment]
这种工具都是内部使用的（名字中缺了`e`），自定义的东西很多，代码也写得较为随意和混乱，缺乏文档说明。可以就具体问题展开讨论，就懒得写文档了。
