### ISSUE TITLE
请教关于 ctex 的 tocline 与titletoc 的兼容问题

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#280]
我的目的是将目录中的“第一章”与章标题之间空一个 \ccwd ，然后我用了titletoc：
```
    \titlecontents{chapter}
        [0bp]
        {\setfontsize{12bp}[20bp]}
        {\thecontentslabel\hskip\ccwd}
        {}{\ustc@leaders\contentspage}
```
但是由于ctex 去年10月新增的 chapter/tocline 默认值，导致生成的 toc 实际为：
```
\contentsline {chapter}{\numberline {第一章\hspace {.3em}}简介}{6}{chapter.1}
```
这样就导致多了\hspace {.3em}。
考虑到兼容性问题，我不想在模板中设置 chapter/tocline，请问：
1. 这个\hspace {.3em}是不是应该加到更加底层的宏里？
2. 有没有其他方法处理这个问题？

**Comment by louisstuart96** [comment]
改 chapter/tocline 和 titletoc 不冲突。chapter/tocline 的值会写到 \nuberline 的参数里，而在 titletoc 宏包里 \nuberline 的参数又整个交给 \thecontentslabel。

@qinglee 这个 \hspace 有没有必要加呢？内核里目录的 label 宽度是由 \@dottedtocline 的参数给出的，label 的默认排版方式是 \def\numberline#1{\hb@xt@\@tempdima{#1\hfil}}。

**Comment by zepinglee** [comment]
我明白你的意思，这是在两个地方设置的距离。

我的意思是，我假定一部分人没有最新版的ctex，一部分人是最新版的，那么我在titletoc中加傻姑娘距离，就得判断ctex的版本。

**Comment by qinglee** [comment]
这个 `\hspace {.3em}`在 ctex 包中很早就有了，你不想用 `tocline` 的话，可以在 titletoc 的 `\thecontentslabel`后用`\unskip`去掉。

**Comment by zepinglee** [comment]
感谢指导！
