### ISSUE TITLE
xeCJK: en and em dashes before a CJK character are not processed when used with newtxtext

### ISSUE THREAD

**Issue by e-kwsm** [CTeX-org/ctex-kit#281]
When xeCJK is used with newtxtext, en dash `--` and em dash `---` before a CJK character are not converted to – and —.

The following MWE
```tex
\documentclass{standalone}
\usepackage{xeCJK}
\setCJKmainfont{NotoSerifCJKjp-Regular}
\usepackage{newtxtext}
\begin{document}
--a--
--漢--

---a---
---漢---
\end{document}
```
gives
![a](https://cloud.githubusercontent.com/assets/11627708/25843808/812826ca-34e3-11e7-90e8-cb982a9acb50.png)

My environment:
* XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017)
* xeCJK 2017/04/01 v3.4.7
* newtxtext 2017/03/11 v1.521

**Comment by leo-liu** [comment]
It is a known issue of `xeCJK`. Not sure how to fix it now. Sorry.

**Comment by leo-liu** [comment]
BTW, some punctuation marks (dashes, quotes, ellipsis) have ambigious widths, which are used both in English and CJK text. It is always prefered to use `--` and `---` for western languages only, and use `——` directly in CJK text, then `xeCJK` will select the proper font for them.

That is to say, you would not need to use `---漢` in the text.

**Comment by e-kwsm** [comment]
Dashes are processed properly when roman font is set by `\setmainfont{TeXGyreTermesX-Regular.otf}` instead of `\usepackage{newtxtext}`, so I believe some configurations of `newtxtext`—I'm not sure which one—affect.
