### ISSUE TITLE
ctex 与 xparse 可能有冲突

### ISSUE THREAD

**Issue by peng-howard** [CTeX-org/ctex-kit#282]
如题，我现在用的是 CTeX 2.9.2.164，下面的代码是正常工作的，但是将其中的`article`改成`ctexbook`或者`ctexart`之后，由`\ccmd{\my code}`指令生成的效果中`\my code`中的`\`会消失掉，只显示`my code`，而直接用`\Colorbox{cmdbg}{\lstinline|\my code|}`生成的效果中`\`不会消失，仍然正确显示为`\my code`。

```tex
% !Mode:: "TeX:UTF-8"
\documentclass{article}
\usepackage{xcolor,xparse}
\usepackage{listings}
\definecolor{cmdbg}{rgb}{0.8,0.8,0.8}
\lstset{%
basicstyle=\ttfamily,
breaklines = true,
backgroundcolor=\color{cmdbg},
}
\usepackage{realboxes}

\DeclareDocumentCommand{\ccmd}{v}{%
    \Colorbox{cmdbg}{\csname lstinline\endcsname~#1~}%
}

\begin{document}

% demo using \lstinline only
This is \lstinline|my code|

% demo using \lstinline and \Colorbox
This is \Colorbox{cmdbg}{\lstinline|\my code|}
\ccmd{\my code}

\end{document}
```

也试过更新 ctex 包和 l3 相关的包后再试，但是更新总遇到问题，所以暂时放弃，想请教下是否有直接 hack 现有代码的方法？谢谢。

**Comment by Liam0205** [comment]
1. 此问题与 ctex-kit 无关
2. TeX Live 2016, all package updated, 一切正常。

请卸载 CTeX 套装，安装 TeX Live 2016。

**Comment by Liam0205** [comment]
唔，是我弄错了，还是有关的。

**Comment by leo-liu** [comment]
简单跟了一下，应该是 `xeCJK-listings.sty` 的问题。最新版本也能重现。

在问题修正之前，最简单的绕过问题的办法是使用 LuaLaTeX 编译（如果你的系统不太旧的话）。

如果你不能使用 LuaLaTeX，简单的绕过问题的办法是放弃短代码的语法高亮，即不使用 `\lstinline` 来定义你的 `\ccmd`。

然后等待修正。——不过看你的样子，`xeCJK` 修正了你自己更新也有问题，这个就没办法了。
