### ISSUE TITLE
lualatex编译出错：lstlisting在minipage

### ISSUE THREAD

**Issue by subaochen** [CTeX-org/ctex-kit#283]
下面是我的测试文件test.tex：
```
  \documentclass{ctexart}
  \usepackage{listings}
                   
  \begin{document}
  \begin{minipage}{.5\textwidth}%
  \begin{lstlisting}
  #include "stdio.h"
   void main() {
  }                
  \end{lstlisting}
  \end{minipage}
  \end{document}  
```
环境： ubuntu 16.04，安装texlive-full 2016（从官网下载iso安装），lualatex的版本信息：
```
This is LuaTeX, Version 0.95.0 (TeX Live 2016)
```

执行xelatex test.tex编译不会出错，正常生成pdf文件。
但是执行lualatex test.tex时报告：
```
! Undefined control sequence.
\lst@frameInit ... \z@ \ifdim \ht \strutbox <\cht 
                                                  \@tempdima =\dimexpr \cht ...

l.6 \begin{lstlisting}

```
连续按两次回车（提示同样的错误）后也生成了pdf文件。

**Comment by subaochen** [comment]
分别在texlive 2015, texlive 2016中测试，存在同样的问题。
下面是tex 2016中执行tex的版本信息：
```
This is TeX, Version 3.14159265 (TeX Live 2016) (preloaded format=tex)

```

下面是texlive 2015中执行tex的版本信息：
```
This is TeX, Version 3.14159265 (TeX Live 2015/Debian) (preloaded format=tex)
```

**Comment by subaochen** [comment]
又在ubuntu 15.10中测试了一下，lualatex编译测试文件通过了！

ubuntu 15.10中的texlive-full版本信息如下(dpkg -l texlive-full)：
```
texlive-full             2015.20150625-1ub
```

其中的lualatex版本信息：
```
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015/Debian) (rev 5238)
```

**Comment by leo-liu** [comment]
以下讨论 LuaTeX-ja 的 20170505 版本。

`ctex-engine-luatex.def` 试图不加载太多 `luatexja` 特有的功能，专门禁用了 `ltj-latex.sty` 包的加载。
`listings` 的补丁 `lltjp-listing.sty` 中用到了 `\cht` 等继承自 pLaTeX 的专有宏。
然而 `\cht` 等宏定义于 `lltjfont.sty` 中，需要由 `ltj-latex.sty` 加载。
这样依赖就出了问题。

解决思路：或者加载更多的 `luatexja` 特有功能（但 NFSS 的修改可能影响中文），或者维护自己的 `lltjp-listing.sty`，要么把 `lltjp-listing.sty` 需要的几个宏单纯抽出来实现。

感觉都不是特别舒服。主要还是 `luatex-ja` 不大考虑非日文用户使用。

**Comment by subaochen** [comment]
首先感谢leo-liu的及时回复！

打开ctex-engine-luatex.def看了一下，我目前的水平就是天书:-(。lltjp-listing.sty文件没有找到，不知道是在哪个目录下？

其实我是希望使用minipage限制listings的宽度，如果有其他方式暂时绕过这个bug也行，还望指点一二，谢谢！

**Comment by leo-liu** [comment]
暂时绕过的话，最简单地处理就是加这样两行：
```
\newdimen\cht
\newdimen\cdp
```
具体我还没细看，结果可能画边框的时候与 luatexja 预设的结果有细微差别。应该问题不大。

**Comment by subaochen** [comment]
测试了一下，加上这两行后，没看出来画出的边框有啥异样！非常感谢！
