### ISSUE TITLE
ctex 导致 \mathbf 的大写希腊字母消失

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#285]
```latex
\documentclass{article}
% \usepackage{ctex}
\begin{document}
$M \Sigma \mathbf{M} \mathbf{\Sigma}$
\end{document}
```
加上 ctex 后，`\mathbf{\Sigma}` 就没啦

**Comment by Stone-Zeng** [comment]
只用 `fontspec` 宏包也会有这个问题。`\mathbf{}` 用了 lmroman10-bold，然后这个字体没有斜体希腊字母。

**Comment by zepinglee** [comment]
看来不是 ctex 的问题……不过我还不太理解，\mathbf 得到的本来就是正体

**Comment by Stone-Zeng** [comment]
我智障了。。。那个字体是没有粗(正)体希腊字母的，所以 `\mathbf{\Sigma}` 就没了。

**Comment by leo-liu** [comment]
呃，还是找长点的教材看看吧。粗体符号是在数学环境之外用 \boldmath，或在数学环境内用 amsmath 包的
\boldsymbol，或在数学环境内用 bm 包的 \bm，推荐最后一种写法。
但总之不是 \mathbf，这是仅针对数学字母的字体命令。

2017-06-02 9:21 GMT+08:00 Zeng Xiangdong <notifications@github.com>:

**Comment by zepinglee** [comment]
我本来是用来表示`矩阵 $\mathbf{X}$, $\mathbf{\Sigma}$` ，所以用正粗体 `\mathbf`。不过既然 `\bm{\Sigma}` 得到的也是正体（跟拉丁字母不统一），就先这样将就了

**Comment by leo-liu** [comment]
`\mathbf` 是由 `\DeclareMathAlphabet` 命令声明的字母字体命令，它控制的是以 `\mathalpha` 类型声明的符号。

在默认的 CM 字体设置下，大小写拉丁字母、数字、大写希腊字母被声明为数字字母即 `\mathalpha` 类型。由于 OT1 字体编码没有小写希腊字母，所以小写希腊字母按 `\mathord` 类型声明。因此 `\mathbf` 只可以作用于拉丁字母、数字、大写希腊字母上。这些符号定义是按 OML 字体编码和 OT1 字母编码的交集给出的。

而使用 `fontspec` 包后，不仅 `\mathbf` 被重定义使用 Unicode 编码的字体，符号定义也改变了，此时希腊字母就不一定包含在该字体中了，只有键盘上有的数字和拉丁字母才有保证。

**Comment by zepinglee** [comment]
感谢指点！我对 fonts and encodings 还不是很熟……
