### ISSUE TITLE
与 listings 宏包冲突

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#297]
如下代码使用 XeLaTeX 或 LuaLaTeX 编译会报错：
```tex
\documentclass{ctexart}
\usepackage{listings}

\begin{document}
\lstset{language=C, basicstyle=\ttfamily}
\begin{lstlisting}
#include <stdio.h>
int main()
  {
    printf("Hello, world!");
    return 0;
  }
\end{lstlisting}
\end{document}
```

XeLaTeX 报错：
```tex
! Undefined control sequence.
<argument> \l__xeCJK_listings_letter_bool 
                                          
l.7 #
     include <stdio.h>
```

LuaLaTeX 报错：
```tex
! Undefined control sequence.
\lst@frameInit ... \z@ \ifdim \ht \strutbox <\cht 
                                                  \@tempdima =\dimexpr \cht ...
l.6 \begin{lstlisting}
```

用 pdfLaTeX 和 upLaTeX 编译则不出现该问题。
所有相关宏包均为更至最新。

是否是由于 LaTeX3 最近更新，导致 bool 变量必须在使用前声明？

可能有关的 issue：
fontspec [#301](https://github.com/wspr/fontspec/issues/301)
unicode-math [#392](https://github.com/wspr/unicode-math/issues/392)
siunitx [#311](https://github.com/josephwright/siunitx/issues/311)

**Comment by qinglee** [comment]
`\bool_if:NTF` 的定义有变化：https://github.com/latex3/latex3/commit/825b9f78259b5d64ac8ca34aeed7962aaa564854#diff-fa2442ddc07a6ed671b20d0e5b85d070R877
原来是用 bool 变量与 `\c_true_bool` 比较，现在是直接用 `\if_bool:N` （`\ifodd`）判断，如果 `bool` 变量没有预先定义，就会报错。

**Comment by qinglee** [comment]
LuaLaTeX 的问题见 #283

**Comment by easior** [comment]
我在 MacTeX 2017 中也碰到了这个问题，跟上游联系！他们说 #297 的补丁没有更新至 CTAN，他们没有办法更新 MacTeX.

**Comment by Stone-Zeng** [comment]
可以自己复制并修改一下 `xeCJK.sty`，然后放到 texmf-local 的对应位置，再刷新一下 texhash。

**Comment by easior** [comment]
这些都是 work around，我希望更新一下 TeX Live 的仓库。不知道开发者碰到了什么情况，无法上传更新至 CTAN？

**Comment by Liam0205** [comment]
@qinglee @leo-liu 
CTAN 那边我没有 xeCJK 的上传权限。这个 bugfix 影响面比较广，所以尽快打个版，然后推到 CTAN 吧。

**Comment by Liam0205** [comment]
[知乎上](https://www.zhihu.com/question/63306149/answer/207570866)也有人提相关的问题了。

**Comment by cvcore** [comment]
我也遇到了同样的问题，使用texlive2017. 请问现在临时的解决方案是什么？我看https://github.com/CTeX-org/ctex-kit/commit/cfd48087c956e249fca00769d5c7bc1a9d7cf3c9这个修复被revert了？

**Comment by Stone-Zeng** [comment]
这个 revert 是因为之前 `\bool_new:N \l_@@_listings_letter_bool` 已经加过了，就在几行下面。解决方案见[知乎](https://www.zhihu.com/question/63306149/answer/207570866)。或者改本地的 `xeCJK.sty`。

**Comment by qinglee** [comment]
@Liam0205 已经上传到 CTAN。我原本打算解决掉 #284 和 #287 再发布新版本的，目前时间和精力所限，留待以后再处理吧。

**Comment by Liam0205** [comment]
@qinglee 辛苦。
