### ISSUE TITLE
How can I put my vertical Chinese writing punctuation mark into right position?

### ISSUE THREAD

**Issue by qnach** [CTeX-org/ctex-kit#302]
In vertical Chinese writing the symbols are rotated, and the pages are rotated at the end.
If I use simsun.ttc font in the code below the punctuation marks works perfect.
However, if I use some fonts like HANAMINA.TTF the punctuation marks are awful.
Actually I think almost every font I tried got the same results like HANAMINA.TTF
So, How can I put them into right position? 

\documentclass{book}

\usepackage{xeCJK}

\setCJKmainfont{HANAMINA.TTF}[Vertical=RotatedGlyphs,RawFeature=vertical]

\newcommand*\CJKmovesymbol[1]{\raise.35em\hbox{#1}}
\newcommand*\CJKmove{\punctstyle{plain}
  \let\CJKsymbol\CJKmovesymbol
  \let\CJKpunctsymbol\CJKsymbol}

\usepackage{everypage}
\AddEverypageHook{\CJKmove\special{pdf: put @thispage <</Rotate 90>>}}

\begin{document}

殷墟遺龜足徵商事，台文詩報毀於櫝中。

\end{document}

**Comment by Man-Ting-Fang** [comment]
HANAMINA.TTF does not have the GSUB feature, so it cannot be used in vertical writing.

> Actually I think almost every font I tried got the same results like HANAMINA.TTF

Old fonts and some free fonts usually too young, too simple. Please try other high-quality fonts.

**Comment by qnach** [comment]
No, you are **wrong**! I have used HANAMINA.TTF for vertical Chinese writing for years, and it works perfect except the punctuation marks. Furthermore, the problem I mentioned is not only for HANAMINA.TTF
In almost every font I tried there is such problem, except sinsun.ttc

**Comment by Man-Ting-Fang** [comment]
> No, you are wrong! I have used HANAMINA.TTF for vertical Chinese writing for years, and it works perfect except the punctuation marks.

我看到您在CTeX論壇也發了帖子，用的是傳統中文，我也直接寫中文了。

錯的不是我，是你。你也承認，花園明朝體在豎排時標點不對。漢字麼，當然是可以旋轉的，所以你認為是可以用的；但是TeX是排版軟體，並且是追求完美的排版軟體，而且標點是排版中很重要的一個問題。標點問題不能解決（字型本身不支援），就不能說這個字型是「可用」的。所以，或者無視標點、甚至直接不用標點；或者換字體。另外，花園明朝體預設是日本漢字寫法，除非你想排的是日文，否則，對中文來說，並不合適。

**Comment by Man-Ting-Fang** [comment]
> Furthermore, the problem I mentioned is not only for HANAMINA.TTF
In almost every font I tried there is such problem, except simsun.ttc

支援直書標點的中文字體太多了，怎麼會除了simsun.ttc之外的大多數都不行？你都試過哪些？商業字型暫且不提，思源宋體、思源黑體試過了嗎？

**Comment by qnach** [comment]
可能是我不懂 GSUB 是甚麼吧? 不是字形能旋轉就好了? 難道標點符號 GSUB 還能特殊處理?
花園明朝大約可以支援十萬個中文字。而且我們打的東西的確有很多是"日本漢字"。例如

眞  煑 却 鷄 啓 眾 冐 朶 靑 寳 艷 强  揷 卽 囘 敎 厨  卌 凉 减 赢 戯 脚 靜....

我們通常用的字體如華康，EDUSTD-15.TTF，ipamjm.ttf ....大致都一樣。

還是回到原來的話題吧，怎麼修正標點符號?

**Comment by aminophen** [comment]
I don't know well, but same problem as #299 (-> wspr/fontspec#279)?

**Comment by qnach** [comment]
#279 #299 都只有討論旋轉的問題。至於轉了以後標點符號就沒說了

**Comment by Man-Ting-Fang** [comment]
「GSUB」是「Glyph Substitution」即「字形替換」的縮寫。在TTF和OTF字型中，絕大多數直書標點都是有單獨的字形的，與橫排標點不是一回事。中文輸入法打出來的（通常）都是橫排標點，需要透過字型的GSUB替換表、以及軟體對GSUB的支援協作，才能夠自動將用戶打出來的橫排標點轉換成直書標點。花園明朝體字型中沒有GSUB表，所以無法自動替換。這就好比，假設有一款不含漢字的英文字型，你卻想要用它來顯示漢字一樣，是不可能的。

有兩個迂迴的方法，可以**部分地**解決問題，但是副作用也非常之大：
方法一：採用xeCJK的功能，單獨將標點部分換為其他字型，與花園明朝體混合使用。
方法二：將中文標點定義成宏（巨集，macro）。
具體做法見：https://www.zhihu.com/question/31252255

總之，想「修正」花園明朝體的標點，除非你直接修正字型本身，否則，沒甚麼好的、萬全的辦法。

**Comment by Man-Ting-Fang** [comment]
> 而且我們打的東西的確有很多是"日本漢字"。例如....你怎麼打? 我非用花園明朝沒辦法。

這些字，能在網頁上顯示，就說明不止花園明朝體一家收錄了它們。再說，這些字有些是「新舊字形」（即康熙字典字形（舊）與俗字字形（新））的問題，有些是異體字。我個人更傾向於使用舊字形的字型，即（例如）把「真」字設計為「眞」的形狀的字型。

如果你不太在意字型設計風格統一與否的話，也可以透過xeCJK的功能，將一款支援直書標點的字型設置為主要字型，然後將花園明朝體設置為fall back字型。具體做法見xeCJK的用戶文檔。

**Comment by qnach** [comment]
>再說，這些字有些是「新舊字形」（即康熙字典字形（舊）與俗字字形（新））的問題，有些是異體
>字。我個人更傾向於使用舊字形的字型，即（例如）把「真」字設計為「眞」的形狀的字型。

因為我在打的是中文專業書籍。就是要那些舊字體。

**Comment by Man-Ting-Fang** [comment]
上面我已經給出了三種解決辦法，請仔細閱讀，嘗試後自行決定採用何種方法。個人意見是透過xeCJK設置fall back字型或分區字型最便捷，副作用最小。

**Comment by leo-liu** [comment]
不只是旋转就行，标点位置有区别。
横排和直排，同一个标点的字符（character）往往要使用字体中的两个图形符号（glyph）表示，这对于标点不在正中的字体尤为重要。

花园明朝体是出名的难看。确实建议你改用思源宋体之类质量更高的字体。

例如，思源宋体的简体中文版本，是新字型，标点在一角
```
\setCJKmainfont{Source Han Serif SC}[Vertical=RotatedGlyphs,RawFeature=vertical]
```
而思源宋体的繁体中文版本，是（台湾标准）旧字型，标点在正中
```
\setCJKmainfont{Source Han Serif TC}[Vertical=RotatedGlyphs,RawFeature=vertical]
```
等等。
