### ISSUE TITLE
How to run UpLaTeX within MikTeX?

### ISSUE THREAD

**Issue by qnach** [CTeX-org/ctex-kit#305]
I am using MiKTeX 209.
There is a package called UpLaTeX which I have installed.
But how should I run the UpLaTeX? Is it a package? Or a compiler?
I cannot run pLaTeX. An error message said my computer had MiKTex209-pdftex.dll missing

When I run 
initexmf --mklinks --force
as suggested I got a lots of error messages:

2017-08-04 19:36:13,814+0800 INFO  initexmf - starting: MiKTeX Configuration Utility 2.9.6419 (MiKTeX 2.9.6400 64-bit)
2017-08-04 19:36:13,831+0800 INFO  initexmf - Operating on the private (per-user) MiKTeX setup
2017-08-04 19:36:13,853+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\arctrl.exe does not exist.
2017-08-04 19:36:13,903+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\cjklatex.exe does not exist.
2017-08-04 19:36:13,903+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-afm2tfm.exe does not exist.
2017-08-04 19:36:13,919+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-asy.exe does not exist.
2017-08-04 19:36:13,935+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-autosp.exe does not exist.
2017-08-04 19:36:13,935+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-axohelp.exe does not exist.
2017-08-04 19:36:13,950+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-bg5conv.exe does not exist.
2017-08-04 19:36:13,966+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-bibtex8.exe does not exist.
2017-08-04 19:36:13,982+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-bibtexu.exe does not exist.
2017-08-04 19:36:13,982+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-bibtex.exe does not exist.
2017-08-04 19:36:13,997+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-cef5conv.exe does not exist.
2017-08-04 19:36:14,013+0800 WARN  initexmf - The link target C:\Users\TING\AppData\Roaming\MiKTeX\2.9\miktex/bin/x64\miktex-cefconv.exe does not exist.

**Comment by aminophen** [comment]
I'm a current maintainer of [upLaTeX](https://www.ctan.org/pkg/uplatex). It is a format (also called a macro package; similar layer to pdfLaTeX,  LuaLaTeX, XeLaTeX), which is based on [pLaTeX](https://www.ctan.org/pkg/platex) and can be built on [upTeX](http://www.t-lab.opal.ne.jp/tex/uptex_en.html). In MiKTeX, there is no way of installing it, because the engine upTeX is not installed.

I guess the reason why upLaTeX/upTeX is not installed in MiKTeX is that there is "platex.exe" for Polish instead of Japanese pLaTeX. upLaTeX macros depend on pLaTeX macros, and build procedure for upTeX depends on pTeX, so MiKTeX cannot install pTeX/pLaTeX/upTeX/upLaTeX.

**Comment by qnach** [comment]
....thanks for the information....

**Comment by aminophen** [comment]
If you want to use upLaTeX, you have to install either [TeX Live](http://www.tug.org/texlive/) or [W32TeX](http://w32tex.org).

**Comment by qnach** [comment]
I have download  and run install-tl-windows.exe (for windows). But don't know where is the results?
Presumably it unpacked the installation files into c:\user\...  but no more?

**Comment by aminophen** [comment]
Read [the official document](http://www.tug.org/texlive/doc/texlive-zh-cn/texlive-zh-cn.pdf) (chinese version is also available). the default installation path will be c:\texlive.

**Comment by qnach** [comment]
I have read the manual, which is the same as I read from the webpage.
I have checked the installing procedure install-tl-windows.bat
It called TLWinGoo.pm
At Line 206 the procedure is requesting the window version......somehow this parameter is missing.
It should be a bug in this new release since July 4th or so. I don't know who should I report this issue.

**Comment by aminophen** [comment]
I never heard of such a bug, as I successfully installed TeX Live 2017 in July.

If you have trouble with GUI-based installation, then I recommend no-GUI mode; Download install-tl.zip and unpack it. Start cmd.exe and execute

~~~~
install-tl-windows.bat -nogui --repository http://mirror.ctan.org/systems/texlive/tlnet/
~~~~

If you still get an error, report to [tex-live mailing list](http://tug.org/mailman/listinfo/tex-live) with your detailed information (eg. OS version, all of your actions, and the exact error messages or screenshot).

**Comment by qnach** [comment]
I executed the command you gave. It said -nogui is unrecognized parameter.
So, I removed it, the command becomes
install-tl-windows.bat --repository http://mirror.ctan.org/systems/texlive/tlnet/
The result is the same as before, the system complained
"use of uninitialized parameter $ver ...." (the same program at line 206 as I mentioned before.)
So, where should Isupply this parameter?

**Comment by aminophen** [comment]
Sorry, -no-gui  was correct

**Comment by qnach** [comment]
yes, the same issue as before $ver undefined at line 206...

**Comment by aminophen** [comment]
Please report to tex-live list, as I mentioned above.

**Comment by qnach** [comment]
I have subscribed to tl mailing list
I am using windows10 and attached is the screen 
![screentl](https://user-images.githubusercontent.com/15334647/28993323-2910820a-79e6-11e7-88d2-7ac6184d4296.jpg)

**Comment by aminophen** [comment]
Send it to the mailing list.

**Comment by aminophen** [comment]
I read TLWinGoo.pm, and there seems no problem in it; `ver` is a command embedded in cmd.exe, and the error from TLWinGoo.pm seems to complain about the missing `ver` command.

I found a strange thing; in your screenshot, the `PATH` value shown does not contain `C:\windows\system32` and so on, which should be available on all windows. Why?

**Comment by qnach** [comment]
I do not know. I never made modification at that level for this windows10 system.
So, how should I add them now? simply c:\windows\system32 is enough?
Attached is the path of my system at this moment.
![path](https://user-images.githubusercontent.com/15334647/28994884-f6028da6-7a0b-11e7-8bd9-c84dc38fe694.jpg)

**Comment by aminophen** [comment]
As far as I know, all windows should have followings;

~~~~
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0
~~~~

You should add these to "Path" in system variables. [This site](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10) might help you setting path.

**Comment by qnach** [comment]
it works....

**Comment by qnach** [comment]
I have installed TeXLive and there is a UpLaTeX.
After generation the .dvi file I am trying to convert it into .pdf
But the system said
dvipdfmx:fatal: unable to find TFM file "upjisr-v"

presumably some fonts are missing? What should I do?

**Comment by aminophen** [comment]
Besides "uplatex", you have to install "uptex-fonts", "ptex-fonts" and "ptex-fontmaps".

**Comment by aminophen** [comment]
Japanese users often install all of the required packages by installing "collection-langjapanese"

**Comment by qnach** [comment]
Those package website such as
https://www.ctan.org/pkg/ptex-fonts
said they are contained in TeXLive...

**Comment by aminophen** [comment]
If you installed TeX Live scheme-full, you should have all the required packages including uptex-fonts. Something wrong has happend to you... Maybe you forgot to execute "mktexlsr"?

**Comment by aminophen** [comment]
If you installed TeX Live scheme-full, you should have all the required packages including uptex-fonts; so you don't need to install them manually.

It seems that something wrong has happend to you... Maybe you forgot to execute "mktexlsr"?

**Comment by aminophen** [comment]
Or, if you already have MiKTeX, some environment variables may interfere. Remove MiKTeX-related paths etc. With TeX Live (win32), `where kpsewhich` should return `c:\texlive\2017\bin\win32` for example.

**Comment by qnach** [comment]
Ｉhave rerun mktexlsr.
kpsewich need an argument. What should I supply?

**Comment by aminophen** [comment]
> I have rerun mktexlsr. (it should have been executed at the very end of the installation?)

Yes, it should have been executed, but I thought some problem prevented the execution; but it seems my guess was not correct

> kpsewich need an argument

That's really odd, as mktexlsr does not require any argument.

What about the paths? As I already mentioned, I recommend to remove all MiKTeX-related environment variables before running any TeX Live commands.

**Comment by Liam0205** [comment]
This is off topic with ctex-kit, hence close the thread.

**Comment by Liam0205** [comment]
For your question, since your look not that familiar with TeX and its friends, the simplest solution might be uninstall MiKTeX and TeX Live cleanly, and fix the `PATH` environment variable, as @aminophen suggested. 

Then, install TeX Live with all package/collections installed. Try downloading <http://mirror.ctan.org/systems/texlive/Images/texlive2017.iso>, mount it and install.
