### ISSUE TITLE
xeCJK conflict with lslisting

### ISSUE THREAD

**Issue by qnach** [CTeX-org/ctex-kit#306]
The problem used can be solved by placing xeCJK before lslisting.
But after recent update........
Here is an example:

\documentclass{book}
\RequirePackage{fontspec}

\usepackage[BoldFont,SlantFont,CheckSingle=true]{xeCJK} 
\usepackage{CJKnumb}

\usepackage{listings}

\begin{document}

\begin{lstlisting}[basicstyle=\small,language=C]
　For I=1  to 20
\end{lstlisting}

\end{document}

**Comment by Liam0205** [comment]
This was fixed in #297 .
