### ISSUE TITLE
LuaTeX 下希腊语和俄语会使用 CJK 字体

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#309]
代码如下：
```tex
\documentclass{ctexart}
\setmainfont{FreeSerif}
\setCJKmainfont{KaiTi}

\begin{document}
(English) From Wikipedia, the free encyclopedia \par
(Greek) Από τη Βικιπαίδεια, την ελεύθερη εγκυκλοπαίδεια \par
(Russian) Материал из Википедии — свободной энциклопедии \par
(Thai) จากวิกิพีเดีย สารานุกรมเสรี \par
(Georgian) მასალა ვიკიპედიიდან — თავისუფალი ენციკლოპედია \par
(Chinese) 维基百科，自由的百科全书
\end{document}
```

编译结果：
![default](https://user-images.githubusercontent.com/18233088/29308408-5e03d68e-81d8-11e7-8dde-31b6e3f1d250.PNG)

使用 XeLaTeX编译没有该问题。

测试环境：`CTeX` v2.4.10，`luatexja` 20170730.0，`fontspec` v2.6d，TeX Live 2017

**Comment by qinglee** [comment]
这是 `luatexja` 的默认设置。

>  **Greek and Cyrillic letters, and ISO 8859-1 symbols** By default, LuaTeX-ja uses Japanese fonts to typeset Greek and Cyrillic letters, To change this behavior, put \ltjsetparameter{jacharrange={-2,-3}} in the preamble. For the detailed description, see Subsection 4.1.

**Comment by Stone-Zeng** [comment]
Enclosed Alphanumerics （`U+2460` ~ `24FF`）也被设成 JAchar 了，您看要不要也改一下？

**Comment by qinglee** [comment]
已改，这些带圈数字用 `\textcircled{1}` 的形式，总是会当成 ALchar 的。

**Comment by Stone-Zeng** [comment]
直接用 `\symbol{"2460}` 这种的可以吗？
另外 `\textcircled{1}` 不是手动生成的带圈数字吗，为什么会被当成 char 处理？

**Comment by qinglee** [comment]
`\symbol` 其实就是 `\char`，得用 `\ltjalchar` 才可以。

`\textcircled` 这种组合命令都是先看参数有没有对应的 `\char` 定义，如果没有才是手动组合起来，如果是 Unicode 字体，`\textcircled` 的符号定义见 `xunicode-extra.def`: 

````TeX
\DeclareUTFEncodedCircle\textcircled{"20DD}{"25EF}
\DeclareUTFCompositeSymbol\textcircled{0}{"24EA}
\DeclareUTFCompositeSymbol\textcircled{1}{"2460}
\DeclareUTFCompositeSymbol\textcircled{2}{"2461}
\DeclareUTFCompositeSymbol\textcircled{3}{"2462}
\DeclareUTFCompositeSymbol\textcircled{4}{"2463}
\DeclareUTFCompositeSymbol\textcircled{5}{"2464}
\DeclareUTFCompositeSymbol\textcircled{6}{"2465}
\DeclareUTFCompositeSymbol\textcircled{7}{"2466}
\DeclareUTFCompositeSymbol\textcircled{8}{"2467}
\DeclareUTFCompositeSymbol\textcircled{9}{"2468}
\DeclareUTFCompositeSymbol\textcircled{10}{"2469}
...
````

所有 `xunicode` 包定义的符号都是 `ALchar`，因为我们加了钩子：
```TeX
\RequirePackage { xunicode-addon }
\AtBeginUTFCommand
  {
    \group_begin:
    \lua_now_x:n { tex.globaldefs = 0 }
    \ltj@allalchar
  }
\AtEndUTFCommand { \group_end: }
```
