### ISSUE TITLE
是否可能添加思源系列字体作为字库选择之一？

### ISSUE THREAD

**Issue by hosiet** [CTeX-org/ctex-kit#310]
当前的字库的确能满足各个平台的需求，不过今天在 Linux 平台上用 Fandol 字体难得遇到一个方块字“珺”（渲染效果是F字母外面套一个框），于是考虑用别的字库。

思源字体（或 Noto 字体）已经发布了宋体和黑体，在 Linux 平台上广泛可用，也许可以作为一个字体库选择之一（虽然不应当成为默认选项，因为没有配套的楷体）。

**Comment by leo-liu** [comment]
我上次看时 Debian-testing 还没进，只在 unstable 里面。Ubuntu 直到版本 artful 才有。所以不急吧。

如果可行，可能会考虑用它来代替现有的 Ubuntu 选项，部分配合 Fandol，估计会好些。
不想设立太多单独的 fontset 了。思源只有两款，还不够多。

**Comment by leo-liu** [comment]
毕竟现在的 Ubuntu 字体太丑了。

另，自己设置 \setCJKmainfont 什么的其实也不是很麻烦。

**Comment by hosiet** [comment]
是的，这次就是直接进行的设置。但是自己处理粗体等情况有点麻烦，所以如果有现成测试过的配置会很方便。

那么可以看合适的时候（字体进入发行版）再正式添加类似的字体配置。

**Comment by leo-liu** [comment]
注意，由于 Linux 发行版比较零散，不同的发行版可能会使用不同版本的字体配置。这会带来复杂的兼容性问题。这个问题以前就有，现在也并没有缓解。

所以从的兼容角度说，出个 ubuntunew 之类的新 fonset 更不容易出问题。但自动检测目前看来是做不到了。

事实上 Linux 发行版似乎并没有直接使用 Adobe 的思源宋体、思源黑体，而更多是使用等价的由 Google 发布的 Noto Sans/Serif CJK。出于不知名的原因，一些发行版还会倾向于使用分四个国家地区的版本，而非 Pan CJK 的大字体。我有些担心会因为发行版的魔改，会和以前一样有字体名不统一的问题。手头没有环境，回头再说吧。

**Comment by stone-zeng** [comment]
见 #457。
