### ISSUE TITLE
ctexbook/ctexrep 在 twoside 模式下页眉节标题空格缺失

### ISSUE THREAD

**Issue by WenboSheng** [CTeX-org/ctex-kit#311]
问题见：
http://bbs.ctex.org/forum.php?mod=viewthread&tid=154076

在`ctexbook`/`ctexrep`文档类中，当使用`twoside`模式时（即`ctexbook`的默认模式），奇数页页眉是section信息，此时序号和标题内容之间缺少合适空格，比如`1.1some title`。应该是给  \ps@heading 和 \ps@fancy 打补丁时引入的，见ctex文档的14.8.4节。

建议打补丁时保留原来的样式，即 `ctex.dtx` 源文件的8143、8171行改为
`{ \CTEXifname { \CTEXthesection . ~ } { } }`

**Comment by qinglee** [comment]
这是后来引进 `\CTEXifname` 时漏了一个 `\quad` 造成的，已修复。
