### ISSUE TITLE
ctex: 使得 ctex 宏包不载入文档类选项

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#312]
目前 `ctex` 宏包与几个文档类一样，采用 `ProcessKeysOptions` 处理选项。是否可以考虑改用 `ProcessKeysPackageOptions`，使其不载入文档类选项？

如果这样不方便，是否有办法使得文档类选项不影响 `ctex` 宏包？

**Comment by Stone-Zeng** [comment]
因为我自己弄的模板有一个 `nofonts`，会被 `ctex` 认为是过时选项，所以想让这个选项不影响 `ctex`。

**Comment by qinglee** [comment]
这个没有什么好办法，比较暴力的方式是在 `ctex` 之前从 `\@classoptionslist` 中删掉 `nofonts` 或者用 `\msg_redirect_name:nnn` 重定向 `deprecated-option` 为 `none`。
