### ISSUE TITLE
可以考虑给ctex宏包添加一个转换大写中文数字的命令么？

### ISSUE THREAD

**Issue by chennanzhang** [CTeX-org/ctex-kit#314]
财务一些数字需要使用大写中文数字。ctex 宏包中的宏\zhnumber{<number>}生成的是小写的中文数字，能否增加一个宏\ZHnumber{<number>}生成大写的中文数字。代码我想应该很简单，只是把"一二三四五六七八九十百千"字符换成“壹贰叁肆伍陆柒捌玖拾佰仟”就行了。

**Comment by wnduan** [comment]
@chennanzhang ctex 宏集的 `\zhnumber{}` 命令是在 zhnumber 宏包中实现的，可以看看 zhnumber 的文档，你的这个需求可以通过 `style` 选项实现：
```tex
\documentclass{article}
\usepackage{ctex}

\begin{document}
\zhnumsetup{style={Traditional,Financial}}
\zhnumber{62012.3}
\end{document}
```
