### ISSUE TITLE
Adobe and Fandol fontset are not recognized by CTEX with Texlive 2017 in Arch Linux

### ISSUE THREAD

**Issue by cryoguy** [CTeX-org/ctex-kit#317]
I installed CTEX along with Texlive 2017 in a Arch Linux system. The Ubuntu fonset works out of box; After copy Windows Microsoft fonts to my linux box, update the database, windowsnew fonset works without issue. The Adobe and Fandol fonsets are not recognized by ctex? I have all the fonts and the name right in the fontset def file. The Ctex manual says "\pdfmapline 不支持 OpenType 字体,因而 adobe 字体集在 pdf 模式下就没有定义。 fandol 的情况类似。 ". I do not know really know what does it mean. Does anybody has the same issue? For more info, see my post here [http://tech.memoryimprintstudio.com/ctex-and-chinese-languages-with-xelatex/]

**Comment by leo-liu** [comment]
To figure out what the problem is, you should provide:

* The code you compiled.
* The command line you use.
* The output or log file.

The most important thing I must say is: **you CANNOT use pdflatex with Adobe and Fandol fonts.** And this is what the manual says.
