### ISSUE TITLE
twoside 模式下会出现 Underfull \vbox

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#318]
示例代码如下：

```tex
\documentclass[twoside]{ctexbook}
\usepackage{lipsum}

\begin{document}
\lipsum[1-12]
\end{document}
```

报错大概长这样：

```tex
Underfull \vbox (badness 10000) has occurred while \output is active [1]
```

换成 `ctexart` 或 `ctexrep` 文档类也都有这个问题。但改用 `oneside`，或者加上 `scheme=plain` 选项就正常了。

**Comment by leo-liu** [comment]
这单纯是字号和行距设置造成的。我来给你重现这个问题：

```latex
\documentclass{book}

% ctex 文档类的默认字体、字号
\def\normalsize{\fontsize{10.5bp}{12.6bp}\selectfont}
\linespread{1.3}

\usepackage{lipsum}

\begin{document}
\lipsum[1-12]
\end{document}
```

**Comment by Stone-Zeng** [comment]
有什么办法可以规避掉呢？

**Comment by Liam0205** [comment]
1. 这是警告，不是错误。
2. 即使是 Knuth 的 The TeXbook 也有很多 box 的警告。
3. 规避的办法就是调整页面的 geometry 和字号、行距的搭配。
4. 最好的办法就是：「忍」，因为绝大多数情况，这种警告都不是问题。

**Comment by Stone-Zeng** [comment]
用这段代码

```tex
\documentclass[oneside]{article}
\def\normalsize{\fontsize{10.5bp}{12.6bp}\selectfont}
\linespread{1.3}
\usepackage{lipsum}
\usepackage[left=1in,right=1in,top=1.25in,bottom=1.25in]{geometry}

\begin{document}
\lipsum[1-6]
\end{document}
```

没有出现 bad box，但改成 `twoside` 就出现了，请问这是为什么呢？

**Comment by Liam0205** [comment]
改成 `twoside`，就改变了页面的 geometry。

很正常的现象，忽略就好。

**Comment by Stone-Zeng** [comment]
好吧，看了一下标准文档类的代码，原来是因为 `twoside` 的时候没有用 `\raggedbottom`。

给个链接吧：https://tex.stackexchange.com/q/50830/136923

像我这样的强迫症患者的确受不了 bad box 的……

**Comment by Liam0205** [comment]
见得多了，就能忍了……

你不会有那个精力仔细处理遇到的每一个坏盒子问题的。

**Comment by leo-liu** [comment]
其实为了左右页面对称，twoside 一般还是需要 flushbottom 的。
