### ISSUE TITLE
将U+2E3A视作破折号 & Noto CJK（Source Han）默认破折号字面不居中

### ISSUE THREAD

**Issue by TitanSnow** [CTeX-org/ctex-kit#320]
单个U+2E3A（TWO-EM DASH）字符是一个中文破折号，可以代替两个U+2014（EM DASH）。
（参见[clreq](https://w3c.github.io/clreq/#table_of_non-bracket_indication_punctuation_marks)）

xeCJK目前未将其视为中文标点：
```latex
\documentclass{minimal}
\usepackage{ctex}
\setCJKmainfont{NotoSerifSC-Regular.otf}
\setmainfont{NotoSerifSC-Regular.otf}
\begin{document}
\ \\
% Double U+2014
壬——壬\\
% Single U+2E3A
壬⸺壬
\end{document}
```
结果：
![image](https://user-images.githubusercontent.com/19969470/32697546-83418e1a-c7cd-11e7-99e4-c9e8630f3492.png)
应将其加入`FullRight`和`MiddlePunct`

另：

对于Source Han（或Noto CJK），破折号默认是西文破折号，位置偏下：
```latex
\documentclass{minimal}
\usepackage{ctex}
\begin{document}
\begin{tabular}{ll}
Noto &
{\fontspec{NotoSerifSC-Regular.otf}\CJKfontspec{NotoSerifSC-Regular.otf}%
壬——壬……壬⸺壬}\\
Fandol &
{\fontspec{FandolSong-Regular}\CJKfontspec{FandolSong-Regular}%
壬——壬……壬⸺壬}
\end{tabular}
\end{document}
```
与Fandol的对比：
![image](https://user-images.githubusercontent.com/19969470/32697594-e464b9a0-c7ce-11e7-8cd4-33d601c62ec3.png)

Source Han中垂直居中的中文破折号通过`locl`特性得到（参见[SourceHanSerifReadMe](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf)中`Language Particulars`中`Proportional & Half-Width CJK Punctuation`一节），但似乎`fontspec`并不支持`locl`。
无论U+2014还是U+2E3A都无法垂直居中。U+2500可以垂直居中，但不适合作为破折号。
对此是否有workaround？

**Comment by Man-Ting-Fang** [comment]
您拼错了吧，不是`iocl`，而是`locl`，我搜了一下`fontspec`的文档，是在“不支持”的表中。不过，可以试试`fwid`。

**Comment by leo-liu** [comment]
U+2E3A 这个破折号，以前大陆这边做的中文字体都不支持，所以没注意到。日文字体好像都会用。现在 Pan-CJK 字体多起来，支持就有必要了。

双破折号这个设置为 FullRight 感觉不大对，因为感觉前后都允许断行更好。目前的 CJK 字符类别偏少，再考虑一下。

xeCJK 对直排目前没有明确支持，有这方面需求直接用 upLaTeX 或 pLaTeX-ng 吧，也不麻烦。

**Comment by TitanSnow** [comment]
> 您拼错了吧，不是`iocl`，而是`locl`

抱歉。已修改。

> 不过，可以试试fwid

尝试了一下，确实有用。

> 双破折号这个设置为 FullRight 感觉不大对

U+2014被设置为`FullRight`, `MiddlePunct`和`LongPunct`。`LongPunct`似乎是使第一个字符前可以断行，第一个字符和第二个字符之间不能断行，第二个字符之后可以断行；似乎不能用于单个U+2E3A。

**Comment by TitanSnow** [comment]
不需要调用`fwid`，只要将`Language`设置为`Chinese Simplified`就能得到中文破折号

```latex
\documentclass{minimal}
\usepackage[LoadFandol=false]{xeCJK}
\xeCJKDeclareCharClass*{FullRight}{`⸺}
\xeCJKsetup{MiddlePunct+={⸺}}
\begin{document}\ \\
{\CJKfontspec{NotoSerifSC-Regular.otf}壬——壬……壬⸺壬}\\
{\CJKfontspec[Language=Chinese Simplified]{NotoSerifSC-Regular.otf}壬——壬……壬⸺壬}
\end{document}
```

![image](https://user-images.githubusercontent.com/19969470/32935587-c848f908-cbab-11e7-845b-abc5b3f88afc.png)

目前xeCJK只是设置了`Script`为`CJK`，`Language`保持为`DFLT`，而在Noto中是有专门的`hani.ZHS`的

```console
$ otfinfo -s NotoSerifSC-Regular.otf
DFLT		Default
cyrl		Cyrillic
grek		Greek
hani		CJK Ideographic
hani.ZHS	CJK Ideographic/Chinese Simplified
kana		Hiragana/Katakana
latn		Latin
latn.ZHS	Latin/Chinese Simplified
```

xeCJK要支持CJK三者，不太好默认把`Language`设置为`Chinese Simplified`，那么为了处理Pan-CJK字体，我想到三种方法：

* 增加`SCfontspec`、`TCfontspec`之类的单独命令，不同的命令在选取字体时设置不同`Language`
* 增加全局的`Language`选项，作为选取字体的默认`Language`
* 如果是Language-specific OTF或Region-specific Subset OTF，或者是选取字体时指明了语言（比如ubuntu系统安装的Noto Sans一般是`Noto Sans CJK JP`，如果不使用`locl`区域默认是日本，选取简中时用的名称是`Noto Sans CJK SC`），是否能检测到默认的语言设置，将其作为`Language`

#310 如果要添加思源系列字体作为字库选择之一，可能就需要考虑这些问题

**Comment by Firestar-Reimu-Pro** [comment]
谢谢，但这个居中的破折号说实在的比较丑，两边撑得太满了 #444

**Comment by Explorer-cc** [comment]
> 谢谢，但这个居中的破折号说实在的比较丑，两边撑得太满了

您最好引用一下这个链接：https://github.com/CTeX-org/ctex-kit/issues/444#issuecomment-4655604340

否则很容易令人对您的上一个 comment 感到一头雾水。
