### ISSUE TITLE
对 lstlisting 可见空格的定制失效

### ISSUE THREAD

**Issue by zohooo** [CTeX-org/ctex-kit#321]
估计是 `xeCJK` 修改了 `listings` 宏包，导致对可见空格的定制失效。

    \documentclass{article}
    
    \usepackage{listings,xcolor}
    
    % 加入 ctex 包后，对可见空格的定制就无效了
    \usepackage{ctex}
    
    \makeatletter
    \def\lst@visiblespace{\textcolor{gray}{\_}}
    \makeatother
    
    \lstset{
      basicstyle = \ttfamily\color{blue},
      showspaces = true,
    }
    
    \begin{document}
    
    \begin{lstlisting}
    Hello  TeX  World
    \end{lstlisting}
    
    \end{document}

**Comment by Stone-Zeng** [comment]
这其实是 `fontspec` 打的补丁。解决办法一种是在导言区把这个补丁直接关掉：
```tex
\ExplSyntaxOn
\cs_set_eq:NN \fontspec_patch_listings: \prg_do_nothing:
\ExplSyntaxOff
```
另一种是把 `\def\lst@visiblespace{\textcolor{gray}{\_}}` 放到 `\begin{document}` 之后。

另外 `fontspec` 对 `fancyvrb` 宏包也有类似的处理。

**Comment by leo-liu** [comment]
用 \AtBeginDocument 吧。
