### ISSUE TITLE
最新版ctex中ctexbeamer类\insertsectionnumber未定义

### ISSUE THREAD

**Issue by tercelxy** [CTeX-org/ctex-kit#325]
环境：

texlive2017, ctex版本: 2.4.11, beamer版本: 3.45

源代码：
------------------------------------------
\documentclass{ctexbeamer}

\begin{document}
\section{节}
\end{document}
------------------------------------------

编译错误信息：
------------------------------------------
! Undefined control sequence.
\CTEX@thesection ->\insertsectionnumber 
------------------------------------------

用 
-----------------------------------------
\documentclass{beamer}

\usepackage{ctex}
-----------------------------------------
编译正常

**Comment by tercelxy** [comment]
编译方式是xelatex

**Comment by louisstuart96** [comment]
beamer 源码做了改动，去掉了这个 `\insert`，因为功能实际上和 `\thesection` 等重复。
现在可以暂时用这个补丁：
```
\let\insertsectionnumber\thesection
\let\insertsubsectionnumber\thesubsection
\let\insertsubsubsectionnumber\thesubsubsection
```

**Comment by qinglee** [comment]
beamer 文档中说明了 `\partpage` 和对应的 `\insertpart`、` \insertpartnumber` 和 ` \insertromanpartnumber`，同时说明了 `\sectionpage` 和 ` \subsectionpage` 与 `\partpage` 类似，所以我建议保留 `\insertsectionnumber` 等命令。这几个命令历史悠久，已经被广泛使用，也不应该被删除。

**Comment by louisstuart96** [comment]
3.46以后的版本改回来了（低头了）。
