### ISSUE TITLE
关于CTeX标识

### ISSUE THREAD

**Issue by Man-Ting-Fang** [CTeX-org/ctex-kit#326]
目前`\CTeX`的定义中用了`\ifincsname`，但(e-)upTeX和ApTeX中没这个原语，无法使用。（pdfTeX、XeTeX、LuaTeX中都有，没问题。）

**Comment by Liam0205** [comment]
`\ifincsname` 是 pdfTeX 在 e-TeX 基础上引入的 primitive。在 `\csname ... \endcsname` 中的时候，它为 true，否则为 false。

LuaTeX 作为 pdfTeX 的继任，自然也有它（部分新增的 primitive 被改名）。XeTeX 是直接在 e-TeX 上做的扩展，与 pdfTeX 并没有继任关系，但也保留了部分 pdfTeX 新增的 primitive。这其中包含了 `\ifincsname`。

这是为什么在 pdfTeX/XeTeX/LuaTeX 里有这个 primitive 的原因。pTeX 系没有这个 primitive（ApTeX 可以让马起园加），在宏的层面我也不知道怎么做……

**Comment by Liam0205** [comment]
按照 Joseph 的说法，如果没有原语支持，在宏的层面没法做到。

<https://tex.stackexchange.com/questions/404663/how-to-test-if-a-macro-is-being-expanded-between-csname-endcsname-in-e>

所以，似乎应该对 (e-)upTeX 和 ApTeX 采用不同的定义？

**Comment by louisstuart96** [comment]
或者退而求其次，在平时用 `C\TeX` 这样的定义，然后用 hyperref 的 PDF string disable。反正纯文本一般都是书签有需求。

**Comment by qinglee** [comment]
定义 `\CTeX` 的时候，还没有考虑到支持 pTeX 系列，加入 `\ifincsname` 也仅是向 hologo 学习而已，并不是很必要的功能，现在可以删掉。

**Comment by Man-Ting-Fang** [comment]
非常感谢各位老师！
