### ISSUE TITLE
muduo库问题

### ISSUE THREAD

**Issue by BeijingWks** [CTeX-org/ctex-kit#327]
您好，
       我是您的读者，也买了书。
       我现在有个问题，想用eclipse+cdt的方式编译muduo库，net和base已经导入，但是发现在net/protorpc/RpcChannel.cc并没有<muduo/net/protorpc/rpc.pb.h>头文件。有些疑惑，多谢！

**Comment by Liam0205** [comment]
完全来错了地方，muduo 是陈硕的 C++ 项目，这里是 LaTeX 项目。

@chenshuo

**Comment by nanmu42** [comment]
估计是看了#322 来的。
