### ISSUE TITLE
zhmCJK not working with dvips

### ISSUE THREAD

**Issue by pianzuo** [CTeX-org/ctex-kit#328]
I already install fonts for dvips using CTeXFonts.lua. CJKutf8 + latex + dvips works fine.
for example: 
\documentclass{article}
\usepackage{CJKutf8}
\begin{document}
\begin{CJK}{UTF8}{song}
  {普通}{\CJKfamily{hei}粗体汉字测试}{\CJKfamily{fs}斜体}
\end{CJK}
\end{document}

But I cannot use zhmCJK+latex+dvips
for example:
\documentclass{article}
\usepackage{CJKutf8}
\usepackage{zhmCJK}
\setCJKmainfont{simsun.ttc}[BoldFont=simhei.ttf,ItalicFont=simkai.ttf]
\begin{document}
\begin{CJK}{UTF8}{song}
{普通}{\bf 粗体汉字测试}{\it 斜体}
\end{CJK}
\end{document}

It seems that latex works good. But dvips cannot find font file:
This is dvips(k) 5.996 Copyright 2016 Radical Eye Software (www.radicaleye.com)
' TeX output 2017.12.13:1205' -> doc.ps

kpathsea: Running mktexpk --mfmode ljfour --bdpi 600 --mag 1+0/600 --dpi 600 zhm17c

blabla
Can any body help me ?

**Comment by Liam0205** [comment]
It just simply does not support the LaTeX-dvips tool chain.

Please kindly check the documentation carefully.

**Comment by pianzuo** [comment]
The zhmetrics package is a set of font metrics for using Chinese fonts under the latex->dvipdfmx or pdflatex route. Note, Since dvips does not support ttf embedding, you should create type1 subfonts from truetype files by your self using the CTeXFonts.lua provided in this package if you insist to use dvips.
