### ISSUE TITLE
CJK 包中的 Big5 编码问题

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#332]
（这个问题不应该在这边问的，但在 TeX.SX 上面的得到的 [回答](https://tex.stackexchange.com/q/408068/136923) 并不是很有帮助……）

具体就是，Big5 编码下使用 `CJK` 宏包有些字会跪掉，比如

- `認` (0xBB7B)，`程` (0xB57B)，`臨`(0xC17B)
报错是 `! File ended while scanning use of \CJK@XX.`

- `開` (0xB67D)，`稀` (0xB57D)，`飼` (0xB97D)
报错是 `! Argument of \CJK@XX has an extra }.`

@yudai-nkt 给的分析是这些汉字的后两个字节正好分别对应了 `{` 和 `}` 的编码，于是就被误识别了。但他没有给出解决方案，请问大神有没有什么办法处理？

我知道尽量应该用 `ctex`，但目前似乎并没有使用 Big5 的现成方案。至于 Big5 本身，我只是测试一下，正常当然还是用 UTF8 会靠谱一些。

示例：

```tex
\documentclass{article}
\usepackage{CJK}
\begin{document}
\begin{CJK*}{Bg5}{bsmi}
認識
\end{CJK*}
\end{document}
```

环境：TeX Live 2017，CJK v4.8.4
编辑器我用的是 VS Code，已经切换到了 Big5 编码。

**Comment by Man-Ting-Fang** [comment]
现在那个回答里已经加上了解决办法，就是先用`bg5conv`之类程序转换一下。在[CTAN](https://ctan.org/pkg/cjk)或者[CJK](https://cjk.ffii.org/)上下载完整的CJK包，里边有详细的说明。（TeX Live安装的当然也完整，但是分散在各处。）貌似还有一些封装的命令，如`bg5latex`、`bg5pdflatex`等。

**Comment by Liam0205** [comment]
这个就是经典的「許蓋功」问题。原因是 GBK/Big5 之类的编码在第二字节并没有避开 ASCII 码的范围，导致部分汉字编码的第二字节恰好是 ASCII 编码中的一些特殊字符。在 TeX 中的话，遇到 `\`/`{`/`}` 尤其容易出问题。问题得名于台湾那边正体中文中，常用字「許蓋功」都因此中招；而这三个字听起来是个人名。

既然问题根植编码方案之中，一劳永逸的方案当然就是放弃这个编码，转向伟大光辉正确的 UTF-8 编码。如果不想用 UTF-8……（我能打人吗？）

如果坚持用 GBK 或者 Big5 之类的编码，就要在传入 LaTeX 之前做预处理。具体来说，就是用 `gbklatex`/`gbkpdflatex`/`bg5latex`/`bg5pdflatex` 代替原始的 `latex` 和 `pdflatex` 命令去编译文件。
