### ISSUE TITLE
关于使用 XeLaTeX 编译文档时，字符“□”（U+25A1）无法显示的问题。

### ISSUE THREAD

**Issue by K-JW** [CTeX-org/ctex-kit#337]
将字符“□”（U+25A1）正常输入之后，使用 XeLaTeX 方式编译，发现字符“□”（U+25A1）无法显示。当然我可以使用符号宏包了的 $\Box$ 输出一个方框，但是很明显这种输出的方框与附近的文字风格不太一致。所以请问这是一个 bug 还是一个 feature 啊？我该如何解决这个问题？

**Comment by Liam0205** [comment]
请检查你使用的字体中是否有这个字符。

在 2018年2月6日 下午12:13，JW <notifications@github.com>写道：

**Comment by K-JW** [comment]
我使用的是ctex默认的设置，具体代码如下：
`\documentclass[UTF8,fontset=windows]{ctexart}
\begin{document}
方框：□
\end{document}`

我看ctex文档，如此设置的话使用的是windows下的宋体字体，我已经查看过了，windows下的宋体字库肯定包含这个字符。谢谢！

**Comment by Liam0205** [comment]
不要想当然啊……

`xeCJK` 设置了 CJK 字符类的 Unicode 区域，以将这部分字符与剩余其他字符的字体分开设置。这个区域的起始是 CJK Radicals Supplement 块，即 `"2E80 -> "2EFF`。

方块的 Unicode 编码是 `25A1`，还在这个区域之前，所以不会使用 `xeCJK` 设置的 CJK 字体。因此方框使用的不是宋体，你看宋体是没意义的。

按照你的代码，用 XeLaTeX 编译时，该字符会使用 Latin Modern 字体。而该字体里没有这个字符。

如下代码可正常显示中易宋体当中的方框。

```tex
\documentclass{article}
\usepackage{fontspec}
\begin{document}
{\fontspec{SimSun}□}
\end{document}
```
