### ISSUE TITLE
ctex 宏包配合 appendices 环境出现问题

### ISSUE THREAD

**Issue by IonizingRadiation** [CTeX-org/ctex-kit#339]
在使用 `ctex.sty` 和 `appendix.sty` 时出现以下问题：
使用 `ctexset` 指定 `section` 的标题样式（`section`的标题显示为`第x章`）后，如果使用 `\appendix` 命令，则可以按照预期结果输出，目录显示正常。
但如果使用 `appendices` 环境，则附录的标题会变为 `第A章`，`第B章`，并且目录中附录的标题也跟着变为`第A章`，`第B章`。 请问这个问题应该如何解决，如果坚持要使用`appendices`环境的话？
![image](https://user-images.githubusercontent.com/17506747/36069663-1401f2f8-0f29-11e8-8131-c564a8bcd8f1.png)

![image](https://user-images.githubusercontent.com/17506747/36069666-254bf2a2-0f29-11e8-9cfc-567fdfad0cfa.png)

MWE 如下
```tex
\documentclass[a4paper]{article}
\usepackage[heading=true]{ctex}
\usepackage[header, toc, page]{appendix}

\ctexset{
	section={%
		format={\centering \heiti \zihao{3}},
		name={第,章}
	}
}

\begin{document}
\tableofcontents
\clearpage
 
\section{First}
First content.
\section{Second}
Second content.

%\clearpage
%\appendix
%\appendixpage

\begin{appendices} 
	\section{Appendix First}
	Appendix first content.
	\section{Appendix Second}
	Appendix second content.
\end{appendices}

\end{document}
```

**Comment by qinglee** [comment]
当初实现时就没有考虑过 appendix 包。不过话说回来，这个包功能比较弱的，有些地方跟 ctex 还是冲突的，我不打算去兼容他了。你非要用，可以在 `appendices` 环境开头加入以下代码，可部分解决问题。

https://github.com/CTeX-org/ctex-kit/blob/7026a4873e593f29c7ac2778b44174add6562ee4/ctex/ctex.dtx#L7779-L7790

**Comment by IonizingRadiation** [comment]
感谢您的解答。 除了appendix包，有没有其他功能类似的包呢？

**Comment by qinglee** [comment]
这我就不清楚了。你不想动内部命令的话，也可以在 `appendices` 环境内部用 `\ctexset` 重新设置章节的名字为附录，这可以借助 `etoolbox` 提供的 `\AtBeginEnvironment` 钩子来完成。

**Comment by IonizingRadiation** [comment]
好的，感谢解答。
