### ISSUE TITLE
xeCJK: 先于 fontenc 使用时会使 \ldots 使用中文标点

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#342]
使用版本：xeCJK v3.6.1 (750a4bca996d9348745ab1a1220d7e14f5b0c3ac)

测试代码：
```latex
\documentclass{article}
\usepackage{xeCJK}[2018/02/27]
\usepackage[T3,TU]{fontenc}
\begin{document}
A\ldots B
\end{document}
```

没有仔细分析。

**Comment by qinglee** [comment]
`tuenc.def` 会覆盖 xunicode-addon 的定义，导致补丁失效。可以在 fontenc 后使用 `\ReloadXunicode{TU}`。

**Comment by leo-liu** [comment]
我也知道是 tuenc 覆盖了 xunicode-addon 的问题。不过不太确定合理的行为是不是应该是把补丁延迟载入。毕竟中文文档再间接调用
fontenc 听常见的，而影响补丁的行为不大可能是有意为之。
倒是可以加一个选项不载入 xunicode-addon 的补丁，留给西文为主的文档用。

2018年3月7日 01:48，"Qing Lee" <notifications@github.com>写道：

tuenc.def 会覆盖 xunicode-addon 的定义，导致补丁失效。可以在 fontenc 后使用 \ReloadXunicode{TU}。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CTeX-org/ctex-kit/issues/342#issuecomment-370867504>,
or mute the thread

**Comment by qinglee** [comment]
fontspec 从去年开始就默认不引入 xunicode 包了，我们也不必再引入 xunicode，那些中西文混用的符号可以单独补丁处理。
