### ISSUE TITLE
英文前双引号中的两个单引号间距问题

### ISSUE THREAD

**Issue by woshiYummy** [CTeX-org/ctex-kit#343]
在使用 ctex 文档类与 newtxtext 过程中发现英文前双引号出现不一致，特别是前双引号后跟中文的时候，双引号中的两个单引号之间距离过宽，效果与跟英文或数学字符有差别！

临时解决方法是在前双引号后加一对花括号，不知道可否有更合理的解决方案？

编译环境是
Win10 + WinEdt 10.2 + MiKTeX 2.9.6600 64-bit + xelatex
XeTeX, Version 3.14159265-2.6-0.9999

然后怀疑是 xeCJK 的问题，ctex 说明文档中说用 xelatex 处理使用的是 xeCJK，使用 pdflatex 处理使用的 CJK。

而当我使用 book 类加 xeCJK 宏包加 xelatex 时候问题仍旧，而使用 pdflatex 编译原文档 ctexbook 类不加 xeCJK 的时候确实就都正常了。

下面是代码
`
\documentclass[UTF8]{ctexbook}%{book}

%\usepackage{xeCJK}
%\setCJKmainfont{SimSun}

\usepackage[T1]{fontenc}
\usepackage{newtxtext}

\begin{document}

\``资本'' ``Text''

\``{}资本'' ``{}Text''

"资本" "Text"

"{}资本" "{}Text"

“资本”“Text”

“{}资本”“{}Text”

\`资本' `Text'

\`{}资本' `{}Text'

\end{document}
`

效果如图
![qq 20180311152847](https://user-images.githubusercontent.com/25896114/37250900-500cccb8-2541-11e8-9167-774ffde3fbda.png)

**Comment by leo-liu** [comment]
基本问题同 #342 ，应该算是一个 bug。

另，中文要用中文引号，不要用 <code>``</code> 和 `''`。

**Comment by qinglee** [comment]
这个问题（包括 #281，#239）是 XeTeX 本身的问题：
```TeX
\XeTeXinterchartokenstate=1

\XeTeXcharclass`a=1
\XeTeXinterchartoks 1 0 = {\1}
\XeTeXinterchartoks 0 1 = {\2}

\font\1=ntx-Regular-tlf-t1
\font\2="[texgyretermes-regular.otf]"

\1

``a''

--a--

---a---

ffaff

ff a

\bye
```

传统 .tfm 字体和现代字体混用时，XeTeX 的字符类机制就会出现这个问题。

其实可以不用 newtxtext 包，直接用 fontspec 包设置正文字体为 TeX Gyre Termes 等现代字体。
