### ISSUE TITLE
设置setmainfont和setsansfont为同一英文字体名时导致ssfamily调用黑体失效

### ISSUE THREAD

**Issue by mohuangrui** [CTeX-org/ctex-kit#348]
尊敬的ctex开发者你们好，我的问题描述和测试代码如下：

```
\documentclass[fontset=fandol]{ctexbook}%
\usepackage{fontspec}% support calling system fonts
\setmainfont{Times New Roman}
\setsansfont{Times New Roman}
\ctexset {
    chapter/format = \bfseries\sffamily\centering,
     section/format = \sffamily\raggedright,
}
\begin{document}
\chapter{bfseries sffamily 退回宋体加粗}
\section{sffamily 退回宋体}
	此问题由设置setmainfont和setsansfont为同一字体名所导致，如果不设置setsansfont或setsansfont采用另一字体名，则不会导致此问题。黑体退回宋体不仅发生在标题，同时也发生在如下文本中，但heiti命令不受影响。
        \begin{itemize}
            \item 宋体：飞扬跋扈 times~或 \textrm{飞扬跋扈 times}
            \item 粗宋体：{\bfseries 飞扬跋扈 times} 或 \textbf{飞扬跋扈 times}
            \item 黑体 sffamily：{\sffamily 飞扬跋扈 times} 或 \textsf{飞扬跋扈 times}
            \item 黑体 heiti：{\heiti 飞扬跋扈 times}
            \item 粗黑体：{\bfseries\sffamily 飞扬跋扈 times} 或 \textsf{\bfseries 飞扬跋扈 times}
            \item 仿宋：{\ttfamily 飞扬跋扈 times} 或 \texttt{飞扬跋扈 times}
            \item 楷体：{\itshape 飞扬跋扈 times} 或 \textit{飞扬跋扈 times}
        \end{itemize}
\end{document}
```
编译效果如图：

<img width="713" alt="test" src="https://user-images.githubusercontent.com/7518165/38069884-d29223e2-32e6-11e8-9cef-14f837ce117f.png">

若不设置setsansfont，则效果如下图：

<img width="729" alt="normal" src="https://user-images.githubusercontent.com/7518165/38069933-0bb511e8-32e7-11e8-9a24-0c4cdfec9b4f.png">

在阅读完 ctex，xecjk， fontspec的文档后，仍不理解问题所在，特别是heiti不失效单ssfamily却失效了，所以特此发问，谢谢解答。

**Comment by qinglee** [comment]
fontspec 包的策略是，如果两个字体完全相同，就不定义新字体。这里，mainfont 和 sansfont 的定义完全相同，都是 Times New Roman，他们就共用了一个族名 `TimesNewRoman(0)`，我们对 `\fontfamily` 的补丁就无法区分用户使用的是 `\rmfamily` 还是 `\sffamily`，导致中文字体族匹配失误。

如果字体的定义完全相同，可以指定 `NFSSFamily` 选项，让 fontspec 总是定义新字体，避免族名复用：

    \setsansfont[NFSSFamily=sf]{Times New Roman}

**Comment by mohuangrui** [comment]
@qinglee 非常感谢您的解答！
