### ISSUE TITLE
ctex: 升级 macOS 下的字体配置，增加默认罗马字族及无衬线字族的字重组合

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#351]
同 <https://github.com/CTeX-org/ctex-kit/issues/335#issuecomment-359146475>，但是好像没下文了。

目前 ctex 在 mac 下的默认字体是这样的：

![1](https://user-images.githubusercontent.com/12290822/38232813-fa8430c6-374a-11e8-8a24-f2a89a21e960.png)

我现在的设置是：
```
\setCJKmainfont{Songti SC}[
  UprightFont    = Songti SC Light,
  ItalicFont     = Kaiti SC,
  BoldItalicFont = Kaiti SC Bold,
]
\setCJKsansfont{Heiti SC}
```
效果：
![2](https://user-images.githubusercontent.com/12290822/38232822-067c5ae8-374b-11e8-9762-b8871ae287cd.png)

但是还有两个问题：
1. 上述设置代码放到 ctex-fontset-mac.def 上因为空格被去掉了导致错误
2. 直接设置文件名 /Library/Fonts/Songti.ttc 有错误

**Comment by Liam0205** [comment]
没下文是因为我 3 月份基本都在住院状态中度过……

**Comment by Liam0205** [comment]
本次对 macOS 下默认字体的修改，计划自 Sierra 开始兼容，放弃或部分放弃对更低版本 OS X/macOS 的兼容性。

Apple 官网可查 Sierra 默认预装的字体：<https://support.apple.com/en-us/HT206872>。

**Comment by Liam0205** [comment]
目前拟将 XeLaTeX 下的默认配置修改为：

```tex
        \setCJKmainfont [ ItalicFont = Kaiti SC, BoldItalicFont = Kaiti SC Bold ]  { Songti SC }
        \setCJKsansfont { Heiti SC }
        \setCJKmonofont { STFangsong }
        \setCJKfamilyfont { zhsong } { Songti SC }
        \setCJKfamilyfont { zhhei }  { Heiti SC }
        \setCJKfamilyfont { zhfs }   { STFangsong }
        \setCJKfamilyfont { zhkai }  { Kaiti SC }
```

**Comment by zepinglee** [comment]
Songti SC Light 的字重跟 STSong 更接近，跟 SimSun 也更接近，所以 regular 应该设为这个

**Comment by mohuangrui** [comment]
@zepinglee @Liam0205 

认同 @zepinglee 的建议，Light字重似乎更和 STSong 和 SimSum 接近，而且 Songti SC 自带 Bold，所以可以不用考虑用黑体替换粗宋体，因此也许可考虑：

```
        \setCJKmainfont[BoldFont=Songti~SC~Bold, ItalicFont=Kaiti~SC]{Songti~SC~Light}
        \setCJKsansfont{Heiti~SC~Light}%
        \setCJKmonofont{STFangsong}%
```
@zepinglee ctex 用的 LaTeX3，所以需要  `~` 显示指定空格

**Comment by mohuangrui** [comment]
对了，换字体过程中，我还遇到的一个状况就是似乎SC类字体xelatex调用没有任何异常时却不为luatex所识别，具体原因我也不知道，所以还请大神们在改代码时能关注测试一下。

**Comment by Liam0205** [comment]
按孙志贵的建议，无衬线字体可考虑使用苹方代替 `Heiti Sc`。或可仿照 `windowsold` 和 `windowsnew` 的设计，配置 `macold` 和 `macnew`；而后在 `macnew` 当中使用苹方作为默认的黑体。

**Comment by Liam0205** [comment]
@qinglee 之前在 <https://github.com/CTeX-org/ctex-kit/issues/335#issuecomment-359146475> 中提及：
「新加字重的字符集大概只覆盖到最基本的 GB2312，与原来字体并不一致」。

这个信息是在哪里查询得到的呢？或是自己测试得到的结论？

**Comment by Liam0205** [comment]
赞，了解了。

**Comment by leo-liu** [comment]
用 macold 加 macnew 是没问题的，同意。然后通过检测字体文件来区分新旧。

新字体集的话，无衬线肯定是用屏幕黑体（冬青黑、苹方之类）比较好，因为 beamer 默认是无衬线体。印刷黑体留给 `\heiti` 命令，仍然可以有多个字重。

如果比较多，是可以增加一些字体命令，类似 Windows 下的 `\yahei` 这种。
比如说，可以给 macOS 定义 `\pingfang` 命令，同时把 `\yahei` 和它定义成别名。

**Comment by zepinglee** [comment]
另外还可以把报隶字体作为 `\lishu`

**Comment by zepinglee** [comment]
我觉得“伪·雅黑”就不要加进去了吧

**Comment by Liam0205** [comment]
@zepinglee 那是按照 @leo-liu 的建议，给 `\yahei` 留的兼容性。

**Comment by zepinglee** [comment]
我现在为了把 windowsnew 的 sffamily 换成 simhei，写的是 `\ifx\yahei\undefined` （[ustctug/ustcthesis/ustcthesis.dtx#172](https://github.com/ustctug/ustcthesis/blob/1efc9801957e237c9d2b4583b8d40490fe2fb69d/ustcthesis.dtx#L712)），这就很尴尬啦

**Comment by mohuangrui** [comment]
@zepinglee 对了，下面是我的对接 ctex 系统检测的方法，这样会比检测某些细节设定更加稳定和一致：

```
\RequirePackage{expl3}% LaTeX3 programming environment
\ExplSyntaxOn%
\providecommand{\g__ctex_fontset_tl}{}% platform fontset state variable
\edef\artxfontset{\g__ctex_fontset_tl}% expanded platform fontset state variable
\ExplSyntaxOff%
\newif\ifartx@windows \artx@windowsfalse
\newif\ifartx@mac \artx@macfalse
\newif\ifartx@adobe \artx@adobefalse
\newif\ifartx@times \artx@timesfalse
\newif\ifartx@others \artx@othersfalse
\RequirePackage{etoolbox}% a toolbox of programming facilities
\newcommand{\artxifstreq}{\expandafter\ifstrequal\expandafter}% expansion control
\artxifstreq{\artxfontset}{windows}{\artx@windowstrue\artx@timestrue}{%
\artxifstreq{\artxfontset}{mac}{\artx@mactrue\artx@timestrue}{%
\artxifstreq{\artxfontset}{adobe}{\artx@adobetrue\artx@timestrue}{%
\artx@otherstrue\artx@timesfalse}}}
```
核心就是首先对接然后检测 ctex 的全局 fontset 变量 `\g__ctex_fontset_tl`

**Comment by Liam0205** [comment]
@mohuangrui 你的思路大体是对的：不应该检测实现细节；但是这个方案不能区分 `windowsnew` 和 `windowsold`。

@zepinglee 可以检查装载了哪一个 `ctex-fontset-*.def` 文件来实现你的需求。

**Comment by mohuangrui** [comment]
@Liam0205 确实无法检测new和old，如ctex本身是通过`\file_if_exist:nTF { C:/bootfont.bin }`来检测new和old的。

实践中发现，往往不会考虑雅黑，所以，我的办法是不管new还是old，都设成simhei就好，简单粗暴但有效～

**Comment by Liam0205** [comment]
`macold` 在 Yosemite 上验证通过。

**Comment by Stone-Zeng** [comment]
话说，这个是不是跳一个大一点的版本号比较合适，比如 2.5.0 这样的？毕竟算是有新功能添加了。

**Comment by Liam0205** [comment]
话是这样说，不过主体逻辑并没有改变，而且 tag 已经打了，所以就这样吧……

**Comment by zepinglee** [comment]
学习了

**Comment by leo-liu** [comment]
所以说

    \setCJKmainfont [ ItalicFont = Kaiti~SC, BoldItalicFont = Kaiti~SC~Bold ]  { Songti~SC }

为什么变成了

    \setCJKmainfont [ UprightFont = Songti~SC~Light, ItalicFont = Kaiti~SC, BoldItalicFont = Kaiti~SC~Bold ]  { Songti~SC }

两个疑问：

1. 默认的字重到底应该是 Regular（Songti SC）还是 Light？
2. 若默认的字重是 Light，为了比较清楚，似乎也是这样写更好：

    \setCJKmainfont {Songti~ SC }
      [
        UprightFont = *~ Light,
        BoldFont = *~ Bold,
        ItalicFont = Kaiti~ SC,
        BoldItalicFont = Kaiti~ SC~ Bold,
      ]

另外，关于 `\songti` 即 `zhsong` 族是不是应该以楷体为斜体，也可以讨论。

**Comment by Liam0205** [comment]
@leo-liu 

1. 按照 @zepinglee 和 @mohuangrui 的说法，`Songti SC Light` 更接近 SimSun 和 STSong，所以 `\rmfamily\mdseries\upshape` 用的是 `Songti SC Light`。
2. `\songti` 这里我犹豫过。后来我的考虑是这是字体选择命令，用户明确说了「我要用宋体」，那么 `\itshape` 给楷书其实蛮奇怪的，如果是我的话宁愿给 `AutoFakeSlant` 上去。所以最后还是不设置楷书为 `ItalicFont`。

**Comment by Liam0205** [comment]
写了一篇作业：https://liam0205.me/2018/05/03/ctex-2-4-14-update-for-the-fontset-for-macOS/

**Comment by zepinglee** [comment]
还有建议加入 Baoli SC 作为 `\lishu` 的字体

**Comment by leo-liu** [comment]
Mavericks 也有 Hiragino Sans GB W3 吧，其实和苹方基本是接近的屏幕黑体（事实上 PingFang.ttc 里面就有 Hiragino Sans GB Interface W3）。

以前我不怎么用 mac 所以也没有在这个问题上多考虑，冬青黑体在 Mavericks 上不能用么？

**Comment by Liam0205** [comment]
印象里 Mavericks 是可以用冬青黑的，不过我手头实在没有环境了，这个不好确认。

是准备把 `macold` 里设置无衬线为冬青黑？

**Comment by leo-liu** [comment]
我觉得设置为冬青黑是好一些。不过既然 macOS 更新那么果决其实也无所谓。

**Comment by Liam0205** [comment]
我还是没想好 `macold` 应该怎么更新，直接换成冬青黑好像也不太好？

所以搞成这样又很麻烦……更多的是，很恶心……？

```tex
%<*macold>
\sys_if_engine_pdftex:TF
  { \ctex_fontset_error:n { mac } }
  {
    \sys_if_engine_uptex:TF
      { \ctex_fontset_error:n { mac } }
      {
        \setCJKmainfont [ BoldFont = STHeiti , ItalicFont = STKaiti ]  { STSong }
        \file_if_exist:nTF { /System/Library/Fonts/Hiragino~Sans~GB~W3.ttc }
          {
            \file_if_exist:nTF { /System/Library/Fonts/Hiragino~Sans~GB~W6.ttc }
              {
                \setCJKsansfont
                  [
                    BoldFont = HiraginoSansGB-W6
                  ] { HiraginoSansGB-W3 }
              }
              { \setCJKsansfong [ BoldFont = STHeiti ] { STXihei } }
          }
          { \setCJKsansfong [ BoldFont = STHeiti ] { STXihei } }
        \setCJKmonofont { STFangsong }
        \setCJKfamilyfont { zhsong } { STSong }
        \setCJKfamilyfont { zhhei }  { STHeiti }
        \setCJKfamilyfont { zhfs }   { STFangsong }
        \setCJKfamilyfont { zhkai }  { STKaiti }
        \file_if_exist:nT { /System/Library/Fonts/Hiragino~Sans~GB~W3.ttc }
          {
            \file_if_exist:nTF { /System/Library/Fonts/Hiragino~Sans~GB~W6.ttc }
              {
                \setCJKfamilyfont { zhdqh }
                  [
                    BoldFont = HiraginoSansGB-W6
                  ] { HiraginoSansGB-W3 }
              }
              { \setCJKfamilyfont { zhdqh }  { HiraginoSansGB-W3 } }
          }
      }
  }
%</macold>
%<macold>\file_if_exist:nT { /System/Library/Fonts/Hiragino~Sans~GB~W3.ttc }
%<macold>  { \NewDocumentCommand \dongqing { } { \CJKfamily { zhdqh } } }
```

**Comment by Liam0205** [comment]
@AlexaraWu `\lishu` 的问题参见 #360 ，`\youyuan` 的问题你可以再开一个 issue 讨论。

**Comment by Liam0205** [comment]
冬青黑的问题，目前 `macold` 还是保留旧配置。有更新消息之后，开新 issue 讨论。
