### ISSUE TITLE
ctex: 在 MacTeX 2018 下 LuaLaTeX 编译结果中字体选择异常

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#358]
在对 #351 的测试过程中发现，使用 LuaLaTeX 编译，得到的结果与 XeLaTeX 编译不一致。具体来说，`\setCJKsansfont` 和 `\setCJKmonofont` 似乎都没有成功，`\heiti` 和 `\fangsong` 命令也是如此。

MWE：

```tex
\documentclass[UTF8, fontset = mac]{ctexart}
\begin{document}
\section{默认字体测试}
罗马字族 \textbf{罗马字族加粗} \textit{罗马字族意大利体} \textbf{\textit{罗马字族意大利体加粗}}

\textsf{无衬线字族} \textbf{\textsf{无衬线字族加粗}}

\texttt{等宽字族} \textbf{\texttt{等宽字族}}

\section{字体选择命令测试}

{\songti 宋体 \textbf{宋体加粗}}

{\kaishu 楷书 \textbf{楷书加粗}}

{\heiti 黑体 \textbf{黑体加粗}}

{\fangsong 仿宋 \textbf{仿宋加粗}}

% {\pingfang 苹方 \textbf{苹方加粗}}

% {\yahei 伪·雅黑 \textbf{伪·雅黑加粗}}
\end{document}
```

Result：

![image](https://user-images.githubusercontent.com/3348485/39500725-2bfec936-4de9-11e8-98c5-dae37a0496c6.png)

**Comment by qinglee** [comment]
代码方面没什么问题，我怀疑是跟 #352 类似的字体方面的问题，你可以试试直接用 fontspec 包或者 luaotfload 包调用字体，看看能成功么。

**Comment by Liam0205** [comment]
好，下班回家之后看看。

**Comment by Liam0205** [comment]
`fontspec` 直接调用也有问题。看起来是更底层的锅。于是忽略这个 Issue。
