### ISSUE TITLE
problem with accents on an empty base

### ISSUE THREAD

**Issue by davidcarlisle** [CTeX-org/ctex-kit#359]
This was reported originally on debian list and then to the latex maintainers as a change in the latex 2018-04-01 release but I think it is a change in xeCJK, as in texlive 2018 the error goes if I use the version of xeCJK.sty from texlive 2017.

```

\documentclass{report}

\usepackage{xeCJK}


\begin{document}


これは、\`{}安定版'


\end{document}

```

Produces

```
! Undefined control sequence.
<argument> \\TU\`-\@empty 
                          
l.10 これは、\`{}
             安定版'
? 
```

in texlive 2018 but if I copy the xeCJK.sty from texlive 2017 the error goes.

the main difference I think is that the older version causes the xunicode package to be loaded.

Sorry I did not trace further but the comments in xeCJK.dtx were a bit  hard for me:-)

David

**Comment by qinglee** [comment]
Fixed. Thanks for reporting!
