### ISSUE TITLE
ctex: 为 macnew 增加 \lishu 的定义

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#360]
据 @zepinglee 在 https://github.com/CTeX-org/ctex-kit/issues/351#issuecomment-386230447 的建议，考虑将 macOS 下的 `Baoli SC` 作为 `\lishu` 的定义加入 `macnew` 字库配置中。

**Comment by Liam0205** [comment]
macOS/OS X 各版本预装字体。

Apple 官网：

* 10.9 Mavericks: <https://support.apple.com/en-us/HT201375>
* 10.10 Yosemite:
* 10.11 Sierra: <https://support.apple.com/en-us/HT206872>
* 10.12 High Sierra: 

第三方：[List of typefaces included with macOS](https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS)。

**Comment by Liam0205** [comment]
目前 `macnew` 以 Yosemite 和 El Capitan 为分界线。目前看到的资料，Baoli SC 在 Mavericks 中加入默认字体库（版本 8.0d1e1）。因此在 `macnew` 中加入 Baoli SC 在这个意义上是没问题的。

Baoli SC 在 Sierra 和 High Sierra 上的版本分别是 12.0d3e2 和 13.0d3e1。

此外，Baoli SC 虽然是 `Baoli.ttc`，但是字重只有 Regular 一个。这里应注意，做个记录。

**Comment by Liam0205** [comment]
根据[极限社区](http://bbs.themex.net/archive/index.php/t-16904843.html)的讨论，目前在 High Sierra 当中，Baoli SC 是附加字体——需要额外下载，并不是默认包含的字体。

这可能会有问题：

1. 如果检测文件存在性，则结果不准确；
2. 若用户没有预先装好 Baoli SC，使用 TeX 调用会报错（而不是触发预装）。

待解决。

**Comment by zepinglee** [comment]
这就奇怪了，我的 High Sierra 一装好就是带 Baoli SC 的……

另外按照 https://support.apple.com/en-us/HT207962 的说法，Kaiti SC Regular 都是在“Fonts available for download”一类的，这就有点让人搞不懂了

如果有这么多问题的话，我觉得那就不要配置 mac 的 `\lishu` 了，用户自己需要时自己去调用就好。

还有我一直没找到 Baoli.ttc 的位置在哪里

**Comment by Liam0205** [comment]
@zepinglee 
```bash
/
$ find . 2>/dev/null | grep -i baoli | grep -i font
./System/Library/Assets/com_apple_MobileAsset_Font3/3abf40766b4cf50b77ebd28e6affbd1849ea61c6.asset/AssetData/Baoli.ttc
./System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/FontInfo/Baoli.ttc.194C4_0.ATSD
./System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/FontInfo/Baoli.ttc.194C4_0.fontinfo
./System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/FontInfo/Baoli.ttc.284E570_0.ATSD
./System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/FontInfo/Baoli.ttc.284E570_0.fontinfo
./System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Support/FontSubsets/Baoli.ttc
```

**Comment by Liam0205** [comment]
看起来 Baoli SC 并不适合选进来做字体，所以这个计划还是放弃比较好= =
