### ISSUE TITLE
xeCJK: 在 beamer 中使用，数学环境中数字字体变为衬线字体

### ISSUE THREAD

**Issue by PNBRQK** [CTeX-org/ctex-kit#361]
比如：
\documentclass{beamer}
\usepackage{xeCJK}

\begin{document}
\frame{$2+3$}
\end{document}
![2018-05-06 11_40_53-a pdf - sumatrapdf](https://user-images.githubusercontent.com/9943990/39669252-138e9f6a-5119-11e8-8af3-1c67a690a543.png)

如果去掉xeCJK宏包：
\documentclass{beamer}

\begin{document}
\frame{$2+3$}
\end{document}
![2018-05-06 11_42_59-a pdf - sumatrapdf](https://user-images.githubusercontent.com/9943990/39669261-5d050d8c-5119-11e8-9b07-8778abe77e91.png)

当然，ctexbeamer也受到了这个影响：
\documentclass{ctexbeamer}

\begin{document}
\frame{$2+3$}
\end{document}
![2018-05-06 11_47_18-a pdf - sumatrapdf](https://user-images.githubusercontent.com/9943990/39669275-fefca122-5119-11e8-88cb-527aea7112a1.png)

我曾经试图在保留xecjk包的情况下把数字字体改成第二个图那样，但多方努力均未奏效，故前来向贵处请教其中原理。

**Comment by qinglee** [comment]
这是由 `fontspec` 包造成的，可以通过给文档类加上全局选项 `no-math` 禁用 `fontspec` 包的数学字体设置来解决：

```latex
\documentclass[no-math]{beamer}
```

**Comment by leo-liu** [comment]
加 no-math 选项，它会传递给 fontspec。

在 2018年5月6日 上午10:43，PNBRQK <notifications@github.com>写道：
