### ISSUE TITLE
xeCJK: 开启伪粗导致 PDF 插图的字体异常

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#362]
```
\documentclass[UTF8]{ctexart}
\setCJKmainfont[AutoFakeBold]{STSong} % SimSun 也能复现
\usepackage{graphicx}
\begin{document}
宋体, \textbf{伪粗宋体} \\
\includegraphics{fig}
\end{document}
```

插入的原图是 [fig.pdf](https://github.com/CTeX-org/ctex-kit/files/1994180/fig.pdf)，但是编译的结果是
<img width="746" alt="screen shot 2018-05-11 at 2 31 40 pm" src="https://user-images.githubusercontent.com/12290822/39910054-0bd007b0-5528-11e8-9753-93a49865c648.png">

目前在 TeX Live 2017/2018, Mac/Windows 都能复现，这是 xetex 底层的 bug 吗？

**Comment by zepinglee** [comment]
@mohuangrui @Stone-Zeng 你们有没有遇到类似的情况？

**Comment by mohuangrui** [comment]
@zepinglee  是的，这也是 xetex 的一个 bug， 我在 [字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE) 进行了讨论。关于 PDF 的部分如下：
* 据 [tex.se 源一](https://tex.stackexchange.com/questions/47200/fontspec-fakebold-affects-text-in-graphics) 和 [tex.se 源二](https://tex.stackexchange.com/questions/220460/incompatibility-between-fontspec-and-graphicx-bug-of-xetex?noredirect=1&lq=1)，若图格式为 .pdf 或 .eps 等矢量图时出现字体加粗问题，则为 xetex 的一个 bug 所导致（已对英文字体进行了修复，中文字体仍存在问题）。其解决方法为：
    * 输出图时选择**不嵌入**字体在图中，特别是 Windows 系统上所生成的图，比如模板所采用的 .pdf 图都没有嵌入字体，测试发现似乎不会出现异常加粗的问题。
        检查 PDF 中字体的方法：
        * Windows: `findstr FontName document.pdf`
        * MacOS: `strings document.pdf | grep -i FontName`
        * Linux: `pdffonts document.pdf`
    * 避免在矢量图中使用中文可消除此问题。如果有大量中文，可考虑使用 .jpg 或 .png 等位图格式， 亦可消除问题。
    * 如果不想修改图本身且需要使用中文，则可考虑对每一个 `\includegraphics{}` 命令进行如下处理：
```
\begingroup
\fontspec{Times New Roman}{\color{white}.}%
\includegraphics{plot}
\endgroup
```

**Comment by mohuangrui** [comment]
@zepinglee 那可能就是你的 xetex 版本是 2015年的，更新似乎是在 xetex 0.99 以后。

**Comment by mohuangrui** [comment]
好吧，那这个问题就是多重的，可能就是你的 PDF 中还嵌入了字体。我用没嵌入字体的PDF在2015版上有异常，但在2018上正常。不管怎样，问题的解决就是：
方案一：  使用位图 .jpg 等而不是用适量图 .pdf
方案二： 用据 [tex.se 源一](https://tex.stackexchange.com/questions/47200/fontspec-fakebold-affects-text-in-graphics) 提供的 group 对插图字体环境进行局部处理：
```
\begingroup
\fontspec{Times New Roman}{\color{white}.}%
\includegraphics{plot}
\endgroup
```

**Comment by muzimuzhi** [comment]
我仿照 @mohuangrui 提到的 [tex.se 源二](https://tex.stackexchange.com/q/220460/79060) 里的例子（下称原例），使用 texlive2018 版 xetex 做了一些测试。

测试发现：
1. 源二里的问题，已经得到解决。无论是使用西文还是中文字体，原问题都得不到复现。对应的 [xetex ticket](https://sourceforge.net/p/xetex/bugs/105/) 中提到，这是一个 dvipdfmx bug.
1. 使用修改后的原例，能复现PDF内嵌文字错误加粗的问题。
```latex
% !TeX program = xetex

\font\x="[cmunrm.otf]"
\font\bx="[cmunrm.otf]:embolden=5;"

normal image: 
\XeTeXpdffile "fig.pdf"  width 2cm\relax
\XeTeXpdffile "example-image.pdf"  width 2cm\relax
\par

\x Words in image are
{\bx bolded}
\XeTeXpdffile "fig.pdf"  width 2cm\relax
Words right after image are not bolded.

\x Words in image are
{\bx bolded}
\XeTeXpdffile "example-image.pdf"  width 2cm\relax
Words right after image are not bolded.

%\tracingoutput=1
\showboxbreadth=\maxdimen
\showboxdepth=\maxdimen

\bye
```
![image](https://user-images.githubusercontent.com/6376638/40037096-ec4176fe-583d-11e8-931f-66e8860abcab.png)

关于测试结果的说明
1. 使用到的图片，fig.pdf 是题主提供的，example-image.pdf 是宏包 mwe 提供的。
1. 使用 poppler 提供的 pdffonts 命令可以看到，两张图片都嵌入了子集化的字体。
1. 两张图片内的文字，都被「加粗」了，而加粗的方式又有差异：
   1. fig,pdf，只要设置了伪粗参数，就得到程度很高的加粗；伪粗参数变大，加粗程度也变大
   1. example-image.pdf，伪粗参数的大小不影响其加粗的程度，且总是只得到程度较低的加粗

另，目前已能确定这个问题是底层（xetex 或 dvipdfmx）导致的，与项目 ctex-kit 无关。

**Comment by zepinglee** [comment]
@mohuangrui @muzimuzhi 感谢指导！
