### ISSUE TITLE
beamer + ctex 宏包用 CJK 方式的支持

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#37]
Original [issue 38](https://code.google.com/p/ctex-kit/issues/detail?id=38) created by LeoLiu.PKU on 2010-11-03T18:09:45.000Z:

不加 CJK 选项可以使用汉字。但 GBK 编码不能在导言区使用汉字。
测试代码：
% !TeX encoding = System
\documentclass{beamer}
\usepackage[GBK,noindent]{ctex}
\ifxetex
\XeTeXinputencoding &quot;GBK&quot;
\fi
\title{测试}
\author{某某}
\begin{document}
\begin{frame}
\titlepage
\end{frame}
\begin{frame}{测试}
测试测试测试
\end{frame}
\end{document}
xelatex 编译无误，pdflatex 会报错。把 \title 等移支 document 环境内可解决。

另外，CJK 方式下，ctex 使用 \begin{CJK*}{GBK/UTF8}{rm} 设置初始字体。但 beamer 中一般默认使用无衬线体，对应于黑体或圆体。或许 ctex 宏包也应该增加一个选项，默认使用 sffamily？

**Comment by leo-liu** [comment]
@qinglee 
目前 `ctex` 包第 2 版的设置是在较早的位置使用 `\CJK@makeActive` 设置 128 以后字节的 catcode，而直到导言区末尾才载入 `\CJK@envStart` 以支持完整的 `CJK` 包功能。

看了一下 `CJK` 包并做了测试，只需要在 `\CJK@makeActive` 之外再加上 `\CJK@@enc`，即可保证 `beamer` 的运行无误。

`\CJK@@enc` 的定义在 `CJK.enc` 中，是
```latex
% dummy encoding for MULE.

\def\CJK@@enc{\CJK@loadBinding{standard}}
```
其主要效果是读入 `standard.bdg` 文件。而 `standard.bdg` 文件会对 `^^81` 到 `^^fe` 的字符进行赋值，使之具有输出汉字的功能。

大部分宏包不会对 128 以后的字节进行重定义，即使重定义也会与中文冲突。由于中文文档的主体是汉字，提早调用 `\CJK@@enc` 对这些字节进行定义应该问题不大。

现拟在原来的 `\CJK@makeActive` 后增加 `\CJK@@enc`，以解决这个 bug。

**Comment by leo-liu** [comment]
http://bbs.ctex.org/forum.php?mod=redirect&goto=findpost&ptid=79955&pid=466415&fromuid=102734

目前的补丁对 GBK 正常了，对 UTF8 编码又出错了。再看……

**Comment by qinglee** [comment]
例子可以精简为
```TeX
% !TeX program  = pdfLaTeX
% !TeX encoding = UTF-8

\documentclass[UTF8]{ctexart}
\usepackage{hyperref}

%\makeatletter
%\CJK@loadBinding{UTF8}
%\makeatother

\hypersetup{pdftitle={贺}}

\begin{document}

测试

\end{document}
```

原因是对汉字首字节的定义不对，UTF8 编码应该用 `UTF8.bdg` 而不是 `\CJK@@enc` 引入的 `standard.bdg`。

**Comment by qinglee** [comment]
呃，才发现 UTF8 编码时可以不用提前引入 CJK 包的 `UTF8.bdg`。

UTF8 编码时，汉字的首字节已经被 `inputenc` 宏包设置为活动字符，并被 `utf8.def` 初始化为 `\UTFviii@three@octets` 之类的东西。`hyperref` 可以处理这种定义的宏。

**Comment by lnsongxf** [comment]
\usefonttheme{serif}              % 使用衬线
\usefonttheme{professionalfonts}  % 数学公式字体

%%下面的组合可以修改中文字体
\usepackage{ctex}
%\usepackage{xeCJK} %经测试使用ctex和xeCJK包都是可以都
% 设置英文默认字体
\setmainfont{Times New Roman} 
% 设置中文默认字体
\setCJKmainfont[BoldFont=楷体-简 粗体]{楷体-简}
%%

不需要 \begin{CJK*}{GBK/UTF8}{rm} 之类其他的关于汉字的设定

这个在TeXlive（MacTeX）+TeXstudio的环境下运行良好

**Comment by Liam0205** [comment]
@lnsongxf 您好。

该 issue 已经十分久远，所讨论的问题在当下已经不成为问题，CJK 也已是早就过时的东西。

经检查，您引用的文章，以及您在回复当中使用的方案，都不是我们推荐的方案。我们推荐直接使用 ``\documentclass{ctexbeamer}`` 来使用中文 ``beamer``

感谢关注。
