### ISSUE TITLE
\bfseries \songti 用 XeLaTeX 编译无法加粗

### ISSUE THREAD

**Issue by DXie123** [CTeX-org/ctex-kit#371]
好像\bfseries只能对默认字体加粗，改成其他字体就没法加粗了
我的测试代码如下
```
\documentclass{ctexart}

\begin{document}

\songti 测试
\bfseries
\songti 测试

\end{document} 
```

**Comment by Liam0205** [comment]
这取决于 `\songti` 在当前 `fontset` 下的定义。如果当前 `fontset` 下，`\songti` 对应的 font family 没有配置 `BoldFont` 并且字体本身没有 Bold 字重，再而且也没有配置 `FakeBold`，那么 `\bfseries` 就不会真的加粗，看起来就没有效果。

目前 `windows*` 就没有配置。这是因为中易宋体没有 Bold 字重，而通常 `\rmfamily` 下的宋体的粗体用黑体来替代。对于 `\songti` 来说，如果用黑体来替代，就破坏了 `\songti` 这个命令的语义了。所以就没有配置。你遇到的问题，当属此类。

另外注意，你在用 LaTeX，而不是 Word。一般情况下，不要用 `\songti`/`\heiti`/`\fangsong` 这些命令，而是使用与西文相同逻辑的 `\rmfamily`/`\sffamily`/`\ttfamily` 字族选择命令来切换字族（而不是 Word 逻辑的切换字体）。
