### ISSUE TITLE
覆盖Path的Bug给我带来了无法估量的损失

### ISSUE THREAD

**Issue by hujiaodigua** [CTeX-org/ctex-kit#376]
覆盖Path的Bug给我带来了无法估量的损失。由于学院每天晚上断点，我的Path也无法找回，CTex覆盖Path的Bug给我带来了无法估量的损失，这个Bug大约4年前就存在了，解决不了问题就不要做开源

**Comment by zepinglee** [comment]
1. 这里是 ctex-kit 不是 CTeX 套装

**Comment by Stone-Zeng** [comment]
相关问题见 https://github.com/CTeX-DEV/CTeX/issues/19 。

根据[《CTeX 中文 TeX 套装》版权说明](https://github.com/CTeX-DEV/CTeX/blob/master/texts/license_zh.txt)：

> 1. 本套装软件只用于科研与学术目的，不得以任何理由用于商业目的。
> 2. 本套装软件中包含的所有免费、共享软件的版权均属于其原作者。
> 3. 本套装软件的安装程序的版权属于 CTEX。
> 4. **CTEX 不承担由于使用本软件造成的所有后果。**

**Comment by hujiaodigua** [comment]
感谢开发者的回答真是让人受益匪浅
