### ISSUE TITLE
zhlineskip: 改进选项名称

### ISSUE THREAD

**Issue by Man-Ting-Fang** [CTeX-org/ctex-kit#383]
目前（2018-10-15）的 zhlineskip 有如下两个选项：
`UseMicrosoftWordMultipleLineSpacingWithSimSunHeiKaiFangFonts`
`MSLineSpacingMultiple`
但是前者的名字实在是太长了……个人感觉可以去掉其中非必要的部分，并适当缩写。再考虑到与后者之间的一致性，对 MS Word 的称呼也以一致为好。因此，个人建议趁尚未向 CTAN 发布时，分别修改如下（因为 Windows 自带的字体中有以“sim”开头的非中文的字体，所以这里使用 `ZhSimFonts`）：
`UseMSWordMultipleLineSpacingWithZhSimFonts`
`MSWordLineSpacingMultiple`

**Comment by RuixiZhang42** [comment]
@Man-Ting-Fang 

> 但是前者的名字实在是太长了……个人感觉可以去掉其中非必要的部分，并适当缩写。

选项 `UseMicrosoftWordMultipleLineSpacingWithSimSunHeiKaiFangFonts` 之所以这么长，其实是有意为之。用户手册里解释了 MS Word 计算单倍行距的方法依赖于字体，并列举了几种常见字体对应的单倍行距倍数。其中，单倍行距倍数 `332/256` 仅适用于中易宋体、中易黑体、中易楷体与中易仿宋，在这个方面觉得缩写 `SimSun`、`SimHei`、`SimKai` 与 `SimFang` 为 `SimSunHeiKaiFangFonts` 更加合适，重在强调此单倍行距值只适用于上述四种字体。

> 再考虑到与后者之间的一致性，对 MS Word 的称呼也以一致为好。

在这一点上，考虑的确欠妥，统一为 `MSWord` 不错。

**Comment by Man-Ting-Fang** [comment]
> 选项 UseMicrosoftWordMultipleLineSpacingWithSimSunHeiKaiFangFonts 之所以这么长，其实是有意为之。用户手册里解释了 MS Word 计算单倍行距的方法依赖于字体，并列举了几种常见字体对应的单倍行距倍数。其中，单倍行距倍数 332/256 仅适用于中易宋体、中易黑体、中易楷体与中易仿宋，在这个方面觉得缩写 SimSun、SimHei、SimKai 与 SimFang 为 SimSunHeiKaiFangFonts 更加合适，重在强调此单倍行距值只适用于上述四种字体。

呃，我个人的想法是，这个在文档中解释清楚并强调即可，似乎不必一定要在名字里写全。而且，具体问题具体分析，中易系列字体的制作者为[北京中易中标公司](http://www.china-e.com.cn/main/index.htm)，跟方正、汉仪等产品丰富的字体大厂不同，中易除宋、黑、仿、楷外，大家通常能见到的似乎也就只有中易隶书和中易幼圆了，而且提起中易字体，一般指的也就是这几个，所以对于中易字体而言，我个人觉得 `ZhSimFonts` 可以认为是几乎没什么歧义、也足够特指了，在文档中强调一下即可。当然，我没验证，如果中易的隶书和／或幼圆跟中易的宋、黑、仿、楷参数不一样或相差太大的话，`ZhSimFonts` 确实就不太合适了；但即使这样，名称似乎也可以再斟酌一下，看看有没有稍微短一些的表达方式……
当然，这只是我的个人想法，仅供参考。

**Comment by RuixiZhang42** [comment]
@Man-Ting-Fang 决定将字体名称从键值选项名中移除，移除之后需要为 MS Word 单倍行距相比字号的倍数新增一个键值，这样的话，用户就可以自行查找相关字体的参数，再自行修改单倍行距的倍数。

原本的两个键值选项现在扩充为三个：

 - `UseMSWordMultipleLineSpacing`
 - `MSWordLineSpacingMultiple`
 - `MSWordSinglespaceRatio`

**Comment by RuixiZhang42** [comment]
Reference: https://github.com/CTeX-org/ctex-kit/commit/a9f16ccc3a12243f763f89ac9032b35293968139
