### ISSUE TITLE
l3kernel 更新后在 ctexart 里不能使用 unicode-math

### ISSUE THREAD

**Issue by RuixiZhang42** [CTeX-org/ctex-kit#384]
`l3kernel` 于 2018&nbsp;年 10&nbsp;月 17&nbsp;日更新，次日上传至 CTAN。更新之后在 CTeX 各文档类中一旦使用 `unicode-math` 就报错，并且不能生成 PDF。

    % !TeX program = XeLaTeX
    % l3kernel update, 2018-10-17:
    % https://ctan.org/ctan-ann/id/mailman.549.1539893624.4481.ctan-ann@ctan.org
    \documentclass{ctexart}
    \usepackage{unicode-math}
    \begin{document}
    $e^{i\pi} = -1$
    \end{document}

相关错误信息：

    ...
    ("C:\Program Files\MiKTeX 2.9\tex\latex\ctex\ctex-c5size.clo")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\ctex\fontset\ctex-fontset-windows.def"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\ctex\fontset\ctex-fontset-windowsnew.de
    f"))) ("C:\Program Files\MiKTeX 2.9\tex\latex\ctex\config\ctex.cfg")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\unicode-math\unicode-math.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\unicode-math\unicode-math-xetex.sty"
    ("C:\Program Files\MiKTeX 2.9\tex\latex\filehook\filehook.sty")
    ("C:\Program Files\MiKTeX 2.9\tex\latex\unicode-math\unicode-math-table.tex")))
    (test-ctex-unicode-math.aux) ABD: EverySelectfont initializing macros)
    Runaway argument?
    76543210\q_stop newline - 'bold' (bx/n) with NFSS spec.: <->s*[0.9999\ETC.
    ! File ended while scanning use of \__iow_wrap_end_chunk:w.
    <inserted text> 
                    \par 
    <*> ./test-ctex-unicode-math.tex
                                    
    ?

**Comment by Stone-Zeng** [comment]
见 <https://github.com/latex3/latex3/issues/491>

**Comment by RuixiZhang42** [comment]
@Stone-Zeng 只测试了 `ctexart` 等文档类与 `article` 等文档类，英文文档类没有出现 `unicode-math` 的问题，中文文档类出现了，所以以为是 CTeX 的 issue。现在看起来，英文文档类也会出问题，应该就只是 `l3kernel` 更新造成的吧。

**Comment by RuixiZhang42** [comment]
是 `l3kernel` 的命令 `\iow_wrap:nnnN` 处理宏展开出了问题，CTeX 并无 bug。参见 https://github.com/latex3/latex3/commit/eff60934d64012c6a12a2c7233b7978f7f17fed0。
