### ISSUE TITLE
ctex: “方正细黑一_GBK”的字体名称问题

### ISSUE THREAD

**Issue by AlexaraWu** [CTeX-org/ctex-kit#385]
在 macOS 下使用方正字库时提示找不到“方正细黑一_GBK”字体：

```console
Package fontspec Error: The font "方正细黑一_GBK" cannot be found.
```
 
我查看了一下文档，发现了下面这一段：

> 在 WPS For Linux 附带的 5.00 版和家庭版 5.20 版的“方正细黑一_GBK”的字体名称是 FZXiHeiI-Z08。但在网上发现不少文档和资料都是 FZXiHei␣I-Z08，而在官方资料《2013 方正字库字体样张》中对应的英文名字是 FZXiHei␣I。可以用 Postscript 名字 FZXH1K--GBK1-0 来统一。经测试时发现(WPS 中的字体)，XeTeX 找该字体时会出现明显的延迟，而用字体文件名 FZXH1K.TTF 又可能会出现大小写问题，遂采用汉字名称。由于 luaotfload 不支持汉字 名称，故使用 Postscript 名字，速度不受影响。

我使用字体是[方正字库官网](http://www.foundertype.com/)下载的最新 5.30 版，我又找来 5.00 版和 5.20 版的字体文件比较了一下，发现字体名称都是 `FZXiHeiI-Z08`。而我在[字客网](https://www.fontke.com/)上查询到的 [1.0 版](https://www.fontke.com/font/10277156/detail/)、[1.10 版](https://www.fontke.com/font/10032543/detail/)和 [3.00 版](https://www.fontke.com/font/10281025/detail/)的字体名称则是 `FZXiHei␣I-Z08`。所以我推测`FZXiHei␣I-Z08` 是旧版的名称，`FZXiHeiI-Z08` 是新版的名称。鉴于旧版的字体文件已经很难见到，这里不如简单一点直接使用 `FZXiHeiI-Z08` 作为字体名称？

**Comment by Liam0205** [comment]
周末验证无误后，考虑更新。
