### ISSUE TITLE
ctexart页面宽度不到1/2

### ISSUE THREAD

**Issue by mgcyung** [CTeX-org/ctex-kit#386]
test-2.tex内容如下
```
  \documentclass[UTF8]{ctexart}

  \begin{document}

  \title{Latex与Winedt}
  \author{jingwhale}
  \date{January 25, 2015}
  \maketitle

  \begin{abstract}
  LATEX（英语发音：/ˈleɪtɛk/ LAY-tek或英语发音：/ˈlɑːtɛk/ LAH-tek，音译“拉泰赫”），是一种基于TEX的排版系统，由美国电脑学家莱斯利•兰伯特在20世纪80年代初期开发，利用这种格式，即使用户没有排版和程序设计的知识也可以充分发挥由TEX所提供的强大功能。对于生成复杂表格和数学公式，这一点表现得尤为突出。因此它非常适用于生成高印刷质量的科技和数学类文档。这个系统同样适用于生成从简单的邮件到完整书籍的所有其他种类的文档。
  \end{abstract}

  \end{document}
```
得到的[test-2.pdf](https://github.com/CTeX-org/ctex-kit/files/2538886/test-2.pdf)文件中文字占据的宽度约只有页面的1/2。这是什么原因呢？

xelatex命令的输出如下
```
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test-2.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.10> and hyphenation patterns for 9 language(s) loaded.
(/usr/share/texmf-dist/tex/latex/ctex/ctexart.cls
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
Document Class: ctexart 2017/04/01 v2.4.9 Chinese adapter for class article (CT
EX)
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/share/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(/usr/share/texmf-dist/tex/latex/ctex/ctexhook.sty)
(/usr/share/texmf-dist/tex/latex/ctex/ctexpatch.sty)
(/usr/share/texmf-dist/tex/latex/base/fix-cm.sty
(/usr/share/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texmf-dist/tex/latex/ms/everysel.sty)
(/usr/share/texmf-dist/tex/latex/ctex/config/ctexopts.cfg)
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def
(/usr/share/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(/usr/share/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texmf-dist/tex/latex/base/tuenc.def))
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/share/texmf-dist/tex/xelatex/xecjk/xunicode-addon.sty
(/usr/share/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(/usr/share/texmf-dist/tex/latex/tipa/t3enc.def)
(/usr/share/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texmf-dist/tex/latex/graphics-def/xetex.def)))))
(/usr/share/texmf-dist/tex/xelatex/xunicode/xunicode.sty
*** Reloading Xunicode for encoding 'TU' ***
) (/usr/share/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def)
(/usr/share/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
(/usr/share/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty
(/usr/share/texmf-dist/tex/generic/ulem/ulem.sty)
(/usr/share/texmf-dist/tex/latex/environ/environ.sty
(/usr/share/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(/usr/share/texmf-site/tex/latex/cjk-latex/CJKfntef.sty)))
(/usr/share/texmf-dist/tex/latex/zhnumber/zhnumber.sty
(/usr/share/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg))
(/usr/share/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-chinese-article.def
(/usr/share/texmf-dist/tex/latex/ctex/config/ctex-name-utf8.cfg))
(/usr/share/texmf-dist/tex/latex/ctex/ctex-c5size.clo)
(/usr/share/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-fandol.def
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'FandolSong-Regular' does not contain script 'CJK'.
*************************************************
)) (/usr/share/texmf-dist/tex/latex/ctex/config/ctex.cfg) (./test-2.aux)
(/usr/share/texmf-dist/tex/latex/tipa/t3cmr.fd)
ABD: EverySelectfont initializing macros [1] (./test-2.aux) )
(see the transcript file for additional information)
Output written on test-2.pdf (1 page).
Transcript written on test-2.log.
```
附[test-2.log](https://github.com/CTeX-org/ctex-kit/files/2538887/test-2.log)

**Comment by mgcyung** [comment]
去掉"abstract"后test-4.tex内容如下

``` tex
\documentclass[UTF8]{ctexart}

\begin{document}

\title{Latex与Winedt}
\author{jingwhale}
\date{January 25, 2015}
\maketitle

LATEX（英语发音：/ˈleɪtɛk/ LAY-tek或英语发音：/ˈlɑːtɛk/ LAH-tek，音译“拉泰赫”），是一种基于TEX的排版系统，由美国电脑学家莱斯利•兰伯特在20世纪80年代初期开发，利用这种格式，即使用户没有排版和程序设计的知识也可以充分发挥由TEX所提供的强大功能。对于生成复杂表格和数学公式，这一点表现得尤为突出。因此它非常适用于生成高印刷质量的科技和数学类文档。这个系统同样适用于生成从简单的邮件到完整书籍的所有其他种类的文档。

\end{document}
```
但[test-4.pdf](https://github.com/CTeX-org/ctex-kit/files/2539276/test-4.pdf)中文字占据的宽度仍约只有页面的1/2

附[test-4.log](https://github.com/CTeX-org/ctex-kit/files/2539280/test-4.log)

**Comment by Stone-Zeng** [comment]
LaTeX 的默认值是：`\textwidth`=390pt`，\paperwidth=597pt`，的确是偏宽松的。需要修改的话，可以通过 `geometry` 宏包进行。

**Comment by mgcyung** [comment]
> LaTeX 的默认值是：`\textwidth`=390pt，`\paperwidth`=597pt，的确是偏宽松的。需要修改的话，可以通过 `geometry` 宏包进行。

LaTeX的`\textwidth`与`\paperwidth`之比约0.653，[test-4.pdf](https://github.com/CTeX-org/ctex-kit/files/2539276/test-4.pdf)中文字区域宽度与页面宽度之比约0.567，比默认值少了约10%，这是为何呢? 另外有`geometry` 宏包示例代码吗?

**Comment by Harry-Chen** [comment]
可以查看 geometry 获得使用帮助。一个简单的示例是：

```
\usepackage{geometry}
\geometry{
	a4paper,
	left=3.18cm,
	right=3.18cm,
	top=2.54cm,
	bottom=2.54cm
}
```

（这是 Word 默认的页边距）

**Comment by Stone-Zeng** [comment]
我讲错了，默认 `\paperwidth` 是 8.5in，也就是 614.295pt。

**Comment by Liam0205** [comment]
如前述，1. 正常现象，2. 与 `ctex` 无关，3. 可通过 `geometry` 修改。

close.

**Comment by RuixiZhang42** [comment]
@Harry-Chen MS Word 这个默认的页边距其实非常的不文不类。真相是 1&nbsp;英寸的天头、地脚，1.25&nbsp;英寸的订口、切口，换算成厘米正好显示为 2.54&#8239;cm 与 3.18&#8239;cm（注意，是可以输入多于两位小数的数值的）。这个页边距显然是从 Letter 纸张尺寸（8.5&#8239;in×11&#8239;in）继承过来的，如果是欧洲那边的 A4 纸张倒也无所谓，但是中文文档的话就不太合适。这是因为要注意[《从「行长为字号的整数倍」说起》](https://thetype.com/2017/07/12513/)。

@mgcyung 高年级的教科书一般建议用五号字，每行大约 32 个字（参见这个知乎问答[《中文排版时，每行文字最优的个数是多少？》](https://www.zhihu.com/question/19621078)）。标准文档类 `article` 也是根据每行大约 66 个字母设计的，所以你的 `test-4.pdf` 差不多就是每行 32 个字。当然了，更好的版心宽度设置可以是 `\geometry{width=336bp}`，保证每行正好 32 个五号字。

**Comment by zepinglee** [comment]
@RuixiZhang42 说到[《从「行长为字号的整数倍」说起》](https://thetype.com/2017/07/12513/)，我试了一下 xeCJK 的处理：
```
\documentclass[UTF8]{ctexart}
\begin{document}
\fontsize{12bp}{22bp}\selectfont
\fboxrule=0.1pt
\fboxsep=-\fboxrule
\newcommand\text{%
  字体排印不是艺术，字体排印也不是科学。字体排印是一项工艺。
  这项工艺不是对那些规则一知半解地盲从，而是要凭借尝试和验证过的
  经验进行精密地运用。}
\fbox{\parbox{180bp}{\text}}\par
\fbox{\parbox{65.5mm}{\text}}\par
\fbox{\parbox{66mm}{\text}}\par
\end{document}
```
![screen shot 2018-11-03 at 10 45 38 am](https://user-images.githubusercontent.com/12290822/47947337-a0ee8300-df55-11e8-98f7-be907c0a7e63.png)

末行也是齐左的。这是 TeX 的限制？

**Comment by RuixiZhang42** [comment]
@zepinglee 正常的“两端对齐”算法都应该是“最后一行左对齐”（阿拉伯文的话是“最后一行右对齐”），这一点《从「行长为字号的整数倍」说起》文中已经描述得比较清楚了。在你给的第二例中，前四行之所以能被拉开，是因为 `xeCJK` 插入的 `\CJKglue` 的缘故；而在第三例中，前三行优先考虑标点压缩，只有第四行是被拉开的。不过，不管怎样，都存在最后一行错位的问题。

据我所知，TeX 应该是不支持“网格”的。如果真的想要“疏排”，用 CTeX 宏集的 `\ziju` 命令做出来的效果不甚理想。此时，可以考虑用 `xeCJK` 修改 `\CJKglue` 的值。但这仍然有问题，原因出在标点符号。因为标点符号要参与禁则、压缩等复杂的处理，所以很难真正实现网格对齐，除非你敢把标点符号归为 CJK 类别。

    % !TeX program = XeLaTeX
    \documentclass{ctexart}
    \usepackage{xcolor}
    % Windows：中易字库的中文底线相比于西文基线下沉 36/256 个单位
    \newcommand*\ideographicbaseline{-0.140625}
    % macOS：华文字库的中文底线相比于西文基线下沉 200/1000 个单位
    % Linux：Fandol 字库与华文字库相同
    %\renewcommand*\ideographicbaseline{-0.2}
    % 示例文本来源：https://thetype.com/2017/07/12513/
    \newcommand*\text{%
      \rule[\ideographicbaseline\ccwd]{0pt}{\ccwd}%
      字体排印不是艺术，字体排印也不是科学。字体排印是一项工艺。%
      这项工艺不是对那些规则一知半解地盲从，而是要凭借尝试和验证过的%
      经验进行精密地运用。%
      \rule[\ideographicbaseline\ccwd]{0pt}{\ccwd}%
    }
    \makeatletter
    \newcount\kongquejihua@example
    \newcommand*\drawgrid[1][0mm]{%
      \leavevmode\llap{%
        \color{blue}%
        \kongquejihua@example\@ne
        \loop
          \hskip\ccwd\relax
          \hskip-0.05pt\relax
            \rule[\dimexpr\ideographicbaseline\ccwd-88bp\relax]%
              {0.1pt}{100bp}%
                \hskip-0.05pt\relax
          \hskip#1\relax
          \hskip-0.05pt\relax
            \rule[\dimexpr\ideographicbaseline\ccwd-88bp\relax]%
              {0.1pt}{100bp}%
                \hskip-0.05pt\relax
          \advance\kongquejihua@example\@ne
        \ifnum\kongquejihua@example<15
        \repeat
        \hskip\ccwd\relax
      }%
    }
    \makeatother
    \begin{document}
    \section*{疏排测试}
    \fontsize{12bp}{22bp}\linespread{1}\selectfont
    \fboxrule=0.1pt%
    \fboxsep=-\fboxrule
    不更改全角逗号、全角句号的类别，有明显的错位：\par
    \fbox{%
      \parbox[t]{72.5mm}{%
        % 多出来的 9mm 均匀分配到每行 14 个 \CJKglue
        \xeCJKsetup{
          CJKglue={\hskip0.642857142857mm\relax}
        }%
        \text
      }%
    }%
    \drawgrid[0.642857142857mm]\par
    \bigskip
    更改了全角逗号、全角句号的类别，失去标点禁则、压缩：\par
    \fbox{%
      \parbox[t]{72.5mm}{%
        % 更改全角逗号、全角句号的类别
        \xeCJKDeclareCharClass{CJK}{`，,`。}%
        % 多出来的 9mm 均匀分配到每行 14 个 \CJKglue
        % 由于 TeX 的舍入误差，允许 \CJKglue 在小范围内伸展和收缩
        \xeCJKsetup{
          CJKglue={\hskip0.642857142857mm plus 1pt minus 1pt}
        }%
        \text
        \xeCJKResetCharClass
      }%
    }%
    \drawgrid[0.642857142857mm]
    \end{document}

![ashupai](https://user-images.githubusercontent.com/39968857/47957430-052c3980-df8c-11e8-9c18-636dff5aed1b.png)
