### ISSUE TITLE
xeCJK: 升级 fontspec v2.6j 后无法编译

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#397]
示例：

```latex
\documentclass{article}
\usepackage{xeCJK}
\setCJKmainfont{FandolSong}  % 默认载入 FandolSong
\begin{document}
Hello, world! 你好，世界！
\end{document}
```

报错信息为：

```
Runaway argument?
\int_set:Nn \l_tmpb_int {\XeTeXOTcountfeatures \l_fontspec_font \l__fontspec_script_int \ETC.
! File ended while scanning use of \__fontspec_strip_leading_sign:Nw.
<inserted text>
                \par
<*> 8

? 
```

问题似乎是 Fandol 系列字体没有 Script=CJK 的信息，展开出了点问题（还未仔细排查）。换成 SimSun、Microsoft YaHei 等则可以正常编译。

版本信息：

- xeCJK 2018/04/30 v3.7.1
- fontspec 2019/01/10 v2.6j
- TeX Live 2018, Windows 10 18309

**Comment by zepinglee** [comment]
我也手贱升级了一发【滑稽】

**Comment by zepinglee** [comment]
我试了一下把 `xeCJK` 的 `\defaultCJKfontfeatures { Script = CJK }` 这一行去掉就不报错了。

另外我比较器奇怪的是，SimSun, SimHei, Songti SC, Source Han Serif 等字体的 script 信息都只有 `Simplified Han`，为何 `fontspec` 的 script 却这个选项？

**Comment by zepinglee** [comment]
原来我用了假的 FontBook……
<img width="1134" alt="screen shot 2019-01-10 at 10 31 57 pm" src="https://user-images.githubusercontent.com/12290822/50975064-9937f580-1527-11e9-98ae-2d3dacc52d56.png">

**Comment by muzimuzhi** [comment]
> OpenType 的 Script Tag 只有 `hani` (CJK Ideographic)，Language Tag 才分 `ZHH `/`ZHS `/`ZHT ` (Chinese Hong Kong SAR/Simplified/Traditional)。

 - Script: CJK Ideographic
 - Script Tag: 'hani'
 - Script (Aliased): CJK

ref:
 - [Script Tags](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags) - docs.microsoft.com
 - Table 16 of document of package `fontspec`

**Comment by RuixiZhang42** [comment]
@muzimuzhi OpenType 的 Script Tag 的确只有 `hani`，[微软 docs](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags) 与之对应的 Script 名称为 `CJK Ideographic`。`fontspec` 里面的那个 `Script=CJK` 的写法完全是为了 backwards compatibility。

@Stone-Zeng 跟我之前报告 CTeX 很多文档编译不通过很类似，这似乎不是 `xeCJK` 的问题。我那次是 LaTeX3 kernel 的问题，这次是 `fontspec` 的问题：

    % !TeX program = XeLaTeX
    \documentclass{article}
    \usepackage{fontspec}
    \setmainfont{FandolSong}[Script=CJK]
    \begin{document}
    Hello, world! 你好，世界！
    \end{document}

同样编译失败：

    Package fontspec Warning: Font 'FandolSong' does not contain script 'CJK'.
    
    )
    Runaway argument?
    \int_set:Nn \l_tmpb_int {\XeTeXOTcountfeatures \l_fontspec_font \l__fontspec_sc
    ript_int \ETC.
    ! File ended while scanning use of \__fontspec_strip_leading_sign:Nw.
    <inserted text> 
                    \par

**Comment by Stone-Zeng** [comment]
wspr 终于在 `fontspec` v2.6l 里面把这个修好了……

**Comment by zepinglee** [comment]
赞！

**Comment by RuixiZhang42** [comment]
之前的 `v2.6l` 修好了 Fandol，但是修崩了别的西文字体，也修崩了数学字体。几个小时前发布的 `v2.7` 终于真正修好了！

**Comment by RuixiZhang42** [comment]
`v2.7` 好像又修崩了……

**Comment by RuixiZhang42** [comment]
`fontspec v2.7a` 已经上线（MiKTeX）至少三天了，终于可以放心关 issue 了。
