### ISSUE TITLE
xunicode-addon: 带圈数字有关问题

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#399]
使用带圈数字时遇到了一些问题，想请教一下。

```latex
\documentclass{ctexart}
\usepackage{xunicode-addon}

\ExplSyntaxOn
\cs_new:Npn \TEST #1#2
  {
    \int_step_inline:nnn {#1} {#2}
      { \textcircled {##1} ~ }
  }
\ExplSyntaxOff

%% ==== 1
\setmainfont{Source Han Serif SC}
%% ==== 2
% \setCJKmainfont{Source Han Serif SC}
%% ==== 3
% \setmainfont{Times New Roman}
% \setCJKmainfont{Source Han Serif SC}
%% ==== 4
% \setmainfont{XITS}
% \setCJKmainfont{Source Han Serif SC}

\begin{document}
\TEST{0}{50}
\end{document}
```

现在有这么几种情况（使用 XeLaTeX 编译）：

1. 设置**西文**字体为思源宋体，则只有 0&ndash;20 的部分，21&ndash;50 为空白：

![image](https://user-images.githubusercontent.com/18233088/51603251-393c4880-1f44-11e9-8212-b500582b605d.png)

增加 `\xeCJKDeclareCharClass{Default}{"3200 -> "32FF}` 之后，21&ndash;50 也能够正常显示。

2. 设置**中文**字体为思源宋体，所有全部为 Latin Modern 拼合的带圈数字：

![image](https://user-images.githubusercontent.com/18233088/51603276-540ebd00-1f44-11e9-9ff7-2fc2f802644e.png)

3. 设置中西文字体分别为思源宋体、思源黑体，显示正常：

![image](https://user-images.githubusercontent.com/18233088/51603403-ab149200-1f44-11e9-94de-b7b68bb09a86.png)

4. 设置中西文字体分别为思源宋体和 XITS（只包含带圈的 0&ndash;10），则 0&ndash;10 部分正常，而后面却是用 XITS 拼合：

![image](https://user-images.githubusercontent.com/18233088/51603492-edd66a00-1f44-11e9-8d85-66e9a98efe56.png)

所以看起来所用的西文字体会影响最终的结果（即使 21&ndash;50 按照设置本应该用中文字体）。

用 LuaLaTeX 测试，情况 1 中 0&ndash;50 都能正常显示而无需其他设置；其他与 XeLaTeX 类似（由于某些未知原因 LuaLaTeX 不能使用思源，用了 IPAexGothic/IPAexMincho 代替，但它没有带圈的 0）。

最后，考虑到带圈数字实际上比较常用，是否可以考虑在 ctex 宏集中定义一个单独的命令？

**Comment by muzimuzhi** [comment]
> 考虑到带圈数字实际上比较常用

请问一般什么时候需要用到带圈数字，尤其是 21--50 的？

**Comment by muzimuzhi** [comment]
> 唔，国内脚注尾注都多用带圈数字，你看看带注释的古诗文，就会知道50不多。

了解了，谢谢。

**Comment by stone-zeng** [comment]
请教一下，那怎样可以把带圈数字全部设为用中文字体显示？

这个例子中，已经把带圈数字换成了 CJK 字符类，但仍全部为拼合：

```latex
\documentclass[scheme=plain]{ctexart}
\usepackage{xunicode-addon}
\xeCJKDeclareCharClass{CJK}{"24EA, "2460->"2473, "3251->"32BF}
\setCJKmainfont{Source Han Serif SC}
\ExplSyntaxOn
\cs_set:Npn \TEST
  { \int_step_inline:nnn {0} {50} { \textcircled{##1} ~ } }
\ExplSyntaxOff

\begin{document}
\TEST
\end{document}
```

**Comment by qinglee** [comment]
`\textcircled` 只在西文字体检查符号是否存在，可以把全体带圈数字都设置成 Default 类，然后对它们使用中文字体。

```
\documentclass[scheme=plain]{ctexart}
\usepackage{xunicode-addon}

\xeCJKDeclareCharClass{Default}{"24EA, "2460->"2473, "3251->"32BF}
\newfontfamily\hanserif{Source Han Serif SC}

\makeatletter
\ExplSyntaxOn

\prg_new_conditional:Npnn \@@_if_integer:n #1 { T }
  {
    \exp_after:wN \@@_if_integer_aux:w
      \if_int_compare:w 10 < 9 \tl_to_str:n {#1} \exp_stop_f:
        \q_mark \prg_return_true:
      \else:
        \q_mark \prg_return_false:
      \fi:
  }
\cs_new:Npn \@@_if_integer_aux:w #1 \q_mark
  {
    \tl_if_empty:nF {#1}
      { \use_i:nn \prg_return_false: }
  }

\AtBeginUTFCommand [ \textcircled ]
  {
    \group_begin:
      \@@_if_integer:nT {#1} { \hanserif }
  }
\AtEndUTFCommand [ \textcircled ]
  { \group_end: }

\cs_set:Npn \TEST
  { \int_step_inline:nnn { 0 } { 200 } { \textcircled { ##1 } ~ } }

\ExplSyntaxOff
\makeatother

\begin{document}

\TEST

\textcircled {A}

\end{document}
```

![00](https://user-images.githubusercontent.com/1782251/54822986-5d689b80-4ce1-11e9-9928-d9d8097a7d94.png)
