### ISSUE TITLE
xeCJK: listings 环境开启 breaklines=true 后复制出现空格

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#400]
考虑如下示例：

```latex
\documentclass{article}
\usepackage{xeCJK,listings}

\begin{document}
\begin{lstlisting}
1 中文测试
\end{lstlisting}
\begin{lstlisting}[breaklines=true]
2 中文测试
\end{lstlisting}
\end{document}
```

XeLaTeX 编译，从 PDF 复制后得到

```
1 中文测试
2 中 文 测 试
```

注意 2 中汉字间有多余的空格，是否有办法除去？

有关宏包版本：

- `xeCJK` v3.7.1
- `listings` v1.7
- `fontspec` v2.6l （还没有同步到最新）

**Comment by Liam0205** [comment]
@stone-zeng 恭喜，400 issues 达成！

**Comment by muzimuzhi** [comment]
无法复现你的问题。mwe 中没有配置中文字体，我使用了 `ctexart` 文档类。

 * 我本地使用 `fontspec` v2.6h
 * 其他的宏包，版本与你的相同
 * PDF 使用 Acrobat Reader for Mac 打开

**Comment by muzimuzhi** [comment]
更新到 `fontspec` v2.7a 后，仍然无法复现

**Comment by stone-zeng** [comment]
忘记说阅读器的事了……

我用的是 Sumatra，会有这个问题；Adobe Acrobat 正常；系统是 Windows 10。

反正涉及 PDF 就很难弄了。

**Comment by clerkma** [comment]
测试文件[test-space.pdf](https://github.com/CTeX-org/ctex-kit/files/2799248/test-space.pdf)。
sumatra阅读器里面的pdf库，用的是mupdf。版本上，是修改过的1.6版本。
先说结论，如果sumatra现在用的是mupdf 1.14的话，那么输出将会是都带空格。
**实际上，这两个版本的mupdf输出都不对。**
第一段文字对应的pdf源码是：`[<11cf>-159<0ed3>-160<04a9>-161<0d6b>]TJ`。
第二段文字对应的pdf源码是：`[<11cf>-200<0ed3>-200<04a9>-200<0d6b>]TJ`。
在1.6版本中，可以使用`mudraw -t test-space.pdf`得到输出：
```
1中文测试

2 中 文 测 试

1


```
在1.14版本中，可以使用`mutool draw -F txt test-space.pdf`得到输出：
```
1
中 文 测 试

2 中 文 测 试

1


```
所以，sumatra调用mupdf的接口，得到的结果中包含的错误也是因为mupdf。
实际上，1.16版本的实现的比较对劲，但是还有毛病，所以不是全对。

pdf里面的文字，复制出来应该是什么样的，在pdf的文档里面其实没说（包括pdf 2.0的iso标准）。所以，这东西在不同的阅读器下面注定是不一样的。不过，pdf标准里面比较推荐的做法是使用ActualText，但是，这东西其实不是特别适合TeX，在word或html环境下倒是比较好事。

所以，这不是xeCJK的毛病啦。
