### ISSUE TITLE
ctexart 文档类 part 标题设置 indent 失效问题

### ISSUE THREAD

**Issue by jiaopjie** [CTeX-org/ctex-kit#401]
我在用 `ctexart` 文档类给 `part` 标题设置 `indent` 格式时碰到了点问题. 代码如下
```
\documentclass[zihao=-4]{ctexart}
\ctexset{
  part={
    name={$|$,},
    indent=8em,
    format=\zihao{-4},
    afterskip=0em,
  },
}
\begin{document}
\part{一二三四五六七八九十}
\noindent 一二三四五六七八九十
\end{document}
```
用 XeLaTeX 编译的. 

![20190127110720](https://user-images.githubusercontent.com/9783188/51795783-2ebfce80-2224-11e9-8c63-2c8eeed3a7d5.png)

标题的缩进看起来并没有 `8em`.

1. 如果对 `section` 做同样的事情, 缩进是正确的.

2. 如果把 `format=\zihao{-4}` 改成 `\fontsize{12bp}{14.4bp}\selectfont` 问题是一样的, 但奇怪的是, 如果删掉 `\selectfont` 只保留 `\fontsize{12bp}{14.4bp}` 结果变正确了.

所以, 我觉得这个问题有点奇怪.

**Comment by Liam0205** [comment]
@jiaopjie

**Comment by jiaopjie** [comment]
@Liam0205 
看到你这个表了, 不过红色箭头指的这个应该是 `book` 文档类吧. 表格里面第一行有个 `part (article)`, 在 `article` 文档类里 `indent` 应该对 `part` 是有效的.

我上面的例子里对 `part/format` 设置为 `\fontsize{12bp}{14.4bp}` 时, `part/indent=8em` 是有效的, 并且是正确的. 但对 `part/format` 设置为 `\fontsize{12bp}{14.4bp}\selectfont` 或者 `\zihao{-4}` 时, `part/indent=8em` 貌似是失效的. 结果是我贴的图片里面的样子. 所以, 我觉得这里有点奇怪.

**Comment by muzimuzhi** [comment]
看了源码 `ctex.dtx`，在 `indent` 的使用上，

 - part 和 chapter 中，`indent` 的值是（通过 `\CTEX@XXX@indent`）赋值给 `\parindent` 后，以「首行缩进」的形式参与排版的，例如
https://github.com/CTeX-org/ctex-kit/blob/e8747633e89d7080e45b876e6f25cabdbc078b2a/ctex/ctex.dtx#L7297
 - section 及以下层级的章节命令中，`indent` 的值是直接使用，以「左侧缩进」的形式参与排版的，例如这里的 `#3`
https://github.com/CTeX-org/ctex-kit/blob/e8747633e89d7080e45b876e6f25cabdbc078b2a/ctex/ctex.dtx#L7611

你的问题可以简化为，在使用 `ctex` 宏包/文档类时，更改字号的操作会把 `\parindent` 更新为默认的 `2em`。具体原因我目前也不知道。下面的例子可以复现

```latex
\documentclass{ctexart}

\begin{document}
\the\parindent, expected: 20pt\par
\parindent=30pt
\the\parindent, expected: 30pt\par
\fontsize{20}{20}\selectfont
\the\parindent, expected: 30pt\par
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/51801644-889fb300-227b-11e9-8f74-97b3af65a42e.png)

仅使用 `article + xeCJK` 是，问题不复现。使用 `article + ctex` 时，问题能复现。

**Comment by muzimuzhi** [comment]
@jiaopjie 
你提问中说的

> 但奇怪的是, 如果删掉 `\selectfont` 只保留 `\fontsize{12bp}{14.4bp}` 结果变正确了.

是因为「删掉 `\selectfont`」后，字号就没有正确更新，这样 `\parindent` 就没被恢复默认值。

@Liam0205 
代码中给（部分情况下的） part 实现了 indent，可在重定义 `\@part` 和 `\@spart` 的部分搜索 `\CTEX@part@indent`。

**Comment by RuixiZhang42** [comment]
@muzimuzhi 不需要 `\noindent\hspace*{8em}`，直接亲自改写 `\parindent` 就可以了：

```tex
% !TeX program = XeLaTeX
\documentclass[zihao=-4]{ctexart}
\ctexset{
  part={
    name={\rule[-0.140625\ccwd]{0.4pt}{\ccwd}\kern-0.4pt,}, %% 0.140625 = 36/256，中易字体，Windows
    format=\zihao{-4}\parindent8\ccwd, %% 建议用 \ccwd 为单位，em 是西文的单位，两者未必相等
    afterskip=0pt,
  },
}
\begin{document}
\part{一二三四五六七八九十}
\noindent 一二三四五六七八九十
\end{document}
```

![aaa](https://user-images.githubusercontent.com/39968857/51804904-4737e500-2234-11e9-99f0-2b375120135f.png)

@jiaopjie 简单来说是 `format=\zihao{-4}` 覆盖了用户指定的 `indent=...`，因为前者是字体变更命令，在默认 `autoindent=true` 时会及时更新 `\parindent` 为 `2\ccwd`。

**Comment by RuixiZhang42** [comment]
@Liam0205 @muzimuzhi 感觉最简单、最合理、影响最小的解决方案是在

```tex
\parindent \dimexpr \CTEX@XXX@indent \relax
```

所处的 local group 里，紧随其后、在 `\CTEX@XXX@format` 之前，加上一句代码即可：

```tex
\tl_clear:N \l_@@_autoindent_tl
```

适用范围：`XXX = part / chapter / section / subsection`，这等价于局部对标题设置了 `autoindent=false`。

**Comment by RuixiZhang42** [comment]
感觉 `\ctex_update_parindent:` 现在的整个逻辑判断结构是有问题的：

顶层判断 `\l_@@_autoindent_tl` 是否为空应该没有问题：

- 空，说明 `autoindent = false`，不做任何调整；
- 非空，则预备将 `\l_@@_autoindent_tl` 的值赋给 `\parindent`。

在「非空」的情况下，内层莫名其妙地有个 `\dim_compare:nNnF \parindent = \c_zero_dim`。也即：

1. 「非空」+「段首原本**零**缩进」=「段首仍然零缩进，用户指定的 `autoindent=XXX` 无效」；
2. 「非空」+「段首原本**有**缩进」=「段首缩进改成用户指定的 `autoindent=XXX`」；

以上第一点**完全没有道理**吧？给我的感觉是（纯属瞎猜）：曾经没加这个内层的判断，结果导致 `part`、`chapter` 这些标题即使在 `\parindent\z@` 下也会因为字号变更而缩进两格，于是便在内部多加了一层判断。&#8288;<sup>1</sup>

<sup>1. 从 `\normalfont \parindent \z@ \raggedright` 到 `\normalfont \parindent \dimexpr \CTEX@part@indent \relax \CTEX@part@format`，默认的 `\CTEX@part@indent = 0pt` 却因为 `\CTEX@part@format` 而导致标题缩进，所以多加一层判断：若已经为零则维持为零。</sup>

**Comment by muzimuzhi** [comment]
题主遇到的问题，已由提交 https://github.com/CTeX-org/ctex-kit/commit/29b4ea129fe59133ab7a85c64876c14c6f388c97 解决，issue 可适时（例如，在 ctex 新版发布后）关闭。

关于 autoindent 的讨论可在 #402 中继续。

**Comment by RuixiZhang42** [comment]
想得太简单了，纯粹交换 `\CTEX@XXX@indent` 与 `\CTEX@XXX@format` 的顺序是不够的，这是因为之后的 `nameformat`、`numberformat`、`titleformat` 都有可能变更字号，先把 https://github.com/CTeX-org/ctex-kit/commit/29b4ea129fe59133ab7a85c64876c14c6f388c97 撤回。

果然还是我第一次提出来的方案是比较好的，即 https://github.com/CTeX-org/ctex-kit/issues/401#issuecomment-457950756 未经过四次修改的初始方案。由于不想再次修改，故将那个方案重新在这里描述一遍，并附加上额外的修改建议：

1. 修正 `\ctex_update_parindent:` 的实现方法，移除内层逻辑判断：

    ```tex
    \cs_new_protected_nopar:Npn \ctex_update_parindent:
      {
        \tl_if_empty:NF \l_@@_autoindent_tl
          {
            \dim_set:Nn \parindent { \l_@@_autoindent_tl }
          }
      }
    ```

2. 在 `\CTEX@XXX@indent` 所处的 local group 内（一共有 7&nbsp;处，`XXX = part / chapter / section / subsection`），在这些 local group 刚刚开始的时候就清空 `\l_@@_autoindent_tl`，相当于局部设置了 `autoindent=false`，例如：

    ```tex
    \def\@part[#1]#2{%
      ...
      {\tl_clear:N \l_@@_autoindent_tl % <- 局部阻止标题的缩进
       % 阻止由于 format、nameformat、numberformat、titleformat 的字号变更影响到缩进值
       \interlinepenalty \@M
    %  \normalfont \parindent \z@ \raggedright
       \normalfont \parindent \dimexpr \CTEX@part@indent \relax \CTEX@part@format
      ...
    ```

**Comment by RuixiZhang42** [comment]
直到相关 https://github.com/CTeX-org/ctex-kit/issues/402 也被修好了再关。

**Comment by qinglee** [comment]
正如文档所说，`indent`选项用于设置章节标题本身的首行缩进。对于 `\part` 和 `\chapter` 这两级标题，实现的手段是直接设置 `\parindent`，而对于 `\section` 以下的标题，是先通过 `\noindent` 禁用段首缩进，然后再加一个 `\hskip` 实现。

我们可以将`\section` 的`indent` 实现方式应用到`\part` 和 `\chapter`，规避`autoindent`的问题，顺便实现 `hang` 选项的功能。
