### ISSUE TITLE
在linux系统上字体选择的问题

### ISSUE THREAD

**Issue by Quanyu-Mars** [CTeX-org/ctex-kit#405]
当前，ctex的版本号8:svn47595-23
os版本: fedora 29
安装方式，通过系统库dnf安装。
在安装后，ctex 自建了以下5种字体模板
1. ctex-fontset-adobe
2. ctex-fontset-fondol
3. ctex-fontset-mac(old,new)
4. ctex-fontset-ubuntu
5. ctex-fontset-windows（old,new)
在使用时，发现其会匹配到ctex-fontset-fondol此字体集，但本系统没有相关字体，反复报错，经扩充本机字库，补全ctex-fontset-ubuntu中字体集，再将ctex-fontset-ubuntu另命名为ctex-fontset-fondol
终此，才能正常运行。
建议：
1. 能否通过自带开源字体库， 在当不能匹配到具体系统时，利用开源字体库作为默认字体库。
2. 若1不可行，若不能匹配到具体操作系统时，在第一次使用到时能否给出明确的设计提示和要求，最好能提供设置工具。

**Comment by Liam0205** [comment]
@Quanyu-Mars 关于 1：Linux 发行版繁多，且相互之间没有显著文件存在性特征可以快速检验，因此无法具体检测发行版。Fandol 是开源字体库，并且了在 TeX Live 获取。因此 CTeX 将其设置为 Linux 中的默认字体。

关于 2：TeX 编译时基本是无状态的。所以做不到「第一次编译时……」。相关说明在 CTeX 宏集的说明文档里也有写，因此不会做改变。

关于你的问题的解决方案：
1. 安装 Fandol 字库；弱者
2. 将你的字库配置保存为 ``ctex-contest-fedora.def`` ，而后为 CTeX 宏集传入参数 ``fontset=fedora``
