### ISSUE TITLE
[ctex] 建议在 mac 字体文件定义中增加隶书

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#412]
目前，隶书（字族 zhli 和命令 `\lishu`）只在 `fontset=windows|founder` 时有定义。macOS 在10.9, 10.12--10.14，都预装了隶书字体「报隶（Baoli SC）」。看起来，在 `fontset=macnew` 添加隶书是安全的。

想了解 mac 中不定义隶书是出于哪些考虑，现在是否能添加它。

macOS 预装字体列表
 - 10.14 Mojave, https://support.apple.com/en-us/HT208968
 - 10.13 High Sierra, https://support.apple.com/en-us/HT207962
 - 10.12 Sierra, https://support.apple.com/en-us/HT206872
 - 10.10 和 10.11 未找到预装字体列表
 - 10.9 Mavericks, https://support.apple.com/en-us/HT201375

**Comment by zepinglee** [comment]
这个我原来也提过，见 #360 ；其实我觉得 Baoli SC 是没啥问题的，另外还有 Yuanti SC 可以考虑一下

**Comment by muzimuzhi** [comment]
阅读了 #360，主要的问题就是 Baoli SC 归入了「available for download」。

我测试了一款「available for download」的字体，在 texstudio 和命令行下编译时，无论是否使用了编译选项 `-interaction=nonstopmode`，都会触发系统弹窗（见下图）。在弹窗中选择「download」后，都会触发下载，下载完成后才继续编译，编译的文档中刚下载的字体能正常使用。
![image](https://user-images.githubusercontent.com/6376638/54861564-eb866580-4d65-11e9-91be-4e1f525e8608.png)

这个行为与 #360 里 [liam 说的](https://github.com/CTeX-org/ctex-kit/issues/360#issuecomment-386245326)
> 若用户没有预先装好 Baoli SC，使用 TeX 调用会报错（而不是触发预装）

不一致，欢迎一起测试。

------
发帖前搜了「隶书」，没有搜 "\lishu"。重复发帖了，抱歉。
