### ISSUE TITLE
[xeCJKfntef] 考虑去掉 environ 的依赖，改用 xparse 实现

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#413]
1. `xparse` (2019-03-05) 新增了表示环境内容的参数类型 "b"，可用于代替 environ 宏包

>  Added
>  - `xparse`: b-type ar­gu­ment to grab body of en­vi­ron­ments 
> 
> [link](https://ctan.org/ctan-ann/id/mailman.2966.1551902625.5014.ctan-ann@ctan.org)

2. 目前 ctex-kit 项目中只有 `xeCJKfntef` 依赖 `environ` 宏包，且仅用于定义 `CJKfilltwosides` 环境。

3. `xeCJKfntef` 目前已经依赖 `xparse`（由依赖的宏包 `xeCJK` 引入）

4. 据此，建议去掉 `xeCJKfntef` 对 `environ` 的依赖，改用 `xparse` 的新功能实现

5. 对应的 `xparse` 的更新，是在 texlive 2018 冻结期提交的，（对 texlive 而言）目前只有 pretest 用户能更新到。在这一时段更新 `xeCJKfntef`，版本依赖的风险较低。

6. 如果确定「想去掉 eviron 的依赖」，我可以尝试提供 pull request

**Comment by qinglee** [comment]
这个代码其实已经更新好了，网络原因没来得及推上来。
