### ISSUE TITLE
ctex: 增加 no-math 选项

### ISSUE THREAD

**Issue by EthanDeng** [CTeX-org/ctex-kit#414]
**问题描述：**

在使用 `newtx` 系列字体包和 `ctex` 时，发现一个问题，数学公式中的数字字体是 CM，而不是 times。经过排查，是因为 `ctex` 调用了 `fontspec` 包。示例代码：

```tex
%!TEX program = xelatex
%\PassOptionsToPackage{no-math}{fontspec}
\documentclass{article}

\usepackage[UTF8]{ctex}
\usepackage[T1]{fontenc}
\usepackage{newtxtext}
\usepackage{newtxmath}

\begin{document} 
English text. 1234567890  $1234567890$.

\begin{equation}
a^2+b^2=c^2 
\end{equation}

\end{document}
```
![newtx-ctex](https://user-images.githubusercontent.com/8111364/55130805-37b31a80-5157-11e9-8cf0-808d59d11ac5.png)

**解决方法：**

`\PassOptionsToPackage{no-math}{fontspec}` 那句注释取消就好了，终于舒服了：

![newtx-ctex-nomath](https://user-images.githubusercontent.com/8111364/55130898-8791e180-5157-11e9-935c-801484c8b108.png)

鉴于此，建议提供一个 `no-math` 选项，方便我这种老年人。

**Comment by stone-zeng** [comment]
为什么我这边没写那句 `no-math` 也还是 times？

**Comment by stone-zeng** [comment]
另外，如果用的是 ctex 相关文档类，`no-math` 是可以直接作为文档类选项，并且传给 `fontspec`。所以建议是使用 `ctexart` 代替 `article`+`ctex`。

**Comment by Liam0205** [comment]
> 另外，如果用的是 ctex 相关文档类，`no-math` 是可以直接作为文档类选项，并且传给 `fontspec`。所以建议是使用 `ctexart` 代替 `article`+`ctex`。

@EthanDeng 这里只是拿出的 MWE，不代表原始问题也适合用 `ctexart` 嘛。

**Comment by qinglee** [comment]
较新版本的 fontspec 已经对 `newtxmath` 包自动打开 `no-math` 选项，见 https://github.com/wspr/fontspec/issues/357

一般地，可以将 `no-math`  作为全局选项：

```tex
\documentclass[no-math]{article}
```

**Comment by EthanDeng** [comment]
@qinglee OK，谢谢！
