### ISSUE TITLE
ctex 手册：更新说明 MiKTeX Console

### ISSUE THREAD

**Issue by RuixiZhang42** [CTeX-org/ctex-kit#415]
2018 年 4 月左右，MiKTeX 就不再提供 Package Manager 了，之前的 Settings、Package Manager、Update Wizard 全部统一为 MiKTeX Console，由此，CTeX 宏集手册「2.2 CTeX 宏集的安装和更新」需要改写。

详见 https://miktex.org/announcement/mfc-deprecation 与 https://tex.stackexchange.com/q/438472

**Comment by stone-zeng** [comment]
我自己不用 miktex，所以如果描述有误欢迎指正。
