### ISSUE TITLE
ctex-uptex: incorrect indent with jlreq

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#416]
See the following example:

```latex
\documentclass{jlreq}  % or \documentclass[tate]{jlreq} for vertical layout
\usepackage[fontset=fandol]{ctex}
\usepackage{zhlipsum}

\begin{document}
\zhlipsum
\end{document}
```

The indent is only one character's width:

![image](https://user-images.githubusercontent.com/18233088/55567065-8cdec580-572f-11e9-9dab-9b67f2d669b9.png)

I have tested some other classes for upTeX, e.g. `ujarticle` and `utarticle`, the result is correct (two ccwd).

PS: @Steve-Cheung-emct reports that this issue may also appears in [日本史学術論文風クラス集](http://www2.kumagaku.ac.jp/teacher/herogw/).

**Comment by qinglee** [comment]
`jlreq` hooks into `\set@fontsize` to set `\parindent=\zw`:

https://github.com/abenori/jlreq/blob/05dae3a459d916cdc05664bdc1cacefc3c45c162/jlreq.cls#L1075-L1079

**Comment by RuixiZhang42** [comment]
This is most likely by design and/or required by the JIS. See also https://w3c.github.io/jlreq/#line-head-indent-at-the-beginning-of-paragraphs
