### ISSUE TITLE
xeCJK: penalty 的值不一致

### ISSUE THREAD

**Issue by RuixiZhang42** [CTeX-org/ctex-kit#419]
如题。有的地方用了 `\c_@@_ten_thousand_int` 也即 `10000`，但是如下几处却是 `1000`：
https://github.com/CTeX-org/ctex-kit/blob/5b0fbb2693a4f8ab0dd9d4020e513c05fa5f1722/xeCJK/xeCJK.dtx#L4319
https://github.com/CTeX-org/ctex-kit/blob/5b0fbb2693a4f8ab0dd9d4020e513c05fa5f1722/xeCJK/xeCJK.dtx#L4365
https://github.com/CTeX-org/ctex-kit/blob/5b0fbb2693a4f8ab0dd9d4020e513c05fa5f1722/xeCJK/xeCJK.dtx#L4714
https://github.com/CTeX-org/ctex-kit/blob/5b0fbb2693a4f8ab0dd9d4020e513c05fa5f1722/xeCJK/xeCJK.dtx#L8008
前两处可能是有意为之，但后两处是错的（与手册不一致）。

**Comment by qinglee** [comment]
由 0612a77273bc56febd708855b2a531bf76a6e139 引入的错误。
