### ISSUE TITLE
xeCJK: \xeCJK_declare_char_class:nN 为何重置 CM 类

### ISSUE THREAD

**Issue by RuixiZhang42** [CTeX-org/ctex-kit#420]
https://github.com/CTeX-org/ctex-kit/blob/5b0fbb2693a4f8ab0dd9d4020e513c05fa5f1722/xeCJK/xeCJK.dtx#L2741
是否多余？

**Comment by qinglee** [comment]
`U+3099` 和 `U+309A` 是在平假名区段（`U+3040..U+309F`）里的，目的是为了防止他们被误设置为其他类。
