### ISSUE TITLE
ctex: 使用 scheme = plain 时 ctexset 的 format 选项无法改变字体大小

### ISSUE THREAD

**Issue by mohuangrui** [CTeX-org/ctex-kit#422]
ctex 开发者你们好，请问可以帮忙测试一下如标题所述问题吗？

版本信息：
```
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex)
Document Class: ctexbook 2018/05/02 v2.4.14 Chinese adapter for class book (CTE
X)
```

MME:
```
\documentclass[scheme=plain]{ctexbook}%
\ctexset {
    chapter = {
        format = \small,
    }
}
\begin{document}
\chapter{Can not change fontsize: it's supposed to be \small{small}}

This is text of normal size: small

{\small This is text of small size: small}
\end{document}
```
结果如下：

<img width="603" alt="Screen Shot 2019-04-15 at 8 13 57 PM" src="https://user-images.githubusercontent.com/7518165/56131788-0477e480-5fbb-11e9-84ac-a5853001a39a.png">

经测试，其他选项诸如 \centering, \linespread 等等似乎都有效，而且 fontsize 的设定在非 plain 模式下工作正常。

**Comment by RuixiZhang42** [comment]
两种不同排版方案的实现方法不统一，优先级的问题。
- `scheme=chinese` 时，章节标题统一由 `format` 给出，而 `nameformat` 与 `titleformat` 为空。
- `scheme=plain` 时，章节标题分别由 `nameformat` 与 `titleformat` 给出，而 `format` 反而为空。

简单解决方法：`scheme=plain` 时，根据需要清空 `nameformat` 或 `titleformat`。

```tex
\documentclass[scheme=plain]{ctexbook}
\ctexset{
  chapter={
    format=\small,
    titleformat={},
  }
}
\begin{document}
\chapter{Can not change fontsize: it's supposed to be {\small small}}
% 原标题里的 \small 用法不正确

This is text of normal size: small

{\small This is text of small size: small}
\end{document}
```

![title](https://user-images.githubusercontent.com/39968857/56157777-62da9e00-5f8e-11e9-9a71-787c8a51d3ac.png)

目测是一个 bug，**应该考虑将两种方案统一**。

**我个人更介意的其实是 chapter 标题的缩进**，感觉在 `scheme=plain` 时不应该有缩进的。

**Comment by mohuangrui** [comment]
@RuixiZhang42 非常感谢你的充分解答，我的困惑已得到解决，并认同 `ctex` 的处理方式。

是的，标题的 `\small{small}` 应为 `{\small small}`，以及 `MME` 应为 `MWE`，谢谢指正以及提醒版本更新～

**Comment by mohuangrui** [comment]
@RuixiZhang42 请教一下，对于章节标题，是否可能通过 `format` 实现 `中文` 调用 `\sffamily` 而 `英文和数字` 调用 `\rmfamily`？

其实我一直很好奇 ctex 是怎样做到中文自动调用中文字体，而英文自动调用英文字体的，因为理论上，利用这种识别机制就可以实现上述要求。

非常感谢你的帮助

**Comment by zepinglee** [comment]
@mohuangrui 可以用 `\heiti` 这样的命令，因为只作用于 CJK 文字上。不过这样西文跟中文不太协调，建议谨慎使用

**Comment by mohuangrui** [comment]
@zepinglee 不太理想，因为这样的话，就会重新回到我以前踩过的坑，即在Windows上无法加粗的问题，请见 #335 和 #371

**Comment by muzimuzhi** [comment]
@mohuangrui 

> 其实我一直很好奇 ctex 是怎样做到中文自动调用中文字体，而英文自动调用英文字体的

字体切换功能，是利用了 xetex 引擎的 char class 机制。粗暴理解，把所有字符按中西文分类，遇到「中-西」边界就切换到西文字体，遇到「西-中」边界就切换到中文字体。[1, Sec. 3] 里有一个简单的例子。

> 对于章节标题，是否可能通过 format 实现 中文 调用 \sffamily 而 英文和数字 调用 \rmfamily

zepinglee 提供的建议是正确且有效的。更一般的方案是，通过 `fontspec` 和 `xeCJK` 的 `\new[CJK]fontfamily` 命令，分别定义中西字体切换命令，然后一起使用。

```latex
% def
\newfontfamily\useSomeEnFont{<font name 1>}
\newCJKfontfamily\useSomeEnFont{<font name 2>}

% use
\normalfont\useSomeEnFont\useSomeEnFont
```

> 因为这样的话，就会重新回到我以前踩过的坑，即在Windows上无法加粗的问题

是否会遇到以前的坑，和字体设置方式有关。一个字体只有同时满足
 - 没有粗体字族
 - 设置时没有开启伪粗

两个条件时，才会「无法加粗」。设置字体切换命令时多加留意，就能避免「无法加粗」的问题。

[1] [XeTeX Reference](http://mirrors.ctan.org/info/xetexref/xetex-reference.pdf)


PS：对当前 issue 而言，你的追问是离题的。应该新开 issue。

**Comment by zepinglee** [comment]
@mohuangrui 那两个 issue 主要是因为字体没有粗体的字重并且没有开启伪粗，所以你可以用
```
{\heiti English 中文}
```
这样 `\heiti` 只对“中文”有效，“English”还是保保持默认的 “`\rmfamily`”

**Comment by mohuangrui** [comment]
@zepinglee @muzimuzhi 好的，谢谢两位的解答 ！
