### ISSUE TITLE
zhlineskip: 增加范例，单独设置西文段落的行距

### ISSUE THREAD

**Issue by YLXDXX** [CTeX-org/ctex-kit#425]
看了一下说明，\linespread{⟨real⟩}命令只有在quotation，quote环境中有效，问一下怎样单独设置某一段中文的行间距？

**Comment by muzimuzhi** [comment]
这样使用，必须加 `\selectfont`：
```latex
\linespread{<real>}\selectfont
```

参考资料
> `\linespread{factor}`
> 
> Equivalent to `\renewcommand{\baselinestretch}{factor}`, and therefore must be followed by `\selectfont` to have any effect. Best specified in the preamble, or use the setspace package, as just described.
> ref: http://latexref.xyz/Low_002dlevel-font-commands.html#Low_002dlevel-font-commands

又及，`\linespread` 是 latex2e 提供的命令，相关问题建议到 https://github.com/CTeX-org/forum 提问。

**Comment by YLXDXX** [comment]
谢谢，通过
{\linespread{1.5}\selectfont
内容
\par}
解决了，原来\linespread是设置整体的行间距用的

**Comment by RuixiZhang42** [comment]
@YLXDXX 嗯，你也注意到了在局部分组中，不仅开头要加上 `\selectfont` 使命令生效，结尾还要加上 `\par`，这是因为「行距」之类属于「段落属性」。

不过此问题不在 `zhlineskip` 包处理范围内，用户手册里记载的是「中文文档中出现成段的西文，可以适当调整行距，使段落行距适用于西文」——前提是西文在特定的环境中。在文章中途更改行距是不太合适的，如果需要频繁切换中西文段落（或许你写的是某种译文），那么一个系统的处理方法会好一些，像这样：

```tex
\documentclass{ctexart}
\usepackage{zhlineskip}

% 新建西文环境
\newenvironment{english}{%
  \par
  \smallskip
  \ignorespaces
}{%
  \par
  \smallskip
  \ignorespacesafterend
}

% zhlineskip 宏包命令
\RestoreTextEnvironmentLeading{english}

\usepackage{blindtext} % 西文乱数假文
\usepackage{zhlipsum}  % 中文乱数假文
\usepackage{geometry}

\begin{document}
\zhlipsum[1]
\begin{english}
\blindtext
\end{english}
\zhlipsum[1]
\begin{english}
\blindtext
\end{english}
\end{document}
```

> ![example](https://user-images.githubusercontent.com/39968857/57005228-2456fd00-6ba4-11e9-99a1-5c6113cc9196.png)

我是不是可以把这里例子加进用户手册额……

**Comment by YLXDXX** [comment]
加入甚好，请问一下你在环境定义中用了两次\smallskip，前面用一次就可以了，不知用意何在呀？

**Comment by RuixiZhang42** [comment]
@YLXDXX 第一个 `\smallskip` 在西文段落开头起作用，第二个 `\smallskip` 在西文段落结尾起作用，你可以试着把第二个换成 `\bigskip` 看效果。用在这里的目的，是为了适当地隔开不同文种。跑题了……

**Comment by YLXDXX** [comment]
明白了，thanks

**Comment by RuixiZhang42** [comment]
范例已经加入用户手册，还有 bug 要修，不着急上传 CTAN。**需要更正一下之前 `english` 的定义**：

```tex
\newenvironment{english}{%
  \smallskip
  \ignorespaces
}{%
  \par
  \smallskip
  \ignorespacesafterend
}
```

移除环境开头的 `\par`，目的是「**提醒用户自己对上文加空行换段**」，这是因为这个 `english` 的实现仅仅是简单的段落。肯定有更好的实现方法，没时间琢磨了。先写成这样吧：

> ![mock](https://user-images.githubusercontent.com/39968857/57742553-90029500-768f-11e9-94cc-7448cc70a61c.png)
