### ISSUE TITLE
ctex: pdftex 下无法通过 zhmetrics 手段调用微软雅黑

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#434]
最小示例：

```latex
\documentclass[UTF8, fontset=windowsnew]{ctexart}
\begin{document}
\yahei 微软雅黑
\end{document}
```

结果使用宋体代替的：

![image](https://user-images.githubusercontent.com/18233088/57920742-5d92ab00-78ce-11e9-8cce-7359cdcb4e7a.png)

有关的 log：

```
LaTeX Font Info:    Try loading font information for C70+zhyahei on input line 
3.
LaTeX Font Info:    No file C70zhyahei.fd. on input line 3.
LaTeX Font Info:    Try loading font information for C70+song on input line 3.

(/usr/local/texlive/2019/texmf-dist/tex/latex/cjk/texinput/UTF8/c70song.fd
File: c70song.fd 2015/04/18 4.8.4
)

LaTeX Font Warning: Font shape `C70/zhyahei/m/n' undefined
(Font)              using `C70/song/m/n' instead on input line 3.
```

根据代码，zhmetrics+pdftex 部分并没有设置微软雅黑。

**Comment by muzimuzhi** [comment]
根据 ctex 文档，使用 pdftex 时，默认使用 zhmetrics 提供的映射机制。
 - zhmetrics 的文档说明和源码中，都没有处理微软雅黑。
 - zhmCJK 映射机制，处理了雅黑，但 zhmCJK 未被 texlive 收录

目前，ctex 的文档中，对字体配置 windows new + 引擎 pdflatex 的说明是，支持中易字库 + 微软雅黑。这与事实不符，可能需要调整。

https://github.com/CTeX-org/ctex-kit/blob/ee88dc49f2807f91a0dd37d98bec421b5c303080/ctex/ctex.dtx#L946-L948

**Comment by muzimuzhi** [comment]
相关源码段

ctex 选项 `zhmap`
https://github.com/CTeX-org/ctex-kit/blob/ee88dc49f2807f91a0dd37d98bec421b5c303080/ctex/ctex.dtx#L3531-L3547

windows 下字体配置文件中与 pdflatex 相关的部分
https://github.com/CTeX-org/ctex-kit/blob/ee88dc49f2807f91a0dd37d98bec421b5c303080/ctex/ctex.dtx#L9640-L9684

zhmetrics 的源码见 http://mirrors.ctan.org/fonts/psfonts/zhmetrics/tex/generic/zhmetrics/zhwinfonts.tex

**Comment by Liam0205** [comment]
`windowsold` 和 `windowsnew` 在 2.5 里已经取消，现在仅有 `windows` 相当于原来的 `windowsnew`。因此，问题依旧存在。
