### ISSUE TITLE
是否可以手動調整標點符號分類？

### ISSUE THREAD

**Issue by GreenYun** [CTeX-org/ctex-kit#435]
出於文檔上的某些要求，希望把～(U+FF5E)當作普通 CJK 字符處理，希望允許其出現在行首，但是代碼中已經設定 const 列表用於禁止其出現在行首。請問有沒有方法可以重新設置該字符的處理？謝謝

**Comment by stone-zeng** [comment]
可以直接把它的字符类改为 `CJK`：

```latex
\documentclass{article}
\usepackage{xeCJK}
\xeCJKsetup{MiddlePunct-={～}}  % U+FF5E
\xeCJKDeclareCharClass{CJK}{`～}

\setCJKmainfont{Source Han Serif SC}
\begin{document}
\fbox{\parbox{5em}{汉字汉字～汉字汉字}}
\fbox{\parbox{5em}{汉字汉字汉～字汉字汉字}}
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/58605268-c9f7ac00-82c9-11e9-8339-e767f913de17.png)
