### ISSUE TITLE
xeCJK: \setCJKsansfont 必须在 \setCJKmainfont 之后使用

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#439]
如果`\setCJKsansfont` 写在 `\setCJKmainfont` 前面，则会给出 warning，但不影响编译结果：

```latex
\documentclass{article}
\usepackage{xeCJK}
\setCJKsansfont{Source Han Sans SC}
\setCJKmainfont{Source Han Serif SC}
\begin{document}
你好
\sffamily 世界
\end{document}
```

```latex
Package xeCJK Warning: Unknown CJK family `\CJKrmdefault' is being ignored.
(xeCJK)                
(xeCJK)                Try to use `\setCJKmainfont[...]{...}' to define it.
```

`\setCJKmonofont` 也是完全类似的，但 `\setCJKfamilyfont` 和 `\newCJKfontfamily` 则并不会有这个问题。

**Comment by qinglee** [comment]
与 fontspec 包类似，xeCJK 会在 `\setCJK(main|sans|mono)font` 最后执行一次 `\normalfont`，目的是让导言区有中文字体可用。如果第一个设置字体的命令，设置的不是 `\CJKfamilydefault`，就会出现警告。我们可以细化判断，避免这个警告。
