### ISSUE TITLE
xeCJK：大括号、右标点、超出版心、多出一行的奇怪 bug

### ISSUE THREAD

**Issue by Ranqumn** [CTeX-org/ctex-kit#442]
**条件**

触发这个 bug 需要

- 一行需要有四个省略号，（默认 A4，默认字号）这一段总共要有 31 个字（首行缩进不计入）；
- 使用楷体字体：fandolkai（fandolsong 没有这个问题）。

**示例**

```latex
\documentclass{ctexart}
\begin{document}

\begin{flushleft}
没有问题：    
\end{flushleft}

\emph{啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊}

\emph{啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊……}


\begin{flushleft}
文字超越版心：
\end{flushleft}

\emph{啊啊啊啊啊啊……啊啊啊啊啊啊……啊啊啊啊……啊啊啊啊啊啊啊……}

多出一行？

啊啊啊啊啊啊……啊啊啊啊啊啊……啊啊啊啊……啊啊啊啊啊啊啊……

没有多出一行。

\end{document}
```
![issue-ctex-xecjk](https://user-images.githubusercontent.com/48835452/61167466-0ce6a980-a52f-11e9-8ca2-ee18efcf95aa.png)

**Comment by muzimuzhi** [comment]
首先，根据 `texdoc xecjk`, sec. 3.1 中关于选项 `LongPunct`（长标点）的介绍，
  * 默认情况下，省略号 `……` 属于长标点
  * 允许在长标点前后断行，但是禁止在它们之间断行
所以，这是 `xecjk` 的预定义行为，不是 bug。

其次，复现条件不用那么苛刻，也和具体字体无关。只需要有一个本在行末的省略号，然后在那一行中间插入一些空格即可。例如
```latex
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊\ 啊啊啊啊啊啊啊啊啊啊啊啊啊啊……
```

**Comment by stone-zeng** [comment]
给个最小示例吧：

```latex
\documentclass[draft]{article}
\usepackage{xeCJK,geometry}
\geometry{showframe,paperwidth=4.5cm, paperheight=6cm}

\begin{document}

{文字文字文字……}

多出一行

\begingroup\itshape 文字文字文字……\endgroup

没有多出一行

文字文字文字……

没有多出一行

\end{document}
```

似乎只要是省略号在 `{...}` 里面就有这个问题，并不是楷体造成的。应该不是预定义行为吧。

![image](https://user-images.githubusercontent.com/18233088/61180383-00a23f80-a648-11e9-9e64-d5b7d0b1ef25.png)

**Comment by muzimuzhi** [comment]
@Ranqumn 
抱歉，我之前把问题理解错了。你说的问题确实存在，而且不是 xecjk 的预期行为。

@stone-zeng 
你提供的 mwe 中，漏了字体设置

**Comment by stone-zeng** [comment]
裸用 `xeCJK` 的话默认会开启 `LoadFandol` 选项，所以用的是 fandol 字体（song+kai）。

**Comment by muzimuzhi** [comment]
是我的问题。编辑器的内置阅读器没有把 fandol glyph 渲染出来。

**Comment by Ranqumn** [comment]
大括号的行为，与 `\begingroup` 是不一样的吗？

**Comment by Liam0205** [comment]
@Ranqumn 不一样。

`\bgroup 是用 \let 定义的，类似这样 \let\bgroup={ 。但是 \begingroup` 不是，它不会和 {} 去匹配，按 Knuth 的说法，是一种 semi-group。

**Comment by Liam0205** [comment]
@Liam0205 详细的可以参考这里：
https://tex.stackexchange.com/a/1932/38350

**Comment by Ranqumn** [comment]
谢谢。

**Comment by RuixiZhang42** [comment]
不是 bug，是正常的断行算法，第三第四段没有合理的断行点，TeX 已经输出 overfull 的警告了。

第一段第一行一共 30 个汉字，29 处可以插入 `\CJKglue`；
第二段第一行一共 29 个汉字，28 处可以插入 `\CJKglue`；
默认情况下，汉字转移到右标点不增加弹性空白，右标点转移到汉字可以增加弹性空白，所以第三第四段只有 22 处可以插入 `\CJKglue`。

越少地方可以加 `\CJKglue`，每个 `\CJKglue` 就要伸展得越多。但是 `\CJKglue` 伸展值有上限，TeX 拉伸不开上一行、多余的内容推不到下一行，就只能把东西往上一行放了，并给出 overfull 的警告。

```latex
\documentclass{ctexart}
\begin{document}

\xeCJKsetup{CJKglue=\hskip0pt plus 0.1\baselineskip\relax}

\begin{flushleft}
现在不超版心了
\end{flushleft}

\emph{啊啊啊啊啊啊……啊啊啊啊啊啊……啊啊啊啊……啊啊啊啊啊啊啊……}

多出一行？（省略号中间不允许断开，怎么样都得放到下一行去的）

啊啊啊啊啊啊……啊啊啊啊啊啊……啊啊啊啊……啊啊啊啊啊啊啊……

没有多出一行。（省略号中间不允许断开，怎么样都得放到下一行去的）

\end{document}
```
![linebreak](https://user-images.githubusercontent.com/39968857/61323131-3cbad900-a7dd-11e9-9847-896dc6416d57.png)

**Comment by RuixiZhang42** [comment]
之前判断失误，应该是「与断行相关的并无 bug」。更精简的例子：

```latex
\documentclass[draft]{article}
\usepackage{xeCJK}
\begin{document}

\emph{\framebox[330pt]{line}。}

多余空行

\textbf{\framebox[330pt]{line}。}

多余空行

\framebox[330pt]{line}。

没有多余空行

\end{document}
```

![extraline](https://user-images.githubusercontent.com/39968857/61324885-7097fd80-a7e1-11e9-9acc-faa45adbfbc2.png)

行末若是汉字、左标点，则没有问题。左标点是因为被断到下一行了，汉字则是 overfull 但不会制造空行。但是如果是右标点，就会多一个空行。用 `\showoutput` 观察发现，前两例各自都有多余一个 `kern 0`，初步判断是 `xeCJK` 在切换字体时往右标点与边界之间插入的，这个 kern 自然地被移到了下一行，所以造成空行。

**Comment by Ranqumn** [comment]
也许，还可以再精简一点？

```latex
\documentclass[draft]{article}
\usepackage{xeCJK}
\begin{document}

{\framebox[330pt]{line}。}

多余空行

\begingroup \framebox[330pt]{line}。 \endgroup

没有多余空行

\framebox[330pt]{line}。

没有多余空行

\end{document}
```

![issue-ctex-xecjk-2](https://user-images.githubusercontent.com/48835452/61348704-264e6500-a851-11e9-89a3-aa184285eb46.png)


> 初步判断是 `xeCJK` 在切换字体时往右标点与边界之间插入的

呃，如 @stone-zeng 之前所述，这可能是大括号的行为？

**Comment by qinglee** [comment]
这个问题与 xeCJK 对标点符号的处理与 TeX 在段末的行为有关，还需要注意 `}` 放在行末正常情况下是会产生一个空格。以上的一些例子在行末的 `}` 后加一个 `%` 抑制空格可以避免，实在不行还可以用 `\xeCJKnobreak`。
