### ISSUE TITLE
xeCJK 与思源系字体的破折号

### ISSUE THREAD

**Issue by Ranqumn** [CTeX-org/ctex-kit#444]
`xeCJK` 好像自动把省略号设置成中文的，然而没有把破折号设置成中文的……

相关参考资料：

- #382 的 [这条 Comment](https://github.com/CTeX-org/ctex-kit/issues/382#issuecomment-491951413)
- [Type is Beautiful - 不离不弃的破折号](https://thetype.com/2019/03/14918/)

与破折号有关的 issue：

- #320

#### 使用思源黑体

```latex
\documentclass{ctexart}

\XeTeXgenerateactualtext=1

\setCJKmainfont{Noto Sans CJK SC}

\begin{document}

美图——国家 % two U+2014

美图⸺国家 % one U+2E3A

美图……国家 % two U+2026

\addCJKfontfeatures{Script=CJK Ideographic,Language=Chinese Simplified}

美图——国家 % two U+2014

美图⸺国家 % one U+2E3A

美图……国家 % two U+2026

\end{document}
```

![issue-font-source-han-1](https://user-images.githubusercontent.com/48835452/62017071-ccc92d00-b1a4-11e9-9b0b-34603cc99219.png)

嗯？为什么破折号中间断开了？

似乎它没有拼成 `U+2E3A`，还是两个 `U+2014`。

然而，如果开了 `\XeTeXgenerateactualtext=1` 复制还是可以复制成 `U+2E3A`。

如果没开 `\XeTeXgenerateactualtext=1` 还是两个 `U+2014`。

#### 使用思源宋体

```latex
\documentclass{ctexart}

\XeTeXgenerateactualtext=1

\setCJKmainfont{Noto Serif CJK SC}

\begin{document}

美图——国家 % two U+2014

美图⸺国家 % one U+2E3A

美图……国家 % two U+2026

\addCJKfontfeatures{Script=CJK Ideographic,Language=Chinese Simplified}

美图——国家 % two U+2014

美图⸺国家 % one U+2E3A

美图……国家 % two U+2026

\end{document}
```

![issue-font-source-han-2](https://user-images.githubusercontent.com/48835452/62017060-c3d85b80-b1a4-11e9-9598-4fc7ca341e73.png)

#### 使用思源黑体

```latex
\documentclass{article}

\usepackage{fontspec}

\XeTeXgenerateactualtext=1

\setmainfont{Noto Sans CJK SC}

\begin{document}

美图——国家

美图⸺国家

美图……国家

\addfontfeatures{Script=CJK Ideographic,Language=Chinese Simplified}

美图——国家

美图⸺国家

美图……国家

\end{document}
```

![issue-font-source-han-3](https://user-images.githubusercontent.com/48835452/62017051-b7540300-b1a4-11e9-8ea8-d679bd7f1109.png)

#### 使用思源宋体

```latex
\documentclass{article}

\usepackage{fontspec}

\XeTeXgenerateactualtext=1

\setmainfont{Noto Serif CJK SC}

\begin{document}

美图——国家

美图⸺国家

美图……国家

\addfontfeatures{Script=CJK Ideographic,Language=Chinese Simplified}

美图——国家

美图⸺国家

美图……国家

\end{document}
```

![issue-font-source-han-4](https://user-images.githubusercontent.com/48835452/62017045-ab684100-b1a4-11e9-9309-58e190697d01.png)

~~好迷好迷~~

……所以，排版应该怎么处理比较好？

**Comment by Ranqumn** [comment]
呃？好像发现已经有[讨论](https://github.com/CTeX-org/ctex-kit/issues/382#issuecomment-430873626)了，我似乎重复发了……

**Comment by Ranqumn** [comment]
所以，一个好像可行的方案是这样的？

```latex
\documentclass{ctexart}

% 将 U+2014 破折号合字
% via: https://github.com/CTeX-org/ctex-kit/issues/382#issuecomment-430873626

\ExplSyntaxOn
\xeCJK_new_class:n { PoZheHao }
\__xeCJK_save_CJK_class:n { PoZheHao }
\xeCJK_declare_char_class:nn { PoZheHao } { "2014 }
\seq_map_inline:Nn \g__xeCJK_class_seq
  {
    \str_if_eq:nnF {#1} { PoZheHao }
      {
        \xeCJK_copy_inter_class_toks:nnnn { PoZheHao } {#1} { FullRight } {#1}
        \xeCJK_copy_inter_class_toks:nnnn {#1} { PoZheHao } {#1} { FullRight }
      }
  }
\ExplSyntaxOff

\setCJKmainfont{Noto Sans CJK SC}[Script=CJK Ideographic,Language=Chinese Simplified]

\begin{document}

美图——国家 % two U+2014

美图⸺国家 % one U+2E3A

美图……国家 % two U+2026

{\fangsong 美图——国家} % two U+2014

{\kaishu 美图——国家} % two U+2014

{\heiti 美图——国家} % two U+2014

{\songti 美图——国家} % two U+2014

\end{document}
```

![issue-font-source-han-5](https://user-images.githubusercontent.com/48835452/62018313-b8d3fa00-b1a9-11e9-868b-7a981cf99b07.png)

这样做好像对 Fandol 系字体没有什么影响。

**Comment by stone-zeng** [comment]
因为只有思源这么做了，其他的中文字体一般都是把两个 U+2014 作为破折号。

**Comment by Firestar-Reimu** [comment]
请问破折号高度不在中间如何解决？

<img width="739" height="56" alt="Image" src="https://github.com/user-attachments/assets/ebd75455-c607-4c4d-a585-7616d3f1daf2" />

```
\usepackage[fontset=none]{ctex}
\setCJKmainfont{Source Han Serif CN Medium}[BoldFont=Source Han Serif CN Bold,ItalicFont=FZKai-Z03]
\setCJKsansfont{Source Han Serif CN Medium}[BoldFont=Source Han Serif CN Bold,ItalicFont=FZKai-Z03]
\setCJKmonofont{Source Han Serif CN Medium}[BoldFont=Source Han Serif CN Bold,ItalicFont=FZKai-Z03]
\addCJKfontfeatures{Script=CJK Ideographic,Language=Chinese Simplified}
```
使用lualatex编译

**Comment by Explorer-cc** [comment]
> 请问破折号高度不在中间如何解决？
> 
> <img alt="Image" width="739" height="56" src="https://private-user-images.githubusercontent.com/65082432/604583168-ebd75455-c607-4c4d-a585-7616d3f1daf2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODA5NzI4OTAsIm5iZiI6MTc4MDk3MjU5MCwicGF0aCI6Ii82NTA4MjQzMi82MDQ1ODMxNjgtZWJkNzU0NTUtYzYwNy00YzRkLWE1ODUtNzYxNmQzZjFkYWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNjA5VDAyMzYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmM2RjZjQzNjRiZWZjOWM4NzNmMWUwNTdlYzI2MWM3YmUxMDkzYjUwNWRkZTc4YjBiYTg5ZWE2MGM3MzNiODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.XOsXft852qsugrg_NotsD93in23cD_fvjd-z5MHPyus">
>
> ```latex
> \usepackage[fontset=none]{ctex}
> \setCJKmainfont{Source Han Serif CN Medium}[BoldFont=Source Han Serif CN Bold,ItalicFont=FZKai-Z03]
> \setCJKsansfont{Source Han Serif CN Medium}[BoldFont=Source Han Serif CN Bold,ItalicFont=FZKai-Z03]
> \setCJKmonofont{Source Han Serif CN Medium}[BoldFont=Source Han Serif CN Bold,ItalicFont=FZKai-Z03]
> \addCJKfontfeatures{Script=CJK Ideographic,Language=Chinese Simplified}
> ```
> 
> 使用lualatex编译

请提供完整代码，并把问题简化。

```latex
\documentclass{article}
% \usepackage[fontset=ubuntu]{ctex}
\usepackage[fontset=none]{ctex}
\setCJKmainfont{Source Han Serif CN Medium}

\begin{document}
我能吞下玻璃——而不—伤身体。
\end{document}
```

<img width="1974" height="327" alt="Image" src="https://github.com/user-attachments/assets/691eefc2-17b3-421b-8bca-b3446ff28f77" />

同时这个问题和本问题不太有关系，本问题主要集中在破折号是否可断行。最好发到 https://github.com/CTeX-org/ctex-kit/issues/320 或者新开一个问题。

https://github.com/CTeX-org/ctex-kit/issues/320#issuecomment-343738979 以及 https://github.com/CTeX-org/ctex-kit/issues/320#issuecomment-344831341 提出：

> 不过，可以试试 fwid。

> 尝试了一下，确实有用。

```latex
\documentclass{article}
% \usepackage[fontset=ubuntu]{ctex}
\usepackage[fontset=none]{ctex}
\setCJKmainfont{Source Han Serif CN Medium}[RawFeature={+fwid}]

\begin{document}
我能吞下玻璃——而不—伤身体。
\end{document}
```

<img width="2003" height="497" alt="Image" src="https://github.com/user-attachments/assets/a690a744-0b59-450f-906a-4e398a46df48" />

不过我个人觉得「fwid」的破折号和「思源宋原先的破折号」不是同一个.... 似乎原先的更粗的破折号和中文字体更match....

> 使用lualatex编译

Just for fun:

```latex
\documentclass{article}
\usepackage[fontset=none]{ctex}
\usepackage{luacode}

\begin{luacode*}
local glyph_id = node.id("glyph")
local list_ids = { [node.id("hlist")] = true, [node.id("vlist")] = true }

local function raise_dash(head)
  for n in node.traverse(head) do
    if n.id == glyph_id then
      if n.char == 0x2E3A or n.char == 0x2014 then
        n.yoffset = (n.yoffset or 0) + tex.sp("0.2ex")
      end
    elseif list_ids[n.id] and n.list then
      n.list = raise_dash(n.list)
    end
  end
  return head
end

luatexbase.add_to_callback("post_linebreak_filter", raise_dash, "raise-dash")
\end{luacode*}

\setCJKmainfont{Source Han Serif CN Medium}

\begin{document}
我能吞下玻璃——而不—伤身体。
\end{document}
```

<img width="2005" height="558" alt="Image" src="https://github.com/user-attachments/assets/b95831a2-16a4-4ffb-9bb5-fe3eb70ade30" />

**Comment by Firestar-Reimu** [comment]
谢谢，原来这个issue在#320有讨论

**Comment by Explorer-cc** [comment]
related: https://tex.stackexchange.com/q/454564
