### ISSUE TITLE
关于 xeCJK 对 CJKfntef 的处理

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#449]
涉及到的 xeCJK 的源码段为
https://github.com/CTeX-org/ctex-kit/blob/dce0e53ef106740d74e676164a9039de27b79596/xeCJK/xeCJK.dtx#L8794-L8817

1. 请问 `\ifCTEX@fntef` 是在哪里定义的
尝试了在当前最新版本的 ctex, xeCJK, xeCJKfntef 中搜索，都没有找到
1. 根据 `判断过于繁琐，应该在 \pkg{ctex} 包中妥善处理。这段代码应在 \pkg{ctex} 包发布新版本后删去。`，现在 ctex 中是否已经处理？在 xecjk 是否可以删去？

ctex 中的相关源码段
https://github.com/CTeX-org/ctex-kit/blob/dce0e53ef106740d74e676164a9039de27b79596/ctex/ctex.dtx#L6218-L6295

**Comment by muzimuzhi** [comment]
会关注到这段 xeCJK 源码，是观察到：

虽然 xeCJK + CJKfntef 会加载 xeCJKfntef，但因为是通过 `\xeCJK_at_end_preamble:n` 加载的，所以在 preamble 部分 xeCJKfntef 中定义的 l3keys 选项（例如 `xeCJK/options/underdot`）无法通过 `\xeCJKsetup{...}设置。

**Comment by qinglee** [comment]
这段代码确实过于繁琐，需要清理。

**Comment by qinglee** [comment]
`\ifCTEX@fntef` 是 ctex v2.0 之前版本定义的，这段代码目前已经清除掉了。

需要注意的是，目前载入 ulem 包后，也不再自动载入 xeCJKfntef 补丁，需要用户显式载入 xeCJKfntef。
