### ISSUE TITLE
ctex: \fontsize{}{}\selectfont 会修改对 CJKglue 的设置

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#450]
例子
```latex
\documentclass{ctexart}
% \setCJKmainfont{STSong}
\usepackage[]{zhlipsum}
\begin{document}
默认效果\par
\zhlipsum[20][name=zhufu]

\xeCJKsetup{CJKglue={\hskip 10pt}}
CJKglue 设置后\par
\zhlipsum[20][name=zhufu]

\fontsize{10}{12}\selectfont
CJKglue 设置被修改\par
\zhlipsum[20][name=zhufu]
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/64012389-2def7200-cb50-11e9-8940-7ab0add91274.png)

 * 使用 ctex 宏包或文档类，问题都能复现
 * 只使用 xecjk 宏包，问题不复现

**Comment by qinglee** [comment]
这个是受 `linestretch` 这个选项的影响，在 ctex 包下改变 CJKglue 可使用`\ziju`。

**Comment by muzimuzhi** [comment]
谢谢。

------

补充两个具体例子，以展示解决方案，便利他人查看。

方案 1，禁用 `linestretch` 选项，劣势是每行的允许伸长量不再按字号自动修改，汉字间的弹性间距固定为 0.08\baselineskip 。
```latex
\documentclass{ctexart}
\usepackage{zhlipsum}

\ctexset{linestretch=\maxdimen} % <<< added

\begin{document}
默认效果\par
\zhlipsum[20][name=zhufu]

\xeCJKsetup{CJKglue={\hskip 10pt}}
CJKglue 设置后\par
\zhlipsum[20][name=zhufu]

\fontsize{10}{12}\selectfont
CJKglue 设置被修改\par
\zhlipsum[20][name=zhufu]
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/66257521-ed2ced80-e7cc-11e9-8938-4673445bd6ec.png)

方案 2，通过 `\ziju{<数值>}` 设定相邻汉字间距为字符宽度的倍数，ccwd = 字符宽度 + 相邻汉字间距。劣势是字间距无法和字号独立。

```latex
\documentclass{ctexart}
\usepackage{zhlipsum}

\begin{document}
默认效果\par
\zhlipsum[20][name=zhufu]

\ziju{1.0}  % <<< added

CJKglue 设置后\par
\zhlipsum[20][name=zhufu]

\fontsize{10}{12}\selectfont
CJKglue 设置被修改\par
\zhlipsum[20][name=zhufu]
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/66257613-0d10e100-e7ce-11e9-8572-55f328a02876.png)
