### ISSUE TITLE
ctex: \CTEXifname 的名称和用法问题

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#451]
目前 `ctex` 文档中对 `\CTEXifname` 的说明如下：

> `\CTEXifname` 用于根据当前章节的名字的有无设置不同的格式。……例如，设置章的标题有名字时左对齐，无名字时居中对齐，并且在标题后画一条横线。

但在代码部分的注释却是「用于判断当前标题是否有编号」，且从后续代码来看确实是用来判断是否有编号而非名字的。

所以，是否应当重新命名这一命令，或是仅仅修改文档？以及这一名称的由来有什么解释吗？

有关信息：`\CTEXifname` 是在 fbfc484f81c1a9568c02642c541d249562b74e26 引入的，之后基本没有做过修改。

**Comment by muzimuzhi** [comment]
「章节的名字」这个名词的初次介绍，是在选项 `name` 处。
![image](https://user-images.githubusercontent.com/6376638/65308601-00c93900-dbbd-11e9-9e07-1340ac65e6bd.png)

个人理解，「章节的名字」是作为「章节的编号」在中文场景下的拓展而存在的。
 - 章节的编号，延续其在英文文档中的对应意思，侧重 `\the<counter>` 的输出
 - 中文场景下，因为有 `name={<pre>,<post>}` 的可配置项，所以用「章节的名字」表示 `<pre> \the<counter> <post>` 的输出，对应 `\CTEXthe<counter>`

实际行为是
 - 若编号（例如使用 `\section`），则输出章节的名字，且 `\CTEXifname == \@firstoftwo` 
 - 若不编号（例如使用 `\section*`），则不输出章节的名字，且 `\CTEXifname == \@secondoftwo`

对开发者而言，是「是否编号」决定了 `\CTEXifname` 的行为；对普通用户而言，影响 `CTEXifname` 的有两点，从输入看「是否编号」，从输出看「是否输出章节的名字」。所以用户文档和源码注释中的用词差异，可能是有意义的。

<!-- 
按照非常教条的理解方式，如果只使用「章节的编号」，那么也许（非常抠字眼的）用户期待 `\section*{<content>}` 输出的是 `<pre><post> <sep> <content>`，即只抑制了编号的输出。所以引入「章节的名字」这个新名词，对于让「章节的编号」作为译名和其在英文文档中的意义保持一致、减少误解，可能是有帮助的。
--!>

<p>
最后，我支持在文档中更清楚地表达「在本文档中，章节的名字表示 xxx，而章节的编号表示 xxx」、「是否编号（即是否使用带星的章节命令），决定是否输出章节的名字」等意思。

**Comment by Liam0205** [comment]
太复杂了，直接把表述调整为和「星号」挂钩就好了。
