### ISSUE TITLE
求教各位大侠：为什么theorem环境下不能显示汉字？

### ISSUE THREAD

**Issue by zhxf115** [CTeX-org/ctex-kit#452]
```tex
\documentclass[a4paper,12pt]{article}%[...]为可选项
\usepackage{indentfirst,latexsym,bm}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{amsfonts, amssymb} % math equations, symbols
\usepackage{CJK}
\newtheorem{thm}{Theorem定理}[section]
\begin{document}
\begin{CJK*}{GBK}{song}
\section{练习}
\subsection{LaTeX练习}
\begin{thm}
为什么不显示为汉字“定理”
\end{thm}
\end{CJK*}
\end{document}
```

<img width="391" alt="不能显示汉字“定理”" src="https://user-images.githubusercontent.com/55942333/65829230-952a4e80-e2d5-11e9-86ed-0f389b5e30b8.png">

**Comment by stone-zeng** [comment]
9102 年求求你别再用 `CJK` 了……

```tex
\documentclass[a4paper,12pt]{ctexart}
\usepackage{amsmath,amsthm}
\newtheorem{thm}{Theorem定理}[section]

\begin{document}
\section{练习}
\subsection{\LaTeX{} 练习}
\begin{thm}
显示为汉字“定理”
\end{thm}
\end{document}
```

用 xelatex 或者 lualatex 编译：

![image](https://user-images.githubusercontent.com/18233088/65829816-eb01f500-e2db-11e9-9296-f14501c3d99a.png)

**Comment by zhxf115** [comment]
太感谢了！
不过用 xelatex编译出来的是烂码，而 lualatex 编译不出来。
还是用PDFLaTeX编译出来的。
再次感谢！
您太厉害了！

**Comment by Liam0205** [comment]
@zhxf115 烂码笑死我……

乱码是因为你没把文件保存成 UTF-8 编码。

**Comment by Liam0205** [comment]
@stone-zeng 应该总是显式声明 UTF8 选项～

**Comment by zhxf115** [comment]
麻烦给个显示声明UTF8选项的句子，谢谢了！

**Comment by stone-zeng** [comment]
```tex
\documentclass[UTF8,a4paper,12pt]{ctexart}
```

当然，前提是这个文件本身的编码就是 UTF-8，如果你用 xelatex/lualatex 文档类参数写不写 `UTF8` 实际上都无所谓。

以及，在现在这个年代，所有的（给人看的）文件在所有的地方基本上都应该用 UTF-8 编码了。

**Comment by zhxf115** [comment]
您帮了我大忙了。太感谢您了！

**Comment by zhxf115** [comment]
向您反馈一下，我的这个article不能加UTF8，加了就不能顺利地编译，不加就完全通过了。再次感谢！

**Comment by stone-zeng** [comment]
没说 `article` 能加 `UTF8` 参数啊，这个是 `ctexart` 等宏包的选项。
