### ISSUE TITLE
newtx 宏包 version 1.60 更新后与 ctex 冲突

### ISSUE THREAD

**Issue by TomBener** [CTeX-org/ctex-kit#454]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] macOS
  
- TeX 发行版
  - [x] TeX Live 2019

## 描述问题

newtx 宏包更新（版本为 version 1.60，2019 年 10 月 9 日更新的版本）后与 ctex 冲突。

## 最小工作示例（MWE）

```latex
\documentclass[12pt,a4paper]{ctexart}

\usepackage{newtxmath}
\usepackage{lipsum}

\begin{document}
\lipsum[1-2]
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
TraditionalBuilder: Engine: xelatex. Invoking latexmk... done.

Errors:

test.tex:763: LaTeX Error: Command `\lvert' already defined. [...thopen}  {symbols}{106}{largesymbols}{12}]
test.tex:764: LaTeX Error: Command `\rvert' already defined. [...thclose} {symbols}{106}{largesymbols}{12}]
test.tex:765: LaTeX Error: Command `\lVert' already defined. [...thopen}  {symbols}{107}{largesymbols}{13}]
test.tex:766: LaTeX Error: Command `\rVert' already defined. [...thclose} {symbols}{107}{largesymbols}{13}]

Warnings:

/usr/local/texlive/2019/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-macnew.def: Package fontspec Warning: Font "Songti SC Light" does not contain requested(fontspec)                Script "CJK".
(Log parsing issues. Disregard unless something else is wrong.)

test.log:1: Double-click here to open the full log.

[Done!]
```

**Comment by stone-zeng** [comment]
有关讨论：

- https://github.com/xueruini/thuthesis/pull/434#pullrequestreview-298613618
- https://github.com/ElegantLaTeX/ElegantBook/issues/59
- https://github.com/sjtug/SJTUThesis/issues/452

**Comment by stone-zeng** [comment]
研究了一下，发现是 `ulem` 宏包把 `\MakeRobust` 命令「自作主张」重定义了，因此使得 `\set@mathdelimiter` 之后 `\lvert` 等命令被多展开了一次，从而与 `newtxmath` 发生冲突。

**Comment by stone-zeng** [comment]
见讨论 <https://chat.stackexchange.com/transcript/message/51984967#51984967>。

**Comment by stone-zeng** [comment]
在 b61b7e616508171ec89873900658d9576c0d33ec 中不再自动载入 `(xe)CJKfntef` 包之后，这个问题至少就被掩盖起来了。如果需要使用 `xeCJKfntef`，只需在 `newtxmath` 之后调用即可：

```tex
\documentclass{ctexart}
\usepackage{newtxmath,xeCJKfntef}
\begin{document}
\CJKunderline{虚室生白，吉祥止止}\par
\CJKunderdblline{虚室生白，吉祥止止}\par
\CJKunderwave{虚室生白，吉祥止止}\par
\CJKsout{虚室生白，吉祥止止}\par
\CJKxout{虚室生白，吉祥止止}
\end{document}
```

**Comment by muzimuzhi** [comment]
> 研究了一下，发现是 `ulem` 宏包把 `\MakeRobust` 命令「自作主张」重定义了，因此使得 `\set@mathdelimiter` 之后 `\lvert` 等命令被多展开了一次，从而与 `newtxmath` 发生冲突。
> https://github.com/CTeX-org/ctex-kit/issues/454#issuecomment-542311858

`ulem` 2019/11/18 修复了该问题。详见 https://github.com/CTeX-org/ctex-kit/issues/470#issuecomment-573939018 。

使用 texlive 2019 的冻结版本（即，安装 texlive 2019 并升级所有宏包）编译 issue 中提供的 mwe（见 https://github.com/CTeX-org/ctex-kit/issues/454#issue-507299436 ），
 - pdflatex 和 xelatex 均不再报错
 - lualatex 会在加载宏包 `newtxmath` 时报错 `\Zbar` 已定义，可通过在 `\usepackage{newtxmath}` 前添加 `\let\Zbar\relax` 避免。
经查 `\Zbar` 在宏包 `xunicode` 中初次定义，属于 `xunicode` 和 `newtxmath` 的兼容性问题。

------
当前 issue 报告的问题（xelatex 编译特定例子时报错，命令 `\lvert` 等已定义）可通过更新 `ulem` 包解决，关闭 issue。
