### ISSUE TITLE
macOS 10.15 Catalina 的 Songti.ttc 路径改变导致判断系统有误

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#455]
macOS 10.15 Catalina 的 `Songti.ttc` 路径改到了 `/System/Library/Fonts/Supplemental/Songti.ttc`，所以目前用 `/Library/Fonts/Songti.ttc` 来判断的逻辑就不对了：
https://github.com/CTeX-org/ctex-kit/blob/dce0e53ef106740d74e676164a9039de27b79596/ctex/ctex.dtx#L6085-L6098

建议换成 `/System/Library/Fonts/STHeiti Light.ttc`，这个目录下的字体似乎稍微稳定些

**Comment by muzimuzhi** [comment]
补一个临时方案，为有相同问题并搜到这个 issue 的用户提供一定的方便。

临时方案：手动指定 `fontset`，例如 
```tex
\documentclass[fontset=macnew]{ctexart}
```
