### ISSUE TITLE
 双栏排版时，如果使用ctexbook等文档类，或调用ctex宏包出问题

### ISSUE THREAD

**Issue by fengzhenhua-vip** [CTeX-org/ctex-kit#458]
当使用ctexbook,ctexart等文档类排版时，如打开双栏排版项，会报错。如下
Underfull \vbox (badness 10000) has occurred while \output is active
Underfull \vbox (badness 10000) has occurred while \output is active [1]

如果使用 article 或 book 文档类直接排版英文，如打开双栏则不会出现问题。
暂时不知道大家是如何处理的。

**Comment by stone-zeng** [comment]
见 #318。
