### ISSUE TITLE
双栏排版 Underfull \box 问题

### ISSUE THREAD

**Issue by fengzhenhua-vip** [CTeX-org/ctex-kit#460]
在使用双栏排版时，会出现
Underfull \vbox (badness 10000) has occurred while \output is active

但是在英文档类 book 等下排版英文不会出现问题。一旦调入 ctex 宏包，就会出现此问题，所以判断应当是ctex 修改字号导致的问题。

**Comment by stone-zeng** [comment]
同一个问题放在一个 issue 里面（#459）吧，这个先关了。

**Comment by muzimuzhi** [comment]
@stone-zeng 
是否引用错了？与当前 issue 重复的是 #458。

**Comment by stone-zeng** [comment]
呃，是我看走眼了……
