### ISSUE TITLE
ctex: 考虑不再默认载入 CJKfntef 和 xeCJKfntef

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#463]
一般的文档其实并不需要，需要的时候手动载入并不麻烦。希望移除的原因，一是 LuaLaTeX、upLaTeX 编译时不能用会给出警告，二是因为使用了 `ulem` 包会出现一些兼容性问题。

**Comment by muzimuzhi** [comment]
#449 与此相关
