### ISSUE TITLE
xeCJKfntef: 取消初始彩色设置

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#466]
`xeCJKfnt` 目前在定义了 `\color` 命令后，会默认开启彩色显式：

https://github.com/CTeX-org/ctex-kit/blob/dacf77095131f169f361437bf4e22dab830a3e7d/xeCJK/xeCJK.dtx#L10048-L10059

根据 #168 中的讨论，这一设定是为了与 `CJKfntef` 兼容。现在看来不是很有必要，可以考虑直接移除。

**Comment by muzimuzhi** [comment]
不向前兼容涉及的方面越来越多了……

设置过渡期的做法是否值得考虑？例如
 - 阶段一，提供选项 `fntefcolor=true/false`，初始化为 `true`；在文档中说明，未来版本将改变初始值。
 - 阶段二，令选项 `fntefcolor` 初始化为 `false`；用户有需要时，可手动恢复到老版本的默认效果。

这样
 - 为用户留出了一定的过渡期
 - 为用户可能的「恢复到以前的 xeCJKfntef 颜色设置」需求，提供了便捷方案
 - 略微增加了维护成本

**Comment by stone-zeng** [comment]
这个本来就是 undocumented 的功能，我怀疑可能就没有多少人注意到……

倒是原来 `ctex` 宏包定义了 `\CTEXunderline` 这些命令，刚刚注意到《LaTeX 入门》里面介绍过了。那我还是恢复一下这几个的定义吧。
