### ISSUE TITLE
使用中文黑体时西文自动使用无衬线体

### ISSUE THREAD

**Issue by zhaiyusci** [CTeX-org/ctex-kit#471]
是否有办法在使用黑体（`\heiti`）的时候西文自动使用默认无衬线体？

小例子：

```LaTeX
\documentclass{ctexart}
\begin{document}
	{\heiti 中文里面的西文 ABC abc 123}
\end{document}
```

会看起来像这样：
![image](https://user-images.githubusercontent.com/3461548/70845263-55f8ac00-1e87-11ea-9715-7c21fcc1fc2f.png)

然而可能这样效果好些
![image](https://user-images.githubusercontent.com/3461548/70845284-7f193c80-1e87-11ea-8cee-4e6a1377ba38.png)

但我只会手动做，搜索文档和github里面好像也没有人提过如何自动实现。
这样的实现是可能的吗？

**Comment by zepinglee** [comment]
`\sffamily`

**Comment by stone-zeng** [comment]
\heiti 和 \sffamily 默认选择的字体其实不完全一样，\sffamily 在可能的情况下回用比较现代一点的无衬线体。
