### ISSUE TITLE
ctex：在和 amsmath 同用时报错“\dot allowed only in math mode”

### ISSUE THREAD

**Issue by CasperVector** [CTeX-org/ctex-kit#473]
（转发自[未名 BBS](https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&postid=21643730)）如题，示例代码改用 article 文档类编译可正常通过：
```latex
\documentclass{ctexart}
\usepackage{amsmath}
\begin{document}
	\begin{equation}\begin{split}
		a=\dot{b} \\ \dot{a}=b
	\end{split}\end{equation}
\end{document}
```

**Comment by RuixiZhang42** [comment]
在第二行行首 `\dot` 前加 `\relax`，这个跟 https://github.com/CTeX-org/ctex-kit/issues/470 重复了，先 close。
