### ISSUE TITLE
关于多行标题居中悬挂对齐在目录中的换行问题

### ISSUE THREAD

**Issue by lingr7** [CTeX-org/ctex-kit#475]
为了实现多行标题的居中悬挂对齐:
```tex
\usepackage{varwidth} %% 提供 varwidth 环境
\ctexset{
chapter/name = {第,回},
chapter/titleformat = \chaptertitleformat
}
\newcommand\chaptertitleformat[1]{%% 以标题内容为参数
\begin{varwidth}[t]{.7\linewidth}#1\end{varwidth}}
......
\chapter{情中情因情感妹妹\\错里错以错劝哥哥}
```
以上代码来自cetx.pdf（Texlive2019携带的文档）
正文效果挺好，回目我用`chapter/name = {\kaishu 第,回},`。
![红楼梦第一回](https://user-images.githubusercontent.com/37898999/71794772-f81e4500-307d-11ea-95a2-d20d9f7cae46.png)

`\@writefile{toc}{\contentsline {chapter}{\numberline {第一回\hspace  {.3em}}甄士隐梦幻识通灵\\贾雨村风尘怀闺秀}{3}{chapter.1}\protected@file@percent }`
在chapter01.aux文件中的`\\`换行符造成在正式目录中，也出现了一个换行效果。

![文档](https://user-images.githubusercontent.com/37898999/71794564-10419480-307d-11ea-95cd-7a95576842f3.png)
![目录换行了](https://user-images.githubusercontent.com/37898999/71794580-22233780-307d-11ea-90f4-807313425f45.png)
[红楼梦排版的github仓库地址](https://github.com/lingr7/HongLouMeng-ZhiPingBen)
想问一下是否有办法解决目录中也换行了这个问题。

**Comment by stone-zeng** [comment]
```tex
\documentclass{ctexbook}
% Fandol 缺字
% \setCJKmainfont{Source Han Serif TC}[ItalicFont=*]
\ctexset{
  chapter/name = {第, 回},
  chapter/titleformat = \chaptertitleformat
}
\newcommand\chaptertitleformat[1]{%
  \parbox[t]{8\ccwd}{#1}}

\begin{document}

\tableofcontents

\chapter{甄士隱夢幻識通靈\hspace{.5em}賈雨村風塵懷閨秀}
\chapter{賈夫人仙逝揚州城\hspace{.5em}冷子興演說榮國府}
\chapter{金陵城起複賈雨村\hspace{.5em}榮國府收養林黛玉}
\chapter{薄命女偏逢薄命郎\hspace{.5em}葫蘆僧亂判葫蘆案}
\chapter{開生面夢演紅樓夢\hspace{.5em}立新場情傳幻境情}
\chapter{賈寶玉初試雨雲情\hspace{.5em}劉姥姥一進榮國府}

\end{document}
```

目录：

![image](https://user-images.githubusercontent.com/18233088/71799840-56a0ee80-3091-11ea-8254-25837444da19.png)

章标题：

![image](https://user-images.githubusercontent.com/18233088/71799852-5ef92980-3091-11ea-9801-04149b298015.png)

页眉：

![image](https://user-images.githubusercontent.com/18233088/71799901-864ff680-3091-11ea-8c38-a1f5044d5de1.png)

手写 `\hspace` 比较暴力，但总之是能用的。觉得不好，也可以加点代码处理一下。

**Comment by lingr7** [comment]
![目录](https://user-images.githubusercontent.com/37898999/71803825-bc46a800-309c-11ea-83e1-e1ccd7cddae7.png)
目前是目录还是有点小问题，比如“目录”二字和章回标题对齐。

**Comment by Liam0205** [comment]
用 `\CTEXifname` 即可解决。

```tex
\documentclass{ctexbook}
\usepackage{geometry}
\geometry{showframe}
\ctexset{
  chapter = {
    format += \centering,
    name = {第,回},
    nameformat += \chapternameformat,
    titleformat = \chaptertitleformat
  }
}
\newcommand{\chapternameformat}[1]{\kaishu #1}
\newcommand{\chaptertitleformat}[1]{%
  \parbox[t]{8\ccwd}{\CTEXifname{\relax}{\centering}#1}}

\begin{document}

\tableofcontents

\chapter{甄士隱夢幻識通靈\hspace{.5em}賈雨村風塵懷閨秀}
\chapter{賈夫人仙逝揚州城\hspace{.5em}冷子興演說榮國府}
\chapter{金陵城起複賈雨村\hspace{.5em}榮國府收養林黛玉}
\chapter{薄命女偏逢薄命郎\hspace{.5em}葫蘆僧亂判葫蘆案}
\chapter{開生面夢演紅樓夢\hspace{.5em}立新場情傳幻境情}
\chapter{賈寶玉初試雨雲情\hspace{.5em}劉姥姥一進榮國府}

\end{document}
```
![image](https://user-images.githubusercontent.com/3348485/80118841-85e55800-85bb-11ea-8659-7c3f8319adff.png)
![image](https://user-images.githubusercontent.com/3348485/80119171-ec6a7600-85bb-11ea-9f10-0411f6386945.png)
