### ISSUE TITLE
ctex: 表 7，format 选项的默认配置中，scheme=plain 一列的信息不完整

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#477]
![image](https://user-images.githubusercontent.com/6376638/71909899-dfac4880-31ab-11ea-82af-4633f78ca313.png)
以 chapter 行和 "scheme = plain" 列对应单元格为例，目前是 `\raggedright`，应当是 `\huge\beseries\raggedright`

**Comment by stone-zeng** [comment]
`scheme =plain` 的时候，为了和 LaTeX 2e 保持一致，`nameformat` 和 `titleformat` 并不一样（`\huge` vs `\Huge`），所以没有合并。

**Comment by muzimuzhi** [comment]
> `scheme =plain` 的时候，为了和 LaTeX 2e 保持一致，`nameformat` 和 `titleformat` 并不一样（`\huge` vs `\Huge`），所以没有合并。

你说得对。我在文档和代码中都没能看出 `\huge` vs `\Huge` 的差异。

**Comment by Liam0205** [comment]
@muzimuzhi 我看了一下代码，这里应该没有问题才是。

以 OP 举例的 `chapter` 为例，目前的设定是这样的：

```tex
\keys_set:nn { ctex / chapter }
  {
    pagestyle   = plain ,
    aftertitle  = \par ,
    hang        = false ,
    beforeskip  = 50 \p@ ,
    afterskip   = 40 \p@ ,
    lofskip     = 10 \p@ ,
    lotskip     = 10 \p@ ,
    break       = \if@openright \cleardoublepage \else \clearpage \fi ,
    name        = \chaptername \space ,
    number      = \thechapter ,
    format      = \raggedright ,
    nameformat  = \huge \bfseries ,
    aftername   = \par \nobreak \vskip 20 \p@ ,
    titleformat = \Huge \bfseries ,
    afterindent = false ,
    tocline     = \CTEXnumberline {#1} #2
  }
```

所以这应该是一个 `wontfix` 的 issue？

**Comment by muzimuzhi** [comment]
当前文档和代码一致，文档没有问题，issue 标题中提到的问题不存在。

从「避免理解错误再次发生」的角度，可在展示 `format` 选项默认配置的表格添加脚注，说明「因 name 和 title 部分字号不同，标题 part 和 chapter 在 `scheme=plain` 下的字号和字族选项 `nameformat` 和 `titleformat` 内设定」。
