### ISSUE TITLE
xeCJK: 更新到 LaTeX 2020 后 BoldFont 等选项失效

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/ctex-kit#483]
最小示例：

```tex
% \RequirePackage[2019/10/01]{latexrelease}
\documentclass{article}
\usepackage[LoadFandol=false]{xeCJK}

\setCJKmainfont{FandolFang-Regular.otf}[
  BoldFont       = FandolHei-Regular.otf,
  ItalicFont     = FandolSong-Regular.otf,
  BoldItalicFont = FandolKai-Regular.otf,
]

\begin{document}
我们要\textit{强调}一下！\par
\textbf{我们要\textit{强调}一下！}
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/74043441-55ead780-4a04-11ea-992a-6355a5a39139.png)

用 `latexrelease` 回退到 2019/10/01 之后：

![image](https://user-images.githubusercontent.com/18233088/74043449-597e5e80-4a04-11ea-8d71-5b1bc3328c6a.png)

怀疑与 #482 有关。

**Comment by muzimuzhi** [comment]
> 怀疑与 #483 有关。

当前 issue 就是 483，是不是引用错了？

**Comment by leo-liu** [comment]
LuaTeX 支持有同样的问题。

**Comment by leo-liu** [comment]
xeCJK 和 ctex 的 LuaTeX 代码更新前，这里先给一个暂时可用的 quick fix:

```latex
\documentclass{ctexart}
% LaTeX 2020-02-02
% xeCJK 3.7.4

% 手动指定西文字体将使中文 BoldFont 选项有效
\setmainfont{Latin Modern Roman}% 注释该行后中文黑体失效

\begin{document}

宋体\textbf{黑体}

Normal \textbf{Bold}
\end{document}
```

**Comment by qinglee** [comment]
新版 NFSS 对 `\bfseries` 的定义作了变化：

```LaTeX
\DeclareRobustCommand\bfseries{%
  \not@math@alphabet\bfseries\mathbf
  \expand@font@defaults
  \fontseries{%
    \ifx\f@family\rmdef@ult      \bfseries@rm
    \else\ifx\f@family\sfdef@ult \bfseries@sf
    \else\ifx\f@family\ttdef@ult \bfseries@tt
    \else                        \bfdefault
    \fi\fi\fi
  }%
  \selectfont
}
```
其中 `\bfseries@rm` 的初始值是 `bx`，而 `\bfdefault` 的初始值是 `b`，这两者的值不一样导致了问题。

如果在导言区改变了西文字体，NFSS 会在文档开始时设置 `\bfseries@rm` 为 `b`，可以避免问题，这是 @leo-liu 上述办法有效的原因。
```LaTeX
\def\init@series@setup{%
  \ifx\bfseries@rm@kernel\bfseries@rm
    \expandafter\in@\expandafter{\rmdefault}{cmr,cmss,cmtt,lcmss,lcmtt,lmr,lmss,lmtt}%
    \ifin@ \else \def\bfseries@rm{b}\fi\fi
  \ifx\bfseries@sf@kernel\bfseries@sf
    \expandafter\in@\expandafter{\sfdefault}{cmr,cmss,cmtt,lcmss,lcmtt,lmr,lmss,lmtt}%
    \ifin@ \else \def\bfseries@sf{b}\fi\fi
  \ifx\bfseries@tt@kernel\bfseries@tt
    \expandafter\in@\expandafter{\ttdefault}{cmr,cmss,cmtt,lcmss,lcmtt,lmr,lmss,lmtt}%
    \ifin@ \else \def\bfseries@tt{b}\fi\fi

  \expand@font@defaults
  \ifx\famdef@ult\rmdef@ult      \rmfamily
  \else\ifx\famdef@ult\sfdef@ult \sffamily
  \else\ifx\famdef@ult\ttdef@ult \ttfamily
  \fi\fi\fi
}%
```

我们也可以强行设定 `\bfseries@rm` 为 `b`

```LaTeX
\DeclareFontSeriesDefault[rm]{bf}{\bfdefault}
```

**Comment by zoushucai** [comment]
> 最小示例：
> 
> ```
> % \RequirePackage[2019/10/01]{latexrelease}
> \documentclass{article}
> \usepackage[LoadFandol=false]{xeCJK}
> 
> \setCJKmainfont{FandolFang-Regular.otf}[
>   BoldFont       = FandolHei-Regular.otf,
>   ItalicFont     = FandolSong-Regular.otf,
>   BoldItalicFont = FandolKai-Regular.otf,
> ]
> 
> \begin{document}
> 我们要\textit{强调}一下！\par
> \textbf{我们要\textit{强调}一下！}
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/18233088/74043441-55ead780-4a04-11ea-992a-6355a5a39139.png)
> 
> 用 `latexrelease` 回退到 2019/10/01 之后：
> 
> ![image](https://user-images.githubusercontent.com/18233088/74043449-597e5e80-4a04-11ea-8d71-5b1bc3328c6a.png)
> 
> 怀疑与 #482 有关。

mactex 2020 更新以后，表示运行上面的最小实例在texstudio中不显示，但是pdf能够正常运行
