### ISSUE TITLE
Ctex中文字体字号与word的中文字体字号不一致

### ISSUE THREAD

**Issue by CSQ223** [CTeX-org/ctex-kit#485]
使用acrobat测量，发现如下命令的LaTeX生成的文档字体字号比word中的要小2pt，中文正文只有10pt。

\documentclass[a4paper, 12pt]{book}
\usepackage{ctex}

**Comment by muzimuzhi** [comment]
建议提供两个 PDF 文件，方便比较
 - 使用 latex 生成的 pdf
 - 使用 word 导出的 pdf

**Comment by CSQ223** [comment]
已经解决。
\documentclass[a4paper]{book}
\usepackage{zihao=-4}{ctex}
