### ISSUE TITLE
[xeCJK] v3.8.0 后，使用 \bfseries 时会在 FullRight 标点处出错

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#486]
例子
```tex
\documentclass{article}
\usepackage{xeCJK}

\begin{document}
\bfseries 测试。
\end{document}
```
第一条报错信息
```
! Missing number, treated as zero.
<to be read again> 
                   \c__xeCJK_xeCJK/FandolSong-Regular(0)/bx/n/10/quanjiao/di...
```

已做的尝试
 - 回退到 xecjk v3.7.4 （texlive revision 51298），报错消失
 - 去掉 `\bfseries`，报错消失
 - 把 `。` 替换为 FullRight 类的其他标点，如 `？）”`，报错维持不变
 - 恢复 `\bfseries` 的定义为
    ```tex
    \DeclareRobustCommand\bfseries
      {\not@math@alphabet\bfseries\mathbf
      \fontseries\bfdefault\selectfont}
    ```
    报错消失。应该和 https://github.com/CTeX-org/ctex-kit/issues/483#issuecomment-583756400 提到的「latex2e 2020-02-02 调整了 `\bfseries` 的定义」有关。

初次报告：https://wenda.latexstudio.net/q-1761.html

**Comment by qinglee** [comment]
我们在 CJK 分组内部修改了 `\f@series`，导致用于标记的 `\l_xeCJK_current_font_tl ` 前后不一致，导致宏没有正确保存。

 https://github.com/CTeX-org/forum/issues/95 也跟这个问题相关。
