### ISSUE TITLE
xeCJK: 切换字体编码到 T1 或 OT1 后，特定输入触发报错

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/ctex-kit#490]
```tex
\documentclass{article}
\usepackage[LoadFandol=false]{xeCJK}
\usepackage[T1]{fontenc} % OT1 同样触发

\begin{document}
（% 左侧圆括号，U+FF08
\end{document}
```

报错
```tex
! Cannot use \XeTeXglyphbounds with rm-lmr10; not a native platform font
```

触发条件
 * 不能定义 CJK main font
   * 去掉 `LoadFandol=false` 或使用 `\setCJKmainfont` 后问题消失
 * 特定输入
   * `字（` 触发报错 `! Missing \endcsname inserted.`
   * `字（）` 触发报错 `! Missing number, treated as zero.`
   * `字（）字` 和 `字（a` 不触发

引擎及宏包均为 texlive 2019 冻结中的最新版。

------

问题来源：用户报告，编译 https://www.latexstudio.net/index/details/index/mid/327.html 中的例子时报错
```tex
! Missing } inserted.
<inserted text> 
                }
l.58   \tcblower
```
首先把例子简化为
```tex
\documentclass{article}
\usepackage[LoadFandol=false]{xeCJK}
\usepackage{newtxtext}
\usepackage{tcolorbox}

\begin{document}
\begin{tcolorbox}{title}
字（
\end{tcolorbox}
\end{document}
```
后发现 `tcolorbox` 可去掉，触发问题的是 `newtxtext` 中的 `\usepackage[T1]{fontenc}`。简化过程中，报错信息有改变，不确定是否是同一处错误。

**Comment by zepinglee** [comment]
看来混用 `xetex` + `fontspec` 和 `newtx` 果然坑

**Comment by qinglee** [comment]
根源是 `\XeTeXglyphbounds` 不能用在传统的 `.tfm` 字体上，正常情况下中文总是要使用 truetype 等现代字体。

当字体是 `.tfm` 字体并且缺字符（`（`）时，`\XeTeXinterchartoks` 机制貌似有一些微妙的行为，这应该是后面的特定输入引发不同错误的原因。
