### ISSUE TITLE
[xeCJK] 同步 Extension G

### ISSUE THREAD

**Issue by RuixiZhang42** [CTeX-org/ctex-kit#494]
字体例如 [BabelStone Han](https://www.babelstone.co.uk/Fonts/Han.html)、[一点明体](https://github.com/ichitenfont/I.Ming)已经开始支持 Unicode&nbsp;13.0 追加的汉字了（部分支持），xeCJK 需要追加对 Extension&nbsp;G 的支持。

```latex
\documentclass{article}
\usepackage{xeCJK}
\newcommand*\ExtensionG{?\char"30EDD \char"30EDE \char"30F54 \char"3106C ?}
\begin{document}
\CJKfontspec{I.Ming}
Extension~A: \char"4DB6 ……\char"4DBF \par
URO: \char"9FF1 、\char"9FF3 ……\par
Extension~B: \char"2A6D7 ……\char"2A6DD \par
\ExtensionG

\fontspec{I.Ming}
\ExtensionG
\end{document}
```

![extg](https://user-images.githubusercontent.com/39968857/78512462-b1221780-7772-11ea-84fc-19464667be50.png)

**Comment by stone-zeng** [comment]
在 6c4319dcf1049d3a3050c3b77cc74c3364bbd6b3 中已经处理过了，还没有发布。@qinglee 要不要发一个新版本？

**Comment by qinglee** [comment]
等 TL 2020 正式发布后再发吧。

**Comment by Liam0205** [comment]
This has been fixed in 6c4319d, hence closing.
