### ISSUE TITLE
ctex: 考虑增强对于 heading 的配置接口

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#498]
这是我在实现下面的效果时想到的。

https://gist.github.com/Liam0205/803a512eb91e4d2b179c46bfb17d783f

![image](https://user-images.githubusercontent.com/3348485/79953608-b68b9b80-84ae-11ea-91ed-98a8510462a5.png)

目前，对于 `.../nameformat` 和 `.../titleformat`，CTeX 宏集都支持在使用一个单参命令来指定格式。借此，CTeX 宏集的 heading 接口已经十分强大，可以做各种花活。

不过，因为 `.../format` 暂不支持这种设定，以致若要将 name 和 title 放在一个不便打断的环境/命令中时（通常源于分组的套叠），就不得不做一些比较 tricky 的操作：

* 事实上禁用 `.../nameformat`；
* 而后在 `.../titleformat` 中，将 name/aftername/title 都输出；
* 在输出 aftername 的过程中，需要修改 `@` 的 catcode。

解决思路有几个，在我心里按顺序如下：

1. 让 `.../format` 也支持用单参命令来指定格式。
2. 仿照 `\CTEXthe...`，设计一套 `\CTEXcontent...` 的宏，将 name/aftername/title 都包在其中。
3. 仿照 `\CTEXthe...`，设计一套 `\CTEXaftername...` 和 `\CTEXtitle...` 的宏，将 aftername/title 分别放在其中。

**Comment by qinglee** [comment]
目前 `\section` 和 `\subsection` 等是可以这么用的，这是 LaTeX 内核原生支持的，参见 `source2e.pdf`。
![image](https://user-images.githubusercontent.com/1782251/79967966-1b042600-84c2-11ea-8324-72925672db77.png)

`\part` 和 `\chapter` 加上这个也应该可以。

**Comment by Liam0205** [comment]
> 目前 `\section` 和 `\subsection` 等是可以这么用的，这是 LaTeX 内核原生支持的，参见 `source2e.pdf`。
> ![image](https://user-images.githubusercontent.com/1782251/79967966-1b042600-84c2-11ea-8324-72925672db77.png)
> 
> `\part` 和 `\chapter` 加上这个也应该可以。

我还真没注意 `\section` 和 `\subsection` 的情况。
