### ISSUE TITLE
ctex: 设定 refname 时报错

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#501]
MWE:

```tex
\documentclass[UTF8, fontset = founder]{ctexart}  % also ctexbook/ctexrep
\ctexset{refname = {参了个考}}
\begin{document}
你好啊 \LaTeX{}。

Hello \LaTeX{}.

\begin{thebibliography}{3}
  \bibitem{key} 嘿嘿嘿
\end{thebibliography}
\end{document}
```

涉及代码：

https://github.com/CTeX-org/ctex-kit/blob/5270692259992dc64c42fc9a6fe921561a114ae0/ctex/ctex.dtx#L7146-L7167

当前文档描述：

![image](https://user-images.githubusercontent.com/3348485/80271445-c5629000-86f2-11ea-8cc2-f769fa0488f3.png)

我不太确定这么写的意图。是准备让 `refname` 只服务于 `ctexbeamer` 而让 `bibname` 服务于三个标准文档类吗？如果是的话就改改文档就行了。

@qinglee 看一下~

**Comment by qinglee** [comment]
在介绍 `refname` 之前，有说明“`此时，还有下列三个选项`”，意思就是说 `refname` 只在 beamer 中有定义。

标准文档类中，article 有 `\refname`，book 和 report 有 `\bibname`，我们可以只定义一个 `bibname` 选项用于统一设置。

beamer 有 `\refname` 和 `\bibname`，需要两个选项都定义。你可以把文档改得更明确一些。

**Comment by Liam0205** [comment]
ok
