### ISSUE TITLE
ctex: 关于 ctxdoc 和 ctxdocstrip

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#502]
这俩已经提到 `support` 里了，ctex 里写 `This package consists of the file  ctex.dtx, ctxdoc.cls, ctxdocstrip.tex,` 是不是不太合适了？@qinglee

**Comment by qinglee** [comment]
这俩文件到时候是跟 ctex 一起打包发布的，这么写没问题。

因为 ctex-kit 里的有其他包也依赖他们，放在 `support` 目录下比较合适。

**Comment by Liam0205** [comment]
ok

这样的话，bdcf6da74c015a777cd69a2d77583ebf39dcf961 之后，我这边没问题了。
