### ISSUE TITLE
xeCJK: 清理遗留代码时的疑问

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#503]
```tex
  \PushPreHook
    { math }
    { \int_gset_eq:NN \g__xeCJK_spacefactor_int \c_one_thousand }
```

清理遗留代码时发现这么一段代码。然后 `\g__xeCJK_spacefactor_int` 现在已经没有定义了。这个宏当年是做什么用的？现在替代的话，要怎么写……？

**Comment by qinglee** [comment]
现在得这么写：

```TeX
\int_gset:Nn \g__xeCJK_space_factor_int { 1000 }
```

`\g__xeCJK_space_factor_int` 保存 `\spacefactor`，用于实现 xCJKecglue 功能，目的是比较保险地将西文与中文之间的空格替换成 `\CJKecglue`。

但我简单看了一下，这个机制目前失效了，等我晚些时候再仔细排查。

**Comment by Liam0205** [comment]
合着我顺手还报了一个 bug。嘿嘿嘿~

**Comment by qinglee** [comment]
修复了，现在可以避免使用私有变量：

```LaTeX
\PushPreHook{math}{\xeCJK_reset_space_factor:}
```

**Comment by Liam0205** [comment]
> 修复了，现在可以避免使用私有变量：
> 
> ```
> \PushPreHook{math}{\xeCJK_reset_space_factor:}
> ```

赞~
