### ISSUE TITLE
ctex: 2.5 发版？

### ISSUE THREAD

**Issue by Liam0205** [CTeX-org/ctex-kit#504]
如题。

@qinglee @stone-zeng @zepinglee @RuixiZhang42

**Comment by Liam0205** [comment]
我先滋磁为敬。

**Comment by qinglee** [comment]
LuaTeX-ja 开发版那边内部代码有调整，对我们有影响的是 `luatexja.jfont.does_alt_set`

https://osdn.net/projects/luatex-ja/scm/git/luatexja/commits/cde2981db1536119901824da56b78766f122266d

我本想等他们发新版之后，我们再发，这样就不用对他们的版本进行新的分支判断了。

现在我打算在晚上把 `AlternateFont` 的语法改一下，然后明天五一统一发吧，选个好日子。

**Comment by qinglee** [comment]
已经都提交到 CTAN 上了。

**Comment by Liam0205** [comment]
辛苦辛苦~
