### ISSUE TITLE
ctex: 建议将 secnumdepth 的设置纳入 \ctexset

### ISSUE THREAD

**Issue by zeetex** [CTeX-org/ctex-kit#506]
目前 `secnumdepth` 这个计数器需要用 `\setcounter` 来设置。我想着既然 `\ctexset` 有完整的标题定制功能，不妨也将 `secnumdepth` 的设置也纳入其中。

**Comment by qinglee** [comment]
我记得当初有过这个想法，后来就一直遗忘了，还有 `tocdepth` 也可以纳入设置。

目标是 `secnumdepth` 和 `tocdepth` 选项的值可以是`-1`, `0` 等表示层次的整数，也可以是 `part`, `chapter` 等名称。
