### ISSUE TITLE
AutoFakeBold 错误的加粗了 eps 内的文本

### ISSUE THREAD

**Issue by sjx95** [CTeX-org/ctex-kit#509]
从 TeX Live 2019 Final 切换至 2020 并 Update 到最新（2020/05/11）后，发现 CTeX 的 AutoFakeBold 选项会把 eps 内的文本一起加粗，现象如下：
![image](https://user-images.githubusercontent.com/18415916/81651302-2a451680-9465-11ea-8543-2c8ed009a3e4.png)

而 TeX Live 2019 Final 可以正常加粗：
![image](https://user-images.githubusercontent.com/18415916/81652175-e999cd00-9465-11ea-91a7-ebc1f95bf230.png)

进一步测试发现此问题还存在于：
TeX Live 2018 Final (Debian 10 WSL repo)
TeX Live 2019 ISO (Windows, http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2019/texlive2019-20190410.iso)
TeX Live 2020 (Windows, tlnet-20200510)
但是 TeX Live 2019 Final (Windows, http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2019/tlnet-final/ ) 就没事，这就让人很郁闷了。现在我重新安装了 2019 Final，总算能继续改大论文了。

根据现象，由于第二个图显示正常，所以我猜测可能是 xeCJK 没有正确结束伪加粗？不知这一问题应当如何解决？

TeX：
```tex
\documentclass[AutoFakeBold]{ctexart}
\usepackage{graphicx}
\setCJKmainfont{SimSun}
\begin{document}

测\textbf{试}
\includegraphics[scale=0.5]{figure}

我\textbf{傻}了
\includegraphics[scale=0.5]{figure}

\textbf{这样不行}{}\relax
\includegraphics[scale=0.5]{figure}

\end{document}
```
测试样例：
[test-eps.zip](https://github.com/CTeX-org/ctex-kit/files/4614002/test-eps.zip)

**Comment by qinglee** [comment]
这是底层 dvipdfmx 驱动的问题，已经被报告过多次了，如本项目中的 #353, #362, #440

这个问题在 TeX Live 2019 中修复了，但是根据 @aminophen 在 https://github.com/pgf-tikz/pgf/issues/692#issuecomment-592883450 提供的信息：

> In [r53973](https://www.tug.org/svn/texlive?view=revision&revision=53973), dvipdfmx restored the previous behavior due to
> 
> * https://tug.org/pipermail/tex-live/2020-February/044855.html
> 
> so the fake-bold problem reappeared.

因为某些原因，TeX Live 2020 中的 dvipdfmx 恢复了之前的修改，导致这个问题又重现了。

总之，这个问题是由上游引起的，本项目无能为力。你可以报告给 [TeX Live](https://tug.org/mailman/listinfo/tex-live) 或 [dvipdfmx](https://tug.org/mailman/listinfo/dvipdfmx) 的邮件列表。

**Comment by muzimuzhi** [comment]
提供一个临时方案，思路是在插图命令前后添加 pdf literal，局部修改 text rendering mode (`0 Tr`)。（还有很少用的 optional star 没有兼顾，理论上可以通过 patch 某个内部宏来实现，先就这样吧。）

```tex
\makeatletter
\let\includegraphics@backup\includegraphics
\renewcommand\includegraphics[2][]{%
  \special{pdf:code q 0 Tr}%
  \includegraphics@backup[#1]{#2}%
  \special{pdf:code Q}%
}
\makeatother
```

效果测试

```tex
% 故意设置很大的 AutoFakeBold，突出效果
\documentclass[AutoFakeBold=10]{ctexart}
\usepackage{graphicx}
% 使用某个没有粗体的字体，macOS 可以用 STSong
\setCJKmainfont{SimSun}

\begin{document}

% 使用 mwe 宏包提供的 eps 文件
默认效果测\textbf{试}
\includegraphics[scale=0.5]{example-image.eps}

\makeatletter
\let\includegraphics@backup\includegraphics
\renewcommand\includegraphics[2][]{%
  \special{pdf:code q 0 Tr}%
  \includegraphics@backup[#1]{#2}%
  \special{pdf:code Q}%
}
\makeatother

临时方案效果测\textbf{试}
\includegraphics[scale=0.5]{example-image.eps}

\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/81724094-62c11080-94b6-11ea-8d14-1418bebab551.png)

 - 参考资料：[PDF Reference, v1.7](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf), Table 5.1 _Text state parameters_, Table 5.3 _Text rendering modes_
 - 相关阅读：知乎文章《[[xetex] 通过 PDF literal 实现文字伪粗](https://zhuanlan.zhihu.com/p/60262200)》

**Comment by sjx95** [comment]
很抱歉没有仔细搜索历史 issue，并十分感谢两位前辈提供的信息。
由于我已经把 TL2020 换成了 TL2019 Final，在论文完稿前应该暂时不会去折腾了，等后面结题了再仔细研究一下。

**Comment by inbzab123** [comment]
你可以改变eps文件的文字为通道，这样就不会被加粗了，Inkscape，可以导出为文字通道格式的eps文件
