### ISSUE TITLE
使用parskip包会导致段落自动缩进无效

### ISSUE THREAD

**Issue by zwz** [CTeX-org/ctex-kit#512]
以下是MWE：
```
\documentclass{ctexbook}
\usepackage{parskip}               % 去掉这个就可以看到有缩进
\begin{document}
\chapter{绪论}
这是测试段落，应该自动缩进。这是测试段落，应该自动缩进。这是测试段落，应该自动缩进。这是测试段落，应该自动缩进。
\end{document}
```

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/82745128-4628b080-9db3-11ea-9b6b-6490931e1e33.png)
`parskip` 是取消段落缩进，而使用加大的段间距来分段的
详情请参照《西文排版》［日］高冈昌生

**Comment by qinglee** [comment]
parskip 默认取消段首缩进，用段间距取代段首缩进来分隔段落是西文排版的一种风格。

当然你也可以使用 `\usepackage[indent]{parskip}` 强制恢复段首缩进。

同时要注意，这时应该设置 `section/fixskip` 等选项为 `true`。
