### ISSUE TITLE
Is there a way to suppress warning "Redefining CJKfamily `\CJKrmdefault' (SimSun(0))."?

### ISSUE THREAD

**Issue by FrankSFLYS** [CTeX-org/ctex-kit#514]
I'm using TeXLive 2019. Is there a way to suppress the warning
```
Redefining CJKfamily `\CJKrmdefault' (SimSun(0)).
```
It is harmless but it is a warning.

**Comment by FrankSFLYS** [comment]
I tried the `silence` package but it didn't work.

**Comment by qinglee** [comment]
调用 ctexart 等文档类时设置 `fontset` 为 `none` 。
