### ISSUE TITLE
pdflatex: ctex 2.5.2, 空白行开始一段

### ISSUE THREAD

**Issue by tpu01yzx** [CTeX-org/ctex-kit#518]
由于我不希望将所有的tex文件转换成UTF8，所以保持GBK格式。这导致我只能用pdflatex编译如下代码：
```
\documentclass[GBK]{ctexbook}
\begin{document}
这里是第一段。

这里是第二段。
\end{document}
```
本机运行环境：(ctex package 2.5.2, MikTex 2.9.7429, OS:Windows 10 64bit version 2004, Compile with pdfLaTex）
错误输出为：（空白行没有产生一个新的段落）
![bad](https://user-images.githubusercontent.com/17909519/83940772-1ea4ff80-a819-11ea-8b58-ab5736297bb0.jpg)

期待输出为：(ctex package 2.4.16, MikTex 2.9.7206, OS:Windows 10 64bit version 1903, Compile with pdfLaTex)
![good](https://user-images.githubusercontent.com/17909519/83940776-22388680-a819-11ea-9d87-edb523176feb.jpg)

**Comment by qinglee** [comment]
原因是 `\endlinechar` 被设置为 `-1`, 导致不能分段。

根源是 `\ctex_file_wrapper:nnn` 没写对，这个问题以前的版本也有，只是阴差阳错没有暴露出来。

**Comment by tpu01yzx** [comment]
我可以等到2.5.3版本正式发布之后再更新MikTex的ctex包。但除了git clone & make之外,  有一个快捷的应急解决方案吗？谢谢。

**Comment by qinglee** [comment]
应急的解决方法是在 `\documentclass` 之后设置 `\endlinechar=13\relax` 。

我马上发一个新版本吧。
