### ISSUE TITLE
Cannot output CJK chars in toc with Polyglossia

### ISSUE THREAD

**Issue by cykerway** [CTeX-org/ctex-kit#519]
```latex
\documentclass[11pt]{book}
\usepackage{polyglossia}
\usepackage{xeCJK}
\setdefaultlanguage{english}
\setotherlanguage{french}
\setmainfont{Noto Serif}
\setCJKmainfont{Noto Serif CJK SC}
\title{xeCJK and Polyglossia}
\author{}
\date{}
\begin{document}
\tableofcontents
\section{中文}
\section{English}
\begin{english}
\end{english}
\section{中文}
\section{French}
\begin{french}
\end{french}
\section{中文}
\section{中文}
\section{中文}
\end{document}
```

![j](https://user-images.githubusercontent.com/392675/84074568-58d2f480-aa05-11ea-81c6-6b359ba7fd3e.jpg)

Can be "fixed" by using a CJK font in `\setmainfont`. But this overwrites the default latin font.

**Comment by cykerway** [comment]
BTW I understand *xeCJK is NOT supposed to be used together with polyglossia*. But this bug doesn't seem related with `\XeTeXinterchartoks`. It looks like a font switch problem. So I think it's probably not very difficult to fix.

**Comment by cykerway** [comment]
The same bug can also be produced with `\begin{otherlanguage}`, which is more or less:

```latex
\begingroup
\selectlanguage{<inner-language>}
...
\endgroup
\selectlanguage{<outer-language>}
```

But an additional grouping doesn't fix it. My current workaround is to use `\begin{otherlanguage*}` instead.

**Comment by zepinglee** [comment]
The result cannot be reproduced.

```
TeX Live 2020
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-03>
polyglossia 2020/04/08 v1.49
xeCJK 2020/06/06 v3.8.4
```

**Comment by cykerway** [comment]
Great. I can't reproduce either with `polyglossia==1.49`. Close it for now.
