### ISSUE TITLE
ctex, hyperref, cleveref 宏包冲突

### ISSUE THREAD

**Issue by kexplorning** [CTeX-org/ctex-kit#524]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux: WSL Ubuntu

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage{hyperref}
\usepackage{cleveref}

\begin{document}

\section{}
\label{sec}
\cref{sec}

\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
9: Extra \endcsname.
<recently read> \endcsname 
                           
l.9 \cref{sec}
```

有警告

```latex
Package ctex Warning: Oops! Command `\refstepcounter@noarg' is NOT patchable.
(ctex)                

Package ctex Warning: Oops! Command `\refstepcounter@optarg' is NOT patchable.
(ctex)
```

## 尝试

1. 去掉 `hyperref` 宏包编译一切正常。
2. 如果忽略问题继续编译会得到 `section 1thesection`，貌似中间再次插入了 `\thesection` 相关命令
3. 可能与最近 ctex 宏包更新了 cleveref 兼容性代码有关
4. （猜测）ctex 最近的补丁不兼容加了 `hyperref` 的 cleveref

**Comment by stone-zeng** [comment]
`cleveref` 在载入 `hyperref` 之后会做一些别的处理，也需要 patch 一下。

**Comment by zwz** [comment]
我发现现在即使没有使用hyperref
```
\documentclass{ctexart}
\usepackage{cleveref}

\begin{document}

\section{}
\label{sec}
\cref{sec}

\end{document}
```
还是会报同样的错误

**Comment by stone-zeng** [comment]
修改代码之后重新编译，可能需要删除辅助文件。下面的警告是说没有生成引用，只要再编译一遍就可以了。

推荐使用 `latexmk`。

**Comment by Liam0205** [comment]
@stone-zeng LaTeXmk 真香。

**Comment by zwz** [comment]
@stone-zeng 我使用的就是latexmk哦

这个警告应该是第一次编译的时候产生的
但是后面就会报同样的**错误**
```
! Extra \endcsname.
<recently read> \endcsname 
                           
l.8 \cref{sec}
```

**Comment by stone-zeng** [comment]
```tex
\documentclass{ctexart}
\usepackage{hyperref,cleveref}

\begin{document}

\section{}
\label{sec}
\cref{sec}

\end{document}
```

上面的代码编译一次，会得到这样的 `.aux` 文件：

```tex
\relax 
\providecommand\hyper@newdestlabel[2]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\global\let\oldcontentsline\contentsline
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\global\let\oldnewlabel\newlabel
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\fi}
\fi}
\global\let\hyper@last\relax 
\gdef\HyperFirstAtBeginDocument#1{#1}
\providecommand*\HyPL@Entry[1]{}
\HyPL@Entry{0<</S/D>>}
\@writefile{toc}{\contentsline {section}{\numberline {1}}{1}{section.1}\protected@file@percent }
\newlabel{sec}{{1}{1}{}{section.1}{}}
\newlabel{sec@cref}{{[section][1][]1thesection\endcsname }{[1][1][]1}}
```

注意到最后一行有一个多余的 `\endcsname`，所以第二次编译读取 `.aux` 文件之后，就会报错。即使在第二次编译中把 `hyperref` 删掉，只要`.aux` 文件没有动，那么仍然是会报错的。

**Comment by zwz** [comment]
首先感谢你的说明
但是我确实都是清理掉辅助文件后，只有tex文件下使用latexmk进行编译的

看起来你这边似乎不会出错
我这边使用的是archlinux，texlive是从pacman直接安装的，都是上面最新的版本

**Comment by sunmy2019** [comment]
latexmk 在没有 aux 的情况下会多次调用 xelatex 编译。
你以为编译了一次，实际上是好几次

**Comment by zwz** [comment]
@sunmy2019 我知道是好几次

**Comment by stone-zeng** [comment]
那就把 `.tex`文件和每一次的编译日志打个包传上来吧

**Comment by zwz** [comment]
每一次的编译日志？
我只有的最终的log文件
[test-doc.zip](https://github.com/CTeX-org/ctex-kit/files/4823608/test-doc.zip)

**Comment by stone-zeng** [comment]
你用的还是 2.5.2 的 `ctex` 宏包，请更新到 2.5.3。

**Comment by zwz** [comment]
因为Archlinux下的包都交给pacman来管理了
所以我就直接换到另一台机器，然后ctex宏包也更新到2.5.3了
但是还是会报这个错哦
[test.zip](https://github.com/CTeX-org/ctex-kit/files/4842450/test.zip)

**Comment by OsbertWang** [comment]
我在 Win 和 WSL 里都试了，确实报错。

**Comment by muzimuzhi** [comment]
> 因为Archlinux下的包都交给pacman来管理了
> 所以我就直接换到另一台机器，然后ctex宏包也更新到2.5.3了
> 但是还是会报这个错哦
> [test.zip](https://github.com/CTeX-org/ctex-kit/files/4842450/test.zip)

@zwz 
 - ctex 2.5.3，编译仅使用 cleveref 的例子 https://github.com/CTeX-org/ctex-kit/issues/524#issuecomment-647210902 ，是不报错的。
 - 你 zip 里的，是同时使用 cleveref 和 hyperref 的例子。让 ctex 同时兼容两者的提交 https://github.com/CTeX-org/ctex-kit/commit/e7d63843c155c80067f6b294632562fb1b9c4832，只是提交到了代码仓库，**没有发布**。在发布之前，你无法通过更新包来修复问题。

PS：也许要向 https://github.com/latex3/latex2e 学习，用 label 区分「已提交到仓库但尚未发布」和「已经发布」两个状态。

**Comment by zwz** [comment]
@muzimuzhi 
是的，不使用 hyperref 确实没有问题
期待2.5.4

**Comment by etclub** [comment]
我用的texlive2014，ctex v2.5.10
```
\documentclass{ctexart}
\usepackage{hyperref,cleveref}

\begin{document}

\section{}
\label{sec}
\cref{sec}

\end{document}
```
这个又会报错
aux文件是这样的
```
\relax
\providecommand\hyper@newdestlabel[2]{}
\providecommand*\HyPL@Entry[1]{}
\HyPL@Entry{0<</S/D>>}
\@writefile{toc}{\contentsline {section}{\numberline {1}}{1}{section.1}\protected@file@percent }
\newlabel{sec}{{1}{1}{}{section.1}{}}
\newlabel{sec@cref}{{[section][1][]1thesection\endcsname }{[1][1][]1}{}{}{}}
\gdef \@abspage@last{1}
```

**Comment by atxy-blip** [comment]
> @etclub 我用的texlive2014，ctex v2.5.10

合理怀疑是 TeX Live 2024。

请避免在已经解决的 issue 下提出新的问题。即使看起来有关联，在新版本遇到的问题也应当另开帖。况且你已经发现了，这个正好是 #725 尝试解决的。我们不妨去那边讨论。
