### ISSUE TITLE
xeCJK inserts extra spaces in listings environment

### ISSUE THREAD

**Issue by cykerway** [CTeX-org/ctex-kit#526]
The problem is exactly as posted here: https://tex.stackexchange.com/a/178708/4288

~~~ tex
\documentclass{article}

\usepackage{xcolor}
\usepackage{listings}
\lstset{commentstyle=\color{blue},morecomment=[l]{//}}

\usepackage{xeCJK}
\setCJKmainfont{FandolSong-Regular.otf}

\begin{document}

\section{Success}
\begin{lstlisting}
// tomorrow明天
\end{lstlisting}

\end{document}
~~~

The package shouldn't introduce extra spaces in code block, otherwise when users copy-paste the code they may get incorrect result. For example: `print("一二三")` is not the same as `print("一 二 三")`.

**Comment by cykerway** [comment]
Adding `columns=fullflexible` in `\lstset` fixed this problem. Probably a bug in `listings` not `xeCJK`.

**Comment by muzimuzhi** [comment]
1. `listings` decides to set `columns=[c]fixed` by default. This is not a bug. 
See https://github.com/CTeX-org/forum/issues/7 and [this question on TeX.SX](https://tex.stackexchange.com/q/200153).
1. There is no guarantee that TeX can produce what-you-copied-is-what-you-see PDF, especially for spaces (or more generally horizontal skips between characters), font encodings issues (try to copy text containing `⟨...⟩` from `listings.pdf`), and xetex's codepoint degeneration (see #286). Also, PDF readers may behave differently when copying from the same PDF, see #400.
