### ISSUE TITLE
xeCJK: 文档的高亮部分标点符号出现重叠

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/ctex-kit#541]
对应的代码为
https://github.com/CTeX-org/ctex-kit/blob/c677c21ebb80fc068f3d636ca7f1d4018ee012ee/xeCJK/xeCJK.dtx#L1407-L1411
效果为
![](https://user-images.githubusercontent.com/49770925/93672121-052f7700-fadb-11ea-9864-12ed1ad778f2.png)

**Comment by stone-zeng** [comment]
See #308

**Comment by sikouhjw** [comment]
> 
> 
> See #308

我没懂，是不同字体的逗号位置问题吗……用 `fandol` 就没这问题
