### ISSUE TITLE
ctex: 使用\ctexset{fontset=fandol}后编译出错

### ISSUE THREAD

**Issue by YijunYuan** [CTeX-org/ctex-kit#544]
环境：WSL2
Toolchain：TexLive 2020

先上代码：
```
\documentclass[fontset=none]{ctexbook}
\ctexset{fontset=fandol}

\usepackage{amssymb}
\newcommand{\bbC}{\mathbb{C}}

\begin{document}
$\bbC_p$
\end{document}
```
报错如下：
>Undefined control sequence.
>\<recently read\> \bbC_p 

以下可以成功编译但是效果是不对的（下划线）：

- `${\bbC}_p$`
- `$\mathbb{C}_p$`

但如果改成
```
\documentclass[fontset=fandol]{ctexbook}

\usepackage{amssymb}
\newcommand{\bbC}{\mathbb{C}}

\begin{document}
$\bbC_p$
\end{document}
```
就没问题。

临时的解决方案是将`\ctexset{fontset=fandol}`放到`\usepackage{amssymb}`后面，但当调用宏包较多的时候这对debug也会产生不小的麻烦。

**Comment by sunmy2019** [comment]
用第一种方法无论如何都会被 amssyb 改掉字体，如果你强行要用第一种方法，应该试图修改 amssyb 宏包，而不是 ctex 宏包
