### ISSUE TITLE
mactex 不显示字体

### ISSUE THREAD

**Issue by zoushucai** [CTeX-org/ctex-kit#545]
```
\documentclass{article}
\usepackage[LoadFandol=false]{xeCJK}

\setCJKmainfont{FandolFang-Regular.otf}[
BoldFont       = FandolHei-Regular.otf,
ItalicFont     = FandolSong-Regular.otf,
BoldItalicFont = FandolKai-Regular.otf,
]

\begin{document}
	我们要\textit{强调}一下！\par
	\textbf{我们要\textit{强调}一下！}
\end{document}

```
字体链接：
[FandolFang-Regular](https://gitee.com/zscqsmy/blogimg/raw/master/uPic/2020101817FandolFang-Regular.otf)

[FandolHei-Regular](https://gitee.com/zscqsmy/blogimg/raw/master/uPic/2020101817FandolHei-Regular.otf)

[FandolKai-Regular](https://gitee.com/zscqsmy/blogimg/raw/master/uPic/2020101817FandolKai-Regular.otf)

[FandolSong-Regular](https://gitee.com/zscqsmy/blogimg/raw/master/uPic/2020101817FandolSong-Regular.otf)

尝试运行上面代码（字体已放到当前目录中）， mactex 2020+  texstudio 不能正确显示中文， 但是编译正常运行，且可以显示字体。 overleaf测试没有问题
请问，则是什么原因？
![QQ20201018-151228](https://user-images.githubusercontent.com/15843338/96360977-60916b00-1154-11eb-9e4f-ea236925c3c9.png)

**Comment by zepinglee** [comment]
无法复现

**Comment by zoushucai** [comment]
@zepinglee  已更新字体链接，您把前面的日期去掉即可。谢谢

**Comment by muzimuzhi** [comment]
这是 texstudio 在 macOS 下的问题，在命令行下依次执行
```tex
brew install poppler # 需要安装 homebrew
ln -s /usr/local/Cellar/poppler/20.* /usr/local/Cellar/poppler/0.84.0-texworks
```
然后重启 texsdutio，问题解决。

更多信息，见《[一个texstudio的小问题：文字无法显示](https://zhuanlan.zhihu.com/p/80728204)》。
