### ISSUE TITLE
开启伪粗后，当\textbf命令后紧跟tikzpicture环境会造成图片中及此后所有文本都被加粗

### ISSUE THREAD

**Issue by MrLmath** [CTeX-org/ctex-kit#546]
开启伪粗后，当\textbf命令后紧跟tikzpicture环境会造成图片中的文本及此后所有文本都被加粗
### 最小示例代码
```LaTex
\documentclass{ctexart}
\newCJKfontfamily\st{SimSun}[AutoFakeBold]
\usepackage{tikz}
\begin{document}
\textbf{\st 测试}
\begin{tikzpicture}
	\draw (0,0) node [left] {$A$} --(1,0) node [right] {$A$};
\end{tikzpicture}
\end{document}
```
![Snipaste_2020-10-19_01-34-42](https://user-images.githubusercontent.com/35299384/96375532-1d62e680-11ac-11eb-9890-f529f4c24c82.png)

**Comment by muzimuzhi** [comment]
和 ctex 无关，是 dvipdfmx 的问题。相关小结见 https://github.com/CTeX-org/ctex-kit/issues/509#issuecomment-627260331

从生成的 PDF 看，实际是 text rendering mode (pdf 运算符 `Tr`) 的作用范围溢出。从现象上看，就是 
 - tikz node text 的轮廓线本不应绘制，现在被以 tikz/pgf 的默认线宽 `0.4pt` 绘制了；
 - 伪粗的程度，不影响错误加粗文字的加粗程度。

https://github.com/CTeX-org/ctex-kit/issues/509#issuecomment-627475541 提供了一种临时方案（保护下方内容不被加粗），下面的 `\markLocalGraphicsState` 提供另一种方案（限制伪粗的作用范围），可以把它 patch 进 `\textbf`，这样自动一些。

```tex
\documentclass{ctexart}
\newCJKfontfamily\st{FandolSong}[AutoFakeBold]
\usepackage{tikz}

\newcommand\markLocalGraphicsState[1]{%
  \special{pdf:code q}%
  #1%
  \special{pdf:code Q}%
}

\begin{document}
\markLocalGraphicsState{\textbf{\st 测试}}
\begin{tikzpicture}
	\draw (0,0) node [left] {$A$} --(1,0) node [right] {$A$};
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/96388019-bc9dd300-11d8-11eb-9021-a02d0d7403a5.png)

**Comment by MrLmath** [comment]
用您的方案完美解决了问题，感谢，我应该先搜索下同类问题的。
