### ISSUE TITLE
Mac上标题字体Songti SC的字重为什么是 Black

### ISSUE THREAD

**Issue by UniverseFly** [CTeX-org/ctex-kit#548]
在`*macnew.def`文件的定义里，`BoldFont`应该是`Songti SC Bold`，但是显示出来却是Black：
<img width="877" alt="image" src="https://user-images.githubusercontent.com/46997596/97864242-3b4f5000-1d43-11eb-8b1a-cdb09b2b631e.png">

代码：

```tex
\documentclass{ctexart}
\begin{document}
\section{你好世界}
你好
\end{document}
```

如果添加了`fontset=mac`又会恢复正常：
<img width="877" alt="image" src="https://user-images.githubusercontent.com/46997596/97864399-7ea9be80-1d43-11eb-9674-97b8905230f8.png">

代码：

```tex
\documentclass[fontset=mac]{ctexart}
\begin{document}
\section{你好世界}
你好
\end{document}
```

这是为什么？？是bug么？

**Comment by sikouhjw** [comment]
额，检查一下你的 CTeX 宏集版本，估计是你没更新

**Comment by UniverseFly** [comment]
> 额，检查一下你的 CTeX 宏集版本，估计是你没更新

应该不是这个问题，我装的是MacTeX2020，对应的ctex是2019，macnew在很早之前就有过相关issue

**Comment by sikouhjw** [comment]
> > 额，检查一下你的 CTeX 宏集版本，估计是你没更新
> 
> 应该不是这个问题，我装的是MacTeX2020，对应的ctex是2019，macnew在很早之前就有过相关issue

所以升级全部宏包啊……texlive 2020 更新时，CTeX 宏集还没更新，所以升级再看

**Comment by UniverseFly** [comment]
> > > 额，检查一下你的 CTeX 宏集版本，估计是你没更新
> > 
> > 
> > 应该不是这个问题，我装的是MacTeX2020，对应的ctex是2019，macnew在很早之前就有过相关issue
> 
> 所以升级全部宏包啊……texlive 2020 更新时，CTeX 宏集还没更新，所以升级再看

啊，是我妄下结论了。确实是版本问题）Close 了
