### ISSUE TITLE
加载ctex包会更改矩阵的行列间距

### ISSUE THREAD

**Issue by yuxtech** [CTeX-org/ctex-kit#549]
`mwe`如下
```
\documentclass{article}
\usepackage{amsmath}
%\usepackage{ctex}
\begin{document}
%\arraycolsep 1cm
\[
  \begin{vmatrix}
    0 & 0 & 0 \\
    0 & 0 & 0 \\
    0 & 0 & 0
  \end{vmatrix}
\]

\end{document}
```
如果加载ctex包，可以看到矩阵被明显放大了

**Comment by sikouhjw** [comment]
`texdoc zhlineskip`

**Comment by yuxtech** [comment]
> `texdoc zhlineskip`

Ok，找到了

**Comment by muzimuzhi** [comment]
- `ctex` 宏包（和相关文档类）默认使用 `scheme=chinese`，此时会全局设置 `linespread=1.3`，这个多倍行距的设置对公式也生效，所以会有 issue 里提到的问题。
 - `zhlineskip` 提供了「在公式、脚注等部分恢复默认行距」的功能，所以能帮助解决/避免提到的问题。

**Comment by yuxtech** [comment]
> * `ctex` 宏包（和相关文档类）默认使用 `scheme=chinese`，此时会全局设置 `linespread=1.3`，这个多倍行距的设置对公式也生效，所以会有 issue 里提到的问题。
> * `zhlineskip` 提供了「在公式、脚注等部分恢复默认行距」的功能，所以能帮助解决/避免提到的问题。

谢谢，通过`zhlineskip`文档的说明知道了
