### ISSUE TITLE
怎么编译ctex模块为latex工作

### ISSUE THREAD

**Issue by love01211** [CTeX-org/ctex-kit#551]
环境：centos7
latex版本：pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)
模块文件树：
ctex
├── ctex.dtx
├── ctex.pdf
├── ctexpunct.spa
├── ctex-zhconv.lua
├── ctex-zhconv-make.lua
├── ctxdoc.cls
├── ctxdocstrip.tex
└── README.md

**Comment by love01211** [comment]
好了，我是用xeCJK代替这个了模块

**Comment by zepinglee** [comment]
1. TeX Live 2013 的版本实在太旧了，建议安装最新版的 TeX Live。
2. `ctex` 宏包的内容是解释执行的，不编译；TeX live 中已经将 `ctex` 的文件 unpack，直接调用即可。具体 unpack 的过程参考 `l3build` 和 `ctex/build.lua`。
3. `xeCJK` 和 `ctex` 处理的是不同层次的东西，具体的内容参考各自的文档（用 `texdoc` 调出）。
