### ISSUE TITLE
l3kernel 12.03

### ISSUE THREAD

**Issue by Choticode** [CTeX-org/ctex-kit#552]
![image](https://user-images.githubusercontent.com/44939213/101279864-590b4b80-3800-11eb-8530-caf318d742df.png)

tlmgr update --self --all 后出现这个问题。
是还未适配 l3kernel 12.03 的更新么？

**Comment by stone-zeng** [comment]
各引擎下均没有复现问题，请检查 TeX 发行版的安装（比如更新后格式文件的重新生成，如果失败可以用 `fmtutil` 手动处理）。

**Comment by Choticode** [comment]
抱歉，忘了说明运行的环境，引擎是xe。已经查明是我个人的问题，包更新后似乎只是更新了系统级别的格式文件（或没有更新），但当前用户目录下的并未更新，导致了上述问题（默认使用的似乎是当前用户目录下的），使用`fmtutil-sys`命令后解决了上面的问题。

谢谢您啊，我个人问题给您带来了不必要的工作。

（ps: 可能是我安装姿势不对，可能是环境变量没有link好，现在需要自己手动处理用户目录下的格式文件了）
