### ISSUE TITLE
ctex对更新后的fancyhdr宏包v4.0补丁失效

### ISSUE THREAD

**Issue by wrfwerrr** [CTeX-org/ctex-kit#554]
\documentclass{book}
\usepackage[heading=true]{ctex}
\usepackage{fancyhdr}
\begin{document}
aaa
\end{document} 

对 ps@fancy 的修补失效，产生警告 Package ctex Warning: Oops! Command `\ps@fancy' is NOT patchable.
(ctex) 。

**Comment by xiaozhongguo** [comment]
使用tlmgr更新的，可暂时从backup里面恢复到fancyhdr v3.10，等待ctex更新

一个临时补救的方法，在使用相应ctex宏包时，去相应的源文件搜索"\ctex_patch_cmd:Nnn \ps@fancy"，替换成”\ctex_patch_cmd:Nnn \f@nch@initialise“，例如，使用ctexbook类，应该修改%TEXLIVE%\texmf-dist\tex\latex\ctex下的ctexbook.cls文件

**Comment by Coder-zhangwei** [comment]
按照这个方法：“还有一个临时补救的方法，在使用相应ctex宏包时，去相应的源文件搜索"\ctex_patch_cmd:Nnn \ps@fancy"，替换成”\ctex_patch_cmd:Nnn \f@nch@initialise“，例如，使用ctexbook类，应该修改%TEXLIVE%\texmf-dist\tex\latex\ctex下的ctexbook.cls文件”，修改了 还是不好使呀？请问还有其他解决办法吗？谢谢

**Comment by zepinglee** [comment]
我已经初步写好了一个 patch，但是 `fancyhdr` 的代码还有些问题，见 <https://github.com/pietvo/fancyhdr/issues/5>。等那边修好了再改吧。
