### ISSUE TITLE
ctex：依赖的 everysel 宏包被标为 obsolete

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/ctex-kit#555]
目前 `ctex` 宏集依赖的 [`everysel`](https://ctan.org/pkg/everysel) 自 2021-01-20 v2.0 开始从 [`ms`](https://ctan.org/pkg/ms) 宏集中移出，而且被标为 obsolete。其提供的钩子功能被 `lthooks` 代替。

应该需要更新一下。

**Comment by muzimuzhi** [comment]
`everysel` 单独上传了，texlive（见 [r57472](http://www.tug.org/svn/texlive?view=revision&revision=57472)）和 miktex 应该都会继续提供它，不会因为标记为 obsolete 而无法安装。

ctex-kit 这边的适配工作不紧急。

**Comment by zepinglee** [comment]
嗯，确实不急。而且这一段看着也复杂。
https://github.com/CTeX-org/ctex-kit/blob/43ad4fd950e1e6da2c90e3112e321f897661b609/ctex/ctex.dtx#L6763-L6768
