### ISSUE TITLE
xeCJK: 使用 \fontsize 后，即使不使用 \selectfont，对中文字体大小的改变仍会生效

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/ctex-kit#558]
MWE
```LaTeX
\documentclass{book}
\usepackage{xeCJK}
\begin{document}
\fontsize{48pt}{72pt}foo
\fontsize{36pt}{72pt}bar

\fontsize{48pt}{72pt}中文
\fontsize{36pt}{72pt}测试

\end{document}
```

![image](https://user-images.githubusercontent.com/34062491/107326409-5110a600-6ae6-11eb-87e0-a20aefce48a9.png)

**Comment by muzimuzhi** [comment]
切换到中文字体时，会隐性调用 `\selectfont`

**Comment by tanukihee** [comment]
> 切换到中文字体时，会隐性调用 `\selectfont`

但是只有字体大小改变了，行距并未改变

**Comment by muzimuzhi** [comment]
可能是这里的事
https://github.com/CTeX-org/ctex-kit/blob/43ad4fd950e1e6da2c90e3112e321f897661b609/xeCJK/xeCJK.dtx#L6754-L6766

避免例子里的那种用法吧。
