### ISSUE TITLE
xecjk with docmute

### ISSUE THREAD

**Issue by naba-nyan** [CTeX-org/ctex-kit#560]
Hi, I am a Japanese user of xecjk package in XeLaTeX with docmute for multi tex files.
Recently, I noticed that xecjk with docmute does not work fine and cannot genrenate a PDF.
Simply, xecjk without docmute works fine.

docmute : v.1.4
xecjk : v.3.8.6

For example, the file structure is

.
├── main.tex
└── subfile.tex

and sample files are below.

------------------------------

main.tex:
\documentclass{amsart}

\usepackage{xeCJK}
\setCJKmainfont{ipaexm.ttf}
\setCJKsansfont{ipaexg.ttf}
\setCJKmonofont{ipaexg.ttf}

\usepackage{docmute}

\begin{document}

\input{subfile}

\end{document}

subfile.tex:
\documentclass{amsart}

\usepackage{xeCJK}
\setCJKmainfont{ipaexm.ttf}
\setCJKsansfont{ipaexg.ttf}
\setCJKmonofont{ipaexg.ttf}

\begin{document}
試験
\end{document}

------------------------------

Then, I have the following error message in main.log

> \docmute@nestinglevel=\count289
 (./subfile.tex
./subfile.tex:8: Improper alphabetic constant.
\<to be read again>
                   \__xeCJK_ambiguous_char:n
l.8 \begin{document}

What should I do?
Please, any ideas.
Thank you.

P.S. There is a [related topic](https://tex.stackexchange.com/questions/568485/compiling-subfiles-with-xecjk) with this problem for the subfiles package.

**Comment by lvjr** [comment]
是不是可以给 xeCJK 发布一个新版本呢？这个 bug 修正了，但是 CTAN 上一直还没有更新．
