### ISSUE TITLE
ctex v2.5.6 中ctex.tds.zip中，\tex\generic\ctex 路径下，zhmap是一个文件，以往版本是一个文件夹，导致ctex更新等出错

### ISSUE THREAD

**Issue by hotbbs** [CTeX-org/ctex-kit#566]
如题

**Comment by Liam0205** [comment]
你说的是 GitHub 上的 release 么？还是 tlmgr 更新的？

**Comment by stone-zeng** [comment]
Releases 里面的文件现在已更新：<https://github.com/CTeX-org/ctex-kit/releases/tag/ctex-v2.5.6>

**Comment by hotbbs** [comment]
我用的MiKTeX，是宏包自动更新的，建议发一个更新，这样能全部同步修正

**Comment by muzimuzhi** [comment]
可以重新上传一次 CTAN，在备注里说明原因，CTAN 团队会更新文件，但不会重新发更新邮件（可能因为不涉及版本递增）。texlive 和 miktex 可能需要邮件各通知一遍。之前我上传 thmmools 时，因为打包错误也经历过一次（当时导致了无法从 dtx 生成 sty，是 texlive 先发邮件过来的）。

**Comment by muzimuzhi** [comment]
> texlive 和 miktex 可能需要邮件各通知一遍

miktex 已经有相应报告 https://github.com/MiKTeX/miktex/issues/756，CTAN 上更新后在那个 issue 下回复（提醒更新）应该就可以了。

**Comment by stone-zeng** [comment]
几天前我已经把修复后的版本上传 CTAN 了，TeX Live 那边稍微延迟了几天，但[昨天也处理了](https://www.tug.org/svn/texlive?view=revision&revision=58583)。

**Comment by stone-zeng** [comment]
根据 https://github.com/MiKTeX/miktex-packaging/issues/236#issuecomment-804079552 中的反馈，miktex 重新打包，应该几天内就可以更新。
