### ISSUE TITLE
Windows10，在 TeX Live 2021 中 ctex 文档类的字体默认使用 fandol。

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/ctex-kit#569]
MWE:
```latex
\documentclass{ctexart}
\begin{document}
    \textbf{黑体}宋体
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/113475125-45b67700-94a6-11eb-9fe5-3d9526fdca89.png)
并且通过 Adobe Acrobat 查看 PDF 内嵌字体为 `FandolSong`

```latex
\documentclass[fontset=windows]{ctexart}
\begin{document}
    \textbf{黑体}宋体
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/113475142-5bc43780-94a6-11eb-99e7-272c14e114c4.png)
此时内嵌字体为 `SimSun` 与 `SimHei`

**Comment by zepinglee** [comment]
WSL？

**Comment by syvshc** [comment]
> WSL？

只有 Windows10，没有子系统。

**Comment by syvshc** [comment]
> WSL？

只有 Windows10，没有子系统。

**Comment by sikouhjw** [comment]
复现条件：`xelatex`+win10(20H2)+texlive2021
我在 ctex v2.5.6 发布后用 texlive2020 更新过，没出现这个 bug
[mwe.zip](https://github.com/CTeX-org/ctex-kit/files/6252876/mwe.zip)

**Comment by zepinglee** [comment]
难道是 L3 kernel 的 bug？可以试下

```
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\c_sys_platform_str\par
\sys_if_platform_windows:TF
  { True }
  { False }
\ExplSyntaxOff
\end{document}
```

**Comment by syvshc** [comment]
> \documentclass{article}
> \begin{document}
> \ExplSyntaxOn
> \c_sys_platform_str\par
> \sys_if_platform_windows:TF
>   { True }
>   { False }
> \ExplSyntaxOff
> \end{document}

看起来是 L3 的问题，输出为
```
unknown
False
```

**Comment by zepinglee** [comment]
这就尴尬了，给 https://github.com/latex3/latex3 提一下 issue 吧。

**Comment by syvshc** [comment]
已经提了 issue https://github.com/latex3/latex3/issues/867

**Comment by stone-zeng** [comment]
后续：https://tug.org/pipermail/tex-live/2021-April/046723.html

**Comment by syvshc** [comment]
后续: https://github.com/latex3/latex3/issues/867#issuecomment-815922541 如果测试成功将关闭该 issue
