### ISSUE TITLE
关于 \rmfamily 下粗体字体不是黑体的问题

### ISSUE THREAD

**Issue by Markhng** [CTeX-org/ctex-kit#572]
在 CTeX v2.4.15 (TeX Live 2019) 中，默认字体族`\rmfamily`下的中文粗体是**黑体**，但在CTeX v2.5.6 (TeX Live 2021) 中默认字体族`\rmfamily`下的中文粗体是粗宋体。
了解到在Windows下使用`\setCJKmainfont{SimSun}[BoldFont={SimHei}]`可以改变粗体的字体，但在其他系统（例如Linux的Overleaf）下就要设置相应字体（如FandolSong, FandolHei）。
然而 CTeX 已经定义了各个平台下的默认宋体和黑体，想了解跨平台下如何使用 CTeX 默认字体设置改变`\rmfamily`下的中文粗体。

---
另外在以下两处发现 Windows 下`\rmfamily`的粗体仍然为黑体，不知道由于版本更新为什么字体设置失效了。
https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/ctex/ctex.dtx#L10720-L10721
https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/ctex/ctex.dtx#L10768

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/ctex-kit/issues/569

**Comment by sikouhjw** [comment]
> 然而 CTeX 已经定义了各个平台下的默认宋体和黑体，想了解跨平台下如何使用 CTeX 默认字体设置改变`\rmfamily`下的中文粗体。

这句话完全读不懂呢……

**Comment by stone-zeng** [comment]
`ctex` 的策略是优先使用加粗的宋体，同时优先使用系统自带字体，总之在 windows 下面就是用中易宋体+中易黑体。TL 2021 早几天 windows 下面有 bug 会使系统识别失效，现已修复。

**Comment by Markhng** [comment]
更新 TeX Live 后在 Windows 下的粗体问题解决了。

但还是有个疑问，在 `fandol`, `macnew` 等下 `\rmfamily` 的粗体的策略是粗宋体，而在 `macold`, `windows` 下 `\rmfamily` 的粗体的策略是黑体。为了使跨平台下的视觉效果相似，是否有办法能简单地跨平台地统一**粗体**的策略为**粗宋体**，或者为**黑体**呢？ @stone-zeng

**Comment by sikouhjw** [comment]
> 更新 TeX Live 后在 Windows 下的粗体问题解决了。
> 
> 但还是有个疑问，在 `fandol`, `macnew` 等下 `\rmfamily` 的粗体的策略是粗宋体，而在 `macold`, `windows` 下 `\rmfamily` 的粗体的策略是黑体。为了使跨平台下的视觉效果相似，是否有办法能简单地跨平台地统一**粗体**的策略为**粗宋体**，或者为**黑体**呢？ @stone-zeng

你可以自己写 `ctex-fontset-<...>` 文件。

**Comment by tanukihee** [comment]
> 为了使跨平台下的视觉效果相似，是否有办法……

没有，因为各平台自带字体不同
