### ISSUE TITLE
l3kernel 2021-05-07 更新后 ctex 宏包报错

### ISSUE THREAD

**Issue by wrfwerrr** [CTeX-org/ctex-kit#575]
系统为 windows10

```
\documentclass{ctexart}

\begin{document} 
你好
\end{document}
```

报错信息
Undefined control sequence.
\sys_if_output_pdf:TF

LaTeX3: Control sequence \ifctexpdf already defined.

LaTeX3: Mismatched LaTeX support files detected.
(LaTeX3)	Loading 'expl3.sty' aborted!
(LaTeX3)	
(LaTeX3)	The L3 programming layer in the LaTeX format
(LaTeX3)	is dated 2021-02-18, but in your TeX tree the files require
(LaTeX3)	at least 2021-05-07.

**Comment by tanukihee** [comment]
无法复现

expl3 版本号：2021-05-07
环境：WSL Debian，TeX Live 2021

**Comment by stone-zeng** [comment]
看起来是 latex3 有关宏包更新失败，重新更新一下 texlive 吧。

**Comment by wrfwerrr** [comment]
> 
> 
> 看起来是 latex3 有关宏包更新失败，重新更新一下 texlive 吧。

我直接复制新版l3kernel.tds的tex/latex/l3kernel到对应文件夹还是报错，换成原来的l3kernel文件夹就正常

**Comment by zepinglee** [comment]
建议 `tlmgr install --reinstall l3kernel` 重装下

**Comment by wrfwerrr** [comment]
> 
> 
> 建议 `tlmgr install --reinstall l3kernel` 重装下

我在网上搜寻办法运行fmtutil-user --all后正常了。
