### ISSUE TITLE
安装CTEX时，清空了win系统的PATH环境变量

### ISSUE THREAD

**Issue by quancs** [CTeX-org/ctex-kit#577]
CTEX版本：CTeX_2.9.2.164_Full
问题：安装CTEX时，CTEX清空了win10系统的PATH环境变量

**Comment by stone-zeng** [comment]
#260, #376

**Comment by stone-zeng** [comment]
除非必要否则请不要使用 CTEX 套装（注意与本 repo 无关）

**Comment by quancs** [comment]
> 
> 
> 除非必要否则请不要使用 CTEX 套装（注意与本 repo 无关）

好的，谢谢。我是看CTEX官网的**CTEX小组**链接到了**CTeX-org**才以为是这个repo。打扰了打扰了！

**Comment by quancs** [comment]
> 
> 
> 除非必要否则请不要使用 CTEX 套装（注意与本 repo 无关）

话说你们能改下www.ctex.org的内容吗？改成使用新的ctex-kit的教程，不然官网的内容有点误导人呢...

**Comment by Liam0205** [comment]
@quancs @aloft 吴老师看下呢？是不是在官网做一些修改？
