### ISSUE TITLE
Package everysel Warning: Everysel is no longer required.

### ISSUE THREAD

**Issue by clysto** [CTeX-org/ctex-kit#578]
使用ctex产生以下warning，有办法可以避免这个warning吗？
```tex
% !TeX program = xelatex
\documentclass[fontset=founder]{ctexart}

\title{\textbf{字体项目}}
\author{毛亚琛}
\date{\today}

\begin{document}

\maketitle

\section{引言}

你好世界

\end{document}
```

```sh
xelatex document.tex
```

```
Package everysel Warning: Everysel is no longer required.,
(everysel)                The LaTeX kernel is now providing the same functional
ity itself.,
(everysel)                See the package documentation or lthooks-doc for furt
her information. .
```

**Comment by sikouhjw** [comment]
您连 `everysel` 都没有加载呢

**Comment by clysto** [comment]
everysel不是ctex宏包内部加载的吗

**Comment by sikouhjw** [comment]
> 
> 
> everysel不是ctex宏包内部加载的吗

提供发行版信息和 log 文件，我编译没有 warning

**Comment by zepinglee** [comment]
#555

**Comment by clysto** [comment]
> #555

谢谢，刚刚才看到了这个issue

**Comment by shuangwen-thu** [comment]
> 
> > everysel不是ctex宏包内部加载的吗
> 
> 提供发行版信息和 log 文件，我编译没有 warning

我也遇到楼主相同的问题了，texlive2021，日志文件如下。
[test.log](https://github.com/CTeX-org/ctex-kit/files/6643237/test.log)

**Comment by shuangwen-thu** [comment]
想问一下楼主这个问题解决了吗？我也遇到这个问题了。每个文档都报错，，，。。

**Comment by zepinglee** [comment]
已经修复但是还没发布。另外警告不是报错。

**Comment by shuangwen-thu** [comment]
> 已经修复但是还没发布。另外警告不是报错。
> […](#)
> 在 2021年6月13日，11:43，shuangwen-thu ***@***.***> 写道： ﻿ 想问一下楼主这个问题解决了吗？我也遇到这个问题了。每个文档都报错，，，。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

sry，打错字了，是警告，不是报错。。。静待更新了。

**Comment by clysto** [comment]
不影响使用，如果使用vscode的LaTeX Workshop插件编写文档，可以ignore这个warning。

**Comment by zepinglee** [comment]
主观上忽略就行
