### ISSUE TITLE
这里是不是多加了一个反大括号？

### ISSUE THREAD

**Issue by chirsz-ever** [CTeX-org/ctex-kit#579]
https://github.com/CTeX-org/ctex-kit/blob/5b8653a0fd05419e6db10948fdb61eb19c0c504f/ctex/ctex.dtx#L3695

阅读文档时发现。

**Comment by stone-zeng** [comment]
并没有，这一行只对 `ctexsize.sty` 生效，与 https://github.com/CTeX-org/ctex-kit/blob/5b8653a0fd05419e6db10948fdb61eb19c0c504f/ctex/ctex.dtx#L3677-L3680

此处 3679 行的大括号匹配。

这种 docstrip 比较反人类，可以对照生成出的代码来检查。

**Comment by chirsz-ever** [comment]
![图片](https://user-images.githubusercontent.com/31474766/121177830-72b14c80-c890-11eb-9b4f-43a030fed607.png)

文档里显示结果就像提前结束区块了一样。

**Comment by stone-zeng** [comment]
所以它才反人类啊😅

对于其他文档类 / 宏包，结束括号出现在 3975 行：

https://github.com/CTeX-org/ctex-kit/blob/5b8653a0fd05419e6db10948fdb61eb19c0c504f/ctex/ctex.dtx#L3962-L3977
