### ISSUE TITLE
xeCJK: Verbatim里不应该自动加空格

### ISSUE THREAD

**Issue by zhsj** [CTeX-org/ctex-kit#580]
```
\documentclass{article}
\usepackage{fancyvrb}
\usepackage[utf8]{inputenc}
\usepackage{xeCJK}

\begin{document}

{
\CJKsetecglue{}
\begin{Verbatim}
"你好"
\end{Verbatim}
}

{
\begin{Verbatim}
"你好"
\end{Verbatim}
}

{
"你好"
}

\end{document}
```

使用 xelatex 编译后渲染出来的效果是

![image](https://user-images.githubusercontent.com/227180/124779188-254dfb00-df74-11eb-9b7a-43f0e9059e4c.png)

我认为Verbatim环境里不应该自动加空格，不需要用户手动设置 `\CJKsetecglue{}`。

原始问题 https://github.com/sphinx-doc/sphinx/issues/9414 在使用 sphinx 编译文档时，发现渲染出来的代码片段里有多余的空格。

**Comment by sikouhjw** [comment]
已知问题：https://github.com/CTeX-org/ctex-kit/issues/580

**Comment by sikouhjw** [comment]
已知问题：https://github.com/CTeX-org/ctex-kit/issues/331

**Comment by zhsj** [comment]
但是问题好像并没有修复呀，是不在xeCJK修复的范围吗？ :cry: 

另外，如果不在 xeCJK 中修复的话，在下游软件（比如sphinx）中推荐的修复方法是哪个呀？ #331 中好像提到了几种方案。。

**Comment by sikouhjw** [comment]
> 但是问题好像并没有修复呀，是不在xeCJK修复的范围吗？ 😢

我觉得是不好修，因为这个环境不是内核里有的。

> 另外，如果不在 xeCJK 中修复的话，在下游软件（比如sphinx）中推荐的修复方法是哪个呀？ #331 中好像提到了几种方案。。

在导言区对环境打补丁。

**Comment by stone-zeng** [comment]
可以考虑给 `fancyvrb` 包单独打个补丁的。

**Comment by muzimuzhi** [comment]
一种补丁方式

```tex
\documentclass{article}
\usepackage{fancyvrb}
% \usepackage{fvextra}
\usepackage{xeCJK}

\makeatletter
\ExplSyntaxOn
\AtBeginDocument
  {
    \xeCJK_if_package_loaded:nTF {fvextra}
      {
        \tl_gput_left:Nn \FV@FormattingPrep@PostHook
          { \__xeCJK_verb_font_hook: }
      }
      {
        \xeCJK_if_package_loaded:nT {fancyvrb}
          {
            \tl_gput_right:Nn \FV@FormattingPrep
              { \__xeCJK_verb_font_hook: }
          }
      }
  }
\ExplSyntaxOff
\makeatother

\begin{document}

normal: "你好"

in \verb|\verb| and \verb|verbatim|
\verb|"你好"|, \begin{verbatim}
"你好"
\end{verbatim}

in \verb|\Verb| and \verb|Verbatim|
\Verb|"你好"|, \begin{Verbatim}
"你好"
\end{Verbatim}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/124786985-bfb13d00-df7a-11eb-8037-7506ff1a128e.png)

**Comment by zhsj** [comment]
多谢。 @stone-zeng 在 https://github.com/sphinx-doc/sphinx/issues/9414#issuecomment-875676739 上的 comment 好像比较简单 :joy:

**Comment by muzimuzhi** [comment]
这里考虑得更多，例如
 - 如果有全局的 `\fvset{formatcom=<code>}`，则再用一次 `formatcom=...` 会覆盖之前的 `<code>`。所以我在 https://github.com/sphinx-doc/sphinx/issues/9414#issuecomment-875705288 建议使用 `formatcom*`。

**Comment by muzimuzhi** [comment]
直接 patch `fancyvrb` 里和 `\verbatim@font` 对应的 `\FV@SetupFont` 也是个办法
```tex
\documentclass{article}
\usepackage{fancyvrb}
\usepackage{xeCJK}

\makeatletter
\ExplSyntaxOn
\AtBeginDocument
  {
    \xeCJK_if_package_loaded:nT {fancyvrb}
      {
        \tl_put_right:Nn \FV@SetupFont
          { \__xeCJK_verb_font_hook: }
      }
  }
\ExplSyntaxOff
\makeatother

\begin{document}
normal: "你好"

in \verb|\verb| and \verb|verbatim|
\verb|"你好"|, \begin{verbatim}
"你好"
\end{verbatim}

in \verb|\Verb| and \verb|Verbatim|
\Verb|"你好"|, \begin{Verbatim}
"你好"
\end{Verbatim}

\end{document}
```
