### ISSUE TITLE
消除经典不包含Script "CJK"警告

### ISSUE THREAD

**Issue by qiancy98** [CTeX-org/ctex-kit#593]
有个经典警告如下:
```log
Package fontspec Warning: Font "FandolHei-Regular" does not contain requested
(fontspec)                Script "CJK".
```
查阅文档后我意识到是由`\defaultCJKfontfeatures{Script=CJK}`导致的.
能不能在`ctex`中设置, 如果使用`fandol`字体时取消该默认设置?
(这应该是最根本的解决这个问题的方法, 我不知道为什么没有检索到... 大家提到的都是绕过这个warning....)
相似的issue: #397 CTeX-org/forum#34

比如说设置选项, 默认CJK, 但是也可以设置`Script=hani`什么的...

**Comment by muzimuzhi** [comment]
> 《[[LaTeX 中文使用] 抑制 xeCJK/fontspec 警告 no-script "CJK"](https://zhuanlan.zhihu.com/p/145429470)》
> <sub>_https://github.com/CTeX-org/ctex-kit/issues/593#issuecomment-950974164_</sub>

我大幅重写了这篇文章，它现在叫《[LaTeX 中文使用] 抑制 xeCJK/fontspec 警告 Font does not contain requested Script "CJK"》。知乎好像取消或放宽了标题长度限制。

**Comment by muzimuzhi** [comment]
[`fontspec` v2.9e](https://github.com/latex3/fontspec/releases/tag/v2.9e) (2024-05-11) 把相关 warning 降级为了 info，之前提到的各种方案已经不再需要。详见提交 latex3/fontspec@0469638 (be quiet when script/lang not found, 2024-05-11)。

如果需要兼容旧版 `fontspec`，可以使用 `\IfPackageAtLeastTF{fontspec}{2024-05-11}{}{<old workaround>}`.
