### ISSUE TITLE
适配latex新版本钩子改动

### ISSUE THREAD

**Issue by wrfwerrr** [CTeX-org/ctex-kit#598]
latex最新版本钩子改动，\ctex_gadd_package_hook:nnn 命令失效

比如编译ctex文档类的一个警告：
LaTeX hooks Warning: Generic hook 'package/after/hyperref' is deprecated.
(hooks)              Use hook 'package/hyperref/after' instead.

**Comment by stone-zeng** [comment]
#594

**Comment by muzimuzhi** [comment]
PS：只是警告，hook 是成功的，没有「失效」
