### ISSUE TITLE
微软雅黑在beamer中的默认设置是否过大？

### ISSUE THREAD

**Issue by tercelxy** [CTeX-org/ctex-kit#600]
ctex v2.5.7, 使用 ctexbeamer 文档类，字体默认设置，显示效果如图
![image](https://user-images.githubusercontent.com/34205978/145417815-b1fe35e0-d8c6-41e4-9e96-d1673f240682.png)
第一个“合”字是微软雅黑，第二个“合”字是windows自带宋体，可以看出无论是英文还是宋体，都明显比雅黑小。下图是将雅黑压缩到0.9倍的效果
![image](https://user-images.githubusercontent.com/34205978/145418287-7e564ca2-7c97-412c-9085-805d2bf54cb5.png)
这个看上去大小似乎比较合适。

我不清楚是否有理由需要将微软雅黑设置的比较大，如果没有特殊理由，是否可以考虑调小一些，这样和英文或其他中文字体搭配使用时看上去比较协调

**Comment by sikouhjw** [comment]
为什么不是微软雅黑在同等字号下就是这么大呢？

**Comment by muzimuzhi** [comment]
雅黑的字面率比较大，算是它的特性，在其他软件里应该也能看到类似的显示差异。缩放……可能带来基线的问题。好吧中文字体的深度比较自由发挥。

**Comment by glatavento** [comment]
默认设置下微软雅黑就是这么大，可以手动选择别的字体（比如思源宋体和思源黑体搭配就不错）

**Comment by stone-zeng** [comment]
`ctex` 宏集只提供基本的字体配置功能，如需进一步调整可以参考 `fontspec`、`xeCJK` 或者 `luatexja` 文档。
