### ISSUE TITLE
显示页眉时，第一个汉字与后面字体不一致

### ISSUE THREAD

**Issue by zongxian** [CTeX-org/ctex-kit#601]
\documentclass[]{book}
\usepackage[UTF8, heading]{ctex}
\usepackage{lipsum}

\ctexset{
	chapter = {
		name = {第,章},
		number = \bfseries\arabic{chapter},
		beforeskip = 30pt,
		afterskip = 30pt,
		format += \bfseries\Large,
		%		format = \raggedright,
		%		pagestyle = empty,
	},
}

\usepackage{fancyhdr}
\fancypagestyle{myhdr1}{%
	\fancyhead{} % clear all header fields
	\fancyhead[CE]{{\small 学位论文}}
	\fancyhead[CO]{{\small\leftmark}}
	\fancyfoot{} % clear all footer fields
	\fancyfoot[CE,CO]{\small\thepage}
	\renewcommand{\headrulewidth}{0.4pt}
	\renewcommand{\footrulewidth}{0pt}
}

\begin{document}

\pagestyle{myhdr1}
\chapter{title}
\lipsum[1-20]

\end{document}

![1](https://user-images.githubusercontent.com/16471794/145716784-9e0b9c42-3834-4682-8443-5cb5320d680c.png)

**Comment by sikouhjw** [comment]
是你的写法错了，设置编号的格式是 `numberformat`，而不是在 `number` 里面写。

**Comment by zongxian** [comment]
> 是你的写法错了，设置编号的格式是 `numberformat`，而不是在 `number` 里面写。

我参考了说明文档，里面确实有这种写法啊，number用来设定数字编号的格式
![2](https://user-images.githubusercontent.com/16471794/145717405-27a41376-9ed8-48f9-b45c-92fc61236be1.png)
。

**Comment by sikouhjw** [comment]
> > 是你的写法错了，设置编号的格式是 `numberformat`，而不是在 `number` 里面写。
> 
> 我参考了说明文档，里面确实有这种写法啊，number用来设定数字编号的格式 ![2](https://user-images.githubusercontent.com/16471794/145717405-27a41376-9ed8-48f9-b45c-92fc61236be1.png) 。

是编号的『输出』格式，不是『加粗』等格式，读书 ok？

**Comment by zongxian** [comment]
> > > 是你的写法错了，设置编号的格式是 `numberformat`，而不是在 `number` 里面写。
> > 
> > 
> > 我参考了说明文档，里面确实有这种写法啊，number用来设定数字编号的格式 ![2](https://user-images.githubusercontent.com/16471794/145717405-27a41376-9ed8-48f9-b45c-92fc61236be1.png) 。
> 
> 是编号的『输出』格式，不是『加粗』等格式，读书 ok？

谢谢，我理解错。

**Comment by muzimuzhi** [comment]
注意 `numberformat` 只在正文中排版章节名时生效 ，对页眉和目录中的章节名没有效果。
