### ISSUE TITLE
草稿模式下不显示 `lstlisting` 环境内容

### ISSUE THREAD

**Issue by atxy-blip** [CTeX-org/ctex-kit#602]
在使用 `listings` 宏包展示代码时，如果开启草稿模式，`lstlisting` 环境的内容都不会输出，也不会像图片一样显示占位的方框，导致后续内容的位置发生了变动。MWE 如下所示：

```
\documentclass[draft]{ctexbook}
\usepackage{listings,zhlipsum}
\begin{document}
\mainmatter
\chapter{Code}
\zhlipsum
\begin{lstlisting}[language=Python]
print("Hello world!")
\end{lstlisting}
\zhlipsum
\end{document}
```

一时间不知道这算草稿模式的 bug 还是 feature……

**Comment by stone-zeng** [comment]
<img width="681" alt="Screen Shot 2021-12-21 at 14 52 00" src="https://user-images.githubusercontent.com/18233088/146884983-b91d8526-b382-4221-939a-20644e0e2f42.png">

**Comment by stone-zeng** [comment]
与 ctex 本身无关的问题可以在 [CTeX-org/forum](https://github.com/CTeX-org/forum) 提问。
