### ISSUE TITLE
newtx宏包(March 2, 2022, v1.7.1)与ctex宏包（2021/12/12 v2.5.8）疑似冲突

### ISSUE THREAD

**Issue by perrogg** [CTeX-org/ctex-kit#609]
# 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

# 编译环境

- 设备及操作系统

   - [x] Macbook Pro (M1 Max); MacOS 12.2.2 

- TeX 发行版

   - [x] TeXLive 2021

# 问题描述

使用ctex字体命令（如`\songti`, `\kaishu`）之后运行报错，不显示字体之后的中文（下图右侧红色标记处缺失“楷书”二字）。
<img width="1134" alt="截屏2022-03-06 23 54 24" src="https://user-images.githubusercontent.com/14990848/156930874-7a4704ec-119b-479f-943a-6c63f597ac69.png">

# 最小工作示例（MWE）

```
\documentclass{ctexart}

\usepackage{newtxtext}
%\usepackage{newtxmath}


\begin{document}
  ABC def 测试 \kaishu 楷书 GH
\end{document}
```

（用 XeLaTeX 编译后）输出报错，问题及日志如下
<img width="1349" alt="截屏2022-03-06 23 55 17" src="https://user-images.githubusercontent.com/14990848/156930920-b1909b34-eca6-4817-b59b-65ae20a40834.png">

<img width="660" alt="截屏2022-03-06 23 55 47" src="https://user-images.githubusercontent.com/14990848/156930922-8b40cc96-a9d2-45c1-a0b5-a614ab8f92fd.png">

# 补充说明

1. 约一年前无此问题（不记得版本号），所有宏包更新到最新，编译之前的文件，才发现此问题。
1.  如果不使用字体命令，不报错（输出默认的宋体）；但只要使用字体命令，即使是宋体`\songti`，报错；
2.  数学字体 `newtxmath` 不冲突，即不加载`newtxtext`，只使用 `newtxmath` 不会报错；
3.  在 `newtx` 文档中找到如下一段话：

> As of version 1.4, newtxtext no longer depends on txfonts but is based on the richer source TeXGyre Termes,

<img width="811" alt="截屏2022-03-06 23 44 01" src="https://user-images.githubusercontent.com/14990848/156930479-adedb7ee-9d2c-4378-89c6-68c03abf4b50.png">

经测试，如果直接如下代码将英文字体设置为 TeXGyreTermes ，不报错：
 ```
\documentclass{ctexart}

%\usepackage{newtxtext}
%\usepackage{newtxmath}
\setmainfont[BoldFont = texgyretermes-bold.otf,
ItalicFont = texgyretermes-italic.otf, 
BoldItalicFont = texgyretermes-bolditalic.otf
]{texgyretermes-regular.otf} %英文字体设置

\begin{document}
ABC \kaishu 楷书 GH
\end{document}
```
<img width="1194" alt="截屏2022-03-06 23 57 50" src="https://user-images.githubusercontent.com/14990848/156931073-dd391109-4bc0-4b98-86a8-aa957c5375d7.png">

**Comment by Sinofine** [comment]
linux下正常
![image](https://user-images.githubusercontent.com/47494321/156931798-48d4ec69-2db5-42c8-9060-01142d950f7e.png)

**Comment by syvshc** [comment]
我已经给作者发了邮件，等待回复吧

**Comment by stone-zeng** [comment]
mac 上可以复现

**Comment by stone-zeng** [comment]
原因应该是 `newtxtext` 宏包加了 `Extension = .otf`：

```tex
\defaultfontfeatures{
  Ligatures = TeX ,
  Scale = \ntx@scale ,
  Extension = .otf ,
  SmallCapsFeatures={\ifntx@scosf Numbers = OldStyle ,
  \fi RawFeature = +\ntx@scraw ,
  \ifluatex Renderer=Basic\fi} ,
  \ntx@dflt ,
  RawFeature=-ss05 ,   
  \ntx@defaultfeatures ,
 }
```

**Comment by zepinglee** [comment]
> 原因应该是 `newtxtext` 宏包加了 `Extension = .otf`：
> 
> ```
> \defaultfontfeatures{
>   Ligatures = TeX ,
>   Scale = \ntx@scale ,
>   Extension = .otf ,
>   SmallCapsFeatures={\ifntx@scosf Numbers = OldStyle ,
>   \fi RawFeature = +\ntx@scraw ,
>   \ifluatex Renderer=Basic\fi} ,
>   \ntx@dflt ,
>   RawFeature=-ss05 ,   
>   \ntx@defaultfeatures ,
>  }
> ```

`newtx` 的 bug，这样设置 `\defaultfontfeatures` 会导致后续的 `\setsansfont` 等 `fontspec` 无法按照字体名调用字体，也无法调用 TTF 字体。

@syvshc 需要我发邮件跟作者解释一下吗？

**Comment by syvshc** [comment]
@zepinglee 可以，您说比我说的会更清楚一些，谢谢了

**Comment by zepinglee** [comment]
> @zepinglee 可以，您说比我说的会更清楚一些，谢谢了

那你把邮件 fwd 给我一份？zepinglee@gmail.com

**Comment by SainoNamkho** [comment]
发现一个小问题，（均用xelatex编译）
```latex
\documentclass{ctexart}

\usepackage{newtxtext}
\ExplSyntaxOn
\makeatletter
\defaultfontfeatures{
	Ligatures = TeX ,
	Scale = \ntx@scale ,
	SmallCapsFeatures={\ifntx@scosf Numbers = OldStyle ,
		\fi RawFeature = +\ntx@scraw ,
		\ifluatex Renderer=Basic\fi} ,
	\ntx@dflt ,
	RawFeature=-ss05 ,   
	\ntx@defaultfeatures ,
}
\ExplSyntaxOff

\begin{document}
	ABC def 测试 \kaishu 楷书 GH
\end{document}
```
编译用了4秒
但是
```tex
\documentclass{ctexart}

\usepackage{newtxtext}
\ExplSyntaxOn
\makeatletter
\cs_undefine:c {\c__keys_code_root_str fontspec-preparse-external/Extension }
\ExplSyntaxOff

\begin{document}
	ABC def 测试 \kaishu 楷书 GH
\end{document}
```
需要8秒，请教一下他俩的区别在哪里？

**Comment by syvshc** [comment]
> 请问解决了吗？我也出现了类似的问题。我把Extension = .otf直接删了，确实没有出现报错，但会有其他影响吗？

宏包作者并没有处理问题, 建议使用 TeX Gyre Termes/STIX Two Text/XITS/TeX Gyre TermesX 进行替代

**Comment by zepinglee** [comment]
> 请问解决了吗？我也出现了类似的问题。我把Extension = .otf直接删了，确实没有出现报错，但会有其他影响吗？

@Guqiuwang 没有。可以在调用 `newtxtext` 后设置 `\defaultfontfeatures{}` 清除掉该宏包设置的 default font features。

**Comment by Guqiuwang** [comment]
> > 请问解决了吗？我也出现了类似的问题。我把Extension = .otf直接删了，确实没有出现报错，但会有其他影响吗？
> 
> 宏包作者并没有处理问题, 建议使用 TeX Gyre Termes/STIX Two Text/XITS/TeX Gyre TermesX 进行替代

好的，多谢建议

**Comment by Guqiuwang** [comment]
> > 请问解决了吗？我也出现了类似的问题。我把Extension = .otf直接删了，确实没有出现报错，但会有其他影响吗？
> 
> @Guqiuwang 没有。可以在调用 `newtxtext` 后设置 `\defaultfontfeatures{}` 清除掉该宏包设置的 default font features。

明白，感谢答复
