### ISSUE TITLE
[与 ctex 无关]  在 CTeX 存在的情况下 nicematrix 的 `\RowStyle` 宏出现编译错误

### ISSUE THREAD

**Issue by lynzrand** [CTeX-org/ctex-kit#611]
# 复现步骤

1. 使用 LaTeX 编译以下代码

```latex
\documentclass{ctexart}

\usepackage{nicematrix}

\begin{document}

\begin{NiceTabular}{l}[]
    \RowStyle{} Foo \\
\end{NiceTabular}

\end{document}
```

2. 欣赏报错信息

```
! Package xcolor Error: Undefined color `仟'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.10     \RowStyle{}
                   Foo \\
```

# 可复现的环境

- Windows 11, MiKTeX 22.1, lualatex 1.14.0 (我)
- Arch Linux, TeXLive 2021, xelatex (telegram sinofine)

## 未能成功复现的环境

- Overleaf 上的 xelatex 和 lualatex

# 备注

我对 LaTeX 的了解仅限于使用的程度，所以 Debug 还是得靠专业用户来……

**Comment by lhy7889678** [comment]
看样子是 nicematrix 中用到了临时变量 `\l_tmpa_tl` 来储存某种颜色，但该变量同时也被 ctex 使用（被设定为 `仟`），导致冲突。（我对 LaTeX3 也并不是很了解，希望有大佬来详细解释一下）

**Comment by lynzrand** [comment]
在 ctex 代码里搜了一下对于这个临时变量的使用情况，只发现了一个地方：

https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/zhnumber/zhnumber.dtx#L1221-L1229

同一个文件中提到 `仟` 字的地方：

https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/zhnumber/zhnumber.dtx#L1924

希望对解决问题有帮助

**Comment by zepinglee** [comment]
应该是 `nicematrix` 的问题，大概是没有将 `\l_tmpa_tl` “初始化”，跟 `ctex-kit` 无关。

```tex
\documentclass{article}

\usepackage{nicematrix}

\begin{document}

\ExplSyntaxOn
  \tl_set:Nn \l_tmpa_tl {foo}
\ExplSyntaxOff

\begin{table}
  \begin{NiceTabular}{l}[]
    \RowStyle{} Foo \\
  \end{NiceTabular}
\end{table}

\end{document}
```
这样会报错
```
./main.tex:13: Package xcolor Error: Undefined color `foo'.

See the xcolor package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.13     \RowStyle{}
                     Foo \\
./main.tex:13:  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by lynzrand** [comment]
感谢！我去联系一下 nicematrix 的作者

**Comment by lynzrand** [comment]
`nicematrix` 的作者已经修复了这个问题
