### ISSUE TITLE
lualatex下破折号问题

### ISSUE THREAD

**Issue by Firestar-Reimu** [CTeX-org/ctex-kit#637]
## Fandol

```
\documentclass[fontset=windows]{ctexart}
\begin{document}
    囗——囗

    \textbf{囗——囗}

    \textit{囗——囗}

    \texttt{囗——囗}
\end{document}
```
![Screenshot_20221002_161402](https://user-images.githubusercontent.com/65082432/193444697-28207b80-c909-4672-8972-358425472795.png)

可见Fandol字体是完好的

## Windows

```
\documentclass[fontset=windows]{ctexart}
\begin{document}
    囗——囗

    \textbf{囗——囗}

    \textit{囗——囗}

    \texttt{囗——囗}
\end{document}
```
![Screenshot_20220930_120006](https://user-images.githubusercontent.com/65082432/193187386-bcf515b0-703a-429b-a119-1b65bc2d132b.png)

可见中易宋体和仿宋是断开的

## Adobe

```
\documentclass[fontset=adobe]{ctexart}
\begin{document}
    囗——囗

    \textbf{囗——囗}

    \textit{囗——囗}

    \texttt{囗——囗}
\end{document}
```
![Screenshot_20220930_120036](https://user-images.githubusercontent.com/65082432/193187473-e25e1d9e-8498-432a-9e5a-940c3bad9ba7.png)
可见adobe宋体是断开的

## Noto/Source Hans

```
\documentclass[fontset=none]{ctexart}
\setCJKmainfont{Noto Serif CJK SC}[BoldFont=Noto Sans CJK SC,ItalicFont=Noto Serif CJK SC]
\setCJKmonofont{Noto Sans Mono CJK SC}[BoldFont=Noto Sans Mono CJK SC Bold,ItalicFont=Noto Serif CJK SC]
\begin{document}
    囗——囗

    \textbf{囗——囗}

    \textit{囗——囗}

    \texttt{囗——囗}
\end{document}
```
![Screenshot_20220930_120912](https://user-images.githubusercontent.com/65082432/193188442-7f6b230b-21fe-4acc-ab0d-612c1a21a068.png)
可见思源字体是完好的

## 方正

```
\documentclass[fontset=none]{ctexart}
\setCJKmainfont{FZShuSong-Z01}[BoldFont=FZHei-B01,ItalicFont=FZKai-Z03]
\setCJKmonofont{FZFangSong-Z02}[BoldFont=FZHei-B01,ItalicFont=FZKai-Z03]
\begin{document}
    囗——囗

    \textbf{囗——囗}

    \textit{囗——囗}

    \texttt{囗——囗}
\end{document}
```
![Screenshot_20220930_121311](https://user-images.githubusercontent.com/65082432/193188882-011677ba-07a3-4cf1-9ea0-17869e90172a.png)
可见方正字体是完好的

**Comment by AlphaZTX** [comment]
请把你的问题表述清楚

**Comment by Firestar-Reimu** [comment]
@AlphaZTX 有些破折号是断开的看不出来吗？？？

**Comment by AlphaZTX** [comment]
@Firestar-Reimu 按照你的说法，中易楷体和中易黑体其实也是断开的，只不过你看的很不仔细，没看出来。你并没有表述你的问题是什么。

**Comment by Firestar-Reimu** [comment]
那你们不打算做一些工作把两个断开的破折号向内压缩连起来吗

**Comment by AlphaZTX** [comment]
@Firestar-Reimu 那是对于字体的优化，不具有普适性。
