### ISSUE TITLE
Chinese support for polyglossia

### ISSUE THREAD

**Issue by t-tk** [CTeX-org/ctex-kit#639]
I have written Chinese support for polyglossia for trial.
I do not speak Chinese and I'm not sure whether it is appropriate or not.
Couldn't I have your advice?

Followings are ldf files:

https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/gloss-chinese.ldf
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/gloss-zh-CN.ldf
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/gloss-zh-TW.ldf

and examples of XeLaTeX & polyglossia with multilingual texts:

https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/city0.tex
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/china002.tex
https://github.com/t-tk/upmendex-package/blob/master/doc/samples/latex/china002.pdf

Related thread in polyglossia:
https://github.com/reutenauer/polyglossia/issues/65

**Comment by zepinglee** [comment]
The translation look good to me.

**Comment by t-tk** [comment]
Thank you for your help.

**Comment by t-tk** [comment]
The ldf files have been merged in polyglossia master blanch.
Thank you for your kind help.
