### ISSUE TITLE
CTeX会影响newpxtext的textcircled显示效果

### ISSUE THREAD

**Issue by Firestar-Reimu** [CTeX-org/ctex-kit#641]
\textcircled in newpxtext do not work with ctex

in newpx documentation, it says:

[![enter image description here][1]][1]

if I use

```
\documentclass{article}
\usepackage{newpxtext}
\usepackage{ctex}
\begin{document}
\textcircled{X}\textcircled{2}
\end{document}
```

it is correct, but **if I add `\usepackage{ctex}` and it will look like this:**

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/0Bvhd.png
  [2]: https://i.stack.imgur.com/lTY5b.png

**Comment by Sophanatprime** [comment]
先加载 `ctex` 再加载 `newpxtext`。

**Comment by Sophanatprime** [comment]
原因是，`ctex`（`ctexsize`）加载 `fix-cm.sty` -> `ts1enc.def`。这个 `ts1enc.def` 里重新定义了大部分以 `text` 开头的命令：
<img width="370" alt="image" src="https://user-images.githubusercontent.com/55335597/197921563-5f58232f-2807-4548-abc8-3a9b6d6ca7d3.png">
从而 `newpxtext` 的定义失效了。

**Comment by Firestar-Reimu** [comment]
谢谢，发现先用ctex或者用ctexart都正常，但是用hyperref也会有问题，需要把hyperref也放在newpxtext前面
