### ISSUE TITLE
思源字体，破折号\symbol{"2E3A}无法改变粗细

### ISSUE THREAD

**Issue by Firestar-Reimu** [CTeX-org/ctex-kit#648]
环境：archlinux+texlive2022
编译：xelatex和lualatex都试过
MWE：
```
\documentclass[fontset=none]{ctexart}
\setCJKmainfont{Noto Sans CJK SC}[RawFeature=+fwid]

\begin{document}
一\symbol{"2E3A}一
\end{document}
```

可以把`Noto Sans CJK SC`改成`Noto Sans CJK SC Bold`或者`Noto Sans CJK SC Light`试试，结果发现破折号`\symbol{"2E3A}`的粗细没有改变

Bold：
![Screenshot_20221229_165448](https://user-images.githubusercontent.com/65082432/209927569-1162f601-bd7c-4b0a-a442-171a578a907e.png)

Light：
![Screenshot_20221229_165513](https://user-images.githubusercontent.com/65082432/209927633-748e3dbe-a913-4b31-83d6-6e5d271965e3.png)

只要开启了`[RawFeature=+fwid]`就会这样，不管是用`——`还是`\symbol{"2E3A}`，可以和不开`[RawFeature=+fwid]`的时候做对比，中文破折号和西文的em dash粗细明显不一样

**这会导致粗体的时候破折号显得非常细，和文字非常不匹配**

当然如果这个是Noto Sans CJK自己设计的问题我就没办法了

**Comment by stone-zeng** [comment]
思源黑体设计如此。
