### ISSUE TITLE
U+002D 的符号类型问题

### ISSUE THREAD

**Issue by NShiroha** [CTeX-org/ctex-kit#659]
根据 GB/T 15834—2011《标点符号用法》，中文连接号分为短横线、一字线、浪纹线三种。其中浪纹线可用 U+FF5E，默认为中文标点，不存在符号类型问题；一字线可以直接用`—`输入，区别于`---`输入的 Em-Dash，会使用中文字体输出，所以尽管两者都是 U+2014，但不存在标点类型的问题。然而短横线似乎没有好的输入方法，直接输入的 U+002D 会被识别为西文标点，有没有办法将其临时设为中文标点呢？

**Comment by zepinglee** [comment]
可以考虑 `\CJKfamily+{}`。

```tex
\documentclass{article}
\usepackage{xeCJK}
\setCJKmainfont{SimSun}
\begin{document}
3-1\par
3{\CJKfamily+{}-}1\par
\end{document}
```

**Comment by NShiroha** [comment]
感谢解答，还是我读手册不够仔细了。
不过这个问题我早就在想了，各种 LaTeX 教程基本不会提这些，之前也在一些 LaTeX 交流群和论坛提问，没有人给出好的解决方案，看来大家不怎么在意这个，也没有太多了解……
