### ISSUE TITLE
Mac 下 xeCJK 的默认中文字体

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#67]
Original [issue 68](https://code.google.com/p/ctex-kit/issues/detail?id=68) created by ericalways on 2011-12-27T08:28:04.000Z:

苹果 Mac OS X 系统自带华文系列的中文字体，建议类似已有的 winfonts 和 adobefonts 的基础上，增加 macfonts 字体设置，使得 ctex 能够在 Mac 下 work out of the box。

黑体、宋体、楷体和仿宋的名称分别为：
STHeiti 
STSong
STKaiti
STFangsong

**Comment by zepinglee** [comment]
现在 mac 下 ctex 是这样配置宋体的：
```
\setCJKmainfont [ BoldFont = STHeiti , ItalicFont = STKaiti ]  { STSong }
```
但是mac 在 10.8 之后提供了 Songti SC （同样在 /Library/Fonts/Songti.ttc），包含了多个字重，那么是不是没必要把粗体设置为黑体了？
