### ISSUE TITLE
使用ctex制作中文毕业论文模板

### ISSUE THREAD

**Issue by mengchaoheng** [CTeX-org/ctex-kit#675]
您好，感谢你们卓越的工作。我一直希望学会制作毕业论文模板，而不是像现在我是使用以前的模板更改而来，有很多冗余代码。

我了解到ctex并希望开始工作，请问官方有这方面的教材吗？我希望更多的关注页面版面控制，而不是图表那些使用其他宏包就可以控制的细节。

**Comment by sikouhjw** [comment]
> 我了解到ctex并希望开始工作，请问官方有这方面的教材吗？

`texdoc ctex`

> 我希望更多的关注页面版面控制，而不是图表那些使用其他宏包就可以控制的细节。

ctex 跟版面控制无关

**Comment by mengchaoheng** [comment]
@sikouhjw 明白了，感谢，我的答案应该是Google: How to write a LaTeX class file

**Comment by zepinglee** [comment]
> 请问官方有这方面的教材吗？我希望更多的关注页面版面控制，而不是图表那些使用其他宏包就可以控制的细节。

目前这方面没有比较系统的指南，但可以参考 <https://www.zhihu.com/question/27017364> 和 《[LaTeX 模板开发最佳实践](https://github.com/ustctug/ustcthesis/wiki/LaTeX-%E6%A8%A1%E6%9D%BF%E5%BC%80%E5%8F%91%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5)》。另外已有的各高校模板也可以参考。举几个我自己比较熟悉的：[ustcthesis](https://github.com/ustctug/ustcthesis), [fduthesis](https://github.com/Stone-Zeng/fduthesis), [sjtuthesis](https://github.com/sjtug/SJTUThesis)。

**Comment by mengchaoheng** [comment]
太感谢了，我已经是模板的改进者了但我想重构模板成为真正的模板开发者，苦于没有合适的教材，感谢您的推荐

**Comment by muzimuzhi** [comment]
> 我已经是模板的改进者了但我想重构模板成为真正的模板开发者

感觉这两者的界限是很模糊的，不用刻意追求「真正的xxx」。阅读 `.cls` 文件内容、找到改进方式，就已经是开发者了。开发新文档类时当然可以、也经常推荐参考和基于既有实现。
