### ISSUE TITLE
Two self-referential declarations in xeCJK.dtx

### ISSUE THREAD

**Issue by rriegs** [CTeX-org/ctex-kit#682]
The declaration for `\textnbacksim` on line 12899 of xeCJK.dtx refers to itself instead of the intended `\textbacksim`:

https://github.com/CTeX-org/ctex-kit/blob/29d70d8bdfbeb1a955ee8a128852cf3069b8ec88/xeCJK/xeCJK.dtx#L12899

The declaration for `\textnlessapprox` on line 13388 similarly refers to itself instead of the intended `\textlessapprox`:

https://github.com/CTeX-org/ctex-kit/blob/29d70d8bdfbeb1a955ee8a128852cf3069b8ec88/xeCJK/xeCJK.dtx#L13388

Also, the declaration for `\textnleqslant` on line 13384 refers to `\textlstrikethrux` instead of the correct `\textlstrikethru`:

https://github.com/CTeX-org/ctex-kit/blob/29d70d8bdfbeb1a955ee8a128852cf3069b8ec88/xeCJK/xeCJK.dtx#L13384

**Comment by muzimuzhi** [comment]
Thanks for reporting these!

A fix corresponding to your similar reports to `hyperref` has also been applied in `xeCJK.dtx`, see #680.
