### ISSUE TITLE
ctex.pdf 文档的一个小小 typo

### ISSUE THREAD

**Issue by rockyzhz** [CTeX-org/ctex-kit#687]
第10页关于 `punct` 选项的说明中，关于 `kaiming` 的说明里，是不是“用占”应该改为“占用”？

![image](https://github.com/CTeX-org/ctex-kit/assets/3292710/e8ec44a3-f167-40ef-8179-a74b336f4966)

**Comment by muzimuzhi** [comment]
与其他描述保持一致，改成了「占」。感谢反馈。
