### ISSUE TITLE
ctex: The key 'ctex/algorithmname' is unknown

### ISSUE THREAD

**Issue by LeoJhonSong** [CTeX-org/ctex-kit#692]
这部分文档称`algorithmname`参数可以设置`\algorithmname`命令的值, 实际使用则会报错. 示例代码和报错信息如下:
```latex
\ctexset{algorithmname={算法}}
```
```log
The key 'ctex/algorithmname' is unknown and is being ignored.
```
是不是实现上已经删掉这个参数了呢?

**Comment by muzimuzhi** [comment]
从实现看，`algorithmname` 只在 `ctexbeamer.cls` 里有定义
https://github.com/CTeX-org/ctex-kit/blob/143022014347ce883d1d7c350ce2d725776b1a5e/ctex/ctex.dtx#L7609-L7614

查 `beamer` 源文件，`\algorighmname` 在 `beamerbasemisc.sty` 里定义
https://github.com/josephwright/beamer/blob/6df15d86dc01cedae42b03f45783c6ab1865e150/base/beamerbasemisc.sty#L143

**Comment by muzimuzhi** [comment]
大概一周前，我发现实际上之前的 ctex 文档（v2.5.10，2022-07-14）就指出了 `algorithmname` 仅在与 `beamer` 搭配使用时才有定义，见文档第 13 页开头，

> 如果使用 `ctexbeamer` 文档类或者在 `beamer` 文档类下使用 `ctex` 包，还会汉化常用定理类环境的诸如“定义”、“定理”和“引理”等名称。此时，还有下列三个选项。
> `refname` = <名字> 
> ……
> `algorithmname` = <名字>
> ……
> `continuation` = <名字>
> ……

也许是纵向间距使得（在选项文档之间插入的）这两句说明不够明显。希望 https://github.com/CTeX-org/ctex-kit/commit/9ef53a4ff185660f5c3a2acdcdb5ef68aabfc1bf 有让文档更清晰一点点。
