### ISSUE TITLE
如何增加"不能出现在行首" 的符号

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/ctex-kit#701]
OS: Win 11 专业版 23H2
TeXLive 2023
xeCJK 版本: 3.9.1; revision: 64059

问题来源: 在 [GB/T 7714-2015](https://lib.tsinghua.edu.cn/wj/GBT7714-2015.pdf) 中参考文献中的符号为全角符号, 包括用 `add.period` 生成的点号, 于是我自行将 [`gbt7714-numerical`](https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-numerical.bst) 中的符号改为了全角, 但是我无法更改 `add.period` 生成的点号. 但是半角的点号没有“不能出现在行首”的规则, 于是会偶然出现点号出现在行首的情况, 于是我的想法是:
1. 将 `add.period` 改为全角点号(U+FF0E), 这样就可以适配 xeCJK 的规则
2. 将半角点号(U+002E)添加到“不能出现在行首”的列表里

1. 我发现 `add.period` 是 `bibtex`  的内置函数 (见 `texdoc btxhak` sec 5.3),  没找到在哪改, 这个问题我提在了 https://tex.stackexchange.com/questions/713065/bibtex-how-to-change-the-behavior-of-add-period
![image](https://github.com/CTeX-org/ctex-kit/assets/38098591/d0ada368-d244-4acd-a8b1-39ca7264c28d)
2. 查找 xeCJK 的源码可以发现 `\c__xeCJK_FullRight_chars_clist` 是需要出现在文字右边的, 我就往其中新加了半角点号, 但是没有用. 下面是 MWE:

```latex
\documentclass{ctexart}
\ExplSyntaxOn
\clist_new:N \hithesis__FullRight_clist
\clist_set:Nn \hithesis__FullRight_clist {"002E}
\clist_gconcat:NNN \c__xeCJK_FullRight_chars_clist 
                   \c__xeCJK_FullRight_chars_clist
                   \hithesis__FullRight_clist
\ExplSyntaxOff
\begin{document}
% 这里的点号是 Fullwidth Full Stop : U+FF0E
\noindent 啊手动阀沙发去问他问题我进去儿童趣味请问天气问题求微分全啊去［好］． 手动阀手动阀撒旦发文发涩发而我却\\
% 这里的点号是 Full Stop : U+002E
\noindent 啊手动阀沙发去问他问题我进去儿童趣味请问天气问题求微分全啊去［好］. 手动阀手动阀撒旦发文发涩发而我却
\end{document}
```

使用 xelatex 编译后可以得到
![image](https://github.com/CTeX-org/ctex-kit/assets/38098591/9db14e78-6ed2-4f5d-8ab0-7f2d593f1603)
可以发现半角点号出现在了行首, 如何解决这个问题呢?

**Comment by muzimuzhi** [comment]
```tex
% !TeX program = xelatex
\documentclass{ctexart}

\newcommand{\test}{%
  % 这里的点号是 Fullwidth Full Stop : U+FF0E
  \noindent 啊手动阀沙发去问他问题我进去儿童趣味请问天气问题求微分全啊去［好］． 手动阀手动阀撒旦发文发涩发而我却\\
  % 这里的点号是 Full Stop : U+002E
  \noindent 啊手动阀沙发去问他问题我进去儿童趣味请问天气问题求微分全啊去［好］. 手动阀手动阀撒旦发文发涩发而我却
}

\begin{document}
\subsection*{默认}
\test

\subsection*{修改后}
\xeCJKDeclareCharClass{FullRight}{"002E}
\test
\end{document}
```
![image](https://github.com/CTeX-org/ctex-kit/assets/6376638/f65b2c6a-c772-4e42-b8f7-486a15b1b782)

`\xeCJKDeclareCharClass` 的文档在 `texdoc xecjk` (v3.9.1 2022/08/05), sec. 3.4 设置 CJK 字符范围。

**Comment by muzimuzhi** [comment]
> ```tex
> \ExplSyntaxOn
> \clist_new:N \hithesis__FullRight_clist
> \clist_set:Nn \hithesis__FullRight_clist {"002E}
> \clist_gconcat:NNN \c__xeCJK_FullRight_chars_clist 
>                    \c__xeCJK_FullRight_chars_clist
>                    \hithesis__FullRight_clist
> \ExplSyntaxOff
> ```

这个修改，
- 从功能上，缺「刷新 char class 这一步」，加上 `\xeCJKResetPunctClass` 就生效了
- 从风格上，
  - 不建议修改常量（`\c_` 开头的），这里是 `\c__xeCJK_FullRight_chars_clist`。
    查 `\xeCJKDeclareCharClass{<class>}{<range>}` 的实现，可以看到它把 `<range>` 存到 `\g__xeCJK_<class>_range_clist` 里，然后刷新了 `<class>` 这个类别的 char class 设置。
  - 建议修改 `\hithesis__FullRight_clist` 的命名，为 `\<prefix>__hithesis_FullRight_clist`，这里的 `<prefix>` 可以是 `l`, `g`, `c` 中的一个，具体见 `texdoc interface3` (2024-02-20), sec. 1.1 "Naming functions and variables"。

开头关于 GB/T 7714-2015 的描述，建议提供包名/仓库链接之类的背景信息。

**Comment by syvshc** [comment]
谢谢 @muzimuzhi 的建议, 我修改了问题并提供了 GB/T 7714-2015 的链接.

**Comment by muzimuzhi** [comment]
> 问题来源: 在 [GB/T 7714-2015](https://lib.tsinghua.edu.cn/wj/GBT7714-2015.pdf) 中参考文献中的符号为全角符号, 包括用 `add.period` 生成的点号, 于是我自行将 `gbt7714-numerical` 中的符号改为了全角, 但是我无法更改 `add.period` 生成的点号.

额，我不是指缺乏 GB/T 7714-2015 这个国家推荐标准的来源，而是缺乏 `add.period`（虽然后面提到了是和 bibtex 相关） 和 `gbt7714-numerical` 的来源信息。

比如，介绍「我在同时使用 `xeCJK` 和 [gbt7714](https://ctan.org/pkg/gbt774) 包时遇到一个问题。`gbt7714` 生成的参考文献里，跟在文献类型后的西文句号 `.` (U+002E) 可能出现在行首。我尝试了 patch `gbt7714`……没有成功。我又想到在 `xeCJK` 里把 `.` 设为不能出现在行首的标点，但我的设置好像没有生效，见下面例子 balabala。」

------

对了，`\xeCJKDeclareCharClass{FullRight}{"002E}` 应该会同时修改 `.` 使用的字体，也许你想要把它改回使用西文字体（通过 `\xeCJKDeclareSubCJKBlock`）。

或者，在 `gbt7714` 那头，如果可以在输出 `］` 时加上 `\nolinebreak`，这样也有用。

```tex
% !TeX program = xelatex
\documentclass{ctexart}

\begin{document}
\subsection*{插入 \string\nolinebreak}
\noindent 啊手动阀沙发去问他问题我进去儿童趣味请问天气问题求微分全啊去［好］． 手动阀手动阀撒旦发文发涩发而我却

\noindent 啊手动阀沙发去问他问题我进去儿童趣味请问天气问题求微分全啊去［好］\nolinebreak. 手动阀手动阀撒旦发文发涩发而我却
\end{document}
```
![image](https://github.com/CTeX-org/ctex-kit/assets/6376638/83d9d6d3-c830-4887-949d-0c4a000c1dae)

**Comment by muzimuzhi** [comment]
虽然 `add.period` 的定义改不了，也许可以在 `gbt7714-numerical.bst` 里定义一个新的 bibtex 函数，替换所有的 `add.period` 使用。

**Comment by syvshc** [comment]
> 虽然 `add.period` 的定义改不了，也许可以在 `gbt7714-numerical.bst` 里定义一个新的 bibtex 函数，替换所有的 `add.period` 使用。

这就是我在 https://tex.stackexchange.com/questions/713065/bibtex-how-to-change-the-behavior-of-add-period 中提到的, 因为看起来内置的 `add.period` 有一些限制:
![image](https://github.com/CTeX-org/ctex-kit/assets/38098591/0403ccc7-24d3-487b-bb92-535621c5df83)
我自行添加的话不知道如何满足这些（

**Comment by muzimuzhi** [comment]
不怕生成的 `.bbl` 丑，还能在每处 `add.period` 之后插入 `\nolinebreak`。

我也不会 bst 里的（操作符后置的）语言。你已经找到 `texdoc btxhak.pdf`（因为我猜你 `add.period` 的文档截图出自这个文档），剩下的就是学了。还能求助 `gb7t7714` 的维护者、latex 社区。

**Comment by zepinglee** [comment]
> 在 [GB/T 7714-2015](https://lib.tsinghua.edu.cn/wj/GBT7714-2015.pdf) 中参考文献中的符号为全角符号

为何是全角？这份标准用的开明式标点，不是很好判断全角、半角。另外，如果是西文文献，使用全角标点很不搭配。

实际中，根据我所了解的国内期刊/学位论文格式，大部分是同一使用半角标点，或者中文用全角、西文用半角。

**Comment by syvshc** [comment]
> > 在 [GB/T 7714-2015](https://lib.tsinghua.edu.cn/wj/GBT7714-2015.pdf) 中参考文献中的符号为全角符号
> 
> 为何是全角？这份标准用的开明式标点，不是很好判断全角、半角。另外，如果是西文文献，使用全角标点很不搭配。

这个我也只是从字形上进行判断的, 查了一些讨论后确实是用的开明标点[^1]

> 实际中，根据我所了解的国内期刊/学位论文格式，大部分是同一使用半角标点，或者中文用全角、西文用半角。

但是在哈工大的研究生论文书写范例中用的确实是全角, 无论中英文…… https://hitgs.hit.edu.cn/2021/0513/c17461a318415/page.htm

[^1]: https://www.zhihu.com/question/23371611

**Comment by zepinglee** [comment]
> 但是在哈工大的研究生论文书写范例中用的确实是全角, 无论中英文…… https://hitgs.hit.edu.cn/2021/0513/c17461a318415/page.htm

第一次看到这种格式，看来是我之前浅薄了。

另外我很不能理解句点使用半角而其他标点（如逗号、冒号）使用全角。因为半角句点加空格的宽度通常小于全角标点，就很不搭配。西文文献搭配全角标点就更离谱了。如果学校没有明确要求用什么的标点的话，我不建议严格按照这份格式使用标点。

<img width="230" alt="Screenshot 2024-03-14 at 11 15 13" src="https://github.com/CTeX-org/ctex-kit/assets/12290822/f2966151-1e0b-4c88-9368-6781fec529ea">
