### ISSUE TITLE
documentclass 设置为 ctexbook，目录第一页的页眉页脚样式无法修改

### ISSUE THREAD

**Issue by Fanchengyan** [CTeX-org/ctex-kit#720]
使用ctex时，把 documentclass 设置为 `ctexbook`，发现使用 `\tableofcontents` 生成的目录第一页的页眉页脚不会发生改变。

请问有什么办法修改目录的第一页的页眉页脚吗？

目录页的配置如下：

```latex
\clearpage
\pagestyle{empty}
\tableofcontents
\clearpage
```

但目录只用从第二页及之后清空了页眉页脚，第一页是正文的页眉页脚，效果如下：

![微信截图_20240920225617](https://github.com/user-attachments/assets/ac576bbb-af3e-4ca3-8e23-789215bdd208)

**Comment by muzimuzhi** [comment]
`book`/`ctexbook` 文档类中，`\tableofcontents` 的标题由 `\chapter*` 产生，它的内部会使用 `\thispagestyle{plain}`。所以，全局的 `\pagestyle{empty}` 影响不到目录第一页的页眉页脚样式。

`\chapter` 标题所在页的页眉页脚，可以用 `\ctexset{chapter/pagestyle=<page style>}` 设置，详见 `ctex` 宏集文档。

**Comment by Fanchengyan** [comment]
根据我们学校的毕业论文要求，目录页与后续正文章节的页眉页脚的要求不一样，请问有办法实现单独修改目录的页眉页脚吗？

**Comment by Fanchengyan** [comment]
哦哦，可以了。我取消了使用`\ctexset`设置chapter设置页面样式，在目录章节处分别单独设置就可以了。

**Comment by Fanchengyan** [comment]
我发现，使用ctex之后，目录章节的样式只能使用 `\ctexset` 设置`pagestyle`,    ` \pagestyle`,   `\thispagestyle` 完全不起作用，请问有什么办法分别单独修改目录和正文章节的页眉页脚吗？

**Comment by muzimuzhi** [comment]
> 我发现，使用ctex之后，目录章节的样式只能使用 `\ctexset` 设置`pagestyle`, ` \pagestyle`, `\thispagestyle` 完全不起作用

什么意思？给一组例子，展示使用 ctex 之前可以、使用它之后不可以。

> 请问有什么办法分别单独修改目录和正文章节的页眉页脚吗？

在目录前设置、目录后改回去。

**Comment by zepinglee** [comment]
> 我发现，使用ctex之后，目录章节的样式只能使用 `\ctexset` 设置`pagestyle`, ` \pagestyle`, `\thispagestyle` 完全不起作用，请问有什么办法分别单独修改目录和正文章节的页眉页脚吗？

建议描述一下具体的格式需求。

另外建议重定义 `\frontmatter`、`\mainmatter` 的 `\pagestyle` 控制不同部分的页眉页脚。

还有可以定义空的 `\ps@none`，再设置 `\cteset{chapter/pagestyle = none}`，相当于取消每章第一页的特殊页眉页脚。

```latex
\newcommand\ps@none{}
\cteset{chapter/pagestyle = none}
```

**Comment by Fanchengyan** [comment]
非常感谢二位解答。经过测试：

- 我创建了一个小的示例，是可以通过 `\thispagestyle` 改变 `\tableofcontents`生成的目录的第一页的页眉页脚。
- 但我的论文中使用`\thispagestyle` 和`\pagestyle` 都无法改变 `\tableofcontents`生成的目录的第一页的页眉页脚。

我猜测应该是论文中使用的库比较多，和某个库冲突，这两条命令被覆盖。所以应该不是ctex的问题。

我现在通过`\ctexset` 将 chapter 的pagestyle 设为empty，保证目录的页眉页脚的样式是空的。然后在生成每一章的时候，单独调用 `\thispagestyle` 来改变章节的样式，可以迂回解决这个问题。

**Comment by Fanchengyan** [comment]
更新一下，供大家参考：

这个问题是因为`\tableofcontents` 使用`chapter*`命令生成标题，所以页眉页脚和chapter是一样的。这种情况下`\pagestyle`, `\thispagestyle`是无法影响页眉页脚的。

## 解决方法：

在正文区使用`\cteset{chapter/pagestyle = usedstyle}`，可以修改后续的代码的`chapter`的`pagestyle`。

根据 @zepinglee 的建议，可以重定义 `\frontmatter`、`\mainmatter`, 将`\cteset{chapter/pagestyle = usedstyle}`加入进去， 这样就可以通过调用`\frontmatter`、`\mainmatter`，在不同的部分使用不同的`pagestyle`了。

下面是我的代码，供参考：

```latex

\renewcommand{\frontmatter}{
  \cleardoublepage
  \pagestyle{roman-page} % Change the page style
  \setcounter{page}{1} % Reset the page counter
  \ctexset{
    chapter={
      format=\heiti \zihao{3} \centering \bfseries,
      pagestyle=roman-page,
      beforeskip=12pt,
      afterskip=24pt,
      fixskip=true,
     }
  }
}

\renewcommand{\mainmatter}{
  \cleardoublepage
  \pagestyle{normal-page} % Change the page style
  \setcounter{page}{1} % Reset the page counter
  \zihao{-4}

  \ctexset{
    chapter={
      format=\heiti \zihao{3} \centering \bfseries,
      pagestyle=normal-page,
      beforeskip=12pt,
      afterskip=24pt,
      fixskip=true,
     }
  }
}
```

**Comment by zepinglee** [comment]
> 更新一下，供大家参考：

1. 定义命令时，每行如果结尾如果不是 `\foo` 这样的命令，需要添加 `%` 注释防止引入隐式的空格。最好养成习惯。
2. `\frontmatter`、`\mainmatter` 原来的定义中有 `\@mainmatterfalse`、`\pagenumbering{roman}` 等内容，如果你不确定这些内容的功能，应该在重定义时保留这些内容，否则容易引起各种奇怪的问题。比如 `\pagenumbering{roman}` 还修改了 `\thepage` 命令。
3. 在 `\mainmatter` 并不能修改正文的默认字号，应该给 `ctex[book]` 传入 `zihao = -4` 选项，或者重定义 `\normalsize` 命令。
4. `\zihao{3} ` 后的是多余的空格，应该避免。

如果是我的话，我会写成下面这样：

```latex
\newcommand\ps@none{}

\ctexset{
  chapter = {
    format = \heiti\zihao{3}\centering\bfseries,
    pagestyle = none,
    beforeskip = 12pt,
    afterskip = 24pt,
    fixskip = true,
  }
}

\renewcommand{\frontmatter}{%
  \cleardoublepage
  \pagestyle{roman-page}%  Change the page style
  \@mainmatterfalse
  \pagenumbering{roman}%
}

\renewcommand{\mainmatter}{%
  \cleardoublepage
  \pagestyle{normal-page}%  Change the page style
  \@mainmattertrue
  \pagenumbering{arabic}%
}

```

**Comment by Fanchengyan** [comment]
学到了，我没系统学习过LaTeX，还在摸索阶段，多谢指正！
