### ISSUE TITLE
更新后编译 xeCJK 时出现 “A floating point with value '0' was misused” 错误

### ISSUE THREAD

**Issue by fangquinlan** [CTeX-org/ctex-kit#724]
我在使用最新的 LaTeX 2024 版本（11/3日使用`tlmgr update -self --all`更新后）编译含有 `xeCJK` 包的文档时，遇到了如下错误：

```
! LaTeX Error: A floating point with value '0' was misused.

To obtain the value of a floating point variable, use '\fp_to_decimal:N',
'\fp_to_tl:N', or other conversion functions.
```

该错误在文档中多次出现，主要发生在包含中文字符的地方。

**环境信息**：

- **操作系统**：Windows 11
- **TeX 发行版**：TeX Live 2024
- **LaTeX 版本**：LaTeX2e <2024-11-01>
- **L3 programming layer**：<2024-10-09>
- **xeCJK 版本**：v3.9.1（2022/08/05）
- **相关宏包**：`fontspec`、`expl3` 均为最新版
- **字体文件**：`simsun.ttf`、`simsun-extb.ttf`、`simsun-extg.ttf`，位于当前目录下

**最小工作示例（MWE）**：

```latex
\documentclass{article}
\usepackage{xeCJK}

\setCJKmainfont[Path=./]{simsun.ttf}
\setCJKfallbackfamilyfont{\CJKrmdefault}[Path=./,Range={"20000-"2A6DF}]{simsun-extb.ttf}
\setCJKfallbackfamilyfont{\CJKrmdefault}[Path=./,Range={"30000-"3134F}]{simsun-extg.ttf}

\begin{document}

测试基本汉字。

测试扩展汉字：𠀁 𠀂 𠀃 𠀄 𠀅 𠀆

\end{document}
```

**编译方式**：

使用 XeLaTeX 编译上述代码。

**错误日志**：

在编译过程中，出现多次以下错误消息：

```
! LaTeX Error: A floating point with value '0' was misused.

To obtain the value of a floating point variable, use '\fp_to_decimal:N',
'\fp_to_tl:N', or other conversion functions.
```

完整的编译日志中，错误信息与 `expl3` 浮点数处理相关。

**问题分析**：

经过分析，可能的原因是 `expl3` 编程层在 LaTeX 2024 版本中对浮点数处理进行了更严格的规范，导致 `xeCJK` 中某些使用浮点数的代码与新版本不兼容。

**Comment by muzimuzhi** [comment]
Duplicate of #723

升级到 l3kernel 2024-11-02（也许要等 1--2 天才能安装到这个版本）自动修复。

提问前可以搜一搜既有 issue。

**Comment by muzimuzhi** [comment]
Duplicate of #723
