### ISSUE TITLE
ctexart文档类可否提供一个参数以使\section{}的计数器与\part{}的计数器关联，可自动重置？

### ISSUE THREAD

**Issue by Mikachu2333** [CTeX-org/ctex-kit#727]
如题，在使用ctexart文档类时，`\section{}`的计数器始终自增，不与`\part{}`的计数器关联。

---

示例：
```latex
\documentclass[UTF8]{ctexart}
\begin{document}

\part{一}
\section{1111}
\section{2222}

\part{二}
\section{11111111}
\section{22222222}

\end{document}
```
结果如下图所示：
![图片](https://github.com/user-attachments/assets/101947c1-a9ac-4dbb-9c29-9afa61a4c035)

---

期望的改进：其他等价于下文所述的代码

```latex
\makeatletter
\@addtoreset{section}{part}
\makeatother
```
结果如下图所示
![图片](https://github.com/user-attachments/assets/f7bade9e-441f-4666-bb73-19f45a477e95)

**Comment by muzimuzhi** [comment]
`\counterwithin*{section}{part}`

命令 `\counterwithin` 和 `\counterwithout` 由 LaTeX kernel 提供，文档散见 `texdoc ltnews`。

顺便，默认行为「part 不重置 chapter/section」，就是为了得到全文档编号唯一的 chapter/section，方便交叉引用。例如，CLRS 的[目录](https://highered.mheducation.com/sites/0070131511/information_center_view0/table_of_contents.html)。

**Comment by Mikachu2333** [comment]
非常感谢您的回答！
