### ISSUE TITLE
mactex 调用 ctex 报错: Undefined  control sequence. \xeCJKDeclarePunctStyle code ... IfInstanceExistTF

### ISSUE THREAD

**Issue by hehancn** [CTeX-org/ctex-kit#728]
小弟最近写毕业论文, 发现调用ctex包后也不能使用中文,  系统是Macos 14.7.1  用自带的texshop编译如下的代码都会直接报错, 

\documentclass{article}
\usepackage[UTF8]{ctex}

\begin{document}
中文
\end{document}

以下是报错的日志内容. 但是在overleaf上是正常的, 有大佬可以忙看看是我的电脑出了什么问吗

<img width="1007" alt="Screenshot 2024-12-14 at 21 33 05" src="https://github.com/user-attachments/assets/356d1cb9-43d7-40c7-927e-72a69d64ad9d" />

----
This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2024-11-01> patch level 1
L3 programming layer <2024-11-02>
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/article.cls
Document Class: article 2024/06/29 v1.4n Standard LaTeX document class
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2024/texmf-dist/tex/latex/ctex/ctex.sty
(/usr/local/texlive/2024/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2024/texmf-dist/tex/latex/l3backend/l3backend-xetex.def))
(/usr/local/texlive/2024/texmf-dist/tex/latex/ctex/ctexhook.sty)
(/usr/local/texlive/2024/texmf-dist/tex/latex/ctex/ctexpatch.sty)
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/fix-cm.sty
(/usr/local/texlive/2024/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/local/texlive/2024/texmf-dist/tex/latex/ctex/config/ctexopts.cfg)
(/usr/local/texlive/2024/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def
(/usr/local/texlive/2024/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(/usr/local/texlive/2024/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.st
y)
/usr/local/texlive/2024/texmf-dist/tex/xelatex/xecjk/xeCJK.sty:2976: Undefined 
control sequence.
\xeCJKDeclarePunctStyle code ...IfInstanceExistTF 
                                                  {xeCJK/punctuation}{#1}{\_...
l.2976 \xeCJKDeclarePunctStyle { quanjiao } { }
                                               
? 
Process aborted

**Comment by muzimuzhi** [comment]
升级 `l3packages` 这个包（执行 `sudo tlmgr update l3packages`）。`xtemplate.sty` 需要至少为 2024-05-08，以包含这个（恢复 `\IfInstanceExistTF` 定义的）提交 https://github.com/latex3/latex3/commit/affc2ed190c50c7c96812bca69e97955f2dead8f 。

或者升级所有包（执行 `sudo tlmgr update --self --all`）。

PS：你只展示了标准输出（stdout），最好展示 log（`main.log`），log 里的信息更多。

**Comment by hehancn** [comment]
> 升级 `l3packages` 这个包（执行 `sudo tlmgr update l3packages`）。`xtemplate.sty` 需要至少为 2024-05-08，以包含这个（恢复 `\IfInstanceExistTF` 定义的）提交 [latex3/latex3@affc2ed](https://github.com/latex3/latex3/commit/affc2ed190c50c7c96812bca69e97955f2dead8f) 。
> 
> 或者升级所有包（执行 `sudo tlmgr update --self --all`）。
> 
> PS：你只展示了标准输出（stdout），最好展示 log（`main.log`），log 里的信息更多（比如能看到 `xtemplate.sty` 的版本）。

我靠感谢大佬orz!!!  升级了l3packages之后就可以正常编译了. (哦哦哦我以为这个就是日志了不好意思, 学到了哈哈
