### ISSUE TITLE
ctex: Asymptote 使用 ctex 宏包时，边框设置不准

### ISSUE THREAD

**Issue by leo-liu** [CTeX-org/ctex-kit#75]
Original [issue 76](https://code.google.com/p/ctex-kit/issues/detail?id=76) created by LeoLiu.PKU on 2012-04-03T13:30:17.000Z:

参见 http://bbs.ctex.org/viewthread.php?tid=70813

应该是 ctex 宏包中，\CTEXsetfont 设置缩进的相关代码所致，具体机制和解决方案待分析

**Comment by qinglee** [comment]
Asymptote 将 LaTeX 文件中的 `\oddsidemargin` 写死了：

```TeX
\oddsidemargin=-17.61pt
\evensidemargin=\oddsidemargin
```

这里的 `17.61pt` 是 `12pt` 字号下标准文档类 `\parindent` 的宽度（实际上是 `1.5em`，合 `17.62482pt`）。`ctex` 包的 `autoindent` 选项会增大 `\parindent`，造成 `\oddsidemargin` 不够，从而边框不准。

我们可以用 `\ASYalign` 作为标志，关闭 `autoindent`，并恢复 `\parindent`：

```TeX
\AtBeginDocument
  {
    \cs_if_free:NF \ASYalign
      {
        \ctexset { autoindent = false }
        \dim_set:Nn \parindent { - \oddsidemargin }
      }  
  }
```

或者更新 `\oddsidemargin`:

```TeX
\AtBeginDocument
  {
    \cs_if_free:NF \ASYalign
      {
        \dim_set:Nn \oddsidemargin { - \parindent }
        \dim_set_eq:NN \evensidemargin \oddsidemargin
      }  
  }
```

**Comment by leo-liu** [comment]
唔……好像通知上流修改更好些，让 Asymptote 正确处理 `\parindent` 问题是否可能？

**Comment by leo-liu** [comment]
唔……好像通知上流修改更好些，让 Asymptote 正确处理 `\parindent` 问题是否可能？

**Comment by qinglee** [comment]
不把 `\oddsidemargin` 写死，而是写成 `\parindent` 的负值应该也可以。

```diff
diff --git a/asymptote/texfile.cc b/asymptote/texfile.cc
index a7873bb..aefaa31 100644
--- a/asymptote/texfile.cc
+++ b/asymptote/texfile.cc
@@ -108,7 +108,7 @@ void texfile::prologue()
            << "\\textheight=" << height+18.0 << "bp" << newl
            << "\\textwidth=" << width+18.0 << "bp" << newl;
       if(settings::pdf(texengine))
-        *out << "\\oddsidemargin=-17.61pt" << newl
+        *out << "\\oddsidemargin=-\\parindent" << newl
              << "\\evensidemargin=\\oddsidemargin" << newl
              << "\\topmargin=-37.01pt" << newl;
       *out << "\\begin{document}" << newl;
```

我觉得把它们都设置为 `0pt` 也是可以的。

**Comment by Liam0205** [comment]
这个 Google Code 时代的 issue 要怎么处理比较好……？

BBS 已经关掉（MWE 看不到了），似乎也不是 `ctex` 的锅？

**Comment by stone-zeng** [comment]
> 原帖：<http://bbs.ctex.org/viewthread.php?tid=70813>

## 求助：asymptote生成图形为什么显示不全？

### superhxl

如题。为什么使用 Asymptote 画得流程图显示不全，边框被吃掉一部分，例如等待、开始框图的边框少了。

### ganganray

我也碰到类似问题。经测试可能是 `ctex` 宏包的问题。譬如下面的代码：

```asy
settings.outformat="pdf";
settings.tex="xelatex";
settings.pdfreload;
usepackage("ctex");

size(200,200);

filldraw(circle((10,10),5));
label("怎么回事？",(0,0));
```

不知道怎么处理？

### LeoLiu

先用裸 `xeCJK` 处理，像我写的教程一样。

`ctex` 关于段首缩进的 patch 代码可能造成 Asymptote 的计算错误，不过怎么改暂时没有精力细看。

### superhxl

果然，一直纠结呢！谢谢！

### doctorjxd

试一试先用 `invisible` 画笔点几个点，定好边界，然后再画图。可以解决被切掉的情况。

### superhxl

> 试一试先用 `invisible` 画笔点几个点，定好边界，然后再画图。可以解决被切掉的情况。

之前也这么干过，但是总归不爽！

**Comment by qinglee** [comment]
看了一下，asymptote 在去年底修复这个问题了，见 https://github.com/vectorgraphics/asymptote/pull/131 ，方法也是将 `\parindent` 和 `
\oddsidemargin` 都设置为 `0pt`，这样 ctex 的 `autoindent` 选项就不生效。

TeX Live 2020 包含的是 asymptote 2.65，包括这个修改。我试了一下，结果也正常。

**Comment by Liam0205** [comment]
@qinglee 您真是社区之光……
